### ISSUE TITLE
Contacts number is not clearly visible

### ISSUE THREAD

**Issue by Akronix** [Trustroots/trustroots#1006]
**Describe the bug**
The contacts number located in profiles is not well visible.

**To Reproduce**
1. Go to any user profile.
2. Try to read the contacts number in the Contacts tab.

**Expected behavior**
Another, more clear, colour for that number.

**Screenshots**
![image](https://user-images.githubusercontent.com/2631430/50315068-95c5c700-04b1-11e9-8f95-7e5406420e4a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version 64

**Comment by simison** [comment]
Oh wow, must be some recent regression.


How does it look with these?
```scss
color: #555; // @gray
border: 1px solid #999; // @gray-light
font-weight: 400;
```

For my screen having both `@gray` jumps little too much out from the navigation.

**Comment by Akronix** [comment]
Much better. I'd even consider to have a darker grey for the number.
