### ISSUE TITLE
I'm not panicking: improve 404 handling

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#1007]
The `Don't panic 404` page annoys me systematically.

1. I'm not panicking. 
2. There should be no redirect.

:slightly_smiling_face:

**Comment by mrkvon** [comment]
Is the _Don't  panic!_ on Trustroots 404 a reference to [The Hitchhiker's guide to the Galaxy](https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker%27s_Guide_to_the_Galaxy#Don't_Panic)?

@simison

**Comment by simison** [comment]
Yes. :-)


Happy to change it to something more universal (🙃) and more inclusive, tho.

**Comment by mrkvon** [comment]
I would be sad to see it go the moment I get to understand it. :)

Although, tbh, I was really getting annoyed each time the app was telling me not to panic. I know of at least one person who has or had similar feelings.

Anyways, the redirect (losing the original (e.g. mistyped) url) seems to be a more tangible issue, isn't it?
