### ISSUE TITLE
show (random) active members in a tribe on tribe page

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#1012]
now we have this https://www.trustroots.org/tribes/trustroots-volunteers - with 12 members, but we can't most of these on the map, it would be nice to be able to just have them show up on the tribe page (if the user is logged in)

**Comment by simison** [comment]
Removing easy+good first since this definitely is more involving.

**Comment by simison** [comment]
While this is definitely easier to implement in many ways than "search result list" at the map, this "goal" would be solved by the map list as well.

So it might make more sense to concentrate our very low resources to that feature instead
