### ISSUE TITLE
smart zoom: only do "Zoom in closer to see everyone" when there's 150+ dots

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#1013]
**Is your feature request related to a problem? Please describe.**
- I'm always frustrated when my filter settings only have a dozen people to show around the world and I have to stay zoomed in a lot and move around the earth to actually find them. "Zoom in closer to see everyone".

**Describe the solution you'd like**
I want the zoom to be smarter: only do "Zoom in closer to see everyone" when there's 150+ dots (or some other arbitrary number). If there's max 12 dots around the globe it can simply show those dots when completely zoomed out.

**Comment by simison** [comment]
As a "goal user has" this has a lot of overlap with "search results list" https://github.com/Trustroots/trustroots/issues/721
