### ISSUE TITLE
when turning off hosting, ask when will you be able to host again?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#1016]
When turning off hosting, ask when will you be able to host again? WarmShowers does this:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/54728/50439918-1b070c80-08f4-11e9-9f70-e394c6c6facb.png">

**Comment by simison** [comment]
Yap, this one is pretty good for keeping folks active. :thumbsup:
