### ISSUE TITLE
Uploading photo from mobile does not work

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#1030]
**Describe the bug**
Nothing happens when pressing "Select a photo" or "Take a photo" buttons at mobile phone.

**To Reproduce**
1. Go to https://www.trustroots.org/profile/edit/photo
2. Click on "Select a photo" or "Take a photo" buttons
    <img width="241" alt="image" src="https://user-images.githubusercontent.com/87168/82373313-16318400-9a26-11ea-8583-0dccd340cf2b.png">
3. Nothing happens

**Expected behavior**
Able to pick a photo from a phone or take a photo with the camera.

**Smartphone (please complete the following information):**
 - OS: Android 8
 - Browser: Trustroots app

**Comment by noahsmindfuck** [comment]
On my 2 mobile devices (Android 7.1.2, Android 8.0.0) when selecting "Select a photo" the file browser is opened to select a picture but after selecting the picture nothing happens. Trying to select a photo again does not call the file browser anymore.
I had a similar problem once when I gave my browser no access to read/write files. Maybe there is a connection.

**Comment by simison** [comment]
Yep, I can confirm this works when opening via Chrome browser directly.

Via Trustroots app, on the other hand, it does not work.

**Comment by noahsmindfuck** [comment]
Another report:

> There I change between 'Gravatar' and 'No profile photo'.
> I have no Facebook account.
> When I want to change in 'My own' I get the message 'First upload photo'
> Here I push the button 'Select a photo'. While doing this the button darkens and remains a bit darker than before. But nothing happens. If I push and hold for a longer time it gives the the result: nothing.
> The same happens with the button 'Take a photo'.
> 
> That's where I stand since yesterday. I have a new HONOR X8 handy with Android EMUI 8.2.0 in the actual version.

https://trustroots.zendesk.com/inbox/conversations/2703

**Comment by noahsmindfuck** [comment]
Another report:

> So I am trying to fill out my info and profile, but I am getting stopped at the profile photo page. I cannot select upload photo on the app and everytime I selct or drag on the website, nothing happens. Very frustrating. Is this a common issue, or is there a workaround?

https://trustroots.zendesk.com/inbox/conversations/2778

**Comment by rumwerfer** [comment]
Changed priority to normal, to express that [this](https://github.com/Trustroots/trustroots/issues/1101) is more urgent

**Comment by noahsmindfuck** [comment]
Changed priority to high as it is ~20% of support messages :) Would really help it someone could figure it out!

**Comment by gabrielsr** [comment]
> 1. Go to https://www.trustroots.org/profile/edit/photo
This was a little miss leading x). The problem is just in the up, right?

**Comment by simison** [comment]
Re-tested today:

- Android-Chrome, worked :white_check_mark:
- Android-Firefox, worked :white_check_mark:
- Android mobile app, nope :confused: (edited)

**Comment by DriesDD** [comment]
I tried this again today and it works in the android app. Version 1.3.0, on a moto g6 on Android 9.

The behavior is not 100% expected as it's exactly the same when clicking 'select a photo' or 'take a photo'. With camera permissions, the app lets you choose between camera and filebrowser. Without  camera permissions, there is only filebrowser. I can confirm that the picture actually did change.
