### ISSUE TITLE
Down arrow button on homepage not clickable

### ISSUE THREAD

**Issue by colemanGH319** [Trustroots/trustroots#1036]
In the desktop site, there's a down arrow on the homepage just below the app store/play store buttons. It would make sense for this to be a clickable scroll down anchor. I checked Chrome/Firefox/Edge and it doesn't work.

**Comment by flor3s** [comment]
hey, anyone working on this? think i could do it pretty simply/quickly

**Comment by simison** [comment]
@flor3s sure!
