### ISSUE TITLE
This splitting the string in a description is risky

### ISSUE THREAD

**Issue by agatatalita** [Trustroots/trustroots#1038]
(https://github.com/Trustroots/trustroots/blob/9de6c1d8c532eeda5a8aaa702a4f519ca51c3b67/modules/users/client/components/AboutMe.component.js#L40)

Based on [https://github.com/Trustroots/trustroots/pull/1005#discussion_r257152861]

@simison:
"This splitting the string was always a bit risky because we might split in the middle of an HTML tag or link. :-(

Just some brainstorming for an alternative approach:

   * We're really concerned only about the visual length of this area, so perhaps the toggle `profileDescriptionToggle` could only change a className?

  * Length of the string doesn't necessarily correlate with the height of the area (depends on so many things such as width and text styling) so that's probably was the reason why I why I went with string splitting originally. :-(

  * This (showing longer text vs and "show more") pattern is used in quite a few places in profile, I wonder if we could wrap it in a component and re-use everywhere?"

**Comment by simison** [comment]
Nice, thanks for collecting this to an issue :-) Should've done myself. 😅

**Comment by agatatalita** [comment]
Preparing for closing #1005 : )
(didn't notice GitHub is helping to create those with "Reference in new issue"!)
