### ISSUE TITLE
Cannot open profiles in new tab

### ISSUE THREAD

**Issue by CRCulver** [Trustroots/trustroots#104]
When one zooms in on the map, clicks on a balloon, and the profile preview pops up, it doesn't seem possible to open the link to that profile in a new tab (by clicking with the middle mouse button or Ctrl+click). I tried this in Firefox (Gecko) and Midori (Webkit) to no avail. If one clicks on the profile link and it opens in the same browser tab, and then one clicks Back, one is returned to the default map screen, not the specific map zoom that one was looking at before. This is frustrating.

**Comment by chmac** [comment]
#198 might be an issue if we fix this
