### ISSUE TITLE
Need a "Report profile" link or other recommended way of reporting spammers

### ISSUE THREAD

**Issue by CRCulver** [Trustroots/trustroots#105]
Just clicking around on the map, I've already found one profile where someone is apparently offering paid accommodation à la Airbnb. If BW is any indication, we’ll also soon start getting tour guides from certain countries signing up to offer their services. Could we have an unobtrusive "Report profile" link on each profile, or at least some discussion somewhere of how to bring these profiles to admins’ attention?

**Comment by simison** [comment]
#173
