### ISSUE TITLE
Profile: link to lives in/from -locations broken

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#1052]
In profile sidebar, links to locations are broken

<img width="284" alt="image" src="https://user-images.githubusercontent.com/87168/53288753-11cfda00-3795-11e9-9832-d2807b63d215.png">

Links to:
```
https://www.trustroots.org/search.map(%7BlocationFrom%7D)
```

...which looks like Angular Router link. 

Should be:
```
https://www.trustroots.org/search?location=Grenoble
```

Where location name of course needs to be [encoded](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

CC @agatatalita @mrkvon

**Comment by mrkvon** [comment]
I'm gonna fix it asap/today.
