### ISSUE TITLE
Feedback/ticket system 

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#106]
Already with this amount of emails WP's [feedback form](http://ideas.trustroots.org/contact/) + emails aren't that great.

Some options:
- [ ] [OSTicket](http://www.osticket.com/) (self hosted, ugly, quite feature rich, FOSS)
- [ ] [UserVoice](https://www.uservoice.com/) (SaaS, paid)
- [ ] [ZenDesk](https://www.zendesk.com/) (Saas, paid)
- [x] [Inbox by ZenDesk](https://signup.zendesk.com/inbox?version=plans) (SaaS, simple, free for now). — let's use this for now. Yay for no need to install anything, simple, more features vs Brimir.
- [ ] [Brimir](https://getbrimir.com/) (self hosted/SaaS, simple, free/paid) — _could be it if we'd host this ourself. Perhaps later._
- _Others?_

**Comment by yogiben** [comment]
I've only used [user voice](https://www.uservoice.com/) before.

Works well.

**Comment by simison** [comment]
@yogiben seems a bit pricey — "agent" is one user account in the system?

**Comment by simison** [comment]
https://github.com/ivaldi/brimir looks interesting

**Comment by simison** [comment]
Playing around with [Inbox by Zendesk](https://signup.zendesk.com/inbox?version=plans):

>_Forever free when you sign up during the beta_

Seems simple but effective.

**Comment by simison** [comment]
Tested also [Brimir](https://getbrimir.com/). It's nice, especially since we could host it ourself (might do in the future when support needs a team). For now SaaS suits us the best and [Inbox](https://signup.zendesk.com/inbox?version=plans) has better features / slicker interface, and it's supposed to be for free.

Quickly tested [Zendesk](https://www.zendesk.com/) and it's very neat. Simple version is just 12$/year but I think simple and free suits us better now.
