### ISSUE TITLE
E-Mail confirmation has delay of up to 24 hours

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#1065]
**Describe the bug**
Recently a number of requests arrived at the support platform with people complaining that the email confirmation doesn't work. Usually after 12-24 hours they reply that "suddenly everything works".

**To Reproduce**
1. Click the confirm email link in the email

**Expected behavior**
You can use the platform with no limits

**Comment by simison** [comment]
As in when they sign up or when they've changed their email via account settings?

**Comment by noahsmindfuck** [comment]
So far I can only recall it for sign up's. I will try to get some numbers later this week if that is of help.

**Comment by simison** [comment]
Dashboard averages look alright:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/87168/56877357-11cead80-6a56-11e9-8207-f74696c45ac7.png">

Are these all coming from same email host?

**Comment by noahsmindfuck** [comment]
Host: gmail.com
https://trustroots.zendesk.com/inbox/conversations/2730
https://trustroots.zendesk.com/inbox/conversations/2740

**Comment by simison** [comment]
Have there been new reports of this happening since?

**Comment by noahsmindfuck** [comment]
nope, imho we can close it, I can reopen it and add data if it happens again.
