### ISSUE TITLE
Limit number of messages (to fight spam)

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#1074]
To catch spammers early on, we should have an automatic notification sent to admins when a profile sends x messages in y time, and the profile should not be able to send more messages until an admin unbans them.

I would say, the message limit should be that high that nobody looking for accommodation would ever reach it, even someone messaging e.g. everyone in Berlin.

200 messages per 24 hours seems like a good idea to me.

**Comment by guaka** [comment]
yes, can be part of #2750
