### ISSUE TITLE
Importing CouchSurfing profiles

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#1080]
**Is your feature request related to a problem? Please describe.**
For new members who have complete couchsurfing profiles: some of these will be very happy to import their data from couchsurfing.

**Describe the solution you'd like**
CS data export there is currently possible at /preferences/privacy
It's a zip file. We can write some code to import the JSON and JPGs and automatically fill in the user's profile.

**Comment by rumwerfer** [comment]
With the recent paywall decision: Can anyone with a CS account answer the question if they let you download your data now if you didn't pay them? (they'd probably have to for EU users at least)

**Comment by Akronix** [comment]
I thought to send them an email about requesting my data, but it'd be interesting to know if someone has tried already.

**Comment by simison** [comment]
We have some code for the importer written here: https://github.com/Trustroots/trustroots/pull/1086

**Comment by simison** [comment]
Plenty more code here: https://github.com/simison/couchspinner/

Now this mostly would need bringing that over, and adding some UI.
