### ISSUE TITLE
Grey out contacted users on map that didn't reply

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#1084]
**Is your feature request related to a problem? Please describe.**
When you are searching in a city with a lot of hosts it gets very messy

**Describe the solution you'd like**
If you contacted a user and that user never replied, grey that user out. if they reply, bring back their color. If you contact them another time later again with a timespam of <x days/weeks/months> in between and they don't reply they get grey again, maybe with a different shade?

**Comment by noahsmindfuck** [comment]
![2019-05-19-094412_1920x1080_scrot](https://user-images.githubusercontent.com/24893086/57979264-9ee4a100-7a1b-11e9-9c49-5ecb61528af2.png)

**Comment by rumwerfer** [comment]
Since recently (can't find the relevant pr), people whose profiles you clicked on will have a less bright colored dot on the map. @noahsmindfuck is this a solution for what you meant, or is this issue still valid?
