### ISSUE TITLE
User gets suspended when clicking confirmation link

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#1095]
User tries to confirm their email adress and gets suspended when clicking the button.

Report via Zendesk:
> Hello, i confirm my mail but if i click the confirmation link then appear message my profile is been suspended. Please keep my profile alive, thanks 
> Kind regards

Probably related to recent changes around the "Suspend"-Feature.

**Comment by simison** [comment]
Couldn't replicate this when testing and don't even see how this would be possible, but I disabled suspending-API temporarily and will investigate more.

**Comment by doktorhorst** [comment]
There was a misunderstanding. The user was suspended by us. Had nothing to do with confirmation link.

**Comment by simison** [comment]
Aight! Reverted API closure then :-)
