### ISSUE TITLE
Mobile: Text field hidden by keyboard when writing a message.

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#1101]
**Describe the bug**
Writing a message on a smartphone with screen keyboard, the reply field does not stay over the keyboard when the keyboard appears. The keyboard is over it, and you have to type blind.

**Screenshots**
![Screenshot_20190710-081930](https://user-images.githubusercontent.com/10289010/60945747-bb4edc80-a2ec-11e9-84dd-104fe0fb12f8.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser Firefox

**Comment by simison** [comment]
Thanks! Which version of Android are you running on?

**Comment by simison** [comment]
I can replicate using the [mobile app](http://android.trustroots.org) version on Android 9.

**Comment by sitarane** [comment]
Oreo.

**Comment by noahsmindfuck** [comment]
This is still happening and very annoying.
I understand that the issue is unloved but it is still pressing ;)

**Comment by nonno** [comment]
I got blocked on this yesterday and I had to use the web app. There is already (at least) a one star review on PlayStore.
