### ISSUE TITLE
Search members fails: text index required

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#1110]
When trying out the [_Find people_](https://www.trustroots.org/search/members) feature in production, no output is returned. API calls to https://www.trustroots.org/api/users?search=username fail with status code 500 and body `{"message":"text index required for $text query"}`.

**Reproduce**
1. Go to https://www.trustroots.org/search/members
2. Open developer tools in your browser
3. Search for something
4. See the xhr call to API and that it fails with the error above.

**Expected behavior**
Api call succeeds with 200 and a few users are found and displayed.

**Desktop:**
 - Arch Linux
 - Mozilla Firefox for Arch Linux
 - 69.0

**Additional context**
Probably a text index on one or several of user properties in mongodb has not been built or has changed. Was this feature ever working in production? What  could have possibly ruined the index if it existed already?

Related source code seems ok to me. (https://github.com/Trustroots/trustroots/blob/master/modules/users/server/controllers/users.profile.server.controller.js#L1413-#L1450, https://github.com/Trustroots/trustroots/blob/master/modules/users/server/models/user.server.model.js#L361)

**Comment by Akronix** [comment]
Hey! I just fixed this. I have added a text index for the fields: displayName, displayUsername and email in the users collection, so the /search/members endpoint search in this fields of the database.

I've been doing some manual tests and, although a better tuning for the returned ranking could be done, the feature works ok :+1: :tada: 

FTR, this the mongo sentence I've used to add the index:
`db.users.createIndex( { displayName : "text", displayUsername: "text", email: "text" }, { name: "usersTextIndex" } )`

Future work is to display more info of the users profile and clear the result list when the user press the `X` button
