### ISSUE TITLE
Add a red icon with the number of non-answered requests in the "Contacts" drop-down menu item

### ISSUE THREAD

**Issue by Akronix** [Trustroots/trustroots#1131]
**Is your feature request related to a problem? Please describe.**
I'm missing a reminder of unanswered contact requests.

**Describe the solution you'd like**
A number reminding you have requests without being answered.

**Describe alternatives you've considered**
Add that number in the dropdown menu of the top right. Here:
![image](https://user-images.githubusercontent.com/2631430/69573513-8e167880-0fc6-11ea-8afc-d4667d3bbb52.png)

Follow up the discussion already happened here: https://github.com/Trustroots/trustroots/pull/1130#issuecomment-555998993

**Comment by simison** [comment]
I'll dropout "easy" tag if you don't mind since this has some potential complexity, but it sure is a good first issue since it might touch quite a few aspects of the codebase! :-)
