### ISSUE TITLE
Meet location is not required to be set manually

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#1141]
**Describe the bug**
A sum of meetups are in Stuttgart although they are not supposed to be there.
 
**To Reproduce**
Create meet event withough changing the location.

**Expected behavior**
A message should ask you either whether the location is correct or maybe whether you forgot to set a location.

**Comment by doktorhorst** [comment]
Connected to #132

**Comment by noahsmindfuck** [comment]
Connected to #126

**Comment by rumwerfer** [comment]
Closing in favor of #126
