### ISSUE TITLE
/profile/:username/tribes is a valid page with errors

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#1142]
#### The bug

The url `/profile/:username/tribes` is [defined](https://github.com/Trustroots/trustroots/blob/master/modules/users/client/config/users.client.routes.js#L229-L237), but the page itself doesn't show anything meaningful.

My browser console shows an error:

> Error: "[$parse:ueoe] Unexpected end of expression: profileCtrl.profile.member |
https://errors.angularjs.org/1.6.10/$parse/ueoe?p0=profileCtrl.profile.member%20%7C"

#### Expected behaviour

Either
- the url and related code doesn't exist, or
- the page shows whatever it's supposed to show, and doesn't show the error. Also some links to that page would be useful.

#### Info
- browser: Mozilla Firefox for Arch Linux v70.0.1 (64-bit)
- system: arch linux

#### Screenshot

![image](https://user-images.githubusercontent.com/7449720/70532183-d2714f00-1b56-11ea-8d56-73267b8f887b.png)

**Comment by simison** [comment]
I think this was supposed to be a thing but never happened; the mini tribes list in profile's "about" section has been sufficient enough.

This can be cleaned out. 👍
