### ISSUE TITLE
 <title>Trustroots ADD MORE</title>

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#116]
e.g. `<title>Trustroots - Hospitality community for hitchhikers</title>`

see also #115

**Comment by simison** [comment]
"Trustroots: travellers hospitality community" ?

**Comment by guaka** [comment]
for front page "Trustroots: travellers hospitality community" is great but
for other pages the title should depend on the specific page, e.g.
something like "guaka on Trustroots" for profiles, "Trustroots FAQ", "About
Trustroots", "Trustroots Team" etc.

could be done generically like "PAGE TITLE | Trustroots.org"

**Comment by simison** [comment]
This one is done.
