### ISSUE TITLE
Background image of support page too large

### ISSUE THREAD

**Issue by Akronix** [Trustroots/trustroots#1165]
In the support page: https://www.trustroots.org/support there is a background image (this one: https://www.trustroots.org/img/board/flickr-forestpath.jpg) which it's way heavier than the whole page and it renders a bit later for slow connections.

The image is not that crucial and is displayed in a much smaller size, so I suggest to compress it, to shrink it or to change it by another one.

**Comment by rmrn65** [comment]
Hi ! It's the first time I'm trying to contribute to an open source project. Is this still available?

**Comment by Akronix** [comment]
Yes, it is! Do you need any help on how to tackle it?

**Comment by rmrn65** [comment]
I forked and modified the photo you mentioned. I reduced it's size at 44% of it's initial size. Please tell me if it's all working as you expected.

**Comment by simison** [comment]
Addressed in https://github.com/Trustroots/trustroots/pull/1166
