### ISSUE TITLE
dev and staging

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#117]
- auto deploy latest push
- robots.txt Disallow: /
- test database to start with?
- later: alpha with test db and beta with real db?

could also have different subdomain, e.g. test.trustroots.org

@chmac any input?

**Comment by simison** [comment]
Created a branch for production now. https://github.com/Trustroots/trustroots/branches

**Comment by simison** [comment]
There's now pretty identical setup to production here: https://dev.trustroots.org (I sent you pass in email)
