### ISSUE TITLE
Profile: 0 contacts throws an error

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#1170]
**Describe the bug**

<img width="566" alt="Screenshot 2020-01-08 at 22 31 09" src="https://user-images.githubusercontent.com/87168/72013479-9d940d00-3266-11ea-8c3f-fbc238225e13.png">

![image](https://user-images.githubusercontent.com/87168/72013419-7b01f400-3266-11ea-8576-bca6bd798987.png)

**To Reproduce**
1. Have user without contacts
2. Go to "Contacts" tab of your profile
3. Observe "wait" text not disappear
4. See an error in the console

The "waiting" message should get resolved to some kind of "no contacts" message instead.

**Comment by Pramuspl** [comment]
Cannot reproduce the issue neither on prod nor on local, everything seems to be fine.
![image](https://user-images.githubusercontent.com/8478114/86830135-958e1c00-c095-11ea-9e38-3d38e64ec12c.png)

**Comment by simison** [comment]
Glad to hear it. :-)
