### ISSUE TITLE
Shadowban

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#1184]
This is a master issue to track various work going to the "shadow ban" feature.

Goal:
- Add a new "shadowban" role which is like suspended, but works slightly differently.
- Add extra protection by filtering out suspended users in various features without them noticing.

PRs:

- [x] https://github.com/Trustroots/trustroots/pull/1180 don't let suspended users remove themself
- [x] https://github.com/Trustroots/trustroots/pull/1179 hide profiles with 'shadowban' role
- [x] https://github.com/Trustroots/trustroots/pull/1183 hide the messages themselves
- [x] https://github.com/Trustroots/trustroots/pull/1185 Add shadow-ban notice to rules
- [x] https://github.com/Trustroots/trustroots/pull/1186 Add moderator role
- [x] https://github.com/Trustroots/trustroots/pull/1187 Improve admin tools

Up next:
- [ ] Hide their messages in other peoples' inboxes (we're getting a lot of support messages regarding this - very annoying for the affected members)
- [ ] https://github.com/Trustroots/trustroots/pull/1181 Remove contact info in profile and offer descriptions for shadowbanned users
- [ ] https://github.com/Trustroots/trustroots/pull/1182 Do not send notifications to/from shadowbanned users
- [ ] Hide FB/social network links in other people's profiles
- [ ] #1189 Hide them from search
- [ ] Hide their contact requests
- [ ] [Don't send welcome emails to them](https://github.com/Trustroots/trustroots/blob/56adf8076a77ed1d91a88d3406196300bc99a48a/modules/users/server/jobs/user-welcome-sequence-first.server.job.js#L45-L51)

Other feature ideas:
- [ ] Don't consider their messages for reply rate calculation
- [ ] Hide their meet & hosting offers from others https://github.com/Trustroots/trustroots/pull/819
- [ ] Hide them in member search results
- [ ] Hide them as a contact in other people's profiles
- [ ] Don't send them any other automated emails
- [ ] Allow admins remove shadowban/suspended/moderator roles

**Comment by TMC89** [comment]
I would like to add that a member through support wanted to remove a shadow banned member, but couldn't.

**Comment by guaka** [comment]
most of it done, but good to double check

**Comment by guaka** [comment]
Progress update: #2782 and #2801 have merged into `main`. These cover restricted-member visibility in member search and contact requests, omit restricted members from existing confirmed-contact lists, keep shadow-hidden messages out of reply statistics, and exclude shadowbanned members from finish-signup reminders.

#2801 also contains an audit of this checklist: hosting/meet offer filtering is already implemented and tested, while the legacy moderator-role item is no longer current. Administrator reports now include a read-only role inventory; role editing/removal and a persistent rules notice remain outside this work. The checklist should be reconciled with that audit before closing the issue.

**Deployment status (12 September 2026):** these changes are not on production yet. Deployment of `main` is expected soon; production verification is still pending.
