### ISSUE TITLE
Suspended users appear in member search

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#1189]
**Describe the bug**

Is it a bug or a feature?
When I (a regular user) go to https://trustroots.org/search/members and type in name of a user who is (most probably) suspended, I can still see them in the results.

**To Reproduce**

0. Know a name of some suspended user
1. Open https://trustroots.org/search/members
2. Type suspended user's name or username
3. See them appear in the results

**Expected behavior**
The suspended users should not appear in the member search output.

**Comment by simison** [comment]
We'll need to add `roles: { $nin: ['suspended','shadowban'] }` to query.

**Comment by jaas666** [comment]
Is this still an issue?
