### ISSUE TITLE
Add 'How to report a member' question to FAQ

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#1192]
There is a question missing in the FAQ:
Q:
>How do I report a member that violates the [rules](https://www.trustroots.org/rules)?

A:
>If you navigate to the profile of a user you will find a link that says "Report member" that will lead you to a report form. Also, at any point you can contact support@trustroots.org with your report. Please include a link to the profile or a username if you provide the report via email.

The "Report member" link is still not visible on small screens which means on all phones afaik. #919

**Comment by noahsmindfuck** [comment]
A short how-to from Mikael in [Slack](https://trustroots.slack.com/archives/CHWDNEDTR/p1579873109000600)
>1. Add the question here so that it appears at the sidebar: https://github.com/Trustroots/trustroots/blob/3dfb08815cb17d2643c01ada2f1c986e8f33a65a/modules/pages/client/views/faq.client.view.html
2. Add the answer to one of the faq-*  files here: https://github.com/Trustroots/trustroots/tree/3dfb08815cb17d2643c01ada2f1c986e8f33a65a/modules/pages/client/views
Note that id has to be correct in both files for that question.

**Comment by Pramuspl** [comment]
Shouldn't be closed? Seems to have been resolved.

**Comment by simison** [comment]
True, thanks for the heads-up!
