### ISSUE TITLE
2 Links in bottom of "meet" page are broken

### ISSUE THREAD

**Issue by md42** [Trustroots/trustroots#1195]
**Describe the bug**
see screenshot. The links "Translations" and "Meta" are broken
![image](https://user-images.githubusercontent.com/857448/73607050-b36cc780-45b1-11ea-9b3d-d433a00cf1f9.png)

**Steps to reproduce**
1. Login
2. Got to https://www.trustroots.org/offer/meet
3. click on either "Translations" or "Meta" at bottom of page
this shows "Unable to connect"

**Comment by rumwerfer** [comment]
Thanks for the report! Both links point to our inactive _Discourse_ instance. We might just get rid of them
