### ISSUE TITLE
Link to GitHub in Support Menu

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#1202]
It would be great to have the support menu showing a link to GitHub.

![2020-02-11-214308_1920x1080_scrot](https://user-images.githubusercontent.com/24893086/74277513-fb10f300-4d17-11ea-9a45-7d4d8595234a.png)

**Comment by simison** [comment]
@rumwerfer wanna take on this? :-)

**Comment by simison** [comment]
I actually personally prefer to have support folks act as a filter between volunteers working on stuff and what sometimes can be a pretty vocal community. A dedicated conversation platform like Discourse feels much more appropriate for something like this. What do you think?

**Comment by noahsmindfuck** [comment]
I agree with @simison 
I remember I have seen the link to Github at some point near the footer and wherever those links appear. Do I remember wrong?

**Comment by simison** [comment]
Still there:
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/87168/74283782-29e49480-4d2b-11ea-99e9-1012df2f2b8c.png">

Just not that many pages are suitable for showing the footer (think e.g. map or messages)

**Comment by rumwerfer** [comment]
Well, I'm definitely in favor of having smth like Discourse again! Would make sense to have discussions about long-term vision somewhere where also non-technical people feel welcome

**Comment by nicksellen** [comment]
I added it as a point for next call :)
