### ISSUE TITLE
Blank page when calling Trustroots with blocked cookies

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#1265]
**Describe the bug**
Disabling all cookies leads to a blank page when when calling https://www.trustroots.org

**To Reproduce**
1. Disable all cookies on your browser
2. Visit https://www.trustroots.org

**Expected behavior**
A page with info about blocked cookies, maybe lead to https://www.trustroots.org/privacy

Slack: https://trustroots.slack.com/archives/C0A3Q15SS/p1582790149003400
Zendesk: https://trustroots.zendesk.com/agent/tickets/3151

**Comment by NobleTyler** [comment]
I'll give this one a shot.
