### ISSUE TITLE
Text goes off-screen when typing a message on mobile

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#128]
When the KB shows up, the text is pushed up off-screen.

Screencast? Screencast.

http://youtu.be/gC3q95lqA0w

**Comment by simison** [comment]
@sitarane was this Android btw? I'm observing how the page jumps upwards on different platforms when virtual keyboard is visible. Here it seems to be working fine.

**Comment by sitarane** [comment]
Android / firefox

**Comment by daiyiwhale** [comment]
I've noticed the jerking/jumping on Android + Chrome too.

**Comment by simison** [comment]
@daiyiwhale I also noticed this very recently. 

@katsuroo did you notice anything? (he's working on message thread now)

**Comment by katsuroo** [comment]
@simison Haven't tested on android. But haven't had any issue on iOS / chrome. I have, however noticed that if you input a significantly long string of characters without any spaces it doesn't get wrapped. So it just continues offscreen horizontally.

**Comment by daiyiwhale** [comment]
(you probably want [word-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap)!)

**Comment by simison** [comment]
Yeah!
