### ISSUE TITLE
Highlight unread messages

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#1311]
Looking at the inbox at https://www.trustroots.org/messages, all messages look the same, no matter if they are read or unread.

Unread messages should be highlighted (e.g. bold & black instead of grey).

**Comment by aldenfbrown** [comment]
I am down to help. I created a profile > https://www.trustroots.org/profile/aldenfbrown would you be so kind to send me some messages for testing? Thanks in advance!

Cheers,
Alden

**Comment by rumwerfer** [comment]
Hi there, that's great.
Since testing can only be done in a local environment, [here](https://team.trustroots.org/Install.html) are instructions how to set up Trustroots locally. If you want, I'll invite you to our team chat.

**Comment by aldenfbrown** [comment]
Sounds good! I will check out local dev setup later today. Please do invite
me to the chat channel.

Cheers!
Alden

**Comment by aldenfbrown** [comment]
Hey there, 
I have read through the setup it all seems straight forward. I should have time tonight to get up my local dev instance up and running. I will let you know I hit any snags.
