### ISSUE TITLE
Redirect to original link after logging in

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#135]
If you try to access a page that is login-only, and you're not logged in, you get a login page. Once you're logged in, instead of being redirected to the page you were trying to reach in the first place, you're sent to the startpage (map).

Example (what happened to me): when I got an email asking to confirm a connection (friend) initiated by another user, I clicked on the "see connection" button (within the email), off to a login page (somehow I wasn't logged in) then to the start page. I had to go back to my email to click the button again to get to the "confirm contact" page.

**Comment by chmac** [comment]
Blocked by #54

**Comment by jancborchardt** [comment]
cc'ing myself here. :)
