### ISSUE TITLE
Map screenshot not based on real data

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#1367]
Very minor issue: I just introduced a friend to TR, and he said: "Well, that's weird. You guys have 
100 members in Luxembourg and noone in Berlin?" – Took me a while to understand he was referring to the map screenshot on the startpage (not logged in):

![screenshot from startpage](https://user-images.githubusercontent.com/31466125/78507855-0ebe6000-7783-11ea-99f1-ca54ef2d03cb.png)

I guess this is still from the early times of Trustroots when the real map was still empty. But now it might make more sense to have the map resemble the real locations of our members. Okay if I replace it with this one?

![screenshot of actual map](https://user-images.githubusercontent.com/31466125/78508158-0bc46f00-7785-11ea-95a5-6f1fa24efddb.png)

**Comment by rumwerfer** [comment]
@simison were the colors changed at some point or is that a filter?

**Comment by simison** [comment]
@rumwerfer yep, map colors have changed since and usually different applications capture/save color information differently too so taht would explain different hue of TR cyan. 

Nice to see old-timey UI. :-) The example probably is using a bunch of randomly generated content.

**Comment by gabrielsr** [comment]
Work on it. My first issue. Lets see.
