### ISSUE TITLE
Hashtags?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#138]
- [ ] in profiles
- [ ] in references

Questions:
- How can this help creating real life connections? (this question should be kept in mind with all new feature)
- What will a hashtag link to?
- Add synonyms?
## Landing page
- Results based on current location
- First of all profiles, ranked on distance and number of times the tag has been used (double for references).
- (editable?) page about the topic? even directly a page from Nomadwiki?

See also user mentions  #120

**Comment by simison** [comment]
Related to #208
