### ISSUE TITLE
Remove unused profiles after x years

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#1381]
Profiles that were not used for years are cluttering the map. Also, it doesn't make sense for us to store their data in the database forever.

After not logging in for x time (@simison's suggestion: 3 years), an email should be sent out saying "Do you still want to use your Trustroots profile? If so, log in. If not, we will delete your profile soon."
There should be a reasonable amount of time (2 weeks?, maybe even a second email?) before the profile is actually deleted.

**Comment by simison** [comment]
To be clear, we do hide these from map by default (you can see the toggle in filters).

It's the fact of keepin un-needed personal data around that's not much fun.

People sometimes try sign-up and forget they already have an account, too. :-D

Here is a nice podcast episode on topic: https://rework.fm/delete-your-account/

**Comment by rumwerfer** [comment]
Oh! I knew about the filter, but wasn't aware it was activated by default.

**Comment by simison** [comment]
I _think_ it is. :-) if it's not, that's a problem to fix. :-) should show up in incognito window.

**Comment by rumwerfer** [comment]
> should show up in incognito window.
it doesn't

**Comment by Lemoert** [comment]
I like the idea of cleaning out old profiles, but perhaps first a "Have you forgotten about us?" email after two years and then a "Hello, we'll delete your account." email about a year later and deletion three-four weeks after that. Would having two emails be trickier to implement than one? Also, should this be combined with notifications seeing as a lot of people do not check their emails often?

**Comment by simison** [comment]
@Lemoert yep, email/notification sequence should definetely be part of it.

Multiple emails in the sequence is no problemo.

Another thing we might wanna do is disable the account first before deleting a month later, so that there is still "last minute" recovery possibility.
