### ISSUE TITLE
Show support team on /support

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#1388]
Some people agreed it would be a good idea to lower the threshold of reporting bad experiences. One idea to accomplish that goal could be, to show that the support form is not some kind of black box, but there are actually humans on the other end caring for you.
So we could show the support team members on `/support`, as in the section on `/team`.

**Comment by simison** [comment]
Agreed, this would be wonderful!

Empty space here seems suitable:

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/87168/79306182-7603af00-7efd-11ea-9dc8-3b0abc1eed8c.png">

**Comment by rumwerfer** [comment]
So, after migrating /team to react, we could make an own SupportTeam component, which is then imported by the other components, right?

**Comment by loberto** [comment]
Wouldn't this be an easy thing to do, by filtering all the volunteers with "Admin" role?
Same as Simison did in https://www.trustroots.org/team, but only for those with "admin" role?

or maybe create a new role?
