### ISSUE TITLE
Serve Gravatar/FBatar from our server

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#145]
- [ ] Gravatar/FBtar goes trough the backend —> gets cached for a week/day and eventually grabs new version after cache outdates —> served to frontend from our server
- [ ] if user edits profile/opens avatar editor, new version is pulled right away

Better if photos go into same/similar directory structure with avatar uploading and possibly even combines with resizing images through common API.

Helps to the problem where some privacy plugins would block FB/Gravatar images. [See discussion](https://github.com/Trustroots/trustroots/issues/7#issuecomment-68347380)

**Comment by chmac** [comment]
Are we allowed to do this by those sites? There's an expression, there are two hard things in computer science, naming and cache invalidation. Caching images from another site, invalidating that cache at some point, refreshing it, deciding what to do if the cache is stale but we can't get a new image, etc. This is all complex stuff. If folks have Gravatar / Facebook images blocked, no worries, they'll not see images for some profiles. Later, users can upload their own images and then there's no issue.

I'd suggest this is something we **do not** implement, now or in the future, as it increases total complexity with only a small gain for the few users who block facebook / gravatar. Again, I'll close this presuming it's not necessary to implement, but feel free to reopen if you disagree.
