### ISSUE TITLE
Embrace new members from CouchSurfing shutting down

### ISSUE THREAD

**Issue by antoinerousseau** [Trustroots/trustroots#1461]
As you may have heard, CouchSurfing is now forcing its members to pay to use the website:
https://blog.couchsurfing.com/couchsurfing-needs-your-help/

As a result, many members are unhappy and already looking for alternatives:
https://www.facebook.com/groups/253525915764545/
https://twitter.com/Couchsurfing/status/1261234974604374016

BeWelcome is laggy and buggy with poor UX, HospitalityClub feels like browsing the Web in the 80's, so the only two options are Trustroots or a new CS.

I would like to know how you feel about listing the features that CS members love and are absent on Trustroots, so that we can consider adding some of them?

A few ones I'm thinking of:
- References
- Photos

**Comment by rumwerfer** [comment]
Good idea!

About references: We didn't document this in the respective Github issue, but during the hackweek in April some years-old approach towards references was revived and this is what it's gonna look like: https://github.com/Trustroots/trustroots/pull/1413

**Comment by nicksellen** [comment]
You are also very welcome to join our efforts @antoinerousseau :)

I see you are coding in react, which we are slowly moving towards (see https://github.com/Trustroots/trustroots/issues/1334), working on _whole new features_ takes us some time, but the more we have a solid/modern react base, the easier that becomes.

I also see you're part of happy dev, I met some of them [last year](https://wiki.coops.tech/wiki/Sheffield_2019), here is [a photo](https://wiki.coops.tech/w/images/0/0c/CoTech_Sheffield.jpg) with me and at least 3 happy dev people I think, maybe you know them.

**Comment by antoinerousseau** [comment]
Oh! I didn't feel like getting involved in Angular dev, but why not help you with some React code!
I'll try to get some free time for this :)

**Comment by nicksellen** [comment]
(I invited you to our slack group, easier to discuss stuff, hope that's ok! no pressure :) )

**Comment by nonno** [comment]
Hi guys, first thing congratulations for your work, very clear and usable.
You may find interesting this FB group full of people speaking about you, BeWelcome, and the recent policy "I kidnapped your profile, to release the hostage I ask X$" of Couchsurfing.
https://www.facebook.com/groups/253525915764545/

**Comment by rumwerfer** [comment]
one of those features people liked a lot on cs was hangouts: #2117

**Comment by annazi-maker** [comment]
I second this and just added a seo-related feature request yet its also related to growth of TR as alternative of the bottom hitting cs: https://github.com/Trustroots/trustroots/issues/2132

**Comment by guaka** [comment]
I think we can close this issue now.

Of course CouchSurfers(tm) and non-CouchSurfers(tm) still welcome
