### ISSUE TITLE
NodeJS crashing occasionally

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#147]
Still have to find a pattern but people sometimes get "bad request" errors. Passenger resolves crashed NodeJS pretty quickly so it causes problems only for some 1min or so. Not sure how often this occurs, NewRelic gives still too much errors but hard to say how much of that is legit crashing.

- [ ] Better logs ([monitoring](https://github.com/Trustroots/trustroots/wiki/Monitoring))
- [ ] Better handling of errors at the backend
- [ ] Better handling of errors at frontend

**Comment by pmauduit** [comment]
(still having some troubles with assets / css, but leaving it for now)

I retried, I can reproduce the 400 errors when submitting a new account, but I don't have more info than that in the console:

```
POST /auth/signup 400 285.748 ms - 34
```
Which gives client-side:

```
{"message":"Something went wrong"}
```

Is there a way to increase log verbosity ?

**Comment by simison** [comment]
@pmauduit You need to add mailer settings to your configs. See 4. from [install instructions](https://github.com/Trustroots/trustroots/blob/master/README.md#installation).

"400 Bad Request" -code itself isn't dangerous, it's just a way for the app to know that something went wrong (instead of "200 OK" code. Tho in this case it should probably be something else and error message more verbose about what actually happened.

**Comment by pmauduit** [comment]
I was just expecting to get more info about the error ;-)

Anyway, after having configured properly the SMTP section in the `development.js` file (I've an exim mailserver running locally), I no longer encounter the `400 bad request` while trying to register.

**Comment by simison** [comment]
:+1:

**Comment by simison** [comment]
Getting only auth-errors nowadays, so everything's good here now.
