### ISSUE TITLE
Welcome Emails get resent when changing email adress

### ISSUE THREAD

**Issue by putzenpu** [Trustroots/trustroots#1484]
**Describe the bug**
When changing my email adress on Trustroots, after confirming I received both welcome emails again ("Welcome to trustroots, <name>!" and "Meet new people at trustroots <name>")

**To Reproduce**
1. Go to your profile, change email adress, and confirm change
2. Check inbox of the new email adress for the next few days

**Comment by rumwerfer** [comment]
Thanks for the report! Duplicate of #880
