### ISSUE TITLE
Incorporate i18n changes back from weblate

### ISSUE THREAD

**Issue by nicksellen** [Trustroots/trustroots#1487]
(part of [i18n overview](https://github.com/Trustroots/trustroots/issues/1485))

## Original issue

(content lifted from comment by @mrkvon here https://github.com/Trustroots/trustroots/issues/492#issuecomment-615422263)

Currently, we have an issue with our `i18next` config in `hosted.weblate`. See [#1373#discussion_r410402108](https://github.com/Trustroots/trustroots/pull/1373#discussion_r410402108).

We use natural translation keys, so `.` is not a special character, but end of a sentence. For this reason, our `./config/client/i18n.js` says: 

```js
nsSeparator: false,
keySeparator: false,
```
however weblate assumes that we use `.` as key separator, so it does weird things like

```json
    "Wait a moment": {
        "": {
            "": {
                "": "Warte einen Moment ..."
            }
        }
    },
```

I haven't found the related config on the website or in weblate documentation.

## Updates

- there is [no setting for it](https://github.com/Trustroots/trustroots/issues/492#issuecomment-617010572)
- my [hope](https://github.com/Trustroots/trustroots/issues/492#issuecomment-617038857) about using basic JSON, instead of nested JSON, I think is unfounded, as we use `i18next JSON file` format, not `JSON file`

You can see the PR from weblate --> https://github.com/Trustroots/trustroots/pull/1373

**Comment by nicksellen** [comment]
I came up with a short-term hacky solution - fix it with [a script](https://gist.github.com/nicksellen/cad99a57f877148a760ba2a9351c3afc) :) - it just re-nests the JSON data properly and puts the dots back in.

Gunna try it out a bit more first... maybe it will need manually applying on the weblate PR and manually merging it initially, but I'm keen to get the translations active.

**Comment by nicksellen** [comment]
Still doesn't work...

https://hosted.weblate.org/projects/trustroots/core/#repository shows the failure.

It seems very odd to me that they seem to be attempting a _rebase_ instead of a _merge_ (a rebase needs to resolve conflicts for each commit, whereas a merge only needs to resolve the conflicts for the latest commit - of which there are none now, I can cleanly merge weblates repo into ours).

Hmmm...

**Comment by simison** [comment]
There was a successful i18n commit yesterday: https://github.com/Trustroots/trustroots/commit/40d9ff4633b34854cfd4758f30159b4be5338804

— is that a good sign? :-)
