### ISSUE TITLE
make about section on public startpage more obvious

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#1489]
Someone I lured to TR told me they would have liked to "see what it looks like inside" before signing up. We do actually have an about section on the public startpage (_home-how_), but the little arrow below the store links didn't catch their eye.

<img width="434" alt="Bildschirmfoto 2020-05-24 um 14 41 45" src="https://user-images.githubusercontent.com/31466125/82754423-171f3880-9dcd-11ea-9367-0ab58fc7185b.png">

Can we make the existence of that section more obvious somehow?
* increase arrow size
* change symbol to something that looks more like an actual arrow
* decrease size of the picture header so that you already see the content that you can scroll down to
* ...?

**Comment by simison** [comment]
>decrease size of the picture header so that you already see the content that you can scroll down to

Yep, this is the most effective way. Something like 40-50px should be enough.
