### ISSUE TITLE
Inaccuracies of location search

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#149]
* https://www.trustroots.org/search?location=Brussels takes me to Brussels, 54204, Wisconsin, United States

* Suzhou city, Jiangsu Province, China, not found. [Google maps](https://www.google.nl/maps/search/Suzhou,+Jiangsu,+China/@31.3248289,120.5828476,11z?hl=en)

* Shkodra (albania)

**Comment by simison** [comment]
MapBox Geocoder just got much better; https://www.mapbox.com/blog/geocoding-type-ahead/

**Comment by simison** [comment]
At least https://www.trustroots.org/search?location=Brussels works now and haven't heard/noticed anything too weird.
