### ISSUE TITLE
support multiple profile pictures

### ISSUE THREAD

**Issue by putzenpu** [Trustroots/trustroots#1492]
Claudiu wrote to trustroots support:
Concerning the possibility of uploading more photos: [..]I can say that looking into someone's eyes I can almost immediately understand if that person makes me feel safe enough to want to spend some time with it or if there is something wrong about it and better to stay away. So from my perspective as hitchhiker, having more photos is a further safety measure. […] I would upload photos so that other "trustroot-ers" can have a better idea about me and be able to better decide if they want to meet or host me when I travel, and for me something that would better allow me to decide if I want to meet or host other trustroot-ers when they are traveling through my area.

**Describe the solution you'd like**
have an album with maybe up to 5 profile pictures.

**Additional context**
challenges:
* disc space on the server
* have people not use TR as their personal photo album?

See also https://trustroots.slack.com/archives/C08SENA9Z/p1590408641382400 on the team slack

**Comment by noahsmindfuck** [comment]
Link to slack convo about it
https://trustroots.slack.com/archives/C0A3Q15SS/p1597335118008600

**Comment by rumwerfer** [comment]
previous issue: #735

**Comment by baptx** [comment]
The issue seems to be still present so I guess it can be reopened? @chmac

**Comment by chmac** [comment]
@baptx We're in maintenance mode and so not adding new features.
