### ISSUE TITLE
Display user references

### ISSUE THREAD

**Issue by nicksellen** [Trustroots/trustroots#1494]
(issue part of overview issue https://github.com/Trustroots/trustroots/issues/1493)

There are three bits of information collected in a reference:

1. interactions (met, hosted me, hosted them)
2. recommend/experience (did you feel comfortable) - includes option to report them too
3. (optional) feedback text

Of the three bits of information, 1 and 3 would be publicly visible in some form, and 2 would be private (initially not used for anything, but for future uses, always kept private though).

The API is available for this (I think? need to double check), but it has not been designed yet, so there is some scope for thinking how it should be displayed, you can see this [previous PR](https://github.com/Trustroots/trustroots/pull/918) for some inspiration/code, but note that it does _not_ follow the above approach (i.e. 2 is public there), so don't use it directly.

One idea that came up could be to display 1 in a generalized way (e.g. _“this person has hosted someone within 6 months”_).

_Note: we did get into some confusion about this after the hackweek, I re-read all the discussions and I think this addresses everything I could find - so if you disagree and have a *critical concern* (i.e. blocking) about this approach, do say so, but otherwise remember we can always iterate/improve in the future_

Related discussions:
- https://wiki.trustroots.org/en/Meeting_Minutes/2020-04-13_Hackweek_-_references_session
- https://trustroots.slack.com/archives/C08SENA9Z/p1587373767234900

(If you want to work on this but have not been involved in previous discussions about it, it would be worth pairing up with somebody who has).

**Comment by noahsmindfuck** [comment]
I played around today with experience listing design... I don't know what the status is atm, maybe this can inspire someone or foster some debate. If anyoen wants to join the miro board to experiment: https://miro.com/app/board/o9J_lU8XQ6Q=/

![2021-02-12-193641_1920x1080_scrot](https://user-images.githubusercontent.com/24893086/107808616-2df62880-6d6a-11eb-928f-7cdcbc8f852a.png)
