### ISSUE TITLE
first newsletter and survey

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#150]
We should soon send out a newsletter to all members who agree to receive a newsletter. Ideally with some kind of simple survey with questions about what people think is important.

**Comment by simison** [comment]
Yep! For now we have [manual signups](http://ideas.trustroots.org/newsletter/) to newsletters + checkbox at signup. These aren't yet combined (#22).

**Comment by guaka** [comment]
Rough first draft
"Thank you for signing up with Trustroots! It's been a great ride. Since we started on December 23rd  xxxx people have signed up and we already know of some people who have found places to stay.

There is also a lot of activity behind the scenes. The current version of Trustroots is the most limited software you can imagine that still works for hospitality. The next steps will be adding a way to leave references and information about how much you trust (or not) your contacts.

We also want to quickly set up communities on Trustroots. That is, you can indicate that you are a hitchhiker, or that you want to host hitchhikers. Of course you can always decide to host people from any community. We're starting out with a limited number of communities, and we would like your input on which communities you first want to see on Trustroots. We also have some other questions that we would like to see your input on. Take the survey here.

You can also help us a lot if you're a JavaScript hacker, if you're good with words or if you have hands on experience with setting up a non profit in the EU."



Rough first draft for questions for survey:
* Which communities do you want to see first?
** Vegans and vegetarians
** Musicians
** Students (e.g. Erasmus)
** Families with children
** Hackers
** Bicyclists
** Party people
** *add some more*
** [free field]
* How much time do you think you spend on Facebook every week?
* Would you be willing to give money to Trustroots to continue our work? If yes, how much? 
** one time: 5 euro | 5-24 euro | 25-99 euro | 100 euro or more
** yearly: 5 euro | 5-24 euro | 25-99 euro | 100 euro or more 
* It helps us a lot if you can give us an idea about what you think is important. Which features (or other) are more important?
** Activities, events
** Group profiles (e.g. for bigger households or nomad bases)
** Trust features
** Legal non profit status
** Android app
* ''add more''

**Comment by simison** [comment]
Our first newsletter is out, sent for over 3K subscribers:
* Newsletter: http://eepurl.com/bxBR9L
* Blog: http://ideas.trustroots.org/2015/08/31/trustroots-is-now-10-000-members-strong/
