### ISSUE TITLE
edit button(s) broken

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#1505]
edit button on https://www.trustroots.org/donate takes me to
https://github.com/Trustroots/trustroots/edit/master/modules/pages/client/views/donate.client.view.html which is 404

probably relates to migration to react?

![image](https://user-images.githubusercontent.com/54728/83334106-26eebf00-a29c-11ea-836c-f4ccb2946f8a.png)

**Comment by simison** [comment]
Likely related yeah. I don't think nobody ever clicked on these though. 🙃

**Comment by simison** [comment]
Deployed the latest React stuff to production.

Looks like folks doing the migration took those out. 😁 Sorry!

I think best course of action would be to move our static pages to WordPress so that it's easier for the whole team to modify those.

**Comment by nicksellen** [comment]
> Looks like folks doing the migration took those out. grin Sorry!

Actually, that was [your call](https://github.com/Trustroots/trustroots/pull/1412#discussion_r412404699) @simison ;)

> I think best course of action would be to move our static pages to WordPress so that it's easier for the whole team to modify those.

Then they wouldn't be part of the translatable content of the site. I once built a site that use/abused wordpress to hold the content and display it in the site. Regretted it later :) 

I'll close this issue as there are no edit buttons to _be_ broken any more, but of course feel free to open and issue related to bringing them back...

**Comment by simison** [comment]
> Then they wouldn't be part of the translatable content of the site. 

Yep, pointed the same out above. That can be good thing in a sense that managing large blobs of content via another translation mechanism can be easier compared to managing interface texts. It's not uncommon to separate these.

WP itself has plenty i18n tooling and it's in the roadmap to make it "natively" i18n capable.

**Comment by simison** [comment]
To be clear, I don't think we should pull from external API (WP) into the app canvas. The browser should just navigate between static pages and the app.

For more content heavy pages such as FAQ this might make more sense.

They makes it also easier to link to those pages from mobile app.

**Comment by nicksellen** [comment]
Yup, could for sure be some improvements to make :) Hopefully a new issue will magically appear with a clear problem statement and/or idea!
