### ISSUE TITLE
Unexpected jump of cursor to newline when typing a message.

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#1506]
**Describe the bug**
I write a message. When I start editing at the end of line, the cursor jumps at the beginning of the next line after every keystroke. This doesn't happen when editing in the middle of the line or at the end of the last line.

**To Reproduce**
1. Write two lines of text
2. Go to the first line and start typing
3. The cursor jumps to the beginning of the second line. If there are any empty lines in between, cursor jumps to the beginning of the first following non-empty line.

**Expected behavior**
The cursor should stay where it is. Not jump unexpectedly.

**Screenshots**
The following happens when I type `aaaaa...`, `Enter`, `bbbbbb.....`, click at the end of the first line and type `ccccccc.......`
![image](https://user-images.githubusercontent.com/7449720/83540524-c1e3d500-a4f8-11ea-8196-b246f940e609.png)

**Desktop:**
 - OS: Arch Linux
 - Browser: Firefox
 - Version 76.0.1 (64-bit)

It happens on Chromium, too.

**Comment by nicksellen** [comment]
I can confirm I experience this too. It's my fault following the react migration...
