### ISSUE TITLE
confirmed contact still not visible in contacts list

### ISSUE THREAD

**Issue by roberts-gh** [Trustroots/trustroots#151]
Contact ("Frank") added to "David's" contact list, seems to be confirmed by "remove contact" on Frank's profile, upper-right.  But, David's list of contacts, still does not display Frank.

![frank](https://cloud.githubusercontent.com/assets/290852/5592840/b543ad82-91b4-11e4-8427-77075989e43e.jpg)
...
...
![john](https://cloud.githubusercontent.com/assets/290852/5592841/bdd71376-91b4-11e4-86ba-ae59ae792871.jpg)

**Comment by simison** [comment]
Does that contact show up at contact list before the other party has confirmed it? If not, then not an actual bug, but instead of "remove contact" it should say something else (like "cancel contact request" or "waiting for confirmation".

Dublicate #6 #124

**Comment by roberts-gh** [comment]
"instead of "remove contact" it should say something else (like "cancel contact request" or "waiting for confirmation". "

Agreed.
