### ISSUE TITLE
Site not accessible from my location.

### ISSUE THREAD

**Issue by kindaro** [Trustroots/trustroots#1517]
**Describe the bug**

I cannot access the site from where I am. It has been going on for a while — maybe a week.

I can connect if I change my apparent location by routing through a VPN. My assumption is that the IP address range is blocked from your side.

**To Reproduce**

1. Visit me in Saint Petersburg, Russia.
2. Connect to my Wi-Fi.
3. Try to connect to `trustroots.org` or `www.trustroots.org`.
4. See error.

**Expected behavior**
Site loads normally.

**Additional context**

    % curl --verbose 'http://www.trustroots.org'
    *   Trying 188.166.32.52:80...
    * Connected to www.trustroots.org (188.166.32.52) port 80 (#0)
    > GET / HTTP/1.1
    > Host: www.trustroots.org
    > User-Agent: curl/7.69.1
    > Accept: */*
    > 
    * Recv failure: Connection reset by peer
    * Closing connection 0
    curl: (56) Recv failure: Connection reset by peer

  

    % curl --verbose 'https://www.trustroots.org'
    *   Trying 188.166.32.52:443...
    * Connected to www.trustroots.org (188.166.32.52) port 443 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: none
    * TLSv1.3 (OUT), TLS handshake, Client hello (1):
    * OpenSSL SSL_connect: Connection reset by peer in connection to www.trustroots.org:443 
    * Closing connection 0
    curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.trustroots.org:443 

 

    % nmap 'www.trustroots.org' -p 443
    Starting Nmap 7.80 ( https://nmap.org ) at 2020-06-10 21:30 +03
    Nmap scan report for www.trustroots.org (188.166.32.52)
    Host is up (0.21s latency).

    PORT    STATE SERVICE
    443/tcp open  https

    Nmap done: 1 IP address (1 host up) scanned in 0.51 seconds

 

    % sudo tcptraceroute -n 'www.trustroots.org' 443
    Selected device wlp2s0, address 192.168.1.128, port 51561 for outgoing packets
    Tracing the path to www.trustroots.org (188.166.32.52) on TCP port 443 (https), 30 hops max
    1  192.168.1.1  1.433 ms  1.212 ms *
    2  109.195.88.57  136.303 ms  81.641 ms
        109.195.88.61  3.505 ms
    3  * * *
    4  * * *
    5  * * *
    6  * * *
    7  * * *
    8  * * *
    9  188.166.32.52 [open]  115.270 ms [closed]  0.014 ms [open]  189.892 ms

**Comment by simison** [comment]
Hi! Yes, the Russian government is blocking a lot of IPs and ours happens to be in the range. :-(

I think their original attempt is to block Telegram messenger, and we happen to be in the range by accident, and it's for my knowledge. We're not blocking access from our side for anything.

It's not all the ISPs in Russia though, so e.g. accessing via mobile internet might work.

Sorry for the trouble and I hope this information helps to bypass the government ban!

**Comment by kindaro** [comment]
@simison  Thank you, good to know!
