### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#152]
Compact, snappy and all covering. If possible, all that at once.

https://www.trustroots.org/#!/faq

**Comment by roberts-gh** [comment]
Q: Why doesn't TR have XYZ feature?
A: We never thought of that, go ahead and add it yourself!

;)

**Comment by guaka** [comment]
There are some more things to add....

Q: Is Trustroots exclusively for hitchhikers?
A: In the initial phase we're focusing on getting hitchhikers on board. Many people who hitchhike have a specific way of traveling that is not always well served by some websites. Hitchhikers are also traveling a lot more than the average Joe, which is a good way to spread the idea further. We don't exclusively focus on hitchhikers though and you're welcome to sign up if you've never hitchhiked. We'll soon add functionality that will make it convenient for people who prefer to host people from within their communities (e.g. vegans, musicians), but it'll always be possible to open your home to anyone on the site if you prefer.

Q: Why the name Trustroots?
A: We were brainstorming about a name. We liked the name Trustroots. Back to roots. And most of all, the domain names were free. We also have some innovative ideas that can help building trust among our members and once the network is big enough we'd love to work with scientists to build something that can really make a difference through trust metrics.

Q: What's your legal status?
A: Good question. We're looking to set up a non profit in the EU soon. Contact us if you have experience with this and you want to help.

Q: Are you going to sell out?
A: NO! We think it's a shame that former non profits have been sold to venture capital.

Q: Decentralize it?
A: Yes please! If you can make a working decentralized prototype we'll happily decentralize the whole thing. Decentralization is not the team's priority though. But we will soon add a quick and easy way to export your profile data, oauth and some API stuff.

Q: How do you want to make the project financially sustainable?
A: Not sure. Donations and grants are possibilities. Again, if you have experience with this it would be great if you contact us.

Q: Why is there no forum?
A: The practical answer: It takes time to set up a forum and even more time to keep it spam-free.  The less practical answer: In our long-term and short-term experience forum activity is not necessarily the best way to get to more real life interactions (or in other less nice words: there's a lot of pointless bickering out there).  In the long term we do want to provide a way to communicate on the site, but this will probably look more like the quick and easy way you can interact on Facebook or Diaspora than a full fledged forum.

Q: What is your long term vision?
A: "We want a world that encourages trust, adventure and intercultural connections." See https://www.trustroots.org/#!/about for more.


[feel free to edit these words - if stuff is not deemed appropriate for the FAQ, move it to the blog as a draft]

**Comment by simison** [comment]
Edited + wrote some more. Feel free to edit/cut bits out:

***Is Trustroots exclusively for hitchhikers?***
In the initial phase we're focusing on getting hitchhikers on board and making the site ideal for that. Many people who hitchhike have a specific way of traveling that is not always well served by some websites. Hitchhikers are also traveling a lot more than the average Joe, which is a good way to spread the idea further.
We don't exclusively focus on hitchhikers though and you're welcome to sign up if you've never hitchhiked. We want to maintain the small community feeling at the site and we have some technical ideas for this. We'll soon add functionality that will make it convenient for people who prefer to host people from within their communities (e.g. vegans, musicians), but it'll always be possible to open your home to anyone on the site if you prefer.

***Why the name Trustroots?***
Back to roots. Earthy. The art of asking — and trusting — is something we often experience while traveling. We also have some innovative ideas that can help building trust among people and once the network is big enough we'd love to work with scientists to build something that can really make a difference through trust metrics. Roots is a network.

***What's your legal status?***
Good question. We're looking to set up a non profit in the EU soon. Contact us if you have experience with this and you want to help.

***Are you going to sell out?***
NO! We think it's a shame that former non profits have been sold to venture capital. We have high ideals and we've been running other big freegan projects for years. This is not a startup.

***How do you want to make the project financially sustainable?***
Donations and grants are the most likely ways. There are many inspiring organisations out there giving great examples: [Wikimedia](https://wikimediafoundation.org/), [Mozilla](https://www.mozilla.org/en-US/foundation/), [Amnesty International](http://www.amnesty.org/) and many more. Again, if you have experience with this it would be great if you contact us.

***Who decides what gets done?***
You are welcome to join brainstorming and development [at GitHub](https://github.com/Trustroots/trustroots/) — we're huge fans of do-cracy and getting things done attitude. Great community values simple translation job to the same level as highly skilled development. We'll aim to keep the entry level for volunteers as low as possible. No bureaucracy. Pragmatic approach. Trust.
This said, any great project needs efficient teams working on specific issues (such as _safety_ or site's _features and usability_). Rather than building complicated voting mechanisms or other structures, we'll try to concentrate in fostering volunteers into responsible, skilled teams. It's also important to make sure everyone has the same goal and vision.

***Why is there no forum?***
The practical answer: It takes time to set up a forum and even more time to keep it spam-free. The less practical answer: In our long-term and short-term experience forum activity is not necessarily the best way to get to more real life interactions (or in other less nice words: there's a lot of pointless bickering out there). In the long term we do want to provide a way to communicate on the site, but this will probably look more like the quick and easy way you can interact on Facebook or Diaspora than a full fledged forum. We have plenty of ways how to contact us and have discussions.

***How can can I contact you?***
In plenty of public and private ways: [our blog](http://ideas.trustroots.org/), [contact form](http://ideas.trustroots.org/contact/), [GitHub](https://github.com/Trustroots/trustroots/issues), [Twitter](https://twitter.com/trustroots), [IRC](http://webchat.freenode.net/?channels=trustroots) and for private contacts see [the team](https://www.trustroots.org/#!/team) page.

***Why is there Facebook connection?***
So that those who have their data and connections there, could free their Facebook data to Trustroots. Read [our blog post about this](http://ideas.trustroots.org/2014/12/29/life-outside-big-blue-box/).

***Are you planning to do X feature?***
See our [todo](https://www.trustroots.org/#!/todo) for main parts and [GitHub](https://github.com/Trustroots/trustroots/issues) for the rest. Feel free to [tell us](http://ideas.trustroots.org/contact/) about your ideas! We're at the very early phase and we simply haven't got time for the most of it. Please be patient.

***Decentralize it?***
Yes please! If you can make a working decentralized prototype we'll happily decentralize the whole thing. Decentralization is technically very challenging and is not the team's priority though. But we will soon add a quick and easy way to export your profile data, oAuth and some API stuff.

***How is this connected to Hitchwiki, Nomadwiki or Trashwiki?***
The team who created Trustroots also created these projects. We will want to integrate them to Trustroots to some degree due these projects share pretty much the same vision and user base.

***What is your long term vision?***
_"We want a world that encourages trust, adventure and intercultural connections."_ See [about](https://www.trustroots.org/#!/about) for more.

**Comment by simison** [comment]
Added this to the code (not in production yet), edits welcome directly there: https://github.com/Trustroots/trustroots/blob/master/public/modules/pages/views/faq.client.view.html

**Comment by libertedeparole** [comment]
"(I'll see tomorrow how to shorten this a bit...)"

Let me know. I'll do a grammar check. There are only a few minor problems, but I'd prefer to wait for your rewrite.

David

**Comment by simison** [comment]
@libertedeparole Yo! Here, [the most recent version](https://www.trustroots.org/#!/faq). You can either post here or write [down to the pad](https://lite5.framapad.org/p/proofreading-trustroots) if that feels easier. Thanks a bunch!

**Comment by guaka** [comment]
"Wikimedia, Mozilla, Amnesty International" might sound a bit pretentious. At least add some of these: Warmshowers Foundation, Abgefahren e.V., BeVolunteer, Servas, WWOOF and similar small/medium orgs.
Also possibly a couple of words about how we want to maximize money spent on realizing the mission and how we prefer do-ocracy over bureaucracy?

**Comment by simison** [comment]
I also thought the do-ocracy bit just now when washing dishes.

Man, like probably half the bugs etc are actually fixed while thinking during shower/dishwashing/sunset strolls. :-)

You're right about foundations, I'll edit it.

**Comment by guaka** [comment]
I know! But I'm still planning to get a dishwasher in my next home!
​
