### ISSUE TITLE
in message view (small screen sizes), profile overview box links to own profile instead of conversation partner's

### ISSUE THREAD

**Issue by putzenpu** [Trustroots/trustroots#1539]
**Describe the bug**
When you click on the box showing summary info about your conversation partner, you get your own profile shown.

**To Reproduce**
1. resize your browser window to something small or use a mobile browser
2. open a conversation with someone
3. click on the box showing your convo partner's profile (it is a link)
4. get redirected to your own profile
The bug only appears when you have a small browser window after the breakpoint

**Expected behavior**
Instead, you should get redirect to your conversation partner's profile

**Screenshots**
![Bug_screenshot_wrong_link](https://user-images.githubusercontent.com/64162694/85198627-63856780-b2ea-11ea-8fa0-3daccc8106ef.png)

See how the link indicated in the firefox footer differs from the user name of the convo partner

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser firefox

Thanks to Ani for spotting this!

**Comment by simison** [comment]
Fixed in https://github.com/Trustroots/trustroots/pull/1609
