### ISSUE TITLE
Suspended users visible in map search

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#1554]
**Describe the bug**
User with role 'suspended' AND 'hidden profile' shows up on the map.

https://trustroots.slack.com/archives/C0A3Q15SS/p1593181377203600

Maybe related: #1189

**Comment by TMC89** [comment]
Does this also mean members that are "shadow banned"? Because we now want to try to use this function more instead of suspend members, because some keep making new profiles. Any way it would be great, safety wise, if this bug would be resolved :)

**Comment by noahsmindfuck** [comment]
Possibly check if they are visible for non-admin users. I don't know the status of the bug atm.
