### ISSUE TITLE
Captcha at signup

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#156]
Implement CAPTCHA for signups. Had a few bounced emails and by the looks of it a few spambots got trough. Before they come in swarms, this has to be implemented.

E.g. modify from [VisualCaptcha](http://visualcaptcha.net/ ) or rather some hosted version such as  reCaptcha.

**Comment by simison** [comment]
Ah, wrong alert; they were fake emails from the test-DB. I'll just switch my gateway back to the debug one so that production one doesn't get garbled by debug bounces. :P

Postponing for later.

**Comment by chmac** [comment]
Do we really need a captcha? I'd guess email verification is OK for a long while. I'm not strongly opposed to captchas, but I think it's better to remove barriers to signup where possible. I'll assume we don't need this, but feel free to re-open if you think we do.
