### ISSUE TITLE
Choose displayname

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#157]
Options:
- Firstname Lastname
- Lastname Firstname
- Firstname
- Lastname
- Username

Or is this not important at all? From other sites I've been developing/following this seems to be an important matter for some people. Wordpress also has a feature exactly like this.

Now this is saved to the DB as "Firstname Lastname" at the [controller](https://github.com/Trustroots/trustroots/blob/master/app/controllers/users/users.profile.server.controller.js#L111) but it could be at [model](https://github.com/Trustroots/trustroots/blob/master/app/models/user.server.model.js) as well. Adding one select field + validator in between would not require too many lines of code.

**Comment by libertedeparole** [comment]
I think you should use first-last.
It's called "first" and "last" for a reason  ;-))
All Western newspapers use first-last order for names, unless the person comes from a non first-last country or tradition. In that case, the general situation is confusion. Some countries like France use last-first in some circumstances, but not in others.
Eastern cultures that use family names first are all used to using "Western order" in international contexts, or at least aware there is a "problem", as are other people whose culture uses other orders.. Many Westerners are unaware of the dilemma.
I think giving user-control would just increase confusion.
It would be possible (if not aesthetic) to indicate "family name". But even that doesn't always correspond to naming conventions in some cultures.

**Comment by guaka** [comment]
Bikeshed! ;)

**Comment by simison** [comment]
Totally, long long term bikeshed. ;-)
