### ISSUE TITLE
A customisable filter (and sort) to search for users based on their response rate on the map or in a city.

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#1573]
The problem is with users who are less active, it's difficult to define what makes a user less active and the problem is you don't want travelers ignored from too many hosts, otherwise they'll be frustrated and leave the community thinking it does not work.

One way to try to solve this would be to allow users to choose how much effort they want to spend and on which users specifically, this is why filtering is a good feature, filtering according to user response rate allows for different users setting a different level of tolerance and also getting a more probable way of getting an answer. Users can also lower the rate if they see that they are not getting any suggestions for specific difficult areas and bump it up again in a different area.

A nice side effect will be, that users would like to have a high response rate because now they will just get much fewer requests if they have a lower response rate, and we can also set a default filter (for example users with 5 % response rate will not be shown but if someone is really willing to try anyway they can reach these people as well)

I think alternatives would be just nice to have as extras but this feature is a really nice feature that does not hurt to have and imho will extremely help with frustration rates of people not getting any answers. Maybe another idea will be to eventually add a parameter which shows how many people asked for a request and got denied and going even further and more controversial, checking which people were denied and how your chances are (old/young, man/woman), so basically a diversity rating.

I couldn't find any library online because I didn't figure out the right keywords but I made a [short video](https://photos.app.goo.gl/RwSimNFnfV54ESHx9) describing something resembling what I think would look good and I added some pictures as well.

![image](https://user-images.githubusercontent.com/31655082/86177158-6e2fd000-bb26-11ea-8deb-41bd2e2923ac.png)

![image](https://user-images.githubusercontent.com/31655082/86177247-93244300-bb26-11ea-92a3-8a281b78854c.png)

![image](https://user-images.githubusercontent.com/31655082/86177252-96b7ca00-bb26-11ea-9ddd-61e19158b9ca.png)

**Comment by simison** [comment]
Thanks for elaborating on idea and for designs! Very helpful.

I think we can simplify this to two aspects that is easier for user to understand and easier for us to implement.

**Show reply rate in profile card that shows up when you click on offer-dot.**

That'll help people manually estimate if they want to invest sending a person a message. Just showing info to people and letting them "manually" filter in their mind is often more helpful than the actual filter, considering that many areas have very few hosts. That way they can prioritize sending to people who have higher reply rate, but also see lower rate profiles. Many profiles also just don't have known reply rate, if you didn't get messages in many months.

It can also be challenging for user to adjust such filter. What does 40% mean? Is it good? Replies in 2 days can be great or really bad depending on your situation.

**Add toggle that filters out people who absolutely don't reply**

There could be simple on/off filter for hiding profiles that we know for sure won't reply. If someone's reply rate is 0%, why bother? Toggle could be on by default and called something like "Hide inactive members". Could even be combined into already existing time-based filter.

These could be implemented independently from each other and get us very far in the idea without a ton of coding or making it very complex UI.

Finally... Let's first check the data if this even is an actual problem to solve. 😁 We already hide based on time — perhaps everyone who has low reply rate also didn't login for a while and thus already gets filtered out. No point implementing something that has no affect. If you can help write a MongoDb query that groups by last seen date and reply rate, I could run that against production data.


What do you think?

**Comment by chagai95** [comment]
Great thoughts, I'm happy of going in any direction on this, I do think a filter would be nice, we can make all the stuff you wrote about first and then after that maybe add a filter without GUI (just type in the percent from 0-100) and eventually get to implementing something nicer, this could also be a thought for very, very long term and a nice precaution for scaling.

Also, this is probably not the place but I would love to discuss how the rating is set now, how it is set on other platforms and if we can come up with better ideas, because in my opinion this will be one of the key features that could make such a platform work well.

I think in the long term it might get annoying going through all the people and checking what their reply rate is.

I would gladly write a query but I think there is a huge difference between offline for a long time and a low reply rate even if it does currently correlate, I clearly remember months of not logging in to Couchsurfing but answering in minutes because I got an email saying someone wrote me.

Adding a toggle that filters out people who do not reply is a great idea but sorting them to show at the bottom is even better I think. In general sorting is better than filtering I think but since I am seeing that we only work with a map (am I write?) filtering is necessary unless we spend more time on GUI and getting the rate to show on the map, which could perhaps be a nice thing (long-term). I don't think there is much of a difference though between people who do not answer at all and people who answered once or twice out of 100 times, but this is going a little back to me wanting to understand more how we rate and also putting in more effort, so I completely agree that a toggle will be great!

**Comment by simison** [comment]
> Great thoughts, I'm happy of going in any direction on this, I do think a filter would be nice, we can make all the stuff you wrote about first and then after that maybe add a filter without GUI (just type in the percent from 0-100) and eventually get to implementing something nicer, this could also be a thought for very, very long term and a nice precaution for scaling.

I'm not big fan of flexible percentage filter as UI because finding an exact percentage limit is pretty arbitrary decision to make as a user and would likely need some trial and error. Turning it into "yes/no" filter would be much easier on them cognitively. We can likely figure out good default that most would agree is useful and use that? Not super tied to this opinion though and maybe a freeform input makes a great advanced filter.


> I think in the long term it might get annoying going through all the people and checking what their reply rate is.

I agree, and it's useful to design features for amount of users we have now (low) rather than for potential future, and also make something that we can ship sooner. It's a good first step to see if the filter still feels like a necessary thing or if this was enough or not.


> I would gladly write a query but I think there is a huge difference between offline for a long time and a low reply rate even if it does currently correlate, I clearly remember months of not logging in to Couchsurfing but answering in minutes because I got an email saying someone wrote me.

Yes, that's my gut feeling too but would be great to confirm it with data and see what patterns we can see there. Maybe the conclusion is that we need to make time limit longer or shorter? Or something else. 

I don't even know how many hosts have a reply rate at all — maybe it's very few?


> In general sorting is better than filtering I think but since I am seeing that we only work with a map (am I write?) filtering is necessary unless we spend more time on GUI and getting the rate to show on the map, which could perhaps be a nice thing (long-term).

Correct, we sadly cannot do sorting yet. You're right in that it would be useful now that we finally have more members on the map, but it's also a bit bigger project to do so not useful for this convo.

We should document how the reply rate exactly works if not only for ourself but possibly also in public FAQ.

**Comment by chagai95** [comment]
> I'm not big fan of flexible percentage filter as UI because finding an exact percentage limit is pretty arbitrary decision to make as a user and would likely need some trial and error. Turning it into "yes/no" filter would be much easier on them cognitively. We can likely figure out good default that most would agree is useful and use that? Not super tied to this opinion though and maybe a freeform input makes a great advanced filter.

Ok so perhaps long-term, I think an extra filter which is a little "hidden" could save a lot of effort for power users and that is a low priority, but I think it's cool...


> > I would gladly write a query but I think there is a huge difference between offline for a long time and a low reply rate even if it does currently correlate, I clearly remember months of not logging in to Couchsurfing but answering in minutes because I got an email saying someone wrote me.
> 
> Yes, that's my gut feeling too but would be great to confirm it with data and see what patterns we can see there. Maybe the conclusion is that we need to make time limit longer or shorter? Or something else.

Sure thing, I just want to point out that this is going in the direction of big data and statistic, I'll gladly try to write a query but I don't feel comfortable with big data I feel like I'm guessing, so I'll leave that part to you.

> > In general sorting is better than filtering I think but since I am seeing that we only work with a map (am I right?) filtering is necessary unless we spend more time on GUI and getting the rate to show on the map, which could perhaps be a nice thing (long-term).
> 
> Correct, we sadly cannot do sorting yet. You're right in that it would be useful now that we finally have more members on the map, but it's also a bit bigger project to do so not useful for this convo.

Another GitHub issue?

> We should document how the reply rate exactly works if not only for ourself but possibly also in public FAQ.

Should I add this as a task somewhere?

**Comment by simison** [comment]
I bet the query to pull those stats should be pretty straightforward and no big data at all. ;-) Happy to get something going for it tho to get ball rolling and we can maybe collab on getting the data answers covered?

**Comment by chagai95** [comment]
Data answers? I think it'll take me some time to get around to understanding where what is in the database, can you point me in the right direction, so I can start figuring it out already?

**Comment by xeruf** [comment]
Hey, is this still moving? In the Berlin area for example there are many hosts, and the filter by online in the last 6 months is not sufficient since you still get lots of inactive ones as result.

**Comment by chagai95** [comment]
Sorry, I don't yet try to tackle this.
