### ISSUE TITLE
Show some stats from other networks at profile

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#158]
Possibilities:
- [ ] number of friends/followers/contacts
- [ ] registration time
- [ ] number of edits/contributions (on github, wikipedia, hitchwiki etc)

Useful Facebook docs:
- https://developers.facebook.com/docs/graph-api/reference/user
- https://developers.facebook.com/docs/graph-api/reference/user-context/
- https://developers.facebook.com/docs/graph-api/reference/v2.3/user/friends

**Comment by platschi** [comment]
just came up to our mind; so far commercial stuff like facebook and twitter "links" can pop up on somebody's profile; but much more important, what about links to the respective somebody's hitchwiki (nomadwiki/trashwiki) profile !? would be great to link my hw profile (User:XXX) to Trustroots. Same with hitchlog.

(hope I catched the right issue, if not, please move)

**Comment by simison** [comment]
Yepp! We'll be adding oAuth to Hitchwiki in ~March when new version goes to production, so we'll finally be able to do exactly that. :-)

**Comment by guaka** [comment]
Maybe this is not really needed anymore?

**Comment by simison** [comment]
If it wasn't for such a long time, nope. And apis aren't great to need to maintain.
