### ISSUE TITLE
Birthdate gets 1 day subtracted after editing and saving

### ISSUE THREAD

**Issue by Skeith00** [Trustroots/trustroots#1584]
**Describe the bug**
An Issue reported to Support:
When you set the birth date, after you click 'save', it subtracts 1 from the date you set.
So I tried it, and if I put 20, it goes to 19...  if you put 1, it goes to the previous date on the calendar (from April 1 it saved March 31)

**To Reproduce**
1. Go to 'Edit Profile'
2. Set Birthdate to '01/04/1981'
3. Save Profile
4. Date is stored as '31/03/1981'

**Expected behavior**
Date stored should be '01/04/1981'

**Additional context**
Some users haven't been able to reproduce this error.

https://trustroots.slack.com/archives/C0A3Q15SS/p1593983250292400

**Comment by simison** [comment]
Funny bug. :-)

So on clientside there is some datepicker library, and date gets passed as a string via API to backend, where it's stored in DB as MongoDB  Date.

I think I'd start looking what's the format date gets passed to API, and doing testing with API only to see if it can be replicated without anything from clientside.

If not, then it's something in the clientside.

**Comment by Pramuspl** [comment]
What I can imagine is happening is that the date is saved correctly but the user's browser shifts "1981-01-04T00:00:00.000Z" to 3rd of January if the timezone is negative to UTC. I'll take a look at it.

**Comment by Totalus** [comment]
That's exactly what's happening @Pramuspl
