### ISSUE TITLE
Option to set unavailable days to host

### ISSUE THREAD

**Issue by RebelMermaid** [Trustroots/trustroots#1588]
**Is your feature request related to a problem? Please describe.**
User received multiple request on the same dates.

**Describe the solution you'd like**
Option to block out dates to be unavailable for hosting

**Describe alternatives you've considered**
None mentioned

**Additional context**
Request submitted by user ticket #3490

Add links to discussion on Slack (or Discourse).
[https://trustroots.slack.com/archives/C016UTYBGAY/p1594130955002500](url)

**Comment by rumwerfer** [comment]
+1 in support

**Comment by rumwerfer** [comment]
+1 in support
