### ISSUE TITLE
Map centered in Europe as default even though I'm in the Americas

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#1604]
I'm always frustrated when I log in because the default is the map(search) and it shows me Europe

The map should be centered according to my location (either my device location if enabled or the city I live in if not enabled ).

Me and Mariano made a short screen cap, take a look to see exactly what we mean.

**Comment by mariyanomaiyademedeiyros** [comment]
Sharing soon, just waiting for my internet to allow Google Photos to finish the upload 🙏🏼

**Comment by mariyanomaiyademedeiyros** [comment]
There you go:
https://photos.app.goo.gl/5FaBKg6pAhrn1mUR9
