### ISSUE TITLE
Wrong routing on the top image inside a conversation, Android

### ISSUE THREAD

**Issue by nonno** [Trustroots/trustroots#1613]
**Describe the bug**
Wrong routing on the user image visible on the top in a conversation.

**To Reproduce**
1. Go to 'Messages'
2. Open a conversation with another member
3. Tap on the (other) user profile image

**Expected behavior**
It should open their profile, while it opens the current user one.

**Screenshots**

**Smartphone (please complete the following information):**
I can see it on many Android devices with different Android versions, on the web it works.

**Additional context**
Routing on the smaller images along the conversations are correct, only the big one on the top is wrong.

**Comment by simison** [comment]
Hi! Thanks for the report!

We just fixed this in https://github.com/Trustroots/trustroots/pull/1609 and it's just pending deploying. I'll get that sorted out soon!
