### ISSUE TITLE
Max number of guests jumps back to 1

### ISSUE THREAD

**Issue by movingpaw** [Trustroots/trustroots#162]
Recently I changed the number of guests I can host at a time. Since then it keeps on jumping back to 1, no matter how many I indicate on the hosting page.

**Comment by simison** [comment]
Interesting, I got a report today about the same thing but couldn't re-produce it.

**Comment by movingpaw** [comment]
Yes, using Firefox on windows8 at the moment, only adblock+ installed, but deactivating it doesn't help. I also shift+refreshed both pages (profile and hosting page) to no avail.

**Comment by guaka** [comment]
Is it a laptop with or without a touchscreen?
I've seen weird things because of that on Windows 8.

**Comment by simison** [comment]
Another user also reported the same issue with Windows 7 Firefox + Chrome.

**Comment by roberts-gh** [comment]
Doesn't this _have_ to be on the server (code) side, not the user's OS/config? No?

**Comment by movingpaw** [comment]
I'm using a laptop without touchscreen (and in desktop mode, not the metro UI). The issue remains when I try to change the number using Firefox on my Android phone, by the way. Same for IE on Win8.

(I also changed my hosting status from "maybe" to "yes" around the same time the issue appeared, but I'm not sure whether this has anything to do with it. I might have changed my hosting status after changing the number, without noticing the issue first. Changing back and forth between yes/maybe/no now doesn't help either.)

**Comment by simison** [comment]
Thanks guys! I'll try to do some heavy testing for this as soon as possible. Got to setup my Windows test env just first and it'll take a while.

**Comment by guaka** [comment]
"issue remains when I try to change the number using Firefox on my Android
phone"

Then I guess the best way to test it is to log in as movingpawon on a dev
copy of the site.

**Comment by roberts-gh** [comment]
my fellow tech geeks... now coining, for future use..."INTUF" It's Not The User's Fault

;)

**Comment by simison** [comment]
Found the problem (wrong native html input pattern). Occurred only with some browsers and only after updating to Angular 1.3 (from 1.2). Apparently Angular is now more strict with validators.
