### ISSUE TITLE
Graphs on statistics page are outdated (time range is hardcoded)

### ISSUE THREAD

**Issue by hlibbabii** [Trustroots/trustroots#1650]
Graphs on the statistics page ('Member growth' and 'Number of messages sent') are outdated and show stats only before 2019. Seeing the stats not being updated for two years might discourage people from signing up. 

From the technical point of view, the problem is that the 'to' parameter in the request to grafana is now hardcoded:

    https://grafana.trustroots.org/render/d-solo/000000001/messages?panelId=3&from=1419289200000&to=1543142370362

Instead the today's timestamp should be passed with the request.

Steps to reproduce:
1. Go to https://www.trustroots.org/statistics
2. Scroll down to 'Member growth' and 'Number of messages sent' graphs 

![image](https://user-images.githubusercontent.com/2955794/89730953-ab4f8200-da43-11ea-8258-adc77516a615.png)

**Comment by simison** [comment]
I think this needs some plugin to be installed on Grafana before it can be made more flexible: https://github.com/Trustroots/trustroots/issues/1464
