### ISSUE TITLE
trustroots.org DNS: low TTL

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#167]
`trustroots.org.		86081	IN	A	188.166.32.52`
`www.trustroots.org.	43906	IN	A	178.62.110.65`

as long as we want to change IP addresses quickly TTL should be ≤3600 sec

**Comment by simison** [comment]
>ah, funny, I thought it was 3600
>looking at joker now, their dashboard sucks
>it says "3600" on top of the row so I thought that's for all the domains in that row. apparently only for ideas.trustroots.org

Oh well, lessons learnt.
