### ISSUE TITLE
Unit tests currently broken due to config file issue

### ISSUE THREAD

**Issue by otupman** [Trustroots/trustroots#168]
As per local & Travis, the tests fail because of a missing `test.js` in ye olde config/secret directory.

Funnily enough, I might just have a fix for that hiding around the corner...

:athletic_shoe:

**Comment by otupman** [comment]
Et voila, possible fix in PR https://github.com/Trustroots/trustroots/pull/169

**Comment by simison** [comment]
Thanks! I'll have a look at this today/tomorrow — whole test set is now mostly relying on MEANJS generators and cover only very basics of things. #34

**Comment by simison** [comment]
Fixed with PL & https://github.com/Trustroots/trustroots/commit/b3cae897d59eba3d843ab534f9f71584464bc9ca
