### ISSUE TITLE
No languages shown for profile on message page

### ISSUE THREAD

**Issue by Lemoert** [Trustroots/trustroots#1692]
For a profile that have more languages shown, this information is missing from the brief summary on the messaging page. See attached screenshots.

On Fedora 31, latest Firefox. No such profile information when opening website on Android.

![Screenshot_2020-08-25_17-20-44](https://user-images.githubusercontent.com/44477593/91335579-e33f1f00-e7d0-11ea-93c3-966ce80b8352.png)
![Screenshot_2020-08-25_17-21-01](https://user-images.githubusercontent.com/44477593/91335580-e3d7b580-e7d0-11ea-9398-8c305c7bd67d.png)

**Comment by hlibbabii** [comment]
I think this issue is gone now. Has this been fixed by #1969, @simison ?

**Comment by simison** [comment]
Yep! Works now:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/87168/109503445-f0e8a080-7aa2-11eb-93db-3963597de9ad.png">

Thanks for triaging 👍
