### ISSUE TITLE
Protecting host privacy regarding exact location

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#1734]
In the current map anyone can see where hosts live, which is a privacy issue. It is also not clear that the address will be so public when asked to enter the address.

We could show a shaded circle of the area instead of the exact location, just like on AirBnB.

Perhaps adding the possibility to not be shown on the map at all until you agree to host?

We heard this feedback from some users who expressed this issue.

**Comment by simison** [comment]
Thanks! It indeed works exactly like Airbnb: it has several hundred meters of fuzziness.

I think it's also written somewhere in interface when adding hosting location? That can of course always be improved if it wasn't clear?

**Comment by MrSalami** [comment]
Thanks for the answer Michael. There is a fuzzy bubble for the host on the profile, but in the generic map, the bubbles appears to be quite small and upon zooming in goes onto a specific house or location. Is that to say that that spot is not really the location of that host that you can then click on?

**Comment by simison** [comment]
Correct. The dot is fuzzy even if it visually seems "exact". The bubble is there as well in theory but as you zoom out, the fuzzy area becomes so small relative to map's zoom level that it doesn't make sense to show it any more.
