### ISSUE TITLE
Adblocker hides "other networks links"

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#1735]
If you have entered a link to Warmshowers, Bewelcome or Couchsurfing in your profile, it won't show up on your public profile anymore.

1. Add a link to another hospitality network in your profile (Edit profile -> Networks)
2. Go to your profile 
3. Section "Elsewhere" on bottom left will stay empty

**Comment by mkamranhamid** [comment]
just followed the steps to reproduce and found it working fine

**Comment by rumwerfer** [comment]
@mkamranhamid thanks for the hint. I checked with different browsers and it seems to be exclusive to Firefox

**Comment by rumwerfer** [comment]
I tried to investigate a bit further, and in uBlock Origin the blocking is caused by those 2 lists: "Fanboy's Social" and "Fanboy's Annoyance". Both lists simply block the section because **the CSS class is called .social-profiles**. ("Fanboy's Annoyance" additionally blocks couchsurfing.com as a whole :D)

Since our motivation for these links is trust, not advertisement, I'd suggest we rename the CSS classes. Other ideas?

**Comment by simison** [comment]
Sounds straightforward enough to just change CSS classes to something else 👍
