### ISSUE TITLE
Activertypub support

### ISSUE THREAD

**Issue by Openmedianetwork** [Trustroots/trustroots#1745]
**Is your feature request related to a problem? Please describe.**

Currently trustroots is a silo - would be good if it joined the network - the way to do this is activertypub.

**Describe the solution you'd like**
maybe start with something simple publish the events as activertypub acter?

**Describe alternatives you've considered**
have a look at the fedivers.

**Additional context**
we are building out the news part by rebooting the indymedia project https://unite.openworlds.info/explore/organizations

Add links to discussion on Slack (or Discourse).
we are useing jabber ;) chat is a mess sadly.

**Comment by simison** [comment]
Hi! Thanks for writing to us. :-)

The only thing that we're not a "social network" in the sense that all the messages between members are private, so there isn't much to pub/sub either.

Let me know if I understood activertypub wrong tho!

**Comment by rumwerfer** [comment]
continue discussion here: #2287
