### ISSUE TITLE
Broken language picker on the homepage when unlogged (on dev2)

### ISSUE THREAD

**Issue by hlibbabii** [Trustroots/trustroots#1827]
**Describe the bug**
Language picker on the homepage when unlogged is broken (not in production yet)

**To Reproduce**
1) Turn on the incognito mode in the browser and go to https://dev2.trustroots.org/
2) Try changing the language in the top right corner

**Expected behavior**
The dropdown should open, and the user should be able to choose the language

**Screenshots**
![image](https://user-images.githubusercontent.com/2955794/99158262-47d39100-26d1-11eb-826b-45c2532da701.png)

**Fix options**:
- Try using more elaborate UI component like https://www.npmjs.com/package/mui-language-picker
- Mikael's colleagues are working on language picker component which is pretty solid: https://github.com/Automattic/wp-calypso/tree/master/packages/language-picker — might not work on our codebase.

**Comment by hlibbabii** [comment]
@simison I tried looking into it today, but with my poor CSS knowledge, couldn't understand what's wrong. Might give another try tomorrow, and also look at other components you suggested.

**Comment by simison** [comment]
I suspect it's the whole React-Bootstrap component that has broken at some point.

**Comment by chagai95** [comment]
I guess this could be a blocker for releasing?

**Comment by simison** [comment]
There's a language switch also at the account page that works, so I wouldn't consider a blocker. But a really nice thing to fix for sure :-)

**Comment by simison** [comment]
Resolved in https://github.com/Trustroots/trustroots/pull/2142 with a modal.
