### ISSUE TITLE
Add experience count to profile

### ISSUE THREAD

**Issue by hlibbabii** [Trustroots/trustroots#1840]
Part of the ongoing work on the experiences feature #1493 

**This issue summarizes the cons and pros of having the count of experiences added to the profile and ideas of how this count could be shown.** In addition to the total count of experiences, we can also show counts for some specific categories of experiences (e.g. negative, neutral, positive, if we finalize our decision to differentiate them like that, TODO link to the non-existent (?) yet issue).

**Might be related to the following replies** (What people don’t like with references) **from the** [user survey](https://codi.kanthaus.online/s/member_survery_references):

_OPINION-1: creates a market/competition of exchanging/having references (8 people)
OPINION-2: contacting hosts with many references bc. chance of being hosted is increased. Leads to the wrong assumption about people and keeps you from meeting unexperienced hosts (1 person)
OPINION-3:  lots of positive references made people feel uncomfortable to leave negative references (1 person)_

**The total number of experiences:**
- Specify the exact total number 
    + allows to immediately understand how much experience the user has
    + this is the UI people would expect(one expects some number when there is a list of something)
- Experience levels: 1 to 10 exp - level 1, 10-50 - level 2, etc (Loberto):
    + Might be good enough to get an idea about the experience of the person (while 2 vs 50 experiences matters, 30 vs 50 does not)
    + partially solves the issues described in _OPINION-1, 2_
- Verbal experience levels: e.g. "Have had a few/some/lots of experiences" or with a single word (Mikael)
    + Might be good enough to get an idea about the experience of the person (while 2 vs 50 experiences matters, 30 vs 50 does not)
    + partially solves the issues described in _OPINION-1, 2_
- Do not specify the number at all
    + Only if can be estimated from the UI (list size, number of pages, tree size)
    + partially solves the issues described in _OPINION-1, 2_
- Make exact number private (Loberto), publicly - nothing it all or levels

**The number of experiences in different categories (negative/positive/neutral if we have them in the end):**
- specify the exact numbers:
    + for the users who are especially concerned about safety will find it convenient to immediately see the number of negative references 
- don't specify the exact numbers:
    + makes sense if we decide not to specify the exact total number
    + partially solves the issue from _OPINION-3_

Link to the slack-discussion: https://trustroots.slack.com/archives/C017JUMR6SZ/p1597749747230700

**Option to be implemented:** TBD

**Comment by chagai95** [comment]
Need to ask more volunteers, they get to decide, if no decision is made it gets left as is, which means the experiences are shown.
