### ISSUE TITLE
Experiences: rename hostedMe/hostedThem to guest/host on the UI

### ISSUE THREAD

**Issue by hlibbabii** [Trustroots/trustroots#1843]
- The latter option is more clear;
- Since we have _experiences_ - not references, and it's more about _us_ than them, guest/host works better.

Work in progress on #1493

**Comment by JessieFrance** [comment]
Hello @hlibbabii and Trustroots team. May I please attempt to solve this as my first issue?

If I understand correctly, variable "hostedMe" needs to become "guest" and "hostedThem" needs to become "host" for all files in the modules/references, bin/fillTestData, and testutils/common folders. Does that sound right? Many thanks in advance for your reply.
