### ISSUE TITLE
References -> Experiences: update text across the user interface

### ISSUE THREAD

**Issue by hlibbabii** [Trustroots/trustroots#1856]
Example:

    Give a reference -> Share the experience

All the strings related to the experience can be found in [this](https://github.com/Trustroots/trustroots/blob/master/public/locales/en/references.json) file. Please do not modify the file directly, change the strings in the code.

This is a part of ongoing work on #1493. Partially blocks #1485 (prevents the "experiences" component from being translated)

**Comment by simison** [comment]
Done! :-)
