### ISSUE TITLE
API / oAuth access

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#186]
Trustroots should have an API so that other people can build awesome stuff on the platform.

I think it makes sense to start experimenting after 20k users or so.

Only sensible and/or "real social" apps should be allowed.

**Comment by kamiel79** [comment]
Agreed.The kind of real social app I think of:
* Plugin/widget for travel bloggers. The write about city XXX, a basic TR widget shows some random users who are currently hosting in that city AND have a privacy checkbox "show my profile on other sites" checked. This way we get link juice and it's cool for travel blog readers

I think once the trust network for travelers is crystalized and solid, it's pure gold. Which means it becomes a verb. You can Trustroot everything, like rideshares, lending, dating, banking, taxes, and death :)

**Comment by simison** [comment]
https://github.com/jaredhanson/passport-http-bearer

**Comment by mrkvon** [comment]
[Leading author] (http://hueniverse.com/oauth/) of oAuth seems to be [disappointed] (http://hueniverse.com/2012/07/26/oauth-2-0-and-the-road-to-hell/) with the oAuth protocol v2.0. The reasons might be worth exploring further (security issues and other) before taking decision using it. (oAuth 1.0 or alternatives?)
disclaimer: based on very shallow knowledge of the topic

**Comment by mrkvon** [comment]
The closing means won't do?
I'd love to use it for a project i work on if it ever existed.

**Comment by simison** [comment]
@mrkvon closing as in not in priority right now but if there's a good reason, then sure! Write out your project idea at chat and let's see! Having an API access for meaningful apps would be nice in general. I think @kenflannery was also interested?

I basically just cleaned out a bunch of 2+ years old issues flying around, some of them already done or some just not that relevant right now.

**Comment by guaka** [comment]
Providing oAuth will make it a lot easier to build good stuff on top of Trustroots

**Comment by guaka** [comment]
https://www.keycloak.org/

"Open Source Identity and Access Management

Add authentication to applications and secure services with minimum effort.
No need to deal with storing users or authenticating users.

Keycloak provides user federation, strong authentication, user management, fine-grained authorization, and more. "
