### ISSUE TITLE
How to implement communities?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#188]
(Can't quickly find issue related to creating the communities feature so opening this one. Other keywords: group: groups.)

First community: hitchhikers.
Then hackers, veg(etari)ans, activists, bicyclists, etc.
Users can choose to stick within your own communities or they can be open to all.

**Comment by libertedeparole** [comment]
Will communities be management-chosen and -defined? Will members be allowed to create their own communities? I don't necessarily consider that a good thing. One can imagine some potential communities that most people would not like to gain a foothold.

I assume members can join multiple communities.

**Comment by libertedeparole** [comment]
Concerning the definition of communities, I assume that the hitchhiker community is open to people who do not hitchhike themselves, but who understand and are open to welcoming hitchhiking travelers.

But what about veg(etari)ans, for example? I am an omnivore myself, but love to have guests or visit people who explore other options, from veg(etari)an to the most idiosyncratic or extreme diets.

**Comment by simison** [comment]
I'll try to find soon some time to elaborate this in more details / list different options.

**Comment by guaka** [comment]
* start with some "management-chosen" communities.
* after we have a dozen communities running) open it up for people to propose new communities, which will be opened up as soon as there are enough members (e.g. at least 100 or 1000).
* we'll close down communities that "we" don't like, e.g. fascist or religious-fundamentalist.

**Comment by chreekat** [comment]
Perhaps StackExechange's Area 51 notion could be useful for incubating
new communities.

**Comment by simison** [comment]
Going to direction #208
