### ISSUE TITLE
Add support contact to email footers

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#190]
Visible & clear, so that people wouldn't be replying directly to emails for support.

**Comment by chmac** [comment]
Can we make the reply-to actually go somewhere? Or do we get too much junk that way?

**Comment by simison** [comment]
It's now hello@tr so I think it comes to us already. Adding contact info to
the footer helps spam filters determine it's not spam.
On Apr 5, 2015 3:32 PM, "Callum Macdonald" <notifications@github.com> wrote:
>
> Can we make the reply-to actually go somewhere? Or do we get too much
junk that way?

**Comment by chmac** [comment]
What info do we want? Link to this http://ideas.trustroots.org/contact/ Anything else? Email? hello@?

**Comment by chmac** [comment]
This appears to be [implemented already, but commented out](../blob/master/app/jobs/message-unread.server.job.js#L88). I'm not sure from the comment what the issue is or what needs to be done. #216 probably solves this issue.

**Comment by chmac** [comment]
I hacked in something crude that might do the job for now. Hopefully somebody else (probably @simison) can test it, and if it works, merge.
