### ISSUE TITLE
existing messaging APIs?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#194]
- jabber, xmpp?
- IRC?
- Telegram API? https://core.telegram.org/api
- TextSecure?
- Whatsapp?

Why?
- Make it possible/easy to switch to other means of communicating if users prefer so.
- Make it easy for users to connect with systems that are cheaper or more convenient to them.
- Make trustroots accessible from other systems.

How?
- If it's inside trustroots.org it should be very easy and simple to use
- Possibly not in core system but through external apps through a Trustroots API?

**Comment by quite** [comment]
What's the pros? How will it be helpful to users of trustroots?

**Comment by guaka** [comment]
I just added a quick note for Telegram, modified the issue now.

**Comment by guaka** [comment]
Happy to reopen if someone wants to dive into this.
