### ISSUE TITLE
Improve accessibility for blind people

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#195]
- Test with [Jaws](http://www.freedomscientific.com/Products/Blindness/JAWS). It's a popular app for blind people to access internet.
- Add Aria labels all around. We have [ngAria](https://docs.angularjs.org/api/ngAria) library in use.
- https://github.com/Trustroots/trustroots/wiki/Accessibility

**Comment by guaka** [comment]
"I wrote [accessibility dev article](https://www.bewelcome.org/wiki/Accessibility) for BW with @guaka, check it out." converted into https://github.com/Trustroots/trustroots/wiki/Accessibility

**Comment by simison** [comment]
Thanks!
