### ISSUE TITLE
don't allow empty profiles to send messages

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#196]
we got a request (2x) from a completely empty profile, which is not cool

**Comment by simison** [comment]
+ Super visible banner to tell user to fill up their profile.

**Comment by chmac** [comment]
How much does somebody have to have in their profile to be able to send messages?

**Comment by guaka** [comment]
A tweet size profile is bare minimum. Just use a "constant"
MIN_PROFILE_SIZE and set it to 140 for now.

**Comment by chmac** [comment]
Should we set this as a default? I guess in the long term it would be ideal if users could decide individually whether they will accept a message from a user with an empty profile or not. But maybe a minimum length makes sense initially...

**Comment by chmac** [comment]
I've implemented this, needs to be tested and reviewed. #219

**Comment by jancborchardt** [comment]
An enhancement to motivate people to fill out their profiles would be something like a »completion gauge« telling you how much percent you fileld out and which fields are missing. That’s basically what Airbnb and LinkedIn (and more) are doing.

**Comment by simison** [comment]
Done & in production.

- Users can't send messages if their profile description is <140 chars.
- Unless someone sent them message first, they can still reply with empty profile.
