### ISSUE TITLE
Can't open second window

### ISSUE THREAD

**Issue by libertedeparole** [Trustroots/trustroots#198]
Sorry to hassle, but since I haven't been able resolve this problem, I'm asking for advice. (For memory, this seems to be a variation of problems I have had on different computers (all Macs) and different browsers since the official launch. [see below]

This issue is particularly important for me individually, because I am unable to respond to requests on the computer where I receive email. On Firefox (most recent version) I am unable to log-in.

In Chrome, I can read the message, but then I am unable to access their profile in a new window. As long as I use a single window in Chrome, it seems to work for the moment. It is impossible to open a second TR window on my Chrome installation. 

It was suggested before that as an early member, my computers may have cache data, but removing the cache does not seem to work.

Is it impossible there is something on my TR end that is causing problems?

**Comment by guaka** [comment]
I noticed a similar (same?) problem: it's hard to open a window in another
tab.

**Comment by libertedeparole** [comment]
Yes, same problem whether it is a new tab or a new window in a separate "window". Both lead (for me) to a new sign-in page, where I can click on sign-in, and it seems to send data, but remains on the sign-in page. (The other working window continues to work, as long as I don't leave it - which can happen if I use links that go to the blog, for example.) Am no (at this moment) getting "server error"

**Comment by libertedeparole** [comment]
Am NOW

**Comment by simison** [comment]
Thank you! I got this somewhat repeated. Seems to occur a bit randomly with new tabs/windows.

Putting this on top of things, definitely needs fixing soon.

**Comment by guaka** [comment]
Thank you very much Natalia!

Time we post the drafted blog post?

sent from my mobile phone

**Comment by simison** [comment]
This seems to be working now after some tweaking. Lemme know if problem still occurs.
