### ISSUE TITLE
Clearer copy for "...in the spirit of Trustroots?" question

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#1987]
In the message thread, we ask:

> _"Do you find messages from this person to be polite, respectful and in the spirit of Trustroots?"_ 

(as re-introduced in https://github.com/Trustroots/trustroots/pull/1978)

We don't have to change this of course — it might work just fine as is, but it's been brought up in past that this could do with some clarification. What does it mean to be "in the spirit of Trustroots"? Should we change wording? Should we just link to rules?

<img width="1218" alt="Screenshot 2020-12-27 at 13 11 47" src="https://user-images.githubusercontent.com/87168/103170902-9b98d480-4850-11eb-98f6-02e98db6dcdd.png">

Tanja suggested:

> is this message inline (I don’t know a better word for now) with the [values](https://www.trustroots.org/rules) of TR?

> [...] did it show every time you send a message to someone? Cause in that case I would prefer a more open question or something more positive promoting :)

Noah suggested:

> I think if we refer to the rules we could do that directly and make it more a "flagging" then a yes/no thingy.
Or maybe make it like "Does this message make you feel uncomfortable? Is this message violating the [rules](https://www.trustroots.org/rules) of Trustroots?"

**Comment by simison** [comment]
@noahsmindfuck I bet there's something in that idea but I'd prefer avoiding working too much on this for now (unless anyone else wants to of course). 

How about just simple addition to rules, like this:

![image](https://user-images.githubusercontent.com/87168/103313396-a312d600-4a28-11eb-85ed-0b526e204929.png)

**Comment by TMC89** [comment]
![Printscreen Messages](https://user-images.githubusercontent.com/74301087/103341324-eac84a80-4a86-11eb-9980-bf0f7ddccd0d.jpeg)
It isn't working already is it....?

**Comment by simison** [comment]
Not yet, I'll put it live later today.
