### ISSUE TITLE
Trustroots in social media & blogsphere

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#20]
Spread:
- [x] Facebook groups
- [x] Hitchwiki channels
- [x] Trashwiki channels
- [x] Nomadwiki channels
- [x] Reddit
- [x] Hitching clubs
- [x] Blog
- [x] Squattheplanet
- Friends

Make sure we have:
- [x] [FB page](https://www.facebook.com/trustroots.org)
- [x] [FB group](https://www.facebook.com/groups/trustroots/)
- [x] [Newsletter](http://ideas.trustroots.org/newsletter/)
- [x] [Blog](http://ideas.trustroots.org)
- [x] [Twitter](https://twitter.com/trustroots)
- [x] [VKontakte](https://vk.com/public83461619)
- [x] [Google+ page](https://google.com/+TrustrootsOrg)
- [x] [Google+ group](https://plus.google.com/communities/110376845532540658554)

**Comment by simison** [comment]
https://www.couchsurfing.com/groups/12/threads/19451191

**Comment by simison** [comment]
https://www.facebook.com/groups/877253045641336/permalink/908244645875509/

https://www.facebook.com/photo.php?fbid=10152510734291423&set=gm.908763312490309&type=1&theater

**Comment by simison** [comment]
https://www.facebook.com/groups/1412018382343212?view=permalink&id=1589636247914757

**Comment by simison** [comment]
http://www.bewelcome.org/groups/33/forum/s13376-Trustroots_and_hitchhiking_community_and_whatnot

**Comment by simison** [comment]
https://www.facebook.com/groups/FREE.NOMADS/permalink/1590643257814056/

**Comment by simison** [comment]
https://www.facebook.com/groups/FREE.NOMADS/permalink/1592027871008928/
https://medium.com/@Sanbaad/why-i-am-leaving-couchsurfing-and-starting-a-new-hospitality-exchange-network-3e4b36e4c7e0

**Comment by simison** [comment]
https://www.facebook.com/events/134863673334252/permalink/452862391534377/

**Comment by simison** [comment]
https://www.facebook.com/nomadslifeofcheapfreetravel/posts/609290199201473

**Comment by simison** [comment]
http://www.bewelcome.org/forums/s13463/#post67568

**Comment by simison** [comment]
https://travelwithoutmoney.org/my-experience-with-trustroots-a-hospitality-website-for-hitchhikers/

**Comment by guaka** [comment]
updated my answer here in the first days, http://www.quora.com/What-are-some-alternatives-to-Couchsurfing
and just added my answer here just now: http://www.quora.com/Are-there-any-worthy-alternatives-to-Airbnb-and-Couchsurfing

**Comment by simison** [comment]
@guaka Cool, thanks. Could you mention "non profit UK foundation" there?

**Comment by guaka** [comment]
done, @simison

**Comment by simison** [comment]
entertaining https://www.facebook.com/groups/877253045641336/permalink/963360690363904/

**Comment by simison** [comment]
http://thedrawingboard.net/hospitality-networks-conclusions/

**Comment by simison** [comment]
http://kernelmag.dailydot.com/issue-sections/features-issue-sections/13124/life-and-death-couchsurfing/

**Comment by simison** [comment]
@guaka wanna add [comparison chart](http://ideas.trustroots.org/comparison-of-hospitality-exchange-platforms/) to Quora?

**Comment by guaka** [comment]
updated http://www.quora.com/What-are-some-alternatives-to-Couchsurfing

**Comment by simison** [comment]
mentioned http://matadornetwork.com/bnt/couchsurfings-destiny-doomed/

**Comment by simison** [comment]
Quite a lot of FB linking going on recently. E.g. https://www.facebook.com/groups/FREE.NOMADS/permalink/1648196532058728/

**Comment by simison** [comment]
Discussion about TR https://www.facebook.com/groups/hitchgathering/permalink/1117317291615169/

**Comment by simison** [comment]
http://www.mo.be/analyse/vergeet-airbnb-dit-is-het-echte-en-gratis-deelreizen @guaka

**Comment by simison** [comment]
http://www.bewelcome.org/forums/s15067-BeWelcome_for_rural_hosts_/#post73869

**Comment by simison** [comment]
https://www.couchsurfing.com/groups/7621/threads/20104403?go_to_last_page=true

**Comment by simison** [comment]
Gary mentions Trustroots on podcast: http://zerototravel.com/podcast/scandinavia-cheap-nomad-life-power-travel/
From 18:10 onwards

**Comment by simison** [comment]
ZZ.TT mentions us http://ze.tt/darum-sollten-wir-wieder-trampen/

**Comment by simison** [comment]
https://www.bewelcome.org/forums/s16686-Hosting_and_being_a_guest_with_BeWelcome/

**Comment by simison** [comment]
https://www.facebook.com/groups/hkeurope/permalink/1168314309899361/

**Comment by Tartesos** [comment]
Can’t read it ….

**Comment by simison** [comment]
Yup, it's closed group, requires joining. I'll send you a screenshot via email.

**Comment by simison** [comment]
http://vandrouki.ru/2016/v-zakladki-35-poleznyih-servisov-i-prilozheniy-dlya-samostoyatelnyih-puteshestviy/

**Comment by simison** [comment]
https://www.facebook.com/groups/FREE.NOMADS/permalink/1839071046304608/

**Comment by simison** [comment]
https://theapolitical.wordpress.com/2017/03/13/couchsurfing-choking-the-community-with-excessive-control-features-wrong-policies-alternatives-opportunities-what-can-others-do-right/

**Comment by simison** [comment]
https://www.facebook.com/groups/FREE.NOMADS/permalink/1896041193940926/

**Comment by simison** [comment]
Kenny speaks about TR in his podcast (from 37:00)

http://www.freestyletravelshow.com/2017/04/3-couchsurfing-and-hospitality-networks.html

**Comment by simison** [comment]
Another podcast! http://filcorbitt.com/van-sounds/2017/6/8/rule-of-thumb :tada:

@guaka's interview about hitchhiking and hitchwiki from 20:45 and Trustroots mentioned at 27:09

**Comment by simison** [comment]
TR mentioned https://nomadasfuck.com/2017-08/ken-flannery

**Comment by simison** [comment]
Nice reviews on Quora: https://www.quora.com/What-is-the-review-of-Trustroots

**Comment by simison** [comment]
https://issuu.com/tvergasteinjournal/docs/tvergastein_issue9_trykk_innhold/28

**Comment by simison** [comment]
Some discussions around The Daily Dot [Why hasn’t there been a new Couchsurfing?](https://www.dailydot.com/debug/new-couchsurfing/) article:

- at [reddit.com/r/couchsurfing](https://www.reddit.com/r/couchsurfing/comments/764wes/why_hasnt_there_been_a_new_couchsurfing/) 
- FB [New Couchsurfing discussion Group](https://www.facebook.com/groups/877253045641336/permalink/1706980152668617/)
- [FB Hitchgathering](https://www.facebook.com/groups/hitchgathering/permalink/1892117514135139/)
- [FB TR group](https://www.facebook.com/groups/trustroots/permalink/1738793992828923/)
- [FB TR page](https://www.facebook.com/trustroots.org/posts/884841174996659)
- [Twitter Daily Dot](https://twitter.com/dailydot/status/918842762870505477)

**Comment by simison** [comment]
>shall we move/continue this and other less tech issues to https://github.com/trustroots/community/issues?

Yes!
