### ISSUE TITLE
interesting map data, in French and a lot in France

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#200]
https://www.google.com/maps/d/u/0/viewer?mid=zCUrDZ_sv7Fw.k9HCrqv3hIVA&hl=fr&usp=sharing

![screen shot 2015-03-11 at 09 27 28](https://cloud.githubusercontent.com/assets/54728/6592641/ddd00226-c7d0-11e4-8b1e-844de7cda9e1.png)

**Comment by simison** [comment]
Moving to Wiki https://github.com/Trustroots/trustroots/wiki/Services-and-resources
