### ISSUE TITLE
Messaging should respond to enter, shift+enter

### ISSUE THREAD

**Issue by aurimus** [Trustroots/trustroots#202]
Currently looks like you can't send a message by pressing enter. I think it's usual standard that enter sends a message in "short" messaging app while shift+enter gives new line, the opposite when messages are longer. In our case here there should be a choice (just like fb).

**Comment by simison** [comment]
Yeah, you're right. I think this should work in a very similar manner to FB actually.

#1

**Comment by aurimus** [comment]
Ctrl+Enter works to send the message in master as a temporary workaround for the very frustrated ;)
