### ISSUE TITLE
Setup Vagrant

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#203]
Basically allows potential devs (especially those doing just quick bugfixing) to skip whole installation process.

https://www.vagrantup.com/

**Comment by simison** [comment]
Tested on OSX, seems to be working fine. More testing would be great!

@daiyiwhale wanna try this out? [Instructions](https://github.com/Trustroots/trustroots/blob/master/INSTALL-VAGRANT.md).

**Comment by honzahosek** [comment]
I will try it. 
I tried to install on my Debian and bower stoped on this issue https://github.com/itsdrewmiller/angular-perfect-scrollbar/issues/33

**Comment by simison** [comment]
Thanks for the heads up! This just confirms my thoughts on switching to iScroll instead... #63 #172

**Comment by simison** [comment]
Note that if you already run `npm install` on OSX, you must `rm -fr node_modules` before setting up the Vagrant box, since some packages are compiled and they're OS dependent.

I have two separate clones of this repo, one for the Vagrant and one with previous "serve with nodejs" style.

**Comment by simison** [comment]
@honzahosek I fixed that bower issue.
