### ISSUE TITLE
Better filter UI

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#2030]
**Is your feature request related to a problem? Please describe.**

I feel like are just too many circles in the filter method and I had filtered by one circle and couldn't figure out why I'm seeing only 2 people in my city... Eventually I figured out that the vollenteers circle was clicked... The clear circles button could have also helped me but I didn't think I needed it because I didn't notice that I had clicked on one circle to filter, so many circles....

**Describe the solution you'd like**

Circles that are part of the current filter on the top of the page, perhaps with a close button (x icon for example on each item)

Change clear circles button to clear filters button.

Only show a certain amount of circles, maybe the ones I'm part of at the top and then have a show more checked button

**Describe alternatives you've considered**

A a clear filters button instead of changing clear circles button to clear filters.

Don't show all circles but just have a search and auto complete drop-down

**Additional context**

I was doing all this from mobile.

Add links to discussion on Slack (or Discourse).

**Comment by simison** [comment]
Number of Circles have definitely outgrown the originally designed UI. 👍
