### ISSUE TITLE
Setup Statsd and Graphite

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#204]
We really need to start collecting more accurate statistics of how numbers develop.

https://codeascraft.com/2011/02/15/measure-anything-measure-everything/

Setup:
- [ ] [StatsD](https://github.com/etsy/statsd) (at stats.trustroots.org) to collect.
- [ ] [Graphite](http://graphite.readthedocs.org/en/latest/) to draw graphs.
- [ ] Add some measures (*)
- [ ] [Triggers](http://www.quora.com/Statsd-Graphite-what-about-alerts-triggers)
- Might require https. 
- StatsD listens to UDP and runs with node.
- [Node lib](https://github.com/sivy/node-statsd).
- For development, https://github.com/hopsoft/docker-graphite-statsd

**\* Measured Events:** (just throwing in some ideas)
- Signups
- Login success/failed 
- Sent messages to new people
- Replied messages (within different time intervals)
- Changed email
- Reset password
- Sent message notifications
- Profile image uploads
- Bounced emails
- Friend connection added/removed/accepted/ignored
- Start hosting/stop hosting
- Adding tag / removing tag
- Donations ([example](http://blog.ghost.org/april-2015-update/))
- Activity based on: locale, country, result...
## metrics and other data
- time on site
- referal
- user id
- user agent (device, browser)
- error messages
## triggers
- time on site too short
- time on site too long

**Comment by guaka** [comment]
added metrics and triggers section

**Comment by simison** [comment]
Done with Grafana and Stathat
