### ISSUE TITLE
profile edit not saved when connecting to Facebook

### ISSUE THREAD

**Issue by michielbdejong** [Trustroots/trustroots#205]
When you click 'Connect to Facebook' after having spent two minutes filling in things in the initial profile editing, the browser redirects, and when you get back, all the values you had filled in have gone.

A lot of web apps nowadays use auto-save for things like this. So from the onblur event of an input field, that field is automatically saved with an xhr request.

Or at least display 'make sure you save your profile before clicking this' above those connect buttons

**Comment by simison** [comment]
Related #176
