### ISSUE TITLE
languages selector way too slow and unusable in Firefox

### ISSUE THREAD

**Issue by michielbdejong** [Trustroots/trustroots#206]
The first time I tried to type in which languages I speak in the profile editor, the suggestions thing was so slow I did not even see it appear. The second time I accidentally saw it, and tried to use it.

It takes about 5 seconds on my computer (Firefox on Ubuntu, and a good laptop and a good internet connection) after I type 'english' before the `English x` bubble appears. If I have to wait 5 seconds before each language, that's very hard to use.

**Comment by simison** [comment]
Interesting! Wonder what's going on with Ubuntu+FF. OSX+FF works fine, although it could work faster with all browsers.

**Comment by michielbdejong** [comment]
Just tried to add 'Swahili' to my profile: after typing 's' into the input field, I have to wait 9 seconds for the dropdown to appear (and it stays at the top with languages that start with 'A', 'Achinese' is selected). After typing the 'w', it takes 3 seconds to scroll down ('Swiss German' is selected now).
After that, the 'a', 'h', 'i', ... is fast.

**Comment by simison** [comment]
@michielbdejong thanks, there's probably some Angular-weirdo-loop going on there.

Could you please test if [this demo](http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview ) works for you? (it's the same library)

**Comment by michielbdejong** [comment]
OK, that one is instant (probably because the list of items is shorter). Actually, I now discovered that I don't even have to type to make the dropdown appear, just clicking the field makes the dropdown appear 6 seconds later. But of course, nobody clicks an input field and then waits for 6 seconds to start typing the first character. :)

**Comment by aurimus** [comment]
Can't say I confirm (Firefox on Ubuntu). It looks like it takes a bit more than a second for dropdown to appear, less for filtering.

**Comment by simison** [comment]
@aurimus same here but our computers are über fast. With mobile this might be an issue as well.

I switched to [Angular-Chosen](https://github.com/localytics/angular-chosen) and it works marvelous. Didn't push yet.

**Comment by michielbdejong** [comment]
Weird, it's 5 to 7 seconds for me each time, from the moment of clicking in the field to the dropdown appearing. During which Firefox CPU usage goes up to 100%. With Chromium it's about 4 seconds.

**Comment by simison** [comment]
@michielbdejong would you have time to test this at https://dev.trustroots.org/ ? Should be pretty fast. :-)

**Comment by michielbdejong** [comment]
That site seems to be down. http://downforeveryoneorjustme.com/dev.trustroots.org

**Comment by simison** [comment]
@michielbdejong yah, sorry my bad. I was working there just now. It's up again!

**Comment by michielbdejong** [comment]
Yes, now it's instant. Thanks!

**Comment by simison** [comment]
Great. :-)
