### ISSUE TITLE
Idea: Compatibility scores

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#207]
@simison @guaka and I have been brainstorming.

Several questions might have a similar answer. How do we...
- handle spam?
- enumerate / measure trust?
- deal with issues between members?
- provide users with trust metrics to make better decisions?

One strategy is to calculate "compatibility" between members.
- It should be called something less datingy.
- We need to figure out how to display it visually to users.
- It breaks down to a number, a score, that is unique to the relationship between users.

Many factors are combined (weighted [bayesian](https://en.wikipedia.org/wiki/Bayesian_probability)?) to generate the score.
- Friends in common.
- Trust metrics (user feedback, number of friends / blocks / etc) #136
- Common interests (tags or tribes) #208
- More to be added...
## People like me

We could take this concept a stage further, and weight feedback based on who gave the feedback. If somebody very similar to me gave feedback about a person, that counts for more than if somebody very different from me gave the feedback. This "people like me" approach might be a better indicator than a more binary interpretation of gender.

**Comment by simison** [comment]
Some food for thought:
- http://nerds.airbnb.com/host-preferences/
- http://nerds.airbnb.com/location-relevance/
