### ISSUE TITLE
Custom tribes as "tags"

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#208]
@simison and I have been brainstorming.
- Users can add tags to their profile.
- Tags that have [>150 members](https://en.wikipedia.org/wiki/Dunbar%27s_number) become tribes.
- We'll start with a curated list of <10 tags.
- Our initial list will automatically be promoted to tribes.
- Initially, users can manually tag themselves.
- In the future, we will auto suggest tags to people based on crawling their existing social graph.
- Auto suggested tags will (probably?) be added to a user's profile automatically as some sort of "low-level" invisible tags. Show them as suggestions to the profile owner and allow removing them.
- Tags can be used as a factor to calculate compatibility between members. #207
- When viewing a user's profile, matching tags can be visually highlighted as a crude indicator of compatibility.

It might be possible for users to only accept requests from members of certain "tribes". (For example, I only accept vegan guests, geek guests, etc.) This needs to be figured out in more detail.

**Comment by guaka** [comment]
Yes! 
* tags can be made equivalent if enough (trusted) people agree. e.g. hitchhiker - hitchhiking - hitching
* let people use hashtags in places such as their profile and references

**Comment by chmac** [comment]
One topic we discussed was human intervention. I'm of the opinion that human intervention is only required if users are able to enter free text. If they're not (in a trust / reference setting), then we may not have a need for human intervention. Human intervention is (in my opinion) extremely hard to get right, without ending up with a small number of people wielding a lot of power in secret.

**Comment by almorsen** [comment]
hi
i like the idea of tags...
it could work same way that i used to use the groups in Cs for filtering, looking for people in the same groups i was...

so having those tags and being able to filter for users that haver got tgs in common with you would be very usefull when the number of users goes on growing up.

**Comment by guaka** [comment]
brainstorm with @chmac and @simison 

hitchwiki referal: add hitchhiker tag automatically (same for trashwiki, veganwiki)

initial tribes, to be rendered precise/clear
- hitchhiker
- tech/geek/hacker (tbd)
- vegan/vegetarian
- parents and family
- dumpster diver

people can add tags that we store and use later on
once 1k people have added their own tags we can get an idea of what to add next or open up, probably 150 people using a tag is a good indication, and we should keep an eye on synonyms

**Comment by chmac** [comment]
Users can add whatever tags they want, but we automatically display a curated list of 5-10 "suggested" tribes.

**Comment by almorsen** [comment]
What about a tribe musicians?
