### ISSUE TITLE
Favorite/bookmark hosts

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#2087]
**Is your feature request related to a problem? Please describe.**

Allow people to plan (to some extent) their trip ahead of time by "bookmarking" hosts, and then only adjust and keep in touch with pre-selected hosts as they go.

Has been popular community requested feature on WarmShowers.

**Describe the solution you'd like**
- Some kind of button on hosts profile to bookmark/favorite them.
- Just store list of IDs either to my profile, or separate Mongo collection (likely better?)
- Add a simple page where these people are listed. Can re-use the contact page componentry for it.

**Additional context**
Convo  https://trustroots.slack.com/archives/C08SENA9Z/p1612953456114700?thread_ts=1612939046.075900&cid=C08SENA9Z

**Comment by mariha** [comment]
It would be great to (1) filter and show on the map favorite host only and (2) to distinguish on the map which pins are for favorite hosts and which are others.
