### ISSUE TITLE
Preliminary donation page

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#210]
For transparency, elaborate funding model already now although we wouldn't be receiving donations just yet.

- [x] make it look good
- [x] more text
- [ ] link from menu

**Comment by simison** [comment]
I consider this pretty much done. 

Next steps are to get the bank account, open up finances, write a short policy etc.

Preview:
- https://dev.trustroots.org/#!/donate
- https://dev.trustroots.org/#!/donate/help
- https://dev.trustroots.org/#!/donate/policy

**Comment by guaka** [comment]
cool.. except, dev.trustroots.org/ is down again

**Comment by simison** [comment]
I'm tuning Nginx there right now — debugging #7 avatar uploads. (Got it working, hope to push to production tonight.)

In future if it's down and doesn't recover in 5-10mins, give me a shout.

Dev is up again.

**Comment by platschi** [comment]
Talking donations, today I stumbled over BitHub (this: https://github.com/WhisperSystems/BitHub), which I think might be an interesting way in receiving donations for the development of TR and at the same time sponsoring/rewarding/supporting developers for contributing to it.

/me +1 the idea.
