### ISSUE TITLE
Change "join chat" in "check out our Team Guide"

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2125]
**Is your feature request related to a problem? Please describe.**
When clicking on "contribute" there's a text about "volunteering" and where is suggested to join the Slack chat. If you click on "volunteering" at the bottom of the page though you get send to the Team Guide first before you can join Slack.

**Describe the solution you'd like**
I think it's best to first send members to the Team Guide and there they can join Slack but at the same time read a bit more about volunteering. 

**Describe alternatives you've considered**
![volunteering](https://user-images.githubusercontent.com/74301087/109681662-ff57ba80-7b7d-11eb-86c7-a403ddb7c6c0.jpeg)

**Comment by rishav-karanjit** [comment]
Is this issue resolved?

**Comment by TMC89** [comment]
No @rishav-karanjit :)

**Comment by TMC89** [comment]
@simison :) I can’t assign unfortunately

**Comment by rishav-karanjit** [comment]
Thank you @simison

**Comment by TMC89** [comment]
I guess someone in the mean time updated it already. Thanks! I'll close the issue.
