### ISSUE TITLE
Close window after successful facebook / twitter link

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#213]
I fixed #205 by adding `target="_blank"` to the facebook and twitter links. That means they pop up in a new window. Which is probably a better solution anyway, saves the whole site being unloaded and then reloaded again. But, now we should close the window once a user is redirected back from the oauth flow. Currently we're sending users to their settings/accounts page, which doesn't exist, and so they land on the homepage again.

**Comment by simison** [comment]
I'm not sure if you can setup that URL from https://developers.facebook.com/apps/374124702743123/dashboard/ or via configs.

**Comment by chmac** [comment]
@simison Don't have access. I think the URL is specified per request, which overrides the per-application settings. I guess we need to process the returned URL, and then if it was successful, close the window via Javascript.

**Comment by simison** [comment]
@chmac you were on "Pending" status. Removed you and re-added, check if you can see notification somewhere. Might be not at your normal FB notifications, but somewhere at https://developers.facebook.com

**Comment by chmac** [comment]
[Found it](../blob/master/app/controllers/users/users.authentication.server.controller.js#L248)

Not sure if we should put that into a config value somewhere or something. But I guess we could just modify that line and instead redirect to a url which throws a javascript close window.

**Comment by simison** [comment]
The page is now structured differently and oauth links are `target="_blank"` instead.
