### ISSUE TITLE
SEO Enhancing Forum/Community Blogs/ Region-specific Forum/ Youtube

### ISSUE THREAD

**Issue by annazi-maker** [Trustroots/trustroots#2132]
It would benefit organic search engine optimization if there are fresh texts written and posted often on a community blog that anyone is clearly invited (send invites to members once per  month by email?) about their location and tourism or anything related to trust-roots. This can be just one blog (someone has to be a moderator) that member are invited to participate in by sending text as simply as email to the blog moderator/manager. 

Regional forums would both help SEO (peole googling ''what to see in Berlin' might see advice written by TR members in the search engine crawled forum) and help members feel more community /local community knit.  

Altho TR is made for travelers its also made for locals who share the same lifestyle or hobby (cycling for examle). A forum would help them discuss and exchange ideas about making events.

I noticed very few events exist in TR. This can be due to low user base count or because of covid19 or both. Couch surfing is using Zoom meeting (video conference) to keep their user-base /community together. Maybe TR would look into this. Altho the zoom meetings I guess could not be of any help to SEO,  the meeting description, time and date, and how many meetings in future are planned, will appear in search results if someone searching for 'traveling community in Holland', might bump onto a blog post by TR announcing several videoconferencing meetings for TR members in Holland. 

Lastly, again about SEO, fresh (new) and frequent videos that are informative in Youtube ranks quickly very high in Google (google it, if you dont believe me).  Members wanting to show off their location's highlights or make videos about hosting or being hosted or any positive (or negative experience but that resolved positively by TR) will eventually make video but not on regular basis. Its not something of priority but for SEo puroses (growth of the app) the manager team can consider creating a volunteer team around SEO and Youtube, producing informative shorts clis twice per week (or more often) for at least a whole year, then they can be less frequent. I tested this myself when I learnt SEO for Google and saw how fast youtube video rank high even compared to new blog posts, Google favors youtube clearly. This can be used to make the user base grow faster amidsts covid19, by focusing maybe on useful themes and tribes /communities than travelling/hosting (most people do not want to host now or in near future).  

**Describe alternatives you've considered**
A forum can exist independently of the app (so that it doesnt make the app bulky) in a forum-hosting vendor or it can be a group in Mastodon or Facebook or in both?
A chatroom can exist in Discord and have 1 channel for all users of TR and then regional channels per country.
Volunteers can be admins of those regional chatrooms.

**Additional context**
discord.com
facebook.com

https://trustroots.slack.com/archives/C017JUMR6SZ/p1615039145000800?thread_ts=1615034367.000200&cid=C017JUMR6SZ

**Comment by simison** [comment]
Hi! Thanks for sharing your thoughts!

Have you seen the blog at https://ideas.trustroots.org/, as well [FB group](https://www.facebook.com/groups/trustroots) and [Reddit group](https://www.reddit.com/r/Trustroots/)?

**Comment by chagai95** [comment]
Hey, could you separate the tickets a bit? You spoke about a lot of different topics and each one of these topics will probably require a whole discussion, I understand they are all related to SEO but you can just mention the new tickets you open in this ticket, that way the conversation stays manageable 🙈

**Comment by simison** [comment]
Let's chat more about this on chat and keep GitHub for technical/design todos.

**Comment by chagai95** [comment]
The problem is we need to document these discussions, because they have been repeating themselves.

For example: 
Why don't we have a forum? Because we didn't have enough moderators and the conversations got toxic

And we could do with a ticket for YouTube, that's basically a feature request but maybe it's better to move this to the community repository.

**Comment by chagai95** [comment]
https://github.com/Trustroots/community

**Comment by simison** [comment]
@chagai95 yep! I agree on documenting, just here is a bit wrong place.
