### ISSUE TITLE
Redirect https://trustroots.org/#!/* to https://www.trustroots.org/#!/

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#215]
Redirect https://trustroots.org/#!/* to https://www.trustroots.org/#!/

right?

**Comment by guaka** [comment]
this was working properly before

(we can also stick to no-www, my personal preference, saves 4 characters in the URL ;)

**Comment by simison** [comment]
Yeah, dunno what happened, it was working before.

See Nginx configs https://github.com/Trustroots/trustroots/wiki/Server

**Comment by chmac** [comment]
Done.

**Comment by chmac** [comment]
Documented the change [here](../wiki/Server)
