### ISSUE TITLE
Enable HTML email templates for message notification

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#216]
Currently message notification emails are only sent in [text format](../blob/master/app/jobs/message-unread.server.job.js#L88).

      /*
       * Skipping this for now and using text-only emails instead.
       * We'll first need to re-render our html templates from
       * header+content+footer parts and then use that file for this.
       *
       */
      // Prepare mail
      /*
      function(users, emailTemplate, done) {
        swig.render('./app/views/email-templates/messages-unread.server.view.html', {
          ourMail: config.mailer.from,
          urlInbox: (config.https ? 'https' : 'http') + '://' + config.domain + '/#!/messages',
        }, function(err, emailHTML) {
          done(err, emailHTML, users);
        });
      },
      */

Re-enable sending of HTML emails, and then test, test, test. Some inspiration might come from this part of [contacts.server.controller.js](..//blob/master/app/controllers/contacts.server.controller.js):

    // Prepare HTML email for friend
    function(contact, messageHTML, messagePlain, friend, done) {

      var url = (config.https ? 'https' : 'http') + '://' + req.headers.host;
      var renderVars = {
        name: friend.displayName,
        message: messageHTML,
        meName: req.user.displayName,
        url: url,
        meURL: url + '/#!/profile/' + req.user.username,
        urlConfirm: url + '/#!/contact-confirm/' + contact._id,
      };

      res.render('email-templates/confirm-contact', renderVars, function(err, emailHTML) {
        done(err, contact, emailHTML, messagePlain, friend, renderVars);
      });
    },

    // Prepare TEXT email for friend
    function(contact, emailHTML, messagePlain, friend, renderVars, done) {

      // Replace html version of attached message with text version
      renderVars.message = messagePlain;

      res.render('email-templates-text/confirm-contact', renderVars, function(err, emailPlain) {
        done(err, emailHTML, emailPlain, friend);
      });
    },

    // If valid email, send reset email using service
    function(emailHTML, emailPlain, friend, done) {

      var smtpTransport = nodemailer.createTransport(config.mailer.options);
      var mailOptions = {
        to: friend.displayName + ' <' + friend.email + '>',
        from: 'Trustroots <' + config.mailer.from + '>',
        subject: 'Confirm contact',
        text: emailPlain,
        html: emailHTML
      };
      smtpTransport.sendMail(mailOptions, function(err) {
        if (!err) {
          res.send({
            message: 'An email was sent to your contact.'
          });
        }
        smtpTransport.close(); // close the connection pool
        done(err);
      });
    }

**Comment by simison** [comment]
Leaving this for #260
