### ISSUE TITLE
Missing pictures

### ISSUE THREAD

**Issue by Janssc** [Trustroots/trustroots#2179]
Some profiles don't have a picture.  I suspect the users have uploaded them and they're just not showing. But I can't be sure. At least I know these profiles had pictures in the past. 

Under 'contacts' these profiles are represented with text only (instead of the picture), the text reads Profile image from Facebook.  If you see this text you are probably blocking Facebook. 

**To Reproduce**
1) Go to a for example: https://www.trustroots.org/profile/kimpjuh
2) Go to this user's contact's contacts page https://www.trustroots.org/profile/ikreis/contacts

**Expected behavior**
Expected to see profile picture shown under contacts

**Screenshots**
![image](https://user-images.githubusercontent.com/81050094/111886431-b604c900-89cd-11eb-82f1-4f1ae6c071d1.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version **89.0.4389.82**

**Comment by Athameon** [comment]
This seams to be a problem with the facebook access token.
I created a new account and tried to connect to facebook to set the facebook picture.
Facebook gives me then following error (German):

Feature nicht verfügbar: Facebook Login ist für diese App derzeit nicht verfügbar.

There seams to be a problem with the Facebook Grap api key.
