### ISSUE TITLE
Merge configs instead of extend

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#218]
Currently config uses lodash's `.assign()` (it actually uses `.extend()` which is an alias to `.assign()`). This means that config objects are overwritten as entire objects. For example `config.settings.foo` in `all.js` will be removed if `config.settings` doesn't have a property called `foo` in `development.js`.

We should use lodash's `.merge()` instead of `.assign()` and it will recursively merge the configs together.

**Comment by chmac** [comment]
Hint [config/config.js](../blob/master/config/config.js#L12)

**Comment by simison** [comment]
Done  https://github.com/Trustroots/trustroots/pull/220#issuecomment-101842551
