### ISSUE TITLE
Improve contacts count in admin tool

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#2193]
When looking at a member's report card in the admin tool, at the top you see a summary like this:
<img width="380" alt="Bildschirmfoto 2021-03-23 um 15 54 15" src="https://user-images.githubusercontent.com/31466125/112168632-c0071180-8bf1-11eb-8ed7-3e90988d17ab.png">

The contacts count doesn't actually reflect confirmed contacts, but all contacts requests, also the unconfirmed ones. At first glance, a member that added a lot of contacts without confirmation, might seem more connected to the network (happened today in handling a report).

The contacts count should better look like this:
> **28 contact request(s)** 27 confirmed 1 unconfirmed

**Comment by simison** [comment]
Good catch!

Would this be more helpful:

> 27 contacts (+ 1 contact request)
