### ISSUE TITLE
At sign up, add a link to import profile from WS

### ISSUE THREAD

**Issue by mariha** [Trustroots/trustroots#2200]
We'd like to make it as easy as possible for WS users to join TR.

To do that, at sign up, add a link to import profile from WS. Most of the info is generally available at the user's profile page without the need to sign up.

**Other ideas to consider:**
If it was possible to get an export of a WS profile (from CS it is), we can first add a preview for it on https://couchspinner.com/  and later maybe even way to import some of it to TR.

**Comment by weex** [comment]
I'm not a member of WS but it seems accessing user information requires login but can anyone confirm if they provide a usable export of account data? In the best case, what information could be pre-filled by loading in such an export?
