### ISSUE TITLE
vagrant: nullmailer and fakemail 

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#222]
- [ ] http://distinctplace.com/2013/06/20/nullmailer-and-fake-mail---two-little-tools-for-every-developer/
- [ ] http://sourceforge.net/projects/fakemail/
- [ ] default [mailer config](https://github.com/Trustroots/trustroots/blob/master/config/secret/_template.js) to reflect these so that emails in Vagrantbox (and with little effort on localhost)

cc @simison

**Comment by simison** [comment]
Docker now has [MailDev](https://djfarrelly.github.io/MailDev/) installed and I recommend that for localhost development, too. Works great!
