### ISSUE TITLE
Add a link/button to the wiki circle pages at the circles on the platform 

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2221]
It would be nice if the current wiki circle pages are linked to the existing circles. This way new members can read more information about the circles and maybe it invites them to expand them with new information. The ones who don't have information could have text inviting members who open that page, to contribute :) I think at the moment the wiki pages are not much used which is a pity because it would make the circles more then just groups to join.

**Comment by TMC89** [comment]
Checkin in on this one since the comment I hear the most about circles is that members would love to see more then just a join button :)

**Comment by guaka** [comment]
Added a link to https://www.trustroots.org/circles/cyclists from https://www.trustroots.org/circles/cyclists, something like this?

relates to #2475

**Comment by TMC89** [comment]
Yes! I think that way all effort for the Wiki pages, wasn’t in vain :)

**Comment by chmac** [comment]
@guaka again, if you make some commits in a branch and let me know I can deploy.

**Comment by guaka** [comment]
It doesn't require a code change, just figuring out what link to put in the circle description, for each circle. And whether to put it. Right now for example https://www.trustroots.org/circles/dumpster-divers links to trashwiki, which is much better than linking to the trustroots wiki stub about dumpster diving.

I think the actual way forward with circles is more in this direction: https://github.com/Trustroots/nostroots/issues/13

So closing this now.

Happy to add links to useful resources related to circles, if anyone has good suggestions, feel free to post them here.

**Comment by TMC89** [comment]
Haven’t read everything but came across this one about hitchhiking a sailboat: https://hitchwiki.org/en/Hitchhiking_a_boat

Maybe we can add volunteersbase.com to the volunteer circle so we widen it a bit to volunteering while traveling?
