### ISSUE TITLE
kasper@trustroots.org not working?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#229]
just tried adding the address to my gmail

**Comment by simison** [comment]
Check your spam folder? ;-)

Ping @chmac

@chmac could you also add mikael@trustroots.org (forwarding to @ihminen.org)

**Comment by chmac** [comment]
It's already done. Both have been setup for ages.

Ah shit, just checked, somebody moved DNS? Or moved the domains? The MX record no longer exists.

Needs to be `mxin.mxes.net` at any priority.

**Comment by simison** [comment]
We moved all domains from our private accounts to Trustroots account at Namecheap. I did set up the MX record there, but now that I look at it again their dashboard is a bit confusing. Under "host name" I had value "trustroots.org" but now I added "@".

@chmac wanna double check it's correct? [Settings page](https://manage.www.namecheap.com/myaccount/modsingle.asp?domain=trustroots.org&type=hosts) (you should have the password to there).

**Comment by chmac** [comment]
Looks good:

    dig +short mx trustroots.org
    50 mxin.mxes.net.
