### ISSUE TITLE
offline docs for developing trustroots

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#236]
great while on the road without internet connection

browser based: http://devdocs.io/

for OSX: https://kapeli.com/dash

anything else?

todo: add to [developer docs](https://github.com/Trustroots/trustroots/wiki/Development)

**Comment by simison** [comment]
Nothing beats good 'ol pdfs. ;-)

+1 for Devdocks.io https://github.com/Thibaut/devdocs

**Comment by simison** [comment]
https://github.com/Trustroots/trustroots/wiki/Development/_compare/dc77064c725cad764263ed3c1f76a6a5e290e02e...49bec953575de294ed1277b4be42bf1b4a8be9e1
