### ISSUE TITLE
ToU & policies

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#237]
- [ ] **Terms of Use**
  - See [Rules of Trustroots](https://www.trustroots.org/rules)
  - Examples: [Warmshowers](https://www.warmshowers.org/terms), [BeWelcome](http://www.bewelcome.org/terms), [Automattic](https://en.wordpress.com/tos/), [UpDown](https://updown.io/tos)
  - [Draft](https://github.com/Trustroots/trustroots/wiki/Terms-of-Use)
- [ ] **Community guidelines**
  - See [Rules of Trustroots](https://www.trustroots.org/rules)
  - Examples: [GitHub](https://blog.github.com/2016-10-19-introducing-github-community-guidelines/)
- [ ] **Privacy policy**
  - [Current](https://www.trustroots.org/#!/privacy)
  - [Draft](https://github.com/Trustroots/trustroots/wiki/Privacy-Policy)
  - Examples: [Warmshowers](https://www.warmshowers.org/privacy), [BeWelcome](http://www.bewelcome.org/privacy), [Automattic](https://automattic.com/privacy/), [UpDown](https://updown.io/privacy_policy)
- [ ] **Donor policy**
  - [I created a stub](https://dev.trustroots.org/#!/donate/policy).
  - Examples: [Wikimedia](http://wikimediafoundation.org/wiki/Donor_policy/en), [Mozilla](https://wiki.mozilla.org/Donate)

These all should be as simple, short and straightforward as possible.

Templates: http://www.docracy.com/
Consult with https://tosdr.org/ (contact: @jancborchardt)

**Comment by simison** [comment]
[Privacy draft](https://github.com/Trustroots/trustroots/wiki/Privacy-Policy), thanks Gerard.

**Comment by guaka** [comment]
Great! I added and corrected some things. Notably 1. we may use other
server providers and 2. there will be an API.

**Comment by simison** [comment]
So privacy policy is quite ready now. ToU should come next.

@Natttalia wanna push this forward? No hurry.

**Comment by simison** [comment]
https://github.com/blog/2267-introducing-github-community-guidelines

**Comment by guaka** [comment]
@simison what's the current status of this? wanna move this one to https://github.com/Trustroots/community/issues?
