### ISSUE TITLE
Message textarea: Cursor does not go to new line when a new line is created

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#2375]
Checkout screen recording.

When writing a message to another user, creating a new line (shift enter) will create the new line below the one I'm on, but the cursor stays on the one I'm on. I need to move the cursor down myself after.

Granted, you're supposed to just hit enter and create a new paragraph. But "shift-enter" is often used by reflex because "enter" sometimes means "send the message" (in other apps).

Firefox on Linux.

https://user-images.githubusercontent.com/10289010/125042481-2b3dfc00-e09a-11eb-8b65-3d9655630a60.mp4

**Comment by krumelmonster** [comment]
On firefox linux, I sometimes get this behaviour too and sometimes even if I don't press shift.

On Fennec F-Droid (using androids onscreen keyboard) I get such unintended behaviour more often than not without doing anything unusual. Also, pressing enter sometimes inserts a newline before inserting a space. Double line breaks get trimmed into a single line break. To work around these issues I've tried drafting on mobile in another app and copying over but even in this case, linebreaks get trimmed and other weird things happen.

My "workflow" for using trustroots in my mobile browser has become to type the message in a note-taking application, then copy it over into the message box and eventually fix some formatting issues that appeared when copying the message over. This is of course quite frustrating.

There are event listeners on the message-reply-content div to sentry. When I remove those, the behaviour is as expected (on desktop).
