### ISSUE TITLE
Map is not displayed in various browsers

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#2379]
**Describe the bug**
Clicking on /search leads to trustroots with a blank page where the map should be
Despite the logs of Firefox I am not in Private Mode but I use uBlockOrigin and Privacy Badger Addons

**Screenshots**
Firefox
![2021-07-16-095909_1920x1080_scrot](https://user-images.githubusercontent.com/24893086/125914363-04483a87-d0f1-469a-a4cb-89a60d84f01d.png)
Qutrebrowser
![2021-07-16-095853_1920x1080_scrot](https://user-images.githubusercontent.com/24893086/125914359-3f541877-9c87-4e06-a8f9-b847d155c192.png)

**Desktop (please complete the following information):**
 - OS: 5.12.14-arch1-1 x86_64 GNU/Linux
 - Browser: Mozilla Firefox 89.0.2, qutebrowser v2.2.2 (Backend: QtWebEngine 5.15.5, based on Chromium 87.0.4280.144
)

**Comment by simison** [comment]
Are those plugins blocking Mapbox.com?

Not sure if it's technically possible to add some notification in they case, but it might be worth exploring.
