### ISSUE TITLE
Foundation missing from "about" page.

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#238]
On: https://www.trustroots.org/#!/about

"We will form a legal organization behind Trustroots and your help with this is very welcome."

It's been done, right?

**Comment by simison** [comment]
Thanks! Yeah, pushing updated texts to production tonight. :-)

Visible already at test version;
- https://dev.trustroots.org/#!/about
- https://dev.trustroots.org/#!/foundation
- https://dev.trustroots.org/#!/faq

If you find feel like proofreading, here: [foundation](https://github.com/Trustroots/trustroots/blob/master/public/modules/pages/views/foundation.client.view.html), [about](https://github.com/Trustroots/trustroots/blob/master/public/modules/pages/views/about.client.view.html), [faq](https://github.com/Trustroots/trustroots/blob/master/public/modules/pages/views/faq.client.view.html) — just click pen-edit button from top-right corner and send us a pull request.

**Comment by guaka** [comment]
thanks! Yes, needs update including link top blog post.

sent from my mobile phone
