### ISSUE TITLE
Photo error in Experiences

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2388]
When going to experiences on ones profile, the only photo that is correctly showing, is the one of the owners profile not of the "other" that wrote an experience. 
![Bug Experiences](https://user-images.githubusercontent.com/74301087/127877687-9f8267ae-3e50-405a-bcfe-99ef6a821403.jpeg)

**Comment by ishan1880** [comment]
Hey. I would like to work on this one. Please assign.

**Comment by ishan1880** [comment]
Hey! I was trying to do the setup and i am getting compilation errors 

You may need an additional loader to handle the result of these loaders.
|     const html = " <avatar-name-mobile profile=profileCtrl.profile></avatar-name-mobile> <profile-overview profile=profileCtrl.profile></profile-overview> <div class=profile-flags ng-if=\"::app.user._id !== profileCtrl.profile._id\"> <report-member-link username=::profileCtrl.profile.username></report-member-link> <br/><br/> <block-member classname=\"'btn btn-xs btn-link text-muted'\" username=::profileCtrl.profile.username isblocked=::app.user.blocked.includes(profileCtrl.profile._id)></block-member> </div> ";
|     angular.module('ng').run(['$templateCache', function($templateCache){
>       $templateCache.put('\modules\users\client\views\profile\profile-view-basics.client.view.html', html);
|     }]);
|     module.exports = '\modules\users\client\views\profile\profile-view-basics.client.view.html';
 @ ./modules/users/client/config/users.client.routes.js 21:58-142
 @ ./modules/users/client/users.client.module.js
 @ ./config/webpack/entries/main.js

ERROR in ./modules/users/client/views/profile/profile-edit-account.client.view.html 4:36
Module parse failed: Bad character escape sequence (4:36)
File was processed with these loaders:
 * ./config/webpack/templateloader.js
 * ./node_modules/html-loader/index.js
You may need an additional loader to handle the result of these loaders.

Please help

**Comment by TMC89** [comment]
@simison can you help out here?

**Comment by mrkvon-tr** [comment]
Please consider opening and merging pull request https://github.com/Trustroots/trustroots/compare/master...mrkvon:fix-avatar-size?expand=1 to fix this.

@guaka @TMC89 @robokow 

Open the above link, edit the Pull Request message as you want, and click `Create pull request`. Then merge after tests pass.
