### ISSUE TITLE
possibility to reorder languages

### ISSUE THREAD

**Issue by maxlath** [Trustroots/trustroots#239]
In my profile preferences, I added the following languages: French, then English, then German. The order is meaningful as it reflects the state of my language skills. Now the result my profile displays is German, then English, then French.
This seems to be due to the selector placing the last selected language first. A quick fix would be to make the last selected language be appended last to keep the intuitive ordering. A more complex UI enhancement would be to let one reorder her languages once selected.

**Comment by simison** [comment]
Good catch.

Also https://github.com/mrhenry/jquery-chosen-sortable/

**Comment by aurimus** [comment]
Just took a look. No, I think it just orders them alphabetically.

**Comment by simison** [comment]
I'll close this up now, I think it would make sense to implement language levels and re-arranging them. In BeWelcome or CS style. As just a language order inside that single input; I don't think it makes sense to spent time.
