### ISSUE TITLE
Server.md points to old Passenger install document location

### ISSUE THREAD

**Issue by weex** [Trustroots/trustroots#2401]
As mentioned in https://github.com/OpenHospitalityNetwork/fedi-trustroots/issues/13, the Passenger installation link in https://github.com/Trustroots/trustroots/blob/master/docs/Server.md says the documentation moved.

The new location is https://www.phusionpassenger.com/library/install/nginx/apt_repo/

**Comment by simison** [comment]
Thanks, good catch!

At some point quite a while back I started migrating Trustroots to [PM2](https://pm2.keymetrics.io/). We now use it for running the background jobs manager, and use Passenger for user-facing website. PM2 used not to be quite so capable and stable but now it is, and it's less up-selly/commercial than Phusion Passenger. Would love to consolidate everything into PM2. 

Thoughts @weex ?

**Comment by weex** [comment]
Hi @simison I wish I had opinion but haven't worked with either. I'm more familiar with python/golang backends. Just ran across this when attempting to setup a demo server for OHN, which works but isn't optimized in any way.
