### ISSUE TITLE
About Trustroots is showing on mobile view but not on web 

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#2403]
**Describe the bug**
About Trustroots is showing on mobile view but not on web, we need to choose either to show it or not?

**To Reproduce**
Steps to reproduce the behaviour:
1. Register

https://user-images.githubusercontent.com/31655082/135747562-e5a14dce-42b3-4147-b8f2-63888473a480.mp4

Place in the code:
https://github.com/Trustroots/trustroots/blob/7376a0406500266481bbddb6f9781378fe6d473d/modules/users/client/views/authentication/signup.client.view.html#L466-L468

**Comment by chagai95** [comment]
@simison do you remember why this is done like this?

**Comment by simison** [comment]
I don't remember but I'd imagine something around how us used to show registration/login forms directly in mobile apps and there needing to be a pathway to about page.

I think something broke some time during Angular/React and we now more often show homepage directly across web/mobile.
