### ISSUE TITLE
Add a reason for why I'm in a circle

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#2406]
Add an optional text field for every user allowing them to explain why they belong to one circle or another.

Why?

This will help fight against people who just join all circles and also just be a way to avoid a long copy pasted message, instead we could just show the text for the circles in common

Example texts which show huge difference in why people join checked:

Hitch hikers:

"I love hitch hicking and I've been doing it all my life" vs. "I have hitch hiked before but now I don't much, still love the idea and would love to host people doing it!"

Dumpster divers:

"I tried this out once and I'd love to find someone to do it with again" vs. "I try to dumpster dive any time I can"

LGBTQ:

"I'm gay" vs. "I'm actually hetero but I see myself as a strong part of the LGBTQ community"

**Comment by simison** [comment]
Yeah, this would be pretty neat way to expand people's profiles and put little less pressure on profile descriptions.

This should be straightforward, wanna look into implementation? :-)

**Comment by chagai95** [comment]
Theoretically yes, realistically probably not soon...

**Comment by TMC89** [comment]
Building on this idea, an idea through support: 

> Add a way to distinguish a possitoon in a circle. Experience level... só to speak. 
> For example. Circle: Eco living clickable sub set and marker (builder) (novice builder) (want to learn about) with possible links to photos. 
> Permaculture: (farm) (agro forest) (green thumb) 
> Would be nice if there was a way other could get or add points when they experience the others area of interest and the can gain visible mark of experience in return. Farm helper radish level. 
> Cyclists, 1000km .... 
> Naturist. (Never not naked) - (nubie nervous while naked) 
> Sailers (own a boat) (sometimes sailor) (wants new see legs) 
> Helps validate the person as actually doing these things Antenor informing other about what I may be interested in but have yet to experience or shows a level of experience with others within the circle.
