### ISSUE TITLE
Add an 'ideology' field on profile

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2419]
When reviewing the circles we (circle review group) came across a lot of requests to add religious circles and a request for a pastafarian circle. We had a discussion and believe creating such circles is not the best option. Because it is important however to some people to put their believes out there and it can effect the hosting/guest experience, we suggest to create a conviction field like the languages field so members can express their conviction.

**Comment by TMC89** [comment]
Not sure about the title for this field though.. Maybe a native English speaker has a good suggestion @MrSalami ?

**Comment by karlkeefer** [comment]
Conviction is mostly associated in my mind with criminal law.

I propose `ideology` as it also captures non-religious belief that is on a sort of similar dimension. It could even stretch to fit things like political labels for folks who feel strongly about broadcasting that.

**Comment by TMC89** [comment]
Yes @karlkeefer, that's a perfect proposition!!

**Comment by guaka** [comment]
let's close this one

relates to #2624 (and #2660)
