### ISSUE TITLE
cut www. on trustroots.org deployment

### ISSUE THREAD

**Issue by jancborchardt** [Trustroots/trustroots#242]
The www. subdomain is not useful and it just makes the address longer. I’d suggest to cut it on the trustroots.org deployment.

**Comment by guaka** [comment]
I also prefer no-www. (But there are some cases where www. is useful.)

**Comment by simison** [comment]
Shorter is prettier, true. But then, people intend to create links to www and 301 redirect won't pass on all the SEO link-juice.

It's important to stay consistent, so I wouldn't start changing this anymore. 

Who types links nowadays anyway? ;-)

**Comment by guaka** [comment]
SEO wise there's not much difference as long as 301 is set up properly.

People can type it without www, not much difference there either ;-)

sent from my mobile phone

**Comment by simison** [comment]
So, should we do this then?

I could do the change at the same time when I change to nice urls without `/#!/` #26 some time soon.

**Comment by guaka** [comment]
This question and its answers are useful
http://webmasters.stackexchange.com/q/507/24487

**Comment by simison** [comment]
Thanks! I hadn't considered cookie issue mentioned there:

>Keep in mind though that using www.example.com lets you to set Cookies only on the main site. Using example.com will only allow you to set cookies on *.example.com which includes static.example.com. So every request for any subdomain will include the cookies which slows down the transfer a bit. Using www.example.com will allow you to decide for what part you want to set cookies.

I think this solves it; we better use www.

We have different systems running at subdomains — one of them is a [Wordpress blog](http://ideas.trustroots.org/) which regularly has XSS holes popping. I'd hate to see anything nasty happening due this, although the risk might be minimal.
