### ISSUE TITLE
Zoom buttons are off on maps

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#2423]
Some CSS tweaking is needed to bring back zoom buttons at least on the profile map.

Worth checking other maps as well.

<img width="468" alt="Screenshot 2021-10-14 at 00 30 27" src="https://user-images.githubusercontent.com/87168/137215247-4a3212d3-44ac-4165-a6d4-4f078cd82a08.png">

**Comment by jalfawadleh** [comment]
Fix
.map-navigation-control-container {
position: absolute;
right: 45px;
top: 10px;
z-index: 5;
}
