### ISSUE TITLE
Redirect to original link after logging in

### ISSUE THREAD

**Issue by jancborchardt** [Trustroots/trustroots#243]
1. Get a notification email
2. Click the link leading to https://www.trustroots.org/#!/messages
3. You aren’t logged in, so faced with log in view

Then when you log in you are redirected to the trustroots.org main page instead of https://www.trustroots.org/#!/messages – the anchor should be remembered though so folks don’t have to manually click through again.

**Comment by simison** [comment]
Yep! Got this already #135

Closing this as a duplicate.
