### ISSUE TITLE
AngularJS End of Support on December 31 2021

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#2436]
AngularJS [stops being supported](https://docs.angularjs.org/misc/version-support-status) on December 31 2021.

As far as i understand that means the team behind AngularJS stops fixing bugs or perhaps doing anything at all beyond this date.

- What does it mean for Trustroots?
- Is AngularJS stable enough so this won't be a concern for _some time_ to come? How long?
- What can/should be done about this?

**Comment by simison** [comment]
Hey hey! Good to hear from you. :-)

We want to get rid of AngularJS in favour of React anyway, so nothing much changes about that goal.

The version we run is anyway behind the latest.

**Comment by mrkvon** [comment]
👋🏾 🙂 
I'm asking because (as you may know) some folks from https://openhospitality.network are trying to federate hospex, atm using [a fork of Trustroots](https://github.com/OpenHospitalityNetwork/fedi-trustroots).
Doing that, they're forking the [technical debt](/OpenHospitalityNetwork/fedi-trustroots/issues/83), too. As they progress, there may be a double motivation to resolve the debt. So it may be worth for the two dev teams to synchronize, e.g. so that each team's progress may be useful for the other one, too?

> Does that answer your question? slightly_smiling_face

Yes, thank you, it answers my question. 🙂

Perhaps @chagai95 @mariha @weex want to discuss this more?

**Comment by AlexisTonneau** [comment]
Hi guys! Do you have a time estimation for the migration from Angular to React?
