### ISSUE TITLE
Map jumps back to initial view when using Android back button

### ISSUE THREAD

**Issue by jancborchardt** [Trustroots/trustroots#244]
1. Search for a city on the map
2. Zoom in, open a user profile by clicking on the map
3. Instead of using the buttons »Back to map«, use the Android back button (or the browser’s back function)

Then, unlike when clicking the »Back to map« buttons, you’re thrown back to the original map centering on Europe. Instead I’d expect to go back to the map area I was just in.

**Comment by simison** [comment]
Thanks! Duplicate again. :-) #184 Although a good reminder to fix on this soon.

Need #26 nice urls without # first.

**Comment by jancborchardt** [comment]
Yeh, sorry for the duplicates. Sometimes I search, sometimes I forget. Need to get a feel for which issues exist already. ;)

**Comment by simison** [comment]
No prob, there's quite a pile of these. I'm considering moving some server related tasks to a separate repository to make things easier. @guaka @chmac ?

**Comment by jancborchardt** [comment]
Hm, it’s the same product though, right? I would advise to use tags instead of splitting it up. Only when it’s completely different apps / products.

**Comment by simison** [comment]
Valid point. And it's just a few tasks.
