### ISSUE TITLE
Uploaded profile picture is broken in Profile page

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#245]
After uploading profile picture from local disk it doesn't show up in user profile. Image source is not found.

The uploaded profile picture
is visible in selecting popup menu:
https://www.trustroots.org/modules/users/img/profile/uploads/[hex code]/avatar/128.jpg?[number]

is visible in Edit profile page (https://www.trustroots.org/#!/profile/[username]/edit)
https://www.trustroots.org/modules/users/img/profile/uploads/[hex code]/avatar/256.jpg?[number]

but is broken in Profile page (https://www.trustroots.org/#!/profile/[username])
https://www.trustroots.org/modules/users/img/profile/uploads/[hex code]/avatar/261.jpg?[number] ...picture doesn't exist/is not served
...so it seems that on the server there are only pictures with size of powers of 2: 32, 64, 128, 256, 512 pixels wide (?)

if i'm repeating what is already mentioned/fixed, my appology.

**Comment by simison** [comment]
@mrkvon Thanks! Which fileformat was it, was it big file (over 10mb?) and which browser?

I just fixed some folder permissions which might've affected. Just tested with Chrome, works here now.

**Comment by mrkvon** [comment]
@simison Now everything seems to be ok. Pic was standard size (~2MB) .jpg, browser chromium (chrome for Debian). Problem seemed to be that the profile img src pointed to file .../avatar/261.jpg (not existent) instead of .../avatar/256.jpg. Right now it points to correct place; the problem disappeared.

**Comment by simison** [comment]
Hmm! Interesting. I'll try to find where we're trying to call for that 261px photo. We're [not generating](https://github.com/Trustroots/trustroots/blob/master/app/controllers/users/users.profile.server.controller.js#L130) that size for sure.

**Comment by simison** [comment]
Indeed seems to work now. I'd like to see some Selenium tests written for this tho...
