### ISSUE TITLE
Map dots disappear when zooming in (IE11)

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#246]
Bug report:
>When I search places for hosts, and the little green circles appear with the number of hosts on them, I try to zoom in (or click on a circle) and all the hosts disappear from the map, and there's nothing I can do to actually view their profiles. 

IE11 on Windows 8.1.
Happens also with mobile IE.

Possibly some problems with CSS or SVG files (although [svg support](http://caniuse.com/#feat=svg) and [support for svg as a background](http://caniuse.com/#feat=svg-css) looks good for IE).

**Comment by guaka** [comment]
selenium/browserstack?

**Comment by simison** [comment]
Tested with IE11, I'll ask around someone to test with WindowsPhone later.
