### ISSUE TITLE
Change the circle name cyclists to tourcyclers

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2475]
A reoccurring subject in Slack. It's a small detail but very important for those to identify with this circle. Maybe even more important since we started to welcome former Warmshower members.

**Comment by guaka** [comment]
Is this still important?

What if we improve the description (instead)?

> Legs of steel or maybe just some grand tour ambitions? Cyclists connect with this circle, before, during and after you hit the road.

https://www.trustroots.org/circles/cyclists

**Comment by guaka** [comment]
This page seems to be the only page on the web that uses the term "tourcyclers", so either we reopen with a more commonly used term or we leave it at "Cyclists", but maybe improve the description a little?

**Comment by TMC89** [comment]
This was actually an input from Mariha, she found it very important.
