### ISSUE TITLE
Implement new circles

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2476]
After reviewing the circle requests (channel Slack), having a meeting, the following circles should be added:
**Activists** 
Power to the people! No oceans, no life! Make love not war! Join this circle to find your fellow activists, add your protests on the map and join eachother in making the world a better place.
**Runners**
Anywhere you travel, your running shoes come with? The more miles the better? You even travel for big competitions? Weither you're a casual-, free-, marathon- or trail runner, this is the group for you.
**Filmmakers**
Aaaand action! Holding a camera, being in front of it, working on the tech side of things, traveling to find the best settings: if this all seems familiar to you, this is the circle to join. Find fellow enthusiasts, exchange experiences, work together on projects and of course travel the world.
**Last Minute Requests**
Are you always in for some last minute surprises? Love hosting people? Want to help out those who're stranded? Join our Last Minute Request circle to make it easier for travellers to find you and reach out.
(For this circle it is necessary to check your messages regularly)
**Zero-wasters**
Interested in reducing the waste going to landfill and incineration ? Connect here with people acting individually and collectively towards a waste free world.
**Ravers**
Love dancing your ass off to beats in underground and secret locations? Come join and find out where the party is at around the world. If you know, you know.
**Scuba divers** 
If you love spending more time underwater than above land exploring amazing worlds, then this circle may be good for you.

![Activist circle](https://user-images.githubusercontent.com/74301087/143677365-879c2b9e-ec01-44f7-b4e0-549520799996.jpeg)
![Runners Circle](https://user-images.githubusercontent.com/74301087/143677386-3b3c4aac-5181-4f9b-b3f4-222c43e2d0af.jpeg)
![Filmmakers Circle](https://user-images.githubusercontent.com/74301087/143677393-3ddc6837-2761-4f1b-a9c5-4317336449d3.jpeg)
![Last Minute Requests Circle](https://user-images.githubusercontent.com/74301087/143677400-58aabc7f-2392-44a3-8613-ffe2130a43d2.jpeg)
![Zero Waste](https://user-images.githubusercontent.com/74301087/143677406-ecd1d132-ed9a-468e-98b4-1886b19f0180.JPG)
![Rave](https://user-images.githubusercontent.com/74301087/143677414-b1fcd53a-be0c-4cb2-b5f4-38f73d2ab7df.jpg)
![Diving](https://user-images.githubusercontent.com/74301087/143677427-4091df39-32f6-4409-ae36-3569a220c3f0.jpg)

**Comment by simison** [comment]
All done!

Can you help compile this info for each image:

- Original image source (link)
- Image license, or other permission to use the image
- Photographer name
