### ISSUE TITLE
Map issues

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#2497]
https://user-images.githubusercontent.com/31655082/146569473-b674106d-868b-42b8-a311-d08ac84657d6.mp4

**Comment by chagai95** [comment]
https://user-images.githubusercontent.com/31655082/146572238-e12c7e43-d5d5-45cc-bc79-741e884b91fc.mp4

**Comment by simison** [comment]
What's the;
- Browser
- Resolution
- Anything else that might help replicate

Tested briefly on 1440px width screen on Chrome and couldn't replicate, but I can test more later with bigger screen.

**Comment by chagai95** [comment]
I tried chrome and edge. Resolution 4k. I'll try thinking of more details that'll help replicate
