### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2504]
Idea submitted through support: 

> when will you guys implement two factor authentication? App (and not SMS) based one preferably?!

**Comment by simison** [comment]
Not on the plans right now but of course happy to accept PRs.

**Comment by chagai95** [comment]
If someone actually does this then please maybe opt in, this isn't a bank 😂

**Comment by Daucus-gh** [comment]
Also because in hospex on average it is more damage that you cannot access your account than someone else enter in your account.
