### ISSUE TITLE
Warning about the wiki pages 

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2509]
Since some time there's a warning when going to the wiki pages about the page being unsafe..

![Screenshot 2022-01-05 at 18 36 40](https://user-images.githubusercontent.com/74301087/148263301-33a8eab8-391d-48e7-af98-eeb623ef8af9.png)

**Comment by guaka** [comment]
<img width="154" alt="image" src="https://github.com/Trustroots/trustroots/assets/54728/7d1d1507-6570-4ea1-98d3-1af277c3ed0c">

fixed a while ago
