### ISSUE TITLE
Automated localhost tunnels with pagekite

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#251]
I spoke to the folks at [pagekite](https://pagekite.net/) and they are happy to offer us a free team account. It's pretty sweet, gives us public urls which forward to localhost. The core of the service is currently a ~160K python file. If we can secure credentials with git-crypt, we could potentially set up something which automates the tunnel setup and teardown (maybe with grunt).

I wonder if we can somehow get things like Facebook authentication to work on any developer's machine using this approach. I think we get sub, sub domains. So domains like `foo.trustroots.pagekite`. Maybe we can authorise `trustroots.pagekite` on our dev Facebook apps.

## Goal

It would be great if a new developer can clone the repo, run the init process, and have a working app that integrates with oauth logins, can receive webhook callbacks, and so on.

Super un-urgent, just recording the itch that I might decide to scratch one day...

**Comment by simison** [comment]
Interesting! I wouldn't mind to start testing this already myself. As I understand, we wouldn't need a separate repo for git-crypt stuff?

I made test apps at Twitter/GitHub/Facebook and I'm using them for dev.trustroots.org — we could add pagekite domains to same apps.

**Comment by simison** [comment]
Testing this now. It's brilliant!

What/when/how can we get this? Can we get our own CNAMe redirect? We can blog like we did with [Browserstack](http://ideas.trustroots.org/2015/04/07/selenium-browserstack-testing/).

**Comment by chmac** [comment]
There's something on their site about free for FOSS. I think there's a form we fill in there. First we need to create a "trustroots" account as I understand it. I created a "chmac" account. Then we just email and they'll set it up.

**Comment by simison** [comment]
I dropped them a message couple days ago.

**Comment by chmac** [comment]
If you don't get any progress via email, I found the person on IRC.

**Comment by simison** [comment]
They sorta just disappeared; it's anyway just to test FB/Twitter connections so I don't feel it's that important.
