### ISSUE TITLE
It's not possible anymore to read (old) messages (particulary) and write new ones

### ISSUE THREAD

**Issue by BernhardBehrendt** [Trustroots/trustroots#2511]
**Describe the bug**
It's actually not possible to read/write messages. The only messages I can read are the ones where I replied that I cannot host.
I

**To Reproduce**
1. Go to some user profile 
2. Click on send a message'

4. See error  (Tested in Chrome and Safari) Page stayes white... nothing happens.. console has errors (see picture)
![Bildschirmfoto 2022-01-07 um 16 29 10](https://user-images.githubusercontent.com/1717382/148566811-393b0323-74ea-4704-8513-76be1613334c.png)

**Expected behavior**
I can write a message

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser chrome, safari
 - Version [latest each]

**Comment by chreekat** [comment]
I can't view any of my messages either. :/

Browser: Firefox 95.0.2
OS: Linux, NixOS 21.11 (21.11.335037.e67c94a1adb)

**Comment by interstates21** [comment]
Same here on MacOS

**Comment by simison** [comment]
Thanks! I rolled production to the previous version so trustroots.org works again, but we need to still fix the issue.

It was caused by https://github.com/Trustroots/trustroots/pull/2494, I'll revert it to get it fixed and we'll have a new attempt at languages with a proper fix.
