### ISSUE TITLE
Bug in the experience tool

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2530]
It seems this experience where someone doesn't recommend the person, isn't showing. On the profile of the person who left the experience, it doesn't either that they left an experience..

![Screenshot 2022-02-07 at 19 32 43](https://user-images.githubusercontent.com/74301087/152850827-80f05e8e-e5d1-4b45-a668-b8ef42cbc2b7.png)

**Comment by TMC89** [comment]
Another bug: it says [this person](https://www.trustroots.org/profile/vince71/experiences) is hosted by everyone, while HE hosted everyone.

**Comment by mrkvon-tr** [comment]
> Another bug: it says [this person](https://www.trustroots.org/profile/vince71/experiences) is hosted by everyone, while HE hosted everyone.

Please consider merging https://github.com/Trustroots/trustroots/compare/master...mrkvon:trustroots:fix-reversed-experience-count?expand=1 to fix this part of the issue.

Click the link, edit PR description, then click `Create pull request`, and merge after the tests pass. Thanks!

@guaka @TMC89 @robokow

**Comment by chmac** [comment]
I (hope) I have fixed this, deploying now. It might take a while for this to actually go live though, as there's a few layers of caching.

**Comment by rumwerfer** [comment]
This is really getting weird. I never thought Trustroots would get a place where comments get deleted and reasonable contributions are blocked.

And I don't understand why. Does anyone have to prove to themselves they can do it all alone? It makes me sad.

**Comment by guaka** [comment]
@rumwerfer, I don't want you to be sad. And I don't think it's needed, I sent you an email.

**Comment by chmac** [comment]
@rumwerfer nobody's trying to do it alone. But Michal has been banned from volunteering for his abusive conduct. His contributions are not welcome.
