### ISSUE TITLE
Notifications App are broken

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2534]
See discussion in Slack: https://trustroots.slack.com/archives/C0A3Q15SS/p1639140642038300

Mikael explained it comes down to: _I don’t know what exactly is broken, but I would guess something around the Firebase implementation and thus native app push notifications don’t appear. We’re quite a lot behind on keeping Firebase up-to-date and something might’ve stopped working. This would be a high-impact issue for anyone to look into while we continue having email deliverability issues._

**Comment by guaka** [comment]
I think we can close this.
