### ISSUE TITLE
Add info about "respect" when writing an experience

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2539]
Through support, to add this info when members write an experience.

> 'Be respectful of others and 
> restrain from any kind of abusive behaviour.'

The member who suggested this feels we don't remember members of this anywhere when writing an experience.

**Comment by TMC89** [comment]
![Screenshot 2022-03-19 at 15 28 36](https://user-images.githubusercontent.com/74301087/159125133-e1849832-338c-4b38-85cf-d56d7bd7b011.png)
What about after this sentence?

**Comment by rishav-karanjit** [comment]
Where is this HTML file located in the repo? Searched but couldn't find it.

**Comment by TMC89** [comment]
Sorry, I don't now anything about coding, so don't know how to help you.. @chagai95, can you help?

**Comment by chagai95** [comment]
I think it's better to ask such questions on the slack, I would assume it's in react so it's not in an html file. I usually just search for the strings 😉

**Comment by guaka** [comment]
OK, we could change "Public feedback" into something like

> "Leave your public feedback here. Remember to be respectful of others and restrain from any kind of abusive behaviour."

here's the file: https://github.com/Trustroots/trustroots/edit/2539-add-info-about-respect-when-writing-an-experience/modules/experiences/client/components/create-experience/Feedback.js

**Comment by TMC89** [comment]
Sounds good! I really appreciate you referring to the code but I have no skills to work with it or is this just for future references so when someone does know how to work with this, they don’t have to look for it anymore?

**Comment by chmac** [comment]
@guaka if you want to try editing the code in a branch, I can take a look, then build and deploy it.
