### ISSUE TITLE
Stricter username validator

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#255]
Username validator should be stricter;
- [x] Can't start or end with `.` (will cause problems with user mentions in a paragraph of text with punctuation.
-  [x] Must have at least one a-zA-Z0-9 (no usernames like `---`) — [stackoverflow](http://stackoverflow.com/a/14850765) for inspiration.
-  [x] Remove max 32 chars limit (`{3,}` instead of `{3,32}` should do)
-  [ ] _Anything else?_

[Current validator](https://github.com/Trustroots/trustroots/blob/master/app/models/user.server.model.js#L24-L41)

**Comment by simison** [comment]
@katsuroo wanna take this? :-)

**Comment by guaka** [comment]
This is a typical case for getting started with test driven development! :)

**Comment by simison** [comment]
Indeed. :-)

**Comment by katsuroo** [comment]
Sure, I'll look into it tonight.
