### ISSUE TITLE
Experiences thoughts

### ISSUE THREAD

**Issue by chagai95** [Trustroots/trustroots#2565]
Hey hey, I think it's time to revive this a little bit,

I feel:
a. Uncomfortable leaving no experience when someone leaves an experience with me - I think we should address this.
b. If I skip the part with the text I also feel uncomfortable especially because I don't know if the other person wrote anything about me, maybe we should inform people if the review had text in it (still without showing the text) or if it was just a - "I recommend"

**Comment by simison** [comment]
What would make it easier for you to feel leave a reference?

Should there be a way to skip leaving reference, in which case it'd be come public right away? (but you couldn't review back as if 14 days limit had passed)

**Comment by chagai95** [comment]
I don't mean skip leaving a reference just skip leaving text with a reference - this field is optional and we deliberately added a skip to make it easier and more accepted for people to just leave a reference without text, because a lot of times you don't really want to write something public shit the person but want to say it was ok being with them I guess?

**Comment by simison** [comment]
I think some guilt and pressure there might be just fine, at the end of the day everyone benefits (notably also collective platform) if people do leave more references?

That said, it would help if "no need to write anything, just click a button" would be more clear up-front. I'd bet it would lead into more references overall.

**Comment by chagai95** [comment]
That's also an argument, I was just following the thoughts of other people, where the idea was to not turn Trustroots into a reference machine, that's why we added some skip button in the first place.

But I completely understand if we do want to go in this direction and get more people to leave more references (with or without text)

Maybe we could have some other wording? I think the difference between text or not it's more like leaving a review than a reference? King of like rating with stars which is also without text but you can always leave a comment as well - which most people usually don't?

**Comment by TMC89** [comment]
Got a request from support to allow members to write an experience after 14 days. Apparently they forgot and it only now says "recommend". Not sure if it's an easy adjustment and if it's something that fits within the philosophy why it isn't possible at the moment :)
