### ISSUE TITLE
Send notification in a radius about nearby meetups

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2568]
Suggestion from support :) So members who want to, get a notification about a new meet up near them (radius can be decided).

**Comment by simison** [comment]
This would be a really fantastic feature to have, maybe with an opt-out mechanism directly in the emails as well as at the settings page.

**Comment by guaka** [comment]
Currently I count 26 meet dots.  Maybe notifications would increase this but then I'd rather spend the effort on thinking how to do this on nostr, and in a way that it can be useful for many other situations.

https://github.com/Trustroots/nostroots/issues/12
