### ISSUE TITLE
73 users in a village near Stuttgard

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#257]
Leinfelden-Echterdingen

A spambot creating a bunch of fake accounts?

**Comment by Remigr** [comment]
It's a bug, see #132

**Comment by simison** [comment]
Yeah, I'm suspecting those guys are coming via mobile.

The plan is to first improve mobile experience when adding hosting pin to the map and then manually write to all those guys and ask them to update their locations.

Closing this and following at the other ticket.

Thanks!
