### ISSUE TITLE
Nudge members to have video call before meeting

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2571]
We had a discussion already about this on Slack I believe and now I got the same suggestion through support: add some info that hints members to make a video call before meeting. The member at support said it would be less uncomfortable when the platform suggests its, than asking for it themselves.

**Comment by tyssniffen** [comment]
this is a great idea, and definitely should be part of the process when connecting to host/visit.  Also should be part of the regular 'this is how we do things' messaging, from intro email to regular newsletter content.

**Comment by mariha** [comment]
@chagai95 made a PR for it: #2029
