### ISSUE TITLE
Email notifications for new messages in existing thread 

### ISSUE THREAD

**Issue by rdoc101** [Trustroots/trustroots#258]
I get an email notification on receiving a message for the first time from another user, but then on them replying to more messages i get no further email notifications which means I have no idea that someone has replied to me.

**Comment by simison** [comment]
Thanks, something's broken there then.

**Comment by simison** [comment]
@rdoc101 just tested this at localhost and it works. 

Unfortunately error catching at that cron script is almost non-existent (improving it now) so I can't see which mails failed to send (if any).

Could you check your spam box in case?

f

**Comment by rdoc101** [comment]
Nope, not in the spam. This has happened twice for me so far.

**Comment by rdoc101** [comment]
Hmm, this morning i got a email notification through from the same thread. So maybe it is something further down the line that was problematic. I will set up a local version of tr and see if i can recreate problem and report back.

**Comment by simison** [comment]
In any case I improved error logging and now if sending notification fails, it'll hold it back and tries to resend.

**Comment by simison** [comment]
I'll close this for now, we badly need job queue for this stuff anyway to be more fail-resistant. #260
