### ISSUE TITLE
Production docker container

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#2592]
This is an issue to document the process of (trying to) get trustroots to run in production mode in a docker container. The theory is that this would dramatically simplify the server admin role, but let's see. Documenting steps here for posterity.

**Comment by chmac** [comment]
Using docker-compose, the trustroots container starts before the mongo container is ready. The mongo 4.4 container doesn't support a healthcheck, so we can't wait until its healthy in the compose file. I hacked a 30s delay into the app startup, that might work for now. Otherwise I could restart the trustroots container once mongo was running and then the container worked.

**Comment by chmac** [comment]
Running `npm run build` inside docker fails for me. It complains about missing support for JSX syntax. Specifically the webpack build. It runs successfully on my laptop, but doesn't seem to include the files which report JSX errors in docker.

**Comment by chmac** [comment]
Progress. I have the app running locally. At least, it looks like it. I can register, edit my profile, etc. Can't see emails, don't think I have the worker running, so can't really see how much works. But the basics are at least there.

Still, that's only because I copied `public/assets` from my host into my container. Somehow that build is still broken inside docker, and it's not clear to me why. Potentially something to do with the NODE_ENV. I dunno. More research required. But at least in theory this seems to show that docker for production is possible. 🥳

**Comment by chmac** [comment]
Got the build working! 🥳 🥳 🥳 

Turns out the build process needs a whole bunch of the dotfiles. But now it works. I'm building successfully in docker, and then I can run the app successfully in docker. This looks like concrete progress.

**Comment by chmac** [comment]
Alright, now I've got a worker, server, and mongo running in docker. They seem to work as expected. Maybe it makes sense to use pm2 to run the worker. Otherwise the setup looks like it'll work.

**Comment by chmac** [comment]
Next question is how to get the built docker image onto a server. Part of the whole point of this is to avoid having to build the production codebase on the production server. That seems like a really bad idea on so many levels. I suppose in a perfect world we'd have a continuous integration process which builds the docker image and pushes it somewhere. But failing that, maybe we can push it to docker hub and pull it from there on the production server(s).

**Comment by mrkvon** [comment]
This effort would be worth synchronizing with that of @sitarane, who has been fixing docker containers.

Some duplicate work may be going on here

**Comment by chmac** [comment]
Just realised that there's some folders like image uploads which need to be mounted from the host into the container.

**Comment by chmac** [comment]
Alright, I think this is ready to test.

    git checkout chmac-docker-for-production
    cd deploy/docker
    docker compose up

To make this useful, you need a `local.js` config file at `deploy/docker/data/local.js`. Figuring out the contents of that file is beyond the scope of this topic.
