### ISSUE TITLE
Uploaded avatar in experiences doesn't show

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#2596]
**Describe the bug**

When an avatar was uploaded manually (i.e. no facebook, no gravatar), it doesn't show up in Experiences.

Seems like images of size 36 and 24 are no longer supported (or have been deleted)...

**To Reproduce**

Find (or generate[^1]) somebody with experiences, who uploaded their profile image (not gravatar nor facebook). See that their profile image is missing in the experience.

[^1]: need to check whether this is an issue for the new members

**Expected behavior**
Profile image shows in experiences

**Screenshots**

(Generated with Dark Reader browser extension on - that's why background is dark)
![image](https://user-images.githubusercontent.com/7449720/190233773-85f3ae26-a34f-485f-8991-bb32f6459536.png)

**Proposed fix**

1. Figure out why sizes 36, 24 and 16 are not present anymore (and check what other sizes may be missing)
1. Generalize [Avatar component](https://github.com/Trustroots/trustroots/blob/master/modules/users/client/components/Avatar.component.js) to accept any image size (round the size number up to the size of the nearest existing image when generating image url) (e.g. size 36 will display the image 64.jpg)

**Comment by mrkvon-tr** [comment]
Duplicate of #2388
