### ISSUE TITLE
Add notes about discussion to contributing.md

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#261]
GitHub issues are not a discussion forum. This is a forum for technical discussion about how to implement features, questions of a technical nature, reporting bugs, and so on.

It is not a place for policy discussion. Personal opinion about which features are important, which features should or should not be implemented, and so on, does not belong here.

We operate a 3 strike policy. 1st warning, 2nd warning, blocked.

Refer to the [Ubuntu Code of Conduct](http://www.ubuntu.com/about/about-ubuntu/conduct) for guidance on how to contribute. Particularly the following points:

* Be considerate
* Be respectful
* Take responsibility for our words and our actions
* Be collaborative
* Value decisiveness, clarity and consensus
* Ask for help when unsure
* Step down considerately

Our code of conduct might be described as follows.

> Be nice to people. Show respect for those who do the work. When in doubt, defer to those with more experience, who have contributed for longer, and support their decisions.

**Comment by chmac** [comment]
@guaka @simison What's missing from the above? Feel free to edit away. Should we move it to a wiki page so we can see a history of edits?

**Comment by simison** [comment]
I'd turn the whole thing reverse — last (positive, encouraging) bits first and first bits (no/don'ts) to the bottom.

Wikipage would be better. On the other hand Github shows a big link to Contributing-file each time when creating and issue, so def. add a link to contributing file.

**Comment by chmac** [comment]
Awesome, look forward to reading your edits! :-)

Yeah, I thought maybe wiki page to edit it, and then copy it into contributing once it's ready.

**Comment by simison** [comment]
;-) I might. It's very good already anyway. Thanks!

**Comment by guaka** [comment]
No need for a wiki page, I copied and remixed it directly at https://github.com/Trustroots/trustroots/blob/master/CONTRIBUTING.md - please edit there, also works quite well from GitHub's web interface.

**Comment by simison** [comment]
Thanks, LGTM.

**Comment by guaka** [comment]
Just added this: "We highly value real life interaction. Both within the network as well as among technical contributors. If possible, try to meet up with other Trustroots contributors in real life."

We should do something cool with the GitHub connection on TR profiles soon :)

**Comment by simison** [comment]
BTW I quite like "be pragmatic" bit at https://owncloud.org/community/code-of-conduct/ (ping @jancborchardt)

**Comment by jancborchardt** [comment]
Yeah – that’s very important to fend off the »power users« who tend to be very loud on the issue tracker. ;)

**Comment by simison** [comment]
Looks good! https://github.com/Trustroots/trustroots/blob/master/CONTRIBUTING.md
