### ISSUE TITLE
Bug & feature tab/FAQ

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2623]
At the moment all bugs, features requests or improvement are submitted through support. More direct would be if members would take a look at the current issues in our GitHub and if needed add a new one. This way they also directly get an update themselves or can ask for progress. 

Suggestion to make this happen:

![Screenshot 2023-03-08 at 13 17 20](https://user-images.githubusercontent.com/74301087/223727591-cf73d057-6f3d-47f4-831d-420bb301b962.png)
Add tab '_Bugs & Features_'

![Screenshot 2023-03-08 at 15 14 51](https://user-images.githubusercontent.com/74301087/223735767-ef749284-8d65-44c7-bf19-6148fb5b06cd.png)
Add '_Bugs & Features_' also in the menu here.

All redirecting to the FAQ's
![Screenshot 2023-03-08 at 13 22 40](https://user-images.githubusercontent.com/74301087/223735989-f0beb8fb-1205-40e2-a05d-b3c9632b1098.png)
Where a new Tab should be created '_Bugs & Features_'; with two questions:
**How do I report a bug?
Where can I suggest an improvement or new feature?**

The following explanations could be used:
**How do I report a bug?**
First of all: thank you for taking the time and making an effort in reporting a bug. We have a technical workspace where we document all our bugs, suggestions and improvement. If you go to our [Github](https://github.com/Trustroots/trustroots/issues) you can see all documented issues we currently have. 

Before you go through the trouble of creating a new issue, use the search bar to see if there's already an issue about the bug. You can check when it's created, the responses and who's working on it. 

If you want to respond or if you need to create a new issue,  you have to sign up at Github. It takes a few minutes and this way, you'll get an email about any updates or responses. When you create a new issue, you'll see some questions to help us to get a good idea of the issue. Fill in as much as you can and submit your issue.

**Where can I suggest an improvement or new feature?**
We're always very happy to hear back from the community how we can improve our current features or have creative ideas for new ones. Bare in mind though all time is donated and we fully rely on volunteers, therefore only when we have plenty of volunteers, there's time to work on these kind of suggestions. 

We work on these kind of things in our technical space in [Github](https://github.com/Trustroots/trustroots/issues). Here you can see everything that is currently documented. First use the search bar to see if someone else has submitted already your suggestion or if you can find a similar one. You have to create an account in order to do so. It takes a few minutes and this way, you'll get an email about any updates or responses. 

When you can't find an existing issue about your suggestion, you can create a new one. When you create a new issue, you'll see some questions to help us to get a good idea of the issue. Fill in as much as you can and submit your issue.

**Comment by guaka** [comment]
Yes I think I like this. There will be more noise on github, but there are also more people who can help with turning noise into signal here.

**Comment by TMC89** [comment]
@chagai95 do you want to take a look at it? We can have a call about it (:

**Comment by chagai95** [comment]
Yeah sure, let's do it!

**Comment by TMC89** [comment]
So Chagai and I gave it a try but without result. Is there someone else willing to help out?

**Comment by chagai95** [comment]
My mum thinks a tab called "Feature Requests" and another one called "Bug Reports" with the same content in both could be nicer than the title "Bugs & Features", what do we think about that?

**Comment by chagai95** [comment]
I think I managed to get some working version, for me the open points are now if the mobile view and how translation works but the English version on a laptop should be a good start.

**Comment by chagai95** [comment]
![Screenshot from 2023-04-07 10-52-57](https://user-images.githubusercontent.com/31655082/230577638-3360a84b-6de2-44fd-a782-72e885ab0130.png)
![Screenshot from 2023-04-07 10-52-52](https://user-images.githubusercontent.com/31655082/230577642-a64276d5-57fd-4b54-a884-927297431a05.png)
![Screenshot from 2023-04-07 10-52-41](https://user-images.githubusercontent.com/31655082/230577644-5317cf86-88ca-44f3-8dfa-9eba8f2339c3.png)
![Screenshot from 2023-04-07 10-52-27](https://user-images.githubusercontent.com/31655082/230577649-62c9418f-4ec3-4f23-b69e-a5e804520ce5.png)
![Screenshot from 2023-04-07 10-52-10](https://user-images.githubusercontent.com/31655082/230577653-24b7a092-f0bb-4bd1-ae69-e5836b147ad4.png)

**Comment by TMC89** [comment]
Amazing!!! Thank you so much! 

Btw, I get your moms idea but I think this is better and less scattered.

**Comment by TMC89** [comment]
@guaka do you think we can deploy this :)
