### ISSUE TITLE
Remove 'missing your circle'

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2624]
The discussion of the functionality of the circles keep rising but no decisions are made, however support does get questions about implementations, so until we decide the future of the circles, I would like this option removed.

![Screenshot 2023-03-08 at 16 22 56](https://user-images.githubusercontent.com/74301087/223754640-fe95cca8-b331-4c75-a570-145e79a3fa54.png)

**Comment by guaka** [comment]
remove  `<SuggestTribe />` here:
https://github.com/Trustroots/trustroots/blob/e1348062bc7eaa048bf84f655345d1875d1a9c6a/modules/tribes/client/components/TribesList.js#L44
