### ISSUE TITLE
Virtual keyboard covers the message textarea

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#264]
If you open keyboard with mobile, it might cover the textarea completely. I saw this happening with Windows pad (with IE) another day.

Here it seems to be working as it should with Firefox: #128 (check the screencast).

Requires heavy testing with pads, phones, different browsers...

I photoshopped how it looks:
![image](https://cloud.githubusercontent.com/assets/87168/7559510/8adb361a-f7c0-11e4-8d89-10d8964adab7.png)

Same same: #265

**Comment by guaka** [comment]
Browserstack is great for this

sent from my mobile phone

**Comment by simison** [comment]
Works fine now with Firefox and Chrome. Didn't test Safari.
