### ISSUE TITLE
after setting my hosting location,my point is not shown on the correct place

### ISSUE THREAD

**Issue by PLUSGear** [Trustroots/trustroots#2655]
I set my location, but when I check it afterwards, the point is around 200 meters away from the point which I set.

 - OS:win 11
 - Browser Firefox

**Comment by mrkvon** [comment]
Hello! Thank you for reporting @PLUSGear!

This is not a bug, but a safety feature. The app shows members' location a little bit randomized on purpose, for safety. You can check out the idea visually [here](https://github.com/Trustroots/trustroots/pull/361#issuecomment-225415213).
