### ISSUE TITLE
no scrum but waffle.io!

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#266]
Scrum could be interesting to try this for TR, especially when there's more focus, e.g. during hackathons, sprints, collectives?

[Jetbrains](http://www.jetbrains.com/youtrack/buy/) is a free scrum tool that integrates with GitHub. It's free for public projects, up to 10 users.

**Comment by guaka** [comment]
https://taiga.io/ looks great, is free+free! (free beer and free software)

**Comment by guaka** [comment]
https://huboard.com/pricing is free for open source projects and it integrates very well with GitHub

**Comment by simison** [comment]
https://waffle.io/

**Comment by simison** [comment]
@jancborchardt  experiences / tips?

**Comment by guaka** [comment]
https://fidop.io started using waffle, it seems better than huboard in a
few ways

**Comment by jancborchardt** [comment]
I would only use a tool with very good Github integration. I don’t have a lot of experience with Scrum except with Jira. And normally I would say for a small team of experienced coders & designers it’s better to not use such a system.

**Comment by simison** [comment]
Kinda my feelings with Jira (from BW) as well. :-) Thanks.

**Comment by guaka** [comment]
no need for scrum but let's try this: https://waffle.io/Trustroots/trustroots
