### ISSUE TITLE
Issue cleanup

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#2660]
We're doing some reorganisation.

Given the number of open issues, and the demotivating effect of so many open issues on volunteer energy levels, I'm bulk closing most issues. We may revisit these issues in the future, but we're not currently accepting feature requests.

**Comment by chmac** [comment]
Same for pull requests.

**Comment by beatnickgr** [comment]
I have taken my time to write down what could be improved on TrustRoots. The only "demotivation" is when you are "bulk closing" without doing anything about them.
If you don't wanna do it it's ok, but then you can leave it open for someone else. No one asked you to close my requests without fixing them.
