### ISSUE TITLE
disable welcome emails

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#2665]
to reduce the number of incoming support tickets

**Comment by guaka** [comment]
Quick and dirty solution: change the configuration so that the second and third emails are only sent after 1000000 days

```
 welcomeSequence: {
      first: { minutes: 0 },
      second: { hours: 24 },
      third: { days: 14 },
 },
```

https://github.com/Trustroots/trustroots/blob/e1348062bc7eaa048bf84f655345d1875d1a9c6a/config/env/default.js#L153

**Comment by guaka** [comment]
just signed up with a test account, no welcome emails have arrived so far

**Comment by TMC89** [comment]
Got a support ticket where the member received an email 31th of January..
Ticket #6603 if you need more details @guaka

**Comment by chmac** [comment]
It's possible that all members who signed up before we disabled the emails will still get their welcome emails. I think we disabled the scheduling of new emails for new users, but not the sending of emails for existing users, if that makes sense.

**Comment by guaka** [comment]
@chmac assessment makes sense. The welcome email relating to ticket 6603 was sent on Jan 31st and says "You signed up a little while ago", so probably the 3rd in the sequence, delivered after 14 days.

There were still 3 agendaJobs (out of 772601) related to a `welcome sequence`, all 3 had `"failReason" : "Operation `users.find()` buffering timed out after 10000ms"` and with `failCount` 408 and 97.   I deleted these.

I could come up with questions (e.g. if it was 14 days there should have been more agendaJobs left, and why did this users.find() operation fail) but this is not important, and I expect that no more welcome emails will go out from now on.
