### ISSUE TITLE
Close "features request" by changing text

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2668]
1. Change tab "bugs and features" to only "Report a bug". 
2. Change[ explanation](https://www.trustroots.org/faq/bugs-and-features) how to submit new ideas etc. to: "we've collected many new ideas and improvements on the last years, so this option is closed at the moment", or something like that. Otherwise support will be flooded again.

**Comment by guaka** [comment]
https://github.com/Trustroots/trustroots/blob/e1348062bc7eaa048bf84f655345d1875d1a9c6a/modules/support/client/components/SupportPage.component.js#L40

**Comment by chmac** [comment]
@guaka missed the menu and only changed the `/support` page. I've renamed the menu and am deploying now.

**Comment by TMC89** [comment]
Thanks to you both!

**Comment by chmac** [comment]
This has just deployed, should be live within a few minutes.

**Comment by chmac** [comment]
The deploy has gone live, but the menu still hasn't changed. I'm baffled. I will investigate further...

**Comment by chmac** [comment]
It has finally updated. I think there's some kind of server side cache that doesn't get immediately flushed on a new deploy.
