### ISSUE TITLE
Task: Remove social links

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#2672]
Removing links to facebook, instagram, etc.

**Comment by TMC89** [comment]
The link to the shop should also be removed (drop down menu at the bottom). I've already put the status on private so it doesn't show anymore in google.

**Comment by chmac** [comment]
Great point. I'll look at that when I'm back at my desk.

**Comment by MrSalami** [comment]
Why remove the social links ? They can still hold space for the community -

**Comment by chmac** [comment]
@MrSalami We're trying to cut down on anything that requires volunteer effort to maintain. I think it also makes sense to be a bit less focused on commercial social networks.

**Comment by chmac** [comment]
Removed social links, also working its way through deployment now.
