### ISSUE TITLE
Experiences feature available on mobile view

### ISSUE THREAD

**Issue by TMC89** [Trustroots/trustroots#2675]
Atm experiences only show when using a desk/laptop, not a mobile device. Might be good to make this possible since travelling people mostly use mobiles. If it's to complicated due to the code that has been used, it might be good to keep this in mind for the NOSTR project?

**Comment by chmac** [comment]
This should be fairly easy to fix I hope. I'll put it on my list.

**Comment by chmac** [comment]
I'm not 100% sure what the issue is here, but it seems to me like there's no link to the experiences section on mobile. So I've changed that, and now the tab bar should be visible on mobile. This should be deployed in the next half hour or so.

**Comment by TMC89** [comment]
Just checked: the tab is there. Thanks @chmac!
