### ISSUE TITLE
nip05

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#2692]
implement [NIP-05](https://github.com/nostr-protocol/nips/blob/master/05.md), now that we have an npub profile field
- [x] convert npub to hex, using nostr-tools
- [ ] put code in the right place, added to core.server.routes.js now but should be elsewhere?
- [x] look up nostrNpub in mongo
- [x] implement `/.well-known/nostr.json?name=bob` returning

```
{
  "names": {
    "bob": "b0635d6a9851d3aed0cd6c495b282167acf761729078d975fc341b22650b07b9"
  }
}
```

**Comment by guaka** [comment]
note I have been struggling with adding a proper library to the code, to convert between bech32 and hex

great if someone with more advanced js wizard skills can tackle this

**Comment by chmac** [comment]
@guaka which package do you want added? In which branch?

**Comment by guaka** [comment]
I don't really care about the specific package (or branch).

nostr-tools could be best, since we're also using that for nostr-map and may help with other nostr stuff later, but the nodejs version for this code base could be too old for that.

**Comment by guaka** [comment]
it works now, and is on production
