### ISSUE TITLE
[Request] Uploading Trustroots APK to F-Droid

### ISSUE THREAD

**Issue by aahmozart** [Trustroots/trustroots#2694]
A lot of people use F-droid to find new apps, as well as install apps outside Google playstore. It should be pretty easy to upload:

https://forum.f-droid.org/t/how-to-publish-my-app-on-f-droid/198

**Comment by chmac** [comment]
There's no official trustroots app. There is a third party app which doesn't seem to work very well. If we release an app then we would be open to publishing it on f-droid, but until then I'll close this.
