### ISSUE TITLE
Registration feedback

### ISSUE THREAD

**Issue by pierreozoux** [Trustroots/trustroots#270]
Hi!

My girlfriend just tried to create an account but she had hard time to login.
Somehow she was using a username with a space, but the feedback in red on top was not really helpful.

I think a better user experience would be to have live feedback, next to the non-valid field.

Best!

Pierre

**Comment by simison** [comment]
True. I was just looking at the signup form another day and thinking the same.

**Comment by simison** [comment]
I love the UI from MailChimp:

![screen shot 2015-05-31 at 22 24 48](https://cloud.githubusercontent.com/assets/87168/7903422/d0361f70-07e4-11e5-8a99-c3627fb238d1.png)

**Comment by simison** [comment]
Stackoverflow:
![stackoverflow-signup](https://cloud.githubusercontent.com/assets/87168/8377514/97cd54e2-1c1a-11e5-9794-97fd50e9f141.png)
---
![stackoverflow-signup-error](https://cloud.githubusercontent.com/assets/87168/8377515/9bc0bfd0-1c1a-11e5-8e73-4d99cf259545.png)
---
![stackoverflow-signup-forgot](https://cloud.githubusercontent.com/assets/87168/8377519/9e193d48-1c1a-11e5-87ec-20c0c6c94120.png)
