### ISSUE TITLE
nip-05: should be at trustroots.org not at www.trustroots.org

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#2701]
"Redirects aren't allowed according to the nip-05 spec. It doesn't work in amethyst for example."

**Comment by davotoula** [comment]
The issue is the redirect to www. for nostr.json.

You can either specify www. in nostr client... Or remove the redirect

**Comment by guaka** [comment]
fixed

**Comment by davotoula** [comment]
Works 
![nostroots](https://github.com/user-attachments/assets/9677c972-05af-46c7-a0b7-8f67176bd228)
