### ISSUE TITLE
way to remove Mean.js contributors from this project?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#274]
https://github.com/Trustroots/trustroots/graphs/contributors shows a lot of [Mean.js](https://github.com/meanjs/mean/graphs/contributors) contributors. Is there a way to only show the genuine TR contributors?

@simison

**Comment by simison** [comment]
Yeah, I did a mistake in the past when I was merging with latest MEAN.JS back then.

@Remigr had a look at this and I understood it's not straightforward, or?

**Comment by Remigr** [comment]
No not straightforward.
I can't find again the info I found before about that.
This can be a start : http://blog.powma.com/git-you-some-mean-js-setup-advanced-git/

**Comment by simison** [comment]
@guaka you get pretty close with this filter: https://github.com/Trustroots/trustroots/graphs/contributors?from=2014-10-06&type=c

Cuts some of my early contribs off it doesn't matter.

**Comment by guaka** [comment]
cool! would be good to add that link to the comparison article - and
similar links for BW and WS...

**Comment by simison** [comment]
Added http://ideas.trustroots.org/comparison-of-hospitality-exchange-platforms/
