### ISSUE TITLE
Persistent settings factory

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#277]
Edit: https://github.com/grevory/angular-local-storage might be sufficient enough.

---

Now we have only global settings coming from the backend via Angular SettingsFactory (under core module).

We've got already number of situations where it would be great to save UI settings/state to the browser. These could also be saved to the DB, but LocalStorage should be enough.

Needs to support both strings and objects.

Each setting could have expiration timestamp and Factory would take care of removing them before returning objects. This way Controllers don't need to ignore them; controller just tells when setting expires.

Could be either implemented into existing SettingsFactory or probably better to create some new "PersistentSettingsFactory" (or "UISettingsFactory"?).

Helps to implement #184 (remember map location) and #202 (messaging/shift+enter) and possibly #148 (cache unfinished message).

**Comment by Remigr** [comment]
What about lazy easy library? Something like https://github.com/agrublev/angularLocalStorage

**Comment by simison** [comment]
Yeah, could be just a simple wrapper around that. Does it support cookie style expirations directly?

**Comment by Remigr** [comment]
Doesn't look like it. But there are others, like this one https://github.com/grevory/angular-local-storage

**Comment by simison** [comment]
Aah, it's a two-way-bind thingy. Snappy. Perhaps it indeed makes sense to use it directly; then just have to implement setting expiration at view controller, but I'm not sure if we need that anywhere else than with map (#184).

**Comment by Remigr** [comment]
Check out the last one, it's good I think, it's not two way bind thingy.

**Comment by simison** [comment]
Doing these per controller instead of a separate Service to go around edge cases/behaviour. It's working at the map to remember the last location already: https://github.com/Trustroots/trustroots/blob/8637a6f545f864217797b4c9c0a48d361cd24f58/modules/search/client/controllers/search.client.controller.js#L224-L232

Thanks for the angular-local-storage tip!

**Comment by Remigr** [comment]
I see that the storage type is set as sessionStorage https://github.com/Trustroots/trustroots/blob/cc2de524a3bf141e2e916f7b2ac181a84066dd87/modules/core/client/app/init.js#L34, so it will not remember the location after the session. Is it on purpose ? I think it's nice if it remembers the location also for the next time you come to the website. Then localStorage setting could be used.

**Comment by simison** [comment]
Yeah, I set it to default 'session' (instead of 'local') by purpose now at first. It gives a bit more space to experiment with the feature and see how it works. Actually, I'll go ahead and something that clears these on logout.
