### ISSUE TITLE
Show message content is email notification

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#278]
When you get a message on TR, an email notification is sent saying "you have a message on TR". User needs to open TR, login, before seeing the message. Reply rates might get better to much better if the message content is shown in the notification. In particular for short notice requests. Which is what hitchhikers do.

**Comment by sitarane** [comment]
Maybe needs its own issue: send the email notification with reply-to as the senders email address (opt-in for privacy reasons). So the person that is requested can reply to the person that is requesting directly from the email, without opening TR.

**Comment by simison** [comment]
Done already, just not in production yet. :-) #177 

Email replies is quite big thing which is on the todo, but there's a bunch of stuff we'll want to get done first before it. #163 

Thanks! :-)

**Comment by simison** [comment]
Oh, and it'll look like this:

![image](https://cloud.githubusercontent.com/assets/87168/8393653/45b2bbb2-1d22-11e5-9ce2-7751594d336e.png)
