### ISSUE TITLE
Map marker for people who just want to meetup

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#28]
- Similar GUI to hosting #4 
- Show markers at the map #3

**Comment by chreekat** [comment]
This is the issue I found when searching for "meetup". I see it's been closed in favor of #358, but what *I* was looking for is a way to organize meetups for Trustrootsers in a particular area. Is that something under consideration somewhere?

**Comment by simison** [comment]
@chreekat eventually, but gotta first do finding and meeting individuals a blast. Then eventually something like that starts making sense, too.

**Comment by simison** [comment]
@chreekat check this out! https://github.com/Trustroots/trustroots/pull/543

**Comment by chreekat** [comment]
Nice!
