### ISSUE TITLE
create landing pages for people not logged in or...

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#280]
create landing pages for people not logged in or...

retain incoming URL such as https://www.trustroots.org/#!/search?location=Amsterdam  and send people there after they log in (or sign up even)

spin off from https://github.com/warmshowers/Warmshowers.org/issues/620

**Comment by simison** [comment]
To test, logout and open:
https://www.trustroots.org/profile/mikael
https://www.trustroots.org/search?location=Paris
https://www.trustroots.org/search

**Comment by guaka** [comment]
Lovely!

(Possible improvement: actually show map with much more randomized
locations of hosts.)
