### ISSUE TITLE
Trustroots song

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#282]
We need an anthem, a song that all hitchhikers all over the world can play on their guitar.

Playable with only 4, 5 simple chords.

**Comment by guaka** [comment]
something like https://www.youtube.com/watch?v=GlDnIPOR8_0

**Comment by simison** [comment]
We should create another repo for this stuff...

**Comment by guaka** [comment]
https://github.com/Trustroots/community

**Comment by guaka** [comment]
https://github.com/Trustroots/community/issues/1
