### ISSUE TITLE
#!

### ISSUE THREAD

**Issue by quite** [Trustroots/trustroots#283]
What's up with the #! in every URL? I doubt that it's a necessary result of function A or development method B, am I wrong? Some trick with nodejs? It does give me a slight... discomfort. But perhaps I should just shake that ;)

**Comment by simison** [comment]
Yup, it comes from AngularJS and meanjs boilerplate we're using. 

We didn't like them either and it's already fixed in the new version, just not in production yet. Patience. :-)

Thanks!
