### ISSUE TITLE
Can't add newlines on messages in Firefox mobile

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#286]
When typing a message on Firefox mobile, pressing the enter key creates a new line, but the cursor remains on line 1. If I click further down the screen to move the cursor onto line 2, whatever I type is inserted at the end of line 1. If I put the cursor on line 2 and press backspace, it deletes the last character of line 1.

I'm able to create more lines, but only ever type on line 1.

**Comment by simison** [comment]
Good catch.

I'll just leave these here: 
https://github.com/thijsw/angular-medium-editor (in use)
https://ghinda.net/angular-meditor/
http://icattlecoder.github.io/ngmeditor/

I want to test how these work with different browser/mobile device combos/situations.

**Comment by simison** [comment]
Tested, works now.
