### ISSUE TITLE
Show a "good hosting request" guide next to message thread

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#287]
Show a link/popup to a short "good hosting request" for members signed less than ~1 month ago.

Somehow quite visible next to the message field. Perhaps under profile-box on the right?

Remember to make sure it works nicely with mobile as well (or just hide it there).

**Comment by guaka** [comment]
related to #196

**Comment by simison** [comment]
@guaka wanna start this by scribbling something short? :-)

**Comment by guaka** [comment]
scribbly wibbly https://github.com/Trustroots/trustroots/wiki/Text:-Good-request

**Comment by simison** [comment]
https://www.facebook.com/trustroots.org/photos/a.433672670113514.1073741830.294353200712129/515485251932255/?type=1&theater
