### ISSUE TITLE
US location form on profile page is confusing

### ISSUE THREAD

**Issue by RichardLitt** [Trustroots/trustroots#289]
Currently, the Location section on the Profile page says "City, Country". This works well for "Paris, France". I live in Cambridge, Massachusetts, USA, however - and it isn't clear to me that I ought to put in my state. When I type in Cambridge, it autosuggests "Cambridge, 02139, Massachusetts, USA". This works - the autosuggest clears up the initial confusion a tiny bit - but that's not my zipcode. 

I think this can be improved by removing the zipcode from the autosuggested results, and changing the placeholder text to "City, (State), Country".

**Comment by simison** [comment]
Yeah that geocoder autosuggestion is a bit crappy. Also #149 

It's also a bit unclear that you can actually write stuff like "Mars" or whatever else into that by skipping the autosuggestion. I think you have to click somewhere outside the list with mouse or something similar.

UX definitely has to be improved.

Thanks!
