### ISSUE TITLE
Unable to add languages that are not autosuggested

### ISSUE THREAD

**Issue by RichardLitt** [Trustroots/trustroots#290]
I am unable to add `Latin`, `Ancient Greek`, or `Na'vi` to my languages. Granted, I am unlikely to speak those languages to a guest - but it's not impossible, and I would like to be able to add that I speak them. I also cannot add `Wompanoag` - a minority language, chosen at random and which I don't speak, with a few hundred speakers in Massachusetts. 

Adding the ability to add your own language by pressing enter would alleviate this issue.

**Comment by RichardLitt** [comment]
Possible duplicate of #98.

**Comment by simison** [comment]
Yup, thanks, I'll copy this to there!
