### ISSUE TITLE
Add links to profiles

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#293]
## Goal

Users can easily add a list of links to any existing profiles in order to "enhance" their profile. It would be nice to decorate the links to show icons and so on, but that could be added later. The priority is to make it easy, and to encourage, users to link to other profiles.

## Steps

Let users easily link to other networks, for example:
* Warm Showers
* CouchSurfing
* BeWelcome

If the user provides a link to a known site we could filter the link to only show the username and the site icon.

Later we could extend the feature to automatically retrieve the site favicon and show it automatically.

**Comment by simison** [comment]
Sticking to hospex profiles (#294) for now, custom links can be always added to the description field, as they aren't anything we need to use at search or get statistics for.

Just need to improve editing that description field, now it's a bit unclear and buggy.
