### ISSUE TITLE
Ask for CS / BW / etc usernames

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#294]
Encourage users to link to their existing hospex profiles by adding links (we probably want to feed the data from this into the same profile field as #293).

Initially let's focus on the most important sites:
* CouchSurfing
* Warm Showers
* BeWelcome

Show a link to the user's profile in the same way as we link to Facebook, Twitter, etc...

**Comment by simison** [comment]
Well, that was quick and simple! :-)

**Comment by simison** [comment]
https://github.com/warmshowers/Warmshowers.org/issues/716

**Comment by simison** [comment]
Holding up publishing this feature until we [get clarity](https://github.com/warmshowers/Warmshowers.org/issues/716) if we can actually connect to Warmshowers via [Passport-Drupal](https://github.com/mixmarket/passport-drupal). That'd be neat.
