### ISSUE TITLE
show deployed version in footer

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#295]
- at deploy time, with a script generating a file (.html or .txt)
- show date and commit of deployed version
- link to [specific commit](https://github.com/Trustroots/trustroots/commit/f34492eae5f1ac3e527123925a8951c9f6f1f923)?

**Comment by simison** [comment]
This is actually visible at [statistics page](https://www.trustroots.org/statistics). It's so unimportant info for the vast majority that I wouldn't dump it to the footer, except in the future only for admins perhaps.

Do you recon that's enough or should there be a timestamp as well? I'm using [git-rev](https://www.npmjs.com/package/git-rev) to fetch the info.

**Comment by guaka** [comment]
This is how it worked at CS 2006/2007: footer showed which SVN revision was
running and there was a direct link to "report bug" in Mantis (bug
tracker), which included the SVN revision, browser info etc. When someone
sent in a bug report there was [Midsch](
http://wiki.csexport.org/en/Special_Contributions/Midsch.html), who did an
amazing job filtering and organizing incoming bugs. Quite a few of the bug
reporters helped a lot with testing and some even became developers.

It'd be great to get something similar going.

**Comment by simison** [comment]
Ah I see, you mean it would attract developers. Cool, I'll look into it.

**Comment by guaka** [comment]
It attracts developers and also non developers who want to be involved in
development, e.g. testing. And it's great to have non devs around in the
entire process :)

**Comment by simison** [comment]
BTW we won't really have much footer showing up most of the time (search/messages) but I've kept this open for inspiration to have some kind of clear path for volunteers from the site.
