### ISSUE TITLE
Copy paste with Android Firefox on edit profile

### ISSUE THREAD

**Issue by bleadof** [Trustroots/trustroots#300]
Because tapping on the text box another time looses the focus from it, it made it reaaaaallly hard to copy paste. 

I'm still unable to move the cursor to the end of the text. I might fix this if I have enough time this weekend.

**Comment by simison** [comment]
I finally have a proper Android phone to test things out. Will do a test run with Firefox.

Also #286

**Comment by bleadof** [comment]
I'm using Firefox 40.0.
