### ISSUE TITLE
Native mobile client

### ISSUE THREAD

**Issue by bleadof** [Trustroots/trustroots#301]
I might be interested in contributing to one. The mobile web is still horrible, especially the maps. My brain 🎉 after trying to use it on Mobile Firefox. It's not the design, but the lack of performance.

**Comment by simison** [comment]
Hey! Great. I'd be glad to help with Android and/or iOS versions.

We already have an API (and it's even [documented](https://www.trustroots.org/developers/api/) pretty well).

I guess the bare minimum would be:
- Able to send/read messages (as a 1st step useful while on the road, map browsing would have to be done from computer screen)
- Able to browse the map & see profiles

**Comment by approgramer** [comment]
i will try to make an ionic app for this and share the code .but i am new to github and everything please guide me :)

**Comment by bleadof** [comment]
@simison So have you started the React Native app already somewhere?

**Comment by simison** [comment]
@bleadof I did a bit of testing with React Native but that's all. Hoping to get started with it this summer!

I think the first version could be even just login + message notifications and nothing more. :-)

**Comment by bleadof** [comment]
So I'd like to learn ClojureScript, reagent and React Native, so this is now a bit higher on my list. Also, Mapbox has react native components: https://github.com/mapbox/react-native-mapbox-gl

**Comment by bleadof** [comment]
So I started the project with a friend and I'll be using one evening a week for it. I'll first create a repo under my account and when I've a bit more done. Now we have the base setup working. We still need to get test running inside the react native container and then we're on a good path. :-)

The tech is 
* Re-Natal https://github.com/drapanjanas/re-natal
* Reagent (CLJS interface to React.js) https://github.com/reagent-project/reagent
* Reframe (Like Flux for CLJS) https://github.com/Day8/re-frame
* Schema for data https://github.com/plumatic/schema
* Material design for React Native http://react-native-material-design.github.io/

**Comment by simison** [comment]
Whoooh! Great news! Excellent.

I'm super busy next two weeks (renovating + moving), but I will try to catch time online here and there so I can help out with this. In August I'll have lots more time finally.

Let's try to have a call this week still about this? The goal could be to plan a bit roadmap / MVP.

I went ahead and created an empty repository here: https://github.com/Trustroots/Trustroots-React-Native — feel free to move over to there at any point. Personally I think the earlier the better.

**Comment by simison** [comment]
Oh and this https://github.com/mapbox/react-native-mapbox-gl

**Comment by bleadof** [comment]
Awesome! Let me know when you have time. My schedule is rather flexible this week. 

He's @ilmirajat.

I'll, make a list of issues as the backlog next week and continue first doing the login and then the messaging.

The progress might not be super fast because Clojure is new language for me and even React is only a slightly more familiar, but it'll make a robust app when it's done. I'll also document setting up the environment next week, because that took quite a bit of time just getting done.

The nice thing is that the development cycle is rather fast thanks to Figwheel. :-)

**Comment by simison** [comment]
>The progress might not be super fast because Clojure is new language for me and even React is only a slightly more familiar, but it'll make a robust app when it's done. I'll also document setting up the environment next week, because that took quite a bit of time just getting done.

No worries. I like figuring out this stuff slowly. ;-) I might hop onto React development at some point towards autumn as well.

Moi @ilmirajat :-)

**Comment by daiyiwhale** [comment]
I'm super interested in this, and will have time to lend starting September! Happy to see this is happening (:

**Comment by simison** [comment]
First bits are up! https://github.com/Trustroots/Trustroots-React-Native :tada:

Closing this and initial requirements will appear at that repo as issues a bit later.
