### ISSUE TITLE
target=_blank for profiles elsewhere

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#304]
We can presume that people just want to check out the profile elsewhere and then continue on Trustroots. So I suggest to add `target="_blank"` to these links.

![screen shot 2015-09-10 at 11 20 30](https://cloud.githubusercontent.com/assets/54728/9784820/15c68750-57ae-11e5-8298-1071d97881c3.png)

**Comment by simison** [comment]
:+1:

**Comment by guaka** [comment]
[image: :+1:][image: :+1:][image: :+1:][image: :+1:]

love how fast things move fwd :)
