### ISSUE TITLE
Disaster response campaigns

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#305]
It's too early for this yet, but writing this down for the future.

Campaigns / entry pages for the areas where something is happening; nature disasters, refugee situation etc.

From elsewhere:

> Because of the high number of refugees coming from Syria to Europe, two HEC students want to build a platform that could help migrants and people who would like to host them for a short period of time to get in touch. They are looking for a developer to build this platform as soon as possible. It is a 100% charitable project which aims to be extended to other social matters.The two students are using their significant network in the social field to develop the project.

And this:
https://www.facebook.com/groups/OuiShare.Labs/permalink/692908620839873/

> Participants of our non-profit ridesharing movement Skjutsgruppen has started "Refugee Ridesharing" within the movement. Could this somehow be combined with any of your projects, like you who are involved in TrustRoots - Maxime and Pavlik and more - for both ridesharing and accommodation? Maxime has access to our code on GitHub https://github.com/skjutsgruppen and more of you can get access as well (we're pushing on to clean it for being Open Source, but are not all done yet. Still pushing on). Any ideas on this?

AirBnb Example:
https://www.airbnb.com/disaster-response

**Comment by guaka** [comment]
Somewhat related: http://refugeewiki.org/

**Comment by simison** [comment]
http://www.refugees-welcome.net/

**Comment by simison** [comment]
at BW: http://www.bewelcome.org/forums/s14836-Syria_s_exodus

**Comment by Tartesos** [comment]
I wrote this a few days ago, just my two cents

Trustroots Refugee Project

Our goal is to set a paralele data base with the info of people willing to hosts refugees freom Siria, or any country in trouble.

The data base will be new and not connected to TR database

Users can not search the hostess refugee.

Users can see how many hostess for refugee are available in an area but not contact them.

Data base is to share with ACNUR and/or other ngos which can help ONLY.

More info about hostess (number of houses, how many months, can you provide work, number of regugees that can be hosted, time, etc) will be needed at the time of sign up

The idea is to copy our existing code and replicate it with the functions needed.

**Comment by MattiasJay** [comment]
Awesome, lets find more ways of connecting us in Skjutsgruppen with you and Trustroots . https://github.com/skjutsgruppen . You are awesome!
