### ISSUE TITLE
Bug with declining a contact request

### ISSUE THREAD

**Issue by globestoppeuse** [Trustroots/trustroots#307]
I got a contact request from a dude I don't know. Getting on in his profile I get 
"XX sent you a contact request Confirm Request Delete Request"

When I click on delete, I get a pop-up "Remove contact?" where it says "Connected since Jul 31, 2015"
When I click Yes, remove contact, I get an error message:
Oops! Something went wrong. Try again later.

Note that I never accepted this contact request - I found him in my contacts.

_Edit: removed screenshot_

**Comment by simison** [comment]
Thanks! The UI is a bit unclear from that part — unaccepted contact requests are visible at the list only for you — there's a todo to make it clearer; #249 

And that's indeed a bug when trying to remove and it gives an error. Good catch.

If you don't mind I took the screenshot away.

**Comment by nicksellen** [comment]
I can't recreate it:

* backend tests are successful
* new frontend tests (in #375) are successful
* trying it on my local machine is successful

Perhaps it got fixed in the meantime?

**Comment by simison** [comment]
@nicksellen Totally possible, good you added tests though. Let's consider resolved?

**Comment by nicksellen** [comment]
@simison sounds good
