### ISSUE TITLE
Use ID instead of username for Warmshowers field

### ISSUE THREAD

**Issue by roberts-gh** [Trustroots/trustroots#308]
is:
warmshowers.org/users/

should be:
warmshowers.org/user/

**Comment by simison** [comment]
How's that?

This works fine:
https://www.warmshowers.org/users/mikael

This doesn't:
https://www.warmshowers.org/user/mikael

**Comment by roberts-gh** [comment]
They obviously use _both_ variations (my working path is /user/username). Please allow for either /user or /users, in the path.

**Comment by simison** [comment]
Whoa, confusing! Cool. Thanks for digging.

**Comment by simison** [comment]
I'll check up with Warmshowers end get back to this.

**Comment by roberts-gh** [comment]
"I'll check up with Warmshowers" ? Why?

**Comment by simison** [comment]
> Why?

To understand why would they have a mixture of profile paths.

But I figured it out myself already.

With username the path is `/users/username` and with user ID `/user/123/`.

**Comment by roberts-gh** [comment]
Never knew I had anything but an ID number...hmmmm  (e.g. https://www.warmshowers.org/user/99999) like what's in my profile URL...

**Comment by simison** [comment]
Could you edit your profile and see if the Username field at the top of the form is empty?

**Comment by roberts-gh** [comment]
found username, thanks...

**Comment by roberts-gh** [comment]
neither
https://www.warmshowers.org/users/myusername
nor
https://www.warmshowers.org/user/myusername

... lead to anything but a 404. For me.  Apparently the _only_ way to access _my_ WS profile, is via /user/99999

Sorry. Can you please just edit/shorten the path you've forced?

**Comment by simison** [comment]
Aight, switching WS field to ID-only:

>No, I turned off that URL alias feature a long time ago (for new users). Also, it never did work predictably with users/username because many usernames urlencode differently, etc.

>The only correct way to get to a user URL is with user/UID where UID is the numeric UID.

https://github.com/warmshowers/Warmshowers.org/issues/769#issuecomment-140143991

**Comment by guaka** [comment]
It's a Drupal thing. /user/ID is the path of the entity. With pathauto a
nicer path /users/USERNAME is created, but this may not have worked all the
time (it's Drupal :)

sent from my mobile phone

**Comment by guaka** [comment]
/user/ID will work for anyone, but almost no-one will know their user id

sent from my mobile phone

**Comment by roberts-gh** [comment]
"almost no-one will know their user id"

FWIW, mine is displayed in my profile page path URL

**Comment by guaka** [comment]
Maybe add some code that will use /user/ if the value is numeric, /users/
otherwise?

sent from my mobile phone

**Comment by simison** [comment]
Man that's _sooo_ wrong to have id's and usernames mixed at the DB... :-)

But I'll go ahead and implement that anyway. Adds to complexity (sucks) but will certainly stop any help requests coming in to the support mail and will work for everyone (yay!).

**Comment by roberts-gh** [comment]
"Maybe add some code that will use /user/ if the value is numeric, /users/
otherwise?"

Won't work, even if I know it.  I can enter .../users/myusername and it will not go to anything (404).  For my WS profile, access is ONLY via .../user/userID

What you really should do, is actively/silently look-up or derive the WS userID value, if a TR user enters their WS myusername.  A Drupal dev might know if that's do-able.

Short of that, just label the TR WS path field to instruct appropriately, and also provide a bit of instruction on how any Drupal user can find his/her userID (for his/her WS account)

**Comment by simison** [comment]
@roberts-gh refresh the page when editing profile and you should get the latest version where it asks for user id instead of username.

Thanks for the heads up with this! Great to get this fixed so soon after initial implementation.
