### ISSUE TITLE
better subject than "You have one unread message at Trustroots"

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#313]
Currently gmail might pile up these messages and things get lost (happened to me this week).

- start with "Trustroots"
- include name of sender, ideally also towards beginning

something like "Trustroots: Johnny Bravo sent 1 message"

**Comment by simison** [comment]
Not so straightforward, as messages from different people are bundled into the same notification:

![image](https://cloud.githubusercontent.com/assets/87168/9957885/b63a9820-5e0c-11e5-87d8-a36f554a2be9.png)

**Comment by guaka** [comment]
Bundling conversations from different people interferes with the way I handle my email... This may be similar for many other users.

**Comment by daiyiwhale** [comment]
^ Agreed. For example I might be more likely to log on to read my messages if I saw a message sent from a new person. Or maybe I'm waiting for a reply from a specific person.
