### ISSUE TITLE
Replace mongoose-paginate with something else

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#315]
https://github.com/edwardhotchkiss/mongoose-paginate

Maintainer has deprecated the package.

Oh the drama...

**Comment by katsuroo** [comment]
Looks like he changed his mind. Seems like there are quite a bit of new activity. It looks like the updates are made to work only with node 4.2 +

**Comment by simison** [comment]
Yup! Updated to newer version and moving to node 4+ anyway. https://github.com/Trustroots/trustroots/commit/ec411af414715fabfd0f4e2327791f25c16d1995
