### ISSUE TITLE
Contact-us form has a weird field

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#317]
Between writing my message and sending it, there's a field I can tick to declare if " I'm using the site with mobile or pad".

It's a headscratcher.

I suppose the question is whether I'm on a smartphone or a tablet. Then it should say: "I'm usually using the site on a smartphone or tablet".

**Comment by simison** [comment]
You're right. I took it off now since we're seeing user agent + screen size anyway already.

http://ideas.trustroots.org/contact/

**Comment by sitarane** [comment]
There was a field asking for my email address and my username too. Those can probably be axed as well.

**Comment by simison** [comment]
Nope, it's a separate setup (Wordpress) at a different domain (ideas.trustroots.org), we'll need those until we add the support form to the main site (not veery high on priority).
