### ISSUE TITLE
Adding github to profile fails

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#321]
When I try to add a github profile (which goes as clicking a link on Edit Profile, authentication on github and redirect to trustroots main page), everything seems to go well. At the end the result doesn't appear in the trustroots profile page. Tested with Chromium and Firefox on Arch Linux and with Safari on iPad.
Not sure how to track this issue further. In javascript console no errors shown. Maybe some settings on GitHub?
Will try to explore further if somebody suggests how.

**Comment by simison** [comment]
Thanks, looks like there's a new version of Passport and then there's this: https://github.com/jaredhanson/passport-github/issues/37

At least it isn't changing as often as Facebook API. :-)

Need to create a tests for this and run it on regular basis....

**Comment by simison** [comment]
https://github.com/cfsghost/passport-github

**Comment by simison** [comment]
Tested, works again.
