### ISSUE TITLE
Change "in a minute" to "less than a minute ago"

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#322]
Feedback:

> When a user sends a message to somebody, it immediately says that it was sent "in a minute." The phrase actually means a point in time in the future, like "I'll go and make a cup of tea in a minute." So it doesn't make sense that a message is sent in a minute, that would mean something more like the message WILL be sent soon but has not been sent yet. You could change it to "a few seconds ago" or "less than a minute ago" which refers to time that has already passed.

It comes from [MomentJS](http://momentjs.com/) so not sure how straight forward fixing it would be.

**Comment by grippon** [comment]
Please don't use that "relative time display" (1 min ago, 2 h ago) more than 2 days after.

I dislike the new trend on the web to display the time "1 year ago" and that's super approximate.

**Comment by simison** [comment]
@grippon yep, might change it to work more like that at some point. BTW you can hover it and see the exact time.

**Comment by simison** [comment]
@grippon you can now click timestamps at inbox/threads and use absolute times instead.
