### ISSUE TITLE
Mobile: in messages, email addresses get corrected by autocorrect

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#330]
You're typing your email address to a host/guest, and as soon as you type the dot, the part before it gets defiled by autocorrect. Is there a way to let the keyboard know one might be typing an email there?

**Comment by simison** [comment]
Hmm, interesting. On the other hand this sounds more like an upstream issue at your phone's autocorrection (it should know better).

There indeed is a simple way to turn it off: http://www.bennadel.com/blog/2307-disabling-auto-correct-and-auto-capitalize-features-on-iphone-inputs.htm

I won't rush with this yet, I'll tinker a bit what's the best practise.
