### ISSUE TITLE
Mobile: dots on the map disappear

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#331]
First time you load the map, no problem. You tap on one dot, profile pops up. You "go back to map", all the people-dots are gone. Reload page, still gone.

Firefox and Chrome

**Comment by sitarane** [comment]
Just experienced it again.

Actually, when you hit "back to map" (from user teaser), you go back to a map *with dots*. But within one second, they fade out and disappear.

Refreshing the page doesn't work. Running the URL doesn't either. Going back to the root URL does. (Deleting the /search/).

**Comment by simison** [comment]
@sitarane This should now be fixed with the latest updates that just went online. Lemme know if this still happens!

**Comment by sitarane** [comment]
Correct. All good now.
