### ISSUE TITLE
Changes to Mandrill

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#332]
Evaluate how changes to Mandrill will affect as and possibly move over to MailGun, SendGrid or other alternative.

https://blog.mailchimp.com/important-changes-to-mandrill/

Deadline 27 April 2016.

**Comment by simison** [comment]
Preparing to switch over https://mailgun.com

First 10K free, 15K $2.5 etc: https://www.mailgun.com/pricing

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

They give 100,000 free emails/month for free.

**Comment by richleland** [comment]
There is also a nodemailer transport for SparkPost here: https://github.com/SparkPost/nodemailer-sparkpost-transport

**Comment by simison** [comment]
^ prime example of effective marketing just there. Should learn from you guys. Cheers. :-)
