### ISSUE TITLE
Residency seems to be a two steps thing

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#333]
A friend of mine (https://www.trustroots.org/profile/korvus) created his profile when he was living in Leipzig, DE. Now he moved to Zurich, CH. He did change his "lives in" to Zurich, but still shows up on the Leipzig map.

Are the "lives in" field and the map placement disconnected? That seems like a bad idea.

**Comment by simison** [comment]
Yep, so "hosting dot" is separate from "from" and "lives in" textfields. It's indeed confusing, we get feedback about it every now and then.

UI requires rethinking.

Related to #11 #132 #289

**Comment by simison** [comment]
Follow ups at #359
