### ISSUE TITLE
Automatic multiple space removing when writing messages is disturbing.

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#339]
Hello,
this is just a personal opinion/feedback; not objective bug:
there seems to be a new feature in messages editor: when writing double spaces or multiple empty lines, the second one is automatically removed by Javascript (not removed when Javascript is disabled in browser).
I find this feature disturbing: it makes editing messages less pleasant: i.e. words have to be added to a sentence after a space; not before; etc.
Is the description understandable?
What do other users think?

**Comment by simison** [comment]
Yepp, it's actually a bug, it's not meant to work like that. I updated Medium Editor to tackle some other bugs on mobile and I overlooked this.

I already patched this yesterday, fill push to git + to production today or tomorrow.

Thanks! Keep reporting inconveniences. :-)

**Comment by simison** [comment]
Fixed at https://github.com/Trustroots/trustroots/commit/47dc2b60966a0f20a1780a0b4d6c71bc0826b03f#diff-734a5e9323ab3b6ae53bf05a31a982eeR31 + fix is live already.

**Comment by mrkvon** [comment]
Cool, the adding multiple empty lines works.
However it is still impossible to write multiple spaces in a row. Is that on purpose?
`disableExtraSpaces: true` > `false`?
