### ISSUE TITLE
Contacts of other users not shown

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#340]
At the moment contacts of other users than _me_ are not shown.
i.e. when i visit my profile and click Contacts, they are shown.
but when i visit Contacts of my friend with many contacts, nothing is shown.
The JSON object with contacts is still received. So there may be a bug in javascript or templates while showing the contacts in browser.
The difference between _mine_ and others' JSON list of contacts seems to be only `confirmed` field (missing in the latter).

Tested with: 
- Chromium v48.0.2564.116
- Firefox 44.0.2
- Safari ???

**Comment by simison** [comment]
Thanks! Can't wait to get started with more thorough Angular controller tests...
