### ISSUE TITLE
Create blocked user role

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#342]
Create a role that effectively causes user to be non-public, but it would be possible to remove this flag only by admin, since `public` flag is possible to turn `true` by just editing + confirming email.

It would mostly be enough to stop blocked users to (re-)authenticate, as the rest is pretty much taken care with `public:false` flag.

Related to #341

**Comment by chmac** [comment]
@simison Any idea how much time is involved in doing this? Wondering how fast we could have it live.

**Comment by simison** [comment]
@chmac lemme poke around, just a mo.

**Comment by simison** [comment]
Done with https://github.com/Trustroots/trustroots/pull/468
