### ISSUE TITLE
Timestamp last password change

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#343]
For stats and possible small UX improvements.

**Comment by trmendes** [comment]
Can I try this one?

**Comment by simison** [comment]
Sure!

It'll require adding a new field to user Model: 

https://github.com/Trustroots/trustroots/blob/master/modules/users/server/models/user.server.model.js#L98

It should be type "Date", default to "now" and we'll need to update it here to `new Date()`:

https://github.com/Trustroots/trustroots/blob/master/modules/users/server/controllers/users.password.server.controller.js#L177-L180

...as well add to this list: https://github.com/Trustroots/trustroots/blob/master/modules/users/server/controllers/users.profile.server.controller.js#L380

**Comment by simison** [comment]
Yep, I'm fixing that here: https://github.com/Trustroots/trustroots/pull/603 — once that's merged, you'll have to rebase your own branch (or just update `master` if you didn't create a branch).
