### ISSUE TITLE
Typing reply message scrolls down the existing messages

### ISSUE THREAD

**Issue by jancborchardt** [Trustroots/trustroots#348]
I want to reply to a message thread which is long enough that it needs to scroll. I want to see a specific part while writing, so I scrolled up a bit. However when I type, after some seconds the message view is scrolled down. This is quite annoying as you can imagine. :)

**Comment by simison** [comment]
Update: 

Still an issue.

There was an attempt to fix this at https://github.com/Trustroots/trustroots/pull/495
