### ISSUE TITLE
In text fields, adding text surrounding and automatically created link makes that text part of the link.

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#352]
Wrting a message step one:

"Hi! Me and https://www.trustroots.org/profile/buddy are coming to your town in"

(The link is recognised as one)

Then I realize I'm writing to a French person and I speak french. Delete the english text.

"https://www.trustroots.org/profile/"

Place the cursor the the right of the link

"Salut! Moi et https://www.trustroots.org/profile/"

Horror! The "Salut! Moi et " bit is now part of the link (the link still points to the correct URL). Let's now place cursor to the right of the link.

""Salut! Moi et https://www.trustroots.org/profile/ on vient dans ta villle "

Damnation! The whole message is a link!

**Comment by simison** [comment]
Yeah, it's UX annoyance with [MediumEditor](https://yabwe.github.io/medium-editor/).

Could work not to turn URLs automatically into links yet at writing phase, but only at sending phase.

**Comment by sitarane** [comment]
This would fix another annoyance, that if you click a link in the text field (while editing a message, message not sent), it follows the link. Lost-message-panoc ensues. Hitting "back" on FF gets the message back, but still.

**Comment by simison** [comment]
True. More elegant way of solving that issue would be adding same confirmation I added to profile editor (try editing about me section without saving, then choose another section from sidebar and see what happens) — #53

**Comment by simison** [comment]
I also realised that when typing e.g. "text.[NEWLINE]In" will turn that into URL. No good.

**Comment by simison** [comment]
Autolinkin is now done only at the backend, not while typing text in.
