### ISSUE TITLE
Manage npm dependency security

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#360]
Currently I'm running  [NCU](https://www.npmjs.com/package/npm-check-updates) every now and then, but that's kinda crappy solution.

https://snyk.io/ is pretty cool platform. It scans dependencies for known vulnerabilities in their database and offers either patches or upgrades to resolve them. It also provides a tracking features which keeps a record of all dependencies and email as new vulnerabilities or arise.

Having this added to build process somehow would be good. Perhaps as a test? It probably shouldn't be blocking builds though, rather alerting us.

**Comment by simison** [comment]
Travis runs [nsp](https://www.npmjs.com/package/nsp) [nodesecurity.io](https://nodesecurity.io/) after each build: https://github.com/Trustroots/trustroots/blob/master/.travis.yml#L25 — but I hardly notice it.

Meanwhile I setup Snyk alerts for myself so I'm getting emails when something noteworthy is vulnerable.

**Comment by nicksellen** [comment]
[https://greenkeeper.io/](greenkeeper) looks useful too

> Greenkeeper sits between npm and GitHub, observing all of the modules you depend on. When they get updated, your project gets a pull request with that update. Your CI tests kick in, and Greenkeeper watches them to see whether they pass. If they do, you can just click the merge button, and we'll even auto-close branches for older versions for you. If not, you can use the branch to fix things.

**Comment by nicksellen** [comment]
https://nodesecurity.io/ can integrate with the pull request workflow too
