### ISSUE TITLE
Duplicate contact

### ISSUE THREAD

**Issue by nicksellen** [Trustroots/trustroots#362]
* got contact request via email, clicked link
* signed in
* clicked confirm on contact confirm page
* got sent to the contact profile page
* it showed a "contact requested" header (I guess it hadn't reloaded and noticed we are now connected)
* clicked confirm
* now contact is added twice! (with unique contact._id)

https://www.trustroots.org/profile/nicksellen/contacts

**Comment by simison** [comment]
Thanks! I noticed this happening but didn't have time yet to dive into it.

**Comment by nicksellen** [comment]
My guess that it was due to not reloading the page was incorrect, it loads the profile and the contact information on each request via a resolve promise, it's solid.

Extra information:
- person who added me as a contact reported seeing an error on her screen
- I only got 1 email, despite there being 2 unique contact ids (creation dates are 18 seconds apart, which suggests a human pressing a button twice, not a computer doing something twice). email was for the second contact request.

So, hypothesis is that:
- first request got to https://github.com/Trustroots/trustroots/blob/master/modules/contacts/server/controllers/contacts.server.controller.js#L81 and so created unconfirmed contact in db
- then an error occured before it had a chance to send the email (seems most likely to occur whilst trying to send)
- showed error on my friends screen, leaving the button available to try again
- she waited 18 seconds, then pressed it again
- I receive 1 email, and have 2 contact requests and can confirm them both

I can recreate it by hacking the contact confirm code to error on the first attempt, and work on the second. Everything behaves according to the hypothesis following that.

I see a few things that could be done:
1. send all emails via an agenda background job that can retry on send error (or at least let you see the sending failed and manually retry, not sure what features agenda has)
2. catch errors and cleanup (i.e. delete the contact that was just created so the request either fully works, or does nothing)
3. when adding a contact, check if there is one already
4. cleanup existing duplicate contacts

I would suggest 1 and/or 2 should be done first. With 3 alone, it would allow users to add a contact and the contact never receive an email about it in the case of failure, at least right now that scenario is unlikely as the user sees as error and doesn't think the first one was successful.

**Comment by nicksellen** [comment]
Point 1 is tracked in https://github.com/Trustroots/trustroots/issues/260

**Comment by simison** [comment]
Oh, great work inspecting!

I would start fixing this by expanding [tests](https://github.com/Trustroots/trustroots/blob/master/modules/contacts/tests/server/contact.server.routes.tests.js) for this module, it's the easiest way to spot errors and useful for the future development, too.

1 definitely, all emails (notifications, signup etc) are quite a headache right now, but it's quite a big chunk of refactoring.

**Comment by nicksellen** [comment]
Tests were expanded in https://github.com/Trustroots/trustroots/pull/367. Next step, make some breaking tests, and fix them!

**Comment by nicksellen** [comment]
Working in PR https://github.com/Trustroots/trustroots/pull/372
