### ISSUE TITLE
notification emails not arriving

### ISSUE THREAD

**Issue by platschi** [Trustroots/trustroots#363]
Received a hosting request 5 days ago by Trustroots. Usually don't check the website, but rely on those messages arriving into my email inbox. That email never arrived. Unfortunately, saw the request only today on the website itself. Might there be problems with email delivery? And no, no Trustroots emails have been caught by Spam/Junk/Antispam/Virus whatever filters. 15 days ago, I received a request, back then all was fine with the notification email.

**Comment by simison** [comment]
The notification setup got two big overhauls in attempt to get them more error resistant — should work much better now.
