### ISSUE TITLE
"Show more" hidden behind "back to map" on Firefox android

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#366]
If you tap on a dot on the map you get a description. At the bottom of the description is a "back to map" button. If the description is long, there's a "show more" link. On Firefox for Android, they overlap. Fine on Chrome for Android.

**Comment by sitarane** [comment]
How fuck do you include a file in this...

https://goo.gl/photos/kXtzwKzCqxuQ3uhy9

**Comment by simison** [comment]
Good catch, thanks!

**Comment by simison** [comment]
Works again.
