### ISSUE TITLE
How to authenticate mobile clients?

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#368]
What changes we'd need to make it easier+safer to build mobile apps that could easily authenticate to Trustroots? (@Trustroots/mobile team)

Current system is simply using [ExpressJS Sessions](https://github.com/expressjs/session).

There's an ongoing effort to add JWT to [MEAN.js](http://meanjs.org/), the boilerplate we're using. https://github.com/meanjs/mean/pull/1163 — so adding that would be super easy, but I'm not very convinced:

Some reading about JWT:
- http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/
- http://cryto.net/~joepie91/blog/2016/06/19/stop-using-jwt-for-sessions-part-2-why-your-solution-doesnt-work/
- https://github.com/yunity/yunity-core/issues/106#issuecomment-228035962 (Talked with @nicksellen about it, he doesn't recommend JWT)

More reading:
- http://samnewman.io/patterns/architectural/bff/

Thoughts?

This is related to upcoming React Native client (#301).

**Comment by nicksellen** [comment]
I don't recommend it for browser clients, but many/most/all of the reasons would not apply to a native mobile app.

**Comment by simison** [comment]
@bleadof says:
>Well, actually sessions seem to be still quite good for the authentication
>You can invalidate them on the server side
>There’s timeout
>It’s pretty easy to get the cookie and set it to the requests
>Especially if SSL is used :)
>Unless @ilmirajat has an idea how to make it better.
>But we might have ideas after we’ve actually used it. :)

**Comment by simison** [comment]
https://github.com/Trustroots/Trustroots-React-Native/issues/1
