### ISSUE TITLE
"Resend confirmation" button doesn't work right after signup

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#377]
After a fresh signup, before clicking "confirm" from first email confirmation (and thus setting the profile public), "resend confirmation" button from email settings page doesn't work.

People go there if they didn't receive first signup message (it might've gone to spam or some other issue) to click "resend".

In other situations it seems to work fine, so there's just something wrong with if-else logic. There could be other patterns when it doesn't work neither, but I couldn't find them with some clicking around.

![image](https://cloud.githubusercontent.com/assets/87168/17100382/b94dbdee-5276-11e6-9177-ad4e421bf5f3.png)

**Comment by nicksellen** [comment]
The user update endpoint [1] is quite complicated and serves multiple purposes, my inclination would be to split it up into multiple endpoints for different purposes to make the logic clearer and simpler. I have to use quite a lot of brain power to follow what it is doing.

Perhaps the first step would be create a _resend confirmation email_ endpoint directly, refactoring out the email building steps into standalone reusable functions.

... ok maybe the first first step could be to see if I can conjure up a failing test for the missing email. I don't think there are any email sending tests yet right? Could be generally useful...

[1] https://github.com/Trustroots/trustroots/blob/master/modules/users/server/controllers/users/users.profile.server.controller.js#L286

**Comment by simison** [comment]
You're right, splitting it to chunks would be good. That would probably mean at least these: 
- update profile
- change subscriptions (currently only newsletter)
- change email
- resend confirmation email

Related to this, `validateEmailToken()` and `confirmEmail()` are at `modules/users/server/controllers/users/users.authentication.server.controller.js`.

>... ok maybe the first first step could be to see if I can conjure up a failing test for the missing email. I don't think there are any email sending tests yet right? Could be generally useful...

Yup. Testing email sending gets really complicated quickly — I've looked into it a couple times now already so if you have any experience with it or ideas, I'm all ears!

**Comment by simison** [comment]
I think you can also just write tests against that new end point straightaway. You could even write them before you actually implement the endpoint, so you'd understand better what to expect from it functionally.

**Comment by simison** [comment]
BTW [there's one relevant test][1] — and there might be more. That `user.server.routes.tests.js` is getting pretty lengthy already, it should probably be split to a few files.

[1]: https://github.com/Trustroots/trustroots/blob/master/modules/users/tests/server/user.server.routes.tests.js#L161

**Comment by nicksellen** [comment]
Should be fixed by #380
