### ISSUE TITLE
Email sending tests

### ISSUE THREAD

**Issue by nicksellen** [Trustroots/trustroots#379]
Originally mentioned in #377, but it's a separate issue really. Right now there is no testing for whether the correct emails get sent. This is not for testing whether the network sending works, but whether the app logic is deciding to send the correct email.

I looked at a mock transport lib [1] but it doesn't handle the case where the `to` is an object [2], which is how it is used in trustroots.

But peeking at how nodemailer does it's testing [3], I just wrote a simple function to collect sent emails into an array, you can see it in action in this branch [4] - I just dumped `testutils.js` into the root as I couldn't see any logical place to put it, maybe there is a better place.

Whaddya think?

If you like the approach I would add tests for all email sending, and remove the stub transport as it would no longer be needed (except in one place where I used it to trigger an error on send).

[1] https://github.com/bcoe/nodemailer-mock-transport
[2] https://github.com/bcoe/nodemailer-mock-transport/blob/master/index.js#L37
[3] https://github.com/nodemailer/nodemailer/blob/master/test/nodemailer-test.js#L27
[4] https://github.com/Trustroots/trustroots/compare/email-testing

**Comment by chreekat** [comment]
Great idea, imho

**Comment by simison** [comment]
Great, a very elegant approach.

I've been putting `testutils.js` kind of stuff to either under `modules/core/server/controllers` or `config/lib` depending if it's used to config/init something or used regularly from other controllers. 

Or maybe this stuff should be either at the root of `modules/core/tests` or under some folder there.

BTW, as a side note, [redirectMessage()](https://github.com/Trustroots/trustroots/blob/master/modules/users/tests/server/user.server.routes.tests.js#L1447-L1458) function from user tests could be moved to `testutils.js` as well.

**Comment by nicksellen** [comment]
This is paused whilst email queue work in #381 is in progress

**Comment by simison** [comment]
@nicksellen This can be closed, right?

**Comment by nicksellen** [comment]
Indeed
