### ISSUE TITLE
E-mails contain non-TR link

### ISSUE THREAD

**Issue by CRCulver** [Trustroots/trustroots#382]
When I get a message on Trustroots, I am sent an e-mail asking me to log in to the site to read it. The message reads (copying and pasting from the text-only version):

To reply, go to:
http://go.sparkpostmail.com/...

When people these days should be wary of phishing, any links in an e-mail from Trustroots should go to trustroots.org itself. Tech-savvy people might understand that you have e-mail infrastructure from sparkpostmail.com, but to other people a completely different domain from trustroots.org in an e-mail from TR will look dodgy.

**Comment by simison** [comment]
Yup, we noticed this as well and I agree with you. We switched from Mandrill to Sparkpost and we might need to change quite a few bits at code side first to hide that behind trustroots domain. With Mandrill it was just a dashboard checkbox.

This is an issue only with text emails, though. HTML version of the email works fine.

**Comment by simison** [comment]
Ah — just checked — looks like Sparkpost offers this setting now directly at their dashboard. Made the change, tho it might take up to 24h to propagate to DNS servers.

In future links will start with `go.trustroots.org`. :-)

Cheers!
