### ISSUE TITLE
Email templates not showing properly at Thunderbird

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#39]
- [x] Take logo image out
- [ ] Test test test
- [x] Create plain text versions #92

**Comment by platschi** [comment]
Issue still persistent, just wanted to report it for Icedove :)

![trustroots_mail](https://cloud.githubusercontent.com/assets/548702/10347056/e30ead38-6d10-11e5-8181-4b5b6350801c.png)

**Comment by simison** [comment]
Thanks, thought this was mostly fixed already. Seems to require more work!
