### ISSUE TITLE
Send another notification about unread messages

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#393]
Currently only one notification message is sent out, there should be at least two more between next 24 hours, if user doesn't read them. These timings should be easily adjustable.

In future there could be other types of notifications:
- SMS #159 
- Desktop #235 
- ~~Facebook #369 (requires #250 first)~~ (done)
- Mobile push notifications

All these should probably be piped trough same service. I don't think it's necessary to make a huge rewrite of the bit that sends these notifications, but it's good to keep all this in mind.

**Comment by nicksellen** [comment]
I'm not sure this is needed. I'm not aware of any other sites that sends multiple notifications for one message.

Imagine I have had a conversation with someone, then close the browser and go out. Then they send a short message, like _ok, great thanks, see you then_. I read it on my phone via the email and it doesn't need a reply. But it will then keep sending me the message until I go to the web interface? Seems a bit much.

**Comment by simison** [comment]
Hmm, a valid point. Let's leave this on for thinking a bit longer.

**Comment by simison** [comment]
Actually, this would be needed if we'd have hosting requests instead of just messages.

**Comment by nicksellen** [comment]
Yeah, some things need reply. In letsmake a booking in _open_ state would represent something that could do with repeated reminders.

**Comment by simison** [comment]
@nicksellen actually, perhaps one notification could be sent about messages which are first in the thread? There's only small change that there's no need to react to those messages and we'd annoy smaller portion of people and make bigger amount of people happy because their first-contact messages won't go unotified.

Perhaps there could be "don't notify me about new messages in this thread" button anyway, though.

**Comment by mrkvon** [comment]
@simison you collected your previous effort to the branch `remind-about-unread-messages`, is that correct? I'm slowly but certainly starting on it now.

**Comment by mrkvon** [comment]
The first attempt to basic implementation is in #470 

It is a bit naive, i.e. not caring whether the message is first in a thread or further. It will send the reminder after 10 minutes passed and after 24 hours passed. The text can be different for the first vs further reminders (not implemented yet).

Can we specify in more detail how this feature should behave?

@nicksellen , @simison What do you think? How do you want this to work?

**Comment by simison** [comment]
@mrkvon great, looks like a good start!

So yeah, further notifications only on threads which don't have any replies for reasons mentioned in discussion above. 1st notification to all the unread messages in the thread.

We'll probably need some limit so that when this will go to production, we don't send 2nd notification about unread messages sent year ago — wouldn't make much sense.

**Comment by mrkvon** [comment]
Good point. The code, as it is, would send the second reminders about all the past unread messages. Can't this be taken care of in migration, i.e. setting `notificationCount` to 2 where previously was `notified: true`?

Or is there some way this could happen with future unseen messages?

**Comment by simison** [comment]
>i.e. setting notificationCount to 2 where previously was notified: true?

Yep, this.

**Comment by simison** [comment]
Implemented at https://github.com/Trustroots/trustroots/issues/470
