### ISSUE TITLE
Show my friends on a map

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#396]
Even if they aren't hosting.

Requires #395 

See also "Show FB friends on map" #27

**Comment by Regenwasser** [comment]
I'm closing this as it seems outdated.

Our new goal is to show everyone on the map even if they are not hosting.

**Comment by simison** [comment]
This is about showing only the people you have the contact list on the map; while hiding everything else.

I can elaborate on the opening description a bit more to have it more clear. :-)

**Comment by platschi** [comment]
I just wanted to add an issue about this. This would be awesome. Recently travelled Europe after a long time (coming from South America) and while looking for new hosts, I was also eager to know where my 30+ trustroots buddies/former hosts/guests/contacts are at the moment - after all, people change location all the time. 

I think the easiest option might be to add a filter (like those for individual tribes), which just shows "My contacts" on the Map. I would love that for the next time I travel Europe :)

**Comment by rumwerfer** [comment]
related: #805 (show only members with common contacts)
