### ISSUE TITLE
Add other members as friend

### ISSUE THREAD

**Issue by velaia** [Trustroots/trustroots#398]
To stay in touch with people and add connections to your real life friends that are already on TR it would be nice to have a '+ Add Friend' feature and overview + modification page.

**Comment by simison** [comment]
@velaia I'm not sure if I follow, or you didn't notice that this exists already? Could you elaborate a bit more?

You can now add any profile as a contact from their profile and see those connections from your own profile under "contacts" tab, or from any other profile.

Is this what you meant?

E.g. my contacts https://www.trustroots.org/profile/mikael/contacts

**Comment by velaia** [comment]
Yes, that's what I'd meant. Have added a few friends since then :smile:  Sorry for the late reply and thanks for the quick response :smile:
