### ISSUE TITLE
Filter people from tribes to the map

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#400]
Tribe filter on the map which returns only hosting offers from people who belong to those tribes.

Related to #397 

See also #208

**Comment by simison** [comment]
Been photoshopping today a bit:

![image](https://cloud.githubusercontent.com/assets/87168/17804939/bc11d45a-6605-11e6-8853-208f71bca2f5.png)

**Comment by sebastien-fauvel** [comment]
👍 for this issue – new to trustroots & missing just that. Happy to do some code review if needed :)

I would rather recommend to use a multiple choice select2 dropdown box to filter tribes, though. It makes sense to pre-fill it with your own tribes, but it is important to keep it flexible. People are not always looking for others who are exactly in the same situation as themselves...

**Comment by simison** [comment]
@sebastien-fauvel great, thanks. :-)

Yup, select2 is on plans:

![image](https://cloud.githubusercontent.com/assets/87168/17928678/84af0494-6a04-11e6-8ebb-c95089795721.png)
