### ISSUE TITLE
On conversation (messages) page, the location of the other user should be displayed.

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#401]
This situation arises when you write to a bunch of people in a bunch of places.
1. "You got new message from a trustroot user"
2. Open https://www.trustroots.org/messages/someguy (attached screenshot)
3. Read reply
4. Right-click his profile to open it in another tab to check where they're writing from.

"4." is bad design and would be prevented by adding, in the little top right block showing a profile summary with picture, username and language, also the location of the user we're reading the messages.

**Comment by sitarane** [comment]
![screenshot from 2016-08-18 16-49-45](https://cloud.githubusercontent.com/assets/10289010/17778520/90c2f9ce-6564-11e6-94bd-558446c6d2e8.png)

**Comment by simison** [comment]
👍  Very good field observation!

This should be added together when restructuring the whole from/living/hosting thing #359 #395
