### ISSUE TITLE
change default image for FB images to image that shows that FB is blocked

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#406]
when facebook social graph is blocked (e.g. thru ghostery) it looks like there's no picture for folks who use FB pics

<img width="1142" alt="screen shot 2016-09-04 at 20 49 16" src="https://cloud.githubusercontent.com/assets/54728/18233220/113006ea-72e1-11e6-9209-e9e258d37b85.png">

best solution is to fetch the image locally
before that it could be good to change the default image with an image that shows that FB is blocked?

**Comment by simison** [comment]
Hm, I'm a bit reluctant to implement local images fetched from FB since it's quite a lot of coding for something that isn't really that widespread issue. Unless @Remigr wants to code something like that? ;-) I'm totally open for PRs.

I'll close this as a dublicate, though: #155

**Comment by simison** [comment]
This is actually pretty neat idea + just a couple lines of CSS:
> change the default image with an image that shows that FB is blocked?

**Comment by guaka** [comment]
(let's test if this shows up on our slack log)
