### ISSUE TITLE
Look into mocking DB data for functional tests

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#414]
This obviously needs a closer look at some point.

Via https://github.com/Trustroots/trustroots/pull/413#pullrequestreview-1592039

---

@chmac:

> database manipulation inside of tests leads to fragility. If the tests crash during execution the database may be left in an unclean state. I'd suggest that where possible it's better to use stubs and mocks.

@simison:

> It's the same as elsewhere at the codebase and following the example from Meanjs boilerplate.
> 
> Each test cleans up after itself and even if you'd "pull the plug" intentionally in the middle of it, on next run it would empty it again. CI tests on Travis run on a fresh container every time anyway.
> 
> The same issue would come up with e2e tests (which we don't have) and database model tests (which we have), so mocking this just for unit testing isn't really worth it.

@chmac:

> I get that theory, and in the context of jenkins it's probably true in practice. But nonetheless, this is a very fragile approach to testing. There are many different things under test here, so this is a "functional test" and not a "unit test". These tests will fail under all kinds of scenarios through no fault of the actual code.
> 
> I'm not deep enough into the whole tr codebase to know what the testing strategy is, but in general, I'd recommend mocking and stubbing over this type of test. Tools like sinon make it fairly easy to produce mocks. Plus, they can often be shared application wide. Although it can require a different architecture to get them into your code under test.

---

```
  // after each test removing all the messages and users
  afterEach(function(done) {
    Message.remove().exec(function() {
      User.remove().exec(done);
```

@chmac:

> This is a very broad action. If at some point fixtures are added to the test database, this will cause unexpected behaviour because it's wiping the whole collection.
> 
> If manipulating the database cannot be avoided (and it almost certainly should be) then as a minimum, we should refer to documents by fixed IDs and then target only those specific documents for deletion.

@simison:

> Tests run on a separate db (not in development db) so there's no harm wiping it empty, as it should be empty at the beginning of each new test anyway.

---

@chmac:

```
// creating te message
message.save(function (err, result) {
  if (err) return done(err);
```

@chmac:

> Presumably if this fails, and err is not falsy, then the test gets failed with the database error. Is that what we really want to do?
> 
> In general, I think this falls under the whole heading of using the database to test versus using mocks / stubs.

**Comment by chmac** [comment]
I think it depends a lot on what kind of testing we want to do. The sorts of tests that I've seen in the codebase currently, look a lot like [unit tests](https://en.wikipedia.org/wiki/Unit_testing). I think the key sentence there is:

> Ideally, each test case is independent from the others.

Of course, if we're doing end-to-end, or functional tests, then this prescription doesn't make sense. But if the goal is to test "does this function pass the correct data to InfluxDB", then using an actual instance of InfluxDB to test leads to fragility. For example, if the test gets run on a different processor architecture (I just acquired an ARM based mini computer!), there may not be a distribution available, or the repo that was added may not include builds for that architecture. Now the test is failing without an obvious reason. Also, in the case of adding the InfluxDB repo, that will never work on OSX or windows. So now our test suite can only ever be run on a dedicated test server with the correct operating system, etc.

In general, with unit tests, I think it's great to be able to write some tests, see them fail, and iteratively work on them until they pass. Then write some more tests, etc. That's not possible if you have complex database dependencies and so on.

A huge argument in favour of React is that it's "easier to reason about". That same argument is true here. If the test is simple and self contained, it's easier to reason about. If the test fails, the code has done something wrong, no other possibilities.

I'd also suggest there's a wider issue here about testing in general. How much testing do we want? On which parts of the application? Do we want to favour metrics over testing? A lot of these decisions will likely change as the size, scale, and maturity of the project (and the codebase) changes.
