### ISSUE TITLE
Data questions & KPI

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#416]
- Questions we want to answer by looking into data
- Data/events we need to collect to answer those questions
- Top priority: get the data to answer KPI

---
#### Users
- [ ] % of users that have logged in the past week, month, year

#### Messages
- [x] n of messages sent (basically for monitoring if something's broken)
- [ ] % of new threads with response within a day/2 days/etc... based on data within last n weeks
- [ ] % of new threads started in past two weeks without reply
- [ ] % of unread threads within last n weeks without reply
- [x] how many new message threads are answered?
- [x] what is the average response time to the new thread (often a request)?
- [x] are the messages long or short?
- [x] how long are they?
- [ ] a graph to see if someone _ever_ received or sent a reply (possibly also over the past 3 months). This would show user involvement. It would also be nice to limit it to a certain period, e.g. last n months. (by @guaka )

#### References

~
#### Offers
- [ ] % of members have hosting offer
#### Tribes

~
#### Search

~
#### Contacts

~

#### More
Some [great ideas from the early days of CouchSurfing](/jxe/jxe.github.com/blob/master/csmetrics/macro.md) pointed out by @guaka 

---
## Daily stats to collect
- [x] Users count
- [ ] Contacts count
- [ ] Pending contact requests count
- [ ] KPI "Useful message threads" (see below)

---
## Events to collect

_List under event possible meta data to collect._
#### Users
- [x] Signup success
- [x] Signup failed
- [x] Login success
- [x] Login failed
#### Messages
- [x] Message sent
  - First message / first reply / other
  - Time between messages
- [ ] Thread opened
#### References
- [x] Vote message thread up/down
#### Offers
- [ ] Saving hosting offer
  - New / modifying old
  - Previous status if modifying
  - New status
- [ ] Change of hosting states: yes/maybe => no
- [ ] Change of hosting states: no => yes/maybe
#### Tribes
- [x] Join tribe
- [x] Leave tribe
#### Search
- [ ] Search event
  - How many tribe filters active?
  - Continent?
  - n of results
#### Contacts
- [ ] Contact request sent
- [ ] Contact request accepted
  - Time to answer

---
## KPI "Useful threads"

Calculated on weekly basis.
- Response within a day is great, 1 point. no response is 0.
- In between, response after a week is probably half a point
- After 2 weeks it's pointless

Also think about:
- discard messages that are rated negatively
- give x% bonus for threads that are rated positively

Some thoughts in pseudocode:

```
points = 0
for t in threads:
   t.points = 1 - (t.first_response_time / 14 days)
   t.points = max(t.points, 0)
   points += t.points
```

**Comment by mrkvon** [comment]
@simison's comment
> Some thoughts on data questions:
> 
> @simison's list (check if these can be answered with current data):
> 
> n of messages sent (basically for monitoring if something's broken)
> % of new threads with response within a day/2 days/etc... based on data within last n weeks
> % of new threads started in past two weeks without reply
> % of unread threads within last n weeks without reply
> @mrkvon's list (suppose influxdb data already answers these):
> 
> how many new message threads are answered?
> what is the average response time to the new thread (often a request)?
> are the messages long or short?
> how long are they?
> @guaka wrote earlier this when we were thinking our KPIs:
> 
> along this line of thinking but better
> 
> response within a day is great, 1 point. no response is 0.
> in between, response after a week is probably half a point, after 2 weeks it's pointless.
> 
> some thoughts in pseudocode
> 
> points = 0
> for t in threads:
>    t.points = 1 - (t.first_response_time / 14 days)
>    t.points = max(t.points, 0)
>    points += t.points
> calculate it on a weekly base? call it useful threads
> 
> also think about:
> 
> discard messages that are rated negatively
> give x% bonus for threads that are rated positively

**Comment by mrkvon** [comment]
to be sorted (by @simison)

> Initial metrics:
> 
>  User count
>  Our KPI?
>  Message response rates?
>  Signups and other recurring actions
>  More info with records (e.g. types: Counter, Gauge...)

**Comment by guaka** [comment]
tried editing but lost my edits...

Change of hosting states: yes/maybe => no and no => yes/maybe

Search: number of searches

Users: % of users that have logged in the past week, month, year

**Comment by simison** [comment]
^ moved those in

**Comment by Natttalia** [comment]
Sorry try to include contacts but looks like I wrote something wrong

**Comment by simison** [comment]
No worries! Markdown can be a bit confusing at first: https://help.github.com/articles/basic-writing-and-formatting-syntax/

Feel free to attempt fixing, or if not then I'll fix later today. :-)

**Comment by Natttalia** [comment]
About changing status it would be nice to be able to see the impact we have with our coming back message. We would have to measure how many where yes, then no and after the message are yes again
