### ISSUE TITLE
Reactivate existing "no" hosts

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#417]
These are mostly users who were hosting at some point, but turned it off due being busy or went traveling. We suspect they didn't remember to turn it on again, so we're just checking in.

- Send email to users who have "no" hosting offer with old enough timestamp (e.g. 3 months), asking them if they still would like to keep it "no".
- Email has links to turn their hosting "yes" or "maybe", and they would bring them to hosting offer page with status changed
- Mark their hosting offer notified — should it  be in a different table or together with hosting offer, dunno yet.
- There's a pretty good frame for this already: https://github.com/Trustroots/trustroots/pull/390

PR: #431

**Comment by chmac** [comment]
First draft of a message...

-----

Subject: Start hosting on trustroots again?

Howdy from trustroots,

Would you like to start hosting on trustroots again?

We noticed that you were hosting in the past, but haven't been for a while. We're making an effort to re-energise the community and so we're reaching out to folks asking this question.

If you decided not to host any longer, and would like to share your thoughts on why, we'd absolutely love to hear from you here (it's a 1 question survey):
SURVEY_LINK

Thanks for being part of the trustroots community.

The team.


PS> This is a one off email, we haven't added you to the newsletter list or anything like that. We're a small team on tech, so we don't have any way to opt out of this specific message. Sorry. If you want to work on that, we'd love to have your input here:
http://developers.trustroots.org

PPS> If you're really unhappy, of course you can always delete your profile here:
DELETE_LINK

**Comment by chmac** [comment]
Second draft

--

Subject: Start hosting on trustroots again?

Howdy from trustroots,

Would you like to start hosting on trustroots again? You can change your status here:
STATUS_CHANGE_LINK

We noticed that you used to host but you haven't been hosting for a while. We're making an effort to re-energise the community and so we're reaching out to folks and asking them. If you decided not to host any longer, and would like to share your thoughts on why, we'd absolutely love to hear from you here (it's a 1 question survey):
SURVEY_LINK

Thanks for being part of the trustroots community.

The team.

**Comment by simison** [comment]
**Subject:** _FirstName, start hosting on Trustroots again?_

**Beginning of the message:** _Hi Firstname,_

**Comment by chmac** [comment]
Third draft

--

You haven't been hosting for a while, would you like to host again? Change your status here:
STATUS_CHANGE_LINK

If you've decided to stop hosting, we'd absolutely love to hear why on this 1 question survey:
SURVEY_LINK

Thanks for being part of the trustroots community.

SIGNOFF
