### ISSUE TITLE
Show common FB friends

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#419]
If both of the users are connect to FB, highlight if we have common friends when looking at their profile. At least a number to start with, preferably names + FB profile links.

~~Somewhat depends on _Periodically refresh oAuth connection data_ (#449)~~ (merged)

**Comment by guaka** [comment]
- ~25% of profiles are connected to FB, so this means roughly ~12.5% of the profile views is someone connected to FB viewing someone else connected to FB
- it's a lot of work and FB API keeps changing

don't think we should spent much time on this unless someone really wants to build this
