### ISSUE TITLE
Quickreplies

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#422]
- Allow just pressing "accept" or "decline" as a reply
- Show these buttons directly at the email (important)
- Show these buttons on top of (or inside?) the message field
- Show the answer right away to the sender (basically just send predefined text as a normal message)
- ~~Add a simple/rough checkbox when sending a message to new thread "[x] this is a hosting request"~~ — this is not be required and should be its own issue anyway. We can just have these buttons always there and assume first message in the thread is a hosting request _most of the time_.

Related in future: _Attached metadata for messages_ #233. At first "quick reply" can be just pre-formatted text though.

**Comment by simison** [comment]
@chmac @guaka this one's a bit fuzzy to me still — how does the description sound to you / wanna edit?

It could also just be that we assume any new message thread to be hosting request and pressing those buttons would just pre fill the content field, but I feel that adding that checkbox would be pretty straightforward, too.

**Comment by simison** [comment]
I did some quick sketching, not super pretty so don't follow the styles strictly.

User would get an email:

![image](https://cloud.githubusercontent.com/assets/87168/25247535/bd399af6-2613-11e7-9590-824060a98ba6.png)

...or if they are looking at their message view they would see:

![image](https://cloud.githubusercontent.com/assets/87168/25247544/c522dc6e-2613-11e7-8298-6aa753b5c7f5.png)

...and when they click on "yes" or "no" buttons, just a pre-defined message gets sent out. Clicking that gray button just hides all the buttons:

![image](https://cloud.githubusercontent.com/assets/87168/25247560/d74f4ef4-2613-11e7-9570-581479876234.png)

...and since we can simply check if the content of 2nd message in the thread is one of those pre-defined ones, we could very easily just show something like:

![image](https://cloud.githubusercontent.com/assets/87168/25247657/1c77d4c4-2614-11e7-82a5-10b806f0f357.png)

**Comment by daiyi** [comment]
By predefined text do you mean user-defined?

If you say yes you still need to follow up with instructions anyway so the yes alone is not saving time or effort. A user-preset yes response can cut down the time and help include all the hosting info, and maybe near the options to set the response can be a helpful reminder to include address, how to find the front door, phone number, etc. 

I find a lot of inefficiency around hosts forgetting to give the address or something and dragging out conversations painfully over poor data connections (I've done this to others myself D:)

**Comment by simison** [comment]
@daiyi I mean pre-defined by us.

The goal is basically to have a _very_ basic (and quickly developed) feature where we can show "yes" / "no" buttons in email. That hopefully encourages people to reply at least just "no" instead of ignoring the email. Hopefully this will increase reply rates across the site.

As usual, would of course be nice to have perfectly developed features, but there's so much to do. ;-) Better publish something simple first and see how we can improve it later.

>A user-preset yes response can cut down the time and help include all the hosting info, and maybe near the options to set the response can be a helpful reminder to include address, how to find the front door, phone number, etc.

Yep, that's #490. So that improves the experience, but it doesn't bring more users to the site or increase reply rate, so we'll wait a bit before doing that. Patience. :-)
