### ISSUE TITLE
When I join a tribe, the status is updated but not the number of members

### ISSUE THREAD

**Issue by NerdyProjects** [Trustroots/trustroots#425]
I went on
https://www.trustroots.org/tribes/foodsharing
and clicked "join tribe". That button updated, but the member count immediately above did not - I have to reload the page for that to happen as well.

**Comment by simison** [comment]
Thanks, good catch. :-)

**Comment by simison** [comment]
That join button is a directive active at multiple places, e.g.:
![image](https://cloud.githubusercontent.com/assets/87168/19393269/ab1b69f0-923c-11e6-93ca-8ac3c5ad9226.png)
![image](https://cloud.githubusercontent.com/assets/87168/19393274/b0b79244-923c-11e6-9f0f-7d71cc4bee52.png)

Probably the best way is to add `tr-tribe-join-counter="scopevariable"` to the directive.

Tho as far as I remember, the directive doesn't have its own scope, so it might complicate this a bit.

**Comment by vssdeo** [comment]
--- a/modules/tags/client/views/tribes-list.client.view.html
+++ b/modules/tags/client/views/tribes-list.client.view.html
@@ -37,7 +37,7 @@
               <h3 class="font-brand-light tribe-label" ng-bind="::tribe.label"></h3>
               <ng-pluralize
                 class="tribe-meta"
-                count="::tribe.count"
+                count="tribe.count"

**Comment by simison** [comment]
Thx, fixed at https://github.com/Trustroots/trustroots/commit/da7b7acbb71bf08501549960193cbc1d73ceee5d
