### ISSUE TITLE
Docker Instructions don't work out of the box // agenda mongodb address wrong

### ISSUE THREAD

**Issue by NerdyProjects** [Trustroots/trustroots#426]
I would have liked to fix #425 but did not manage to get it running.

To be honest, I did not try really well...

Following the steps on
https://github.com/Trustroots/trustroots/blob/master/INSTALL-DOCKER.md

on up2date archlinux gave me with errors connecting to the mongo via socket(?!):

```
trustroots    | Loaded "development" environment configuration
trustroots    | 
trustroots    | 
trustroots    | /trustroots/node_modules/agenda/node_modules/mongodb/lib/server.js:242
trustroots    |         process.nextTick(function() { throw err; })
trustroots    |                                       ^
trustroots    | Error: connect ECONNREFUSED 127.0.0.1:27017
trustroots    |     at Object.exports._errnoException (util.js:1012:11)
trustroots    |     at exports._exceptionWithHostPort (util.js:1035:20)
trustroots    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
trustroots    | Shutting down...
trustroots    | 
trustroots    | [Worker] Script exited.
```

(repeatedly). I wondered, why the example config did not include a db section and added the one from development.js:

```
  db: {
    uri: 'mongodb://mongodb/trustroots-dev',
    options: {
      auth: {
        authMechanism: ''
      }
      // user: '',
      // pass: ''
    },
    // Enable mongoose debug mode
    debug: process.env.MONGODB_DEBUG || false
  },
```

without success.

I finally found out, that the message was coming from agenda (well..... reading helps)

```
diff --git a/scripts/agendash-dev b/scripts/agendash-dev
index 8d43065..2efb2dc 100755
--- a/scripts/agendash-dev
+++ b/scripts/agendash-dev
@@ -1,3 +1,3 @@
 #!/bin/bash
 
-$(npm bin)/agendash --db=mongodb://localhost/trustroots-dev --collection=agendaJobs --port=1081
+$(npm bin)/agendash --db=mongodb://mongodb/trustroots-dev --collection=agendaJobs --port=1081
```

I don't know what should be in there or how this should be configured via environment, this let it work for me.

**Comment by simison** [comment]
I haven't given Docker a spin for a while. Lemme test.

**Comment by NerdyProjects** [comment]
It's actually really just the agendash - sorry, I found out while writing this issue and did not really clean up in the end. So the instructions are fine, as long as the mongo db address would be taken from the environment in that script as well.

**Comment by simison** [comment]
@NerdyProjects I made tiny change to drop maildev and agendash from NPM's start script, could you test with changes at #427

**Comment by simison** [comment]
>Don't spend too much time on me, as I might not become a contributor :D

No worries mate. :-) Good to keep Docker working for these situations anyway!
