### ISSUE TITLE
Catch email glitches with Grafana

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#428]
@nicksellen [12:59 AM]  
"""
a bit of post-thinking from my chat with @guaka about email/stats stuff: the high level task is to have a graph in grafana that makes it very clear when email sending is failing. it could be failing at multiple levels (app logic does not decide to send email, agenda job fails, agenda job processor is not running, sparkpost smtp call fails, address bounces, email goes to spam). at the moment none of those issues are really visible. the recent outage was because the agenda job process was not running due to error (the deploy script needs to restart it).

the sparkpost graph showed stats graphs going to _near_ zero during that time, but not actually zero. the suspicion was that the sparkpost account is used for multiple purposes.

we also talked about the idea of link tracking inside the emails - the downside is there are quite a few features to implement, and it still would only have visiblity into clicked emails.

turning the above into a concrete suggestion:
- [x] ensure the production Sparkpost account is only used for that
- [x] create a sparkpost webhook endpoint [1] and write the data into influxdb (done #439) 
- [ ] Set up Grafana/Stathat alerts (#480)

[1] - https://support.sparkpost.com/customer/portal/articles/1976204-webhook-event-reference (edited)
"""

**Comment by simison** [comment]
An issue going on right now with sending out some emails:

What we know so far:

- Checked blacklists, all good: https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3atrustroots.org&run=toolpage
- `db.getCollection('agendaJobs').find({name:'check unread messages'})` has `failReason` "Greeting never received" and `failCount` 329
- Other emails are leaving the system normally
- Emails like this pass validation and Sparkpost declines them: `email.@gmail.com`

**Comment by simison** [comment]
>ensure the production Sparkpost account is only used for that

@chmac the blog isn't using this, right?

I'm gonna check the dev server.

**Comment by chmac** [comment]
@simison Nope, the blog is sending via the hosting provider's server right now.

**Comment by chmac** [comment]
Just as a general point of feedback, issues like the email outage are totally acceptable. I'd prefer to spend time on features that grow our user base and deepen our engagement than spend any time at all on preventing stuff like this. The net effect of the outage was zero. I'd suggest we forget about it and move on.

**Comment by simison** [comment]
Follow ups #29
