### ISSUE TITLE
Push metrics to StatHat

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#432]
The awesome folks at @stathat have given us a free premium account (to be activated in the next day or two).

Pushing data to stathat is incredibly easy, it works like this:

```
var stathat = require('stathat');
stathat.trackEZCount("KEY", "user created", 1, function(status, json) {});
```

Stathat supports 2 types of metrics which are counts and values.

A count is when something happened. For example, message sent, reply sent, etc. These are typically aggregated by `SUM()`. A value is the measurement of something at a given point in time. For example, queue depth, number of members, number of members hosting, and so on. These are typically aggregated by `MEAN()`.

One major advantage of stathat over our own influxdb + grafana infrastructure is the automated anomaly detection. If one of our metrics changes dramatically from the norm, we should receive an automatic email alert. Zero configuration required, it "just works" (we hope!).

I would suggest we create a standardised metrics API which we can call from our code, which in turn pushes data to influx, stathat, and potentially other places in the future. Actually, we should probably also log these events to some kind of text based log for posterity's sake.

**Comment by simison** [comment]
Related to #428 "Catch email glitches with Grafana"

**Comment by simison** [comment]
Done with https://github.com/Trustroots/trustroots/pull/466
