### ISSUE TITLE
Search does not show profile names/images

### ISSUE THREAD

**Issue by platschi** [Trustroots/trustroots#435]
When using the map and clicking on any random user, there's only an empty "head" picture of a users profile, an @ symbol for the user name and the user (short) description. Clicking to open a profile does not work. See attached image.

![tr](https://cloud.githubusercontent.com/assets/548702/19875359/2f2b6ddc-9fdd-11e6-817b-a0d65252e7ce.JPG)

**Comment by simison** [comment]
Thanks, I rolled to previous version so this works again.
