### ISSUE TITLE
Is papertrail's remote_syslog running on startup?

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#442]
This: https://github.com/papertrail/remote_syslog2

    sudo service remote_syslog status

Is it enabled by default? It should be.

**Comment by simison** [comment]
@chmac I remember taking something related to this out from crontab's "on restart" block.

**Comment by simison** [comment]
Confirmed syslogs getting logged also after restart.

**Comment by chmac** [comment]
It's a little confusing, `remote_syslog` doesn't push syslog logs to papertrail, it pushes plain text file logs to papertrail. I think the machine was rebooted, and `sudo remote_syslog status` shows that it's not running, so I guess it is not started on reboot.

**Comment by chmac** [comment]
I ran this, which hopefully has enabled it on boot:

    $ sudo update-rc.d remote_syslog defaults

I guess we need to wait until the next reboot to check again.

**Comment by simison** [comment]
Right, all I checked was that after reboot I can see `sshd` and `cron` stuff appearing at Papertrail, so I confused this with something else then.

I'll check on next reboot.

**Comment by chmac** [comment]
There are 2 processes, `rsyslogd` pushes to papertrail on its own, and then the `remote_syslog` program tracks text files and pushes them to papertrail as well. It's confusing. :-)
