### ISSUE TITLE
IE testing

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#45]
- [ ] IE11
- [ ] IE10
- [ ] IE9

Just for "fun" and curiosity check
- [ ] IE8

https://www.modern.ie/en-gb/virtualization-tools

**Comment by Theunmighty** [comment]
Still need IE testing?  I dual-boot a win7 machine for work, I can install all of the IEs and play around.

Trying to be helpful,
-Matt Stove

**Comment by simison** [comment]
Yay! That would be great — although eventually somebody with coding skills+time has to do the same and fix issues while testing. But an overview would do!

**Comment by simison** [comment]
Though probably you can't install multiple IEs at once. I use https://www.virtualbox.org/ to have multiple Windows, each with different IE version. Additionally there's also http://www.my-debugbar.com/wiki/IETester/HomePage but I haven't tested that for ages.

**Comment by honzahosek** [comment]
IE11 can emulate older versions. There is Emulation tab if you open developer tools F12. It's not same as testing all versions of IE on all versions of Windows, but for us it's good enough.

**Comment by simison** [comment]
Totally, thanks for the tip.

**Comment by guaka** [comment]
I'm about to pay for a browserstack account. (With a [crazy amount](
http://www.browserstack.com/list-of-browsers-and-platforms?product=automate)
of supported browser/platform combos.)

If someone writes generic selenium tests I can run those on my browserstack
account. Also if it's done for local use, I can easily adapt them for use
with browserstack (and there's free test account with 100 minutes).

**Comment by guaka** [comment]
done with #225 and #199!

![screen shot 2015-04-07 at 01 58 34](https://cloud.githubusercontent.com/assets/54728/7014788/b7ef4130-dcc9-11e4-8366-82082d44733f.png)
