### ISSUE TITLE
Mongo indexes on Messages

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#455]
Probably related to #59 

Are there any custom [indexes](https://docs.mongodb.com/manual/indexes/) on `Message` and `Thread` mongoose models? I can't see any, but it is possible that they're defined elsewhere (?).

Indexing `userFrom` and `userTo` fields may improve performance (a lot) and also keep a stable query time as the number of messages will grow. Without index, the database has to scan all the documents of that type when queried on `userFrom` and `userTo` fields.

The indexes come with a cost: need for further storage space and computation power when creating and updating the index. Benefit should outweigh the cost though. (I don't know details.)

I would suggest separate indexes on `userFrom` and `userTo`. There could be another compound index on both of these (useful when searching a specific thread).

**Comment by simison** [comment]
Chatted about this => merged the PR.
