### ISSUE TITLE
Check `MessageStat` for double entries

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#457]
After it has been out for a ~week/two.

See https://github.com/Trustroots/trustroots/pull/448#issuecomment-261773891 for detals.

**Comment by simison** [comment]
@mrkvon can this be closed?

**Comment by mrkvon** [comment]
@simison 
I don't know. This has to be checked by somebody with access to the trustroots mongo database. Or ignored.

The double entries were supposed to happen only when users would write a first message to each other at the same time. Very unlikely.

To actually get this solved, one needs to search in `MessageStat` for duplicate `firstMessageUserFrom` + `firstReplyUserFrom`(and these flipped) (as far as i remember).

**Comment by simison** [comment]
If you think it should be checked I could get you the stats table.


> The double entries were supposed to happen only when users would write a first message to each other at the same time. Very unlikely.

…but sounds indeed so unlikely that it doesn’t even matter if this happens once or twice a month. ;-)
