### ISSUE TITLE
Better DB seeding

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#462]
(_Now, this isn't an urgent task by any means but it's a really good one for getting to know the codebase and DB structures, and some nodejs._) ;-)

Now we have quite outdated [DB seeding script](https://github.com/Trustroots/trustroots/blob/master/scripts/fillTestData.js) which seeds only users + hosting offers.

It should add a bunch of messages and tribes, too. Actually it probably makes sense to just start writing that script from scratch.

Mean.js (our boilerplate upstream) has some functionality (and even tests!) written for this, but I'm not sure if their strategy is the way to go: https://github.com/meanjs/mean/search?utf8=%E2%9C%93&q=seed — it's pretty close to core and it might make sense to have this a bit more separate.

@kalpaitch wrote:
>I actually tend to take it that we should be able to take the master db and sanitise it periodically. Can be helpful identifying issues with real uses cases.

For this we have a python script elsewhere to be able to analyse data quickly (written by @guaka). I'll give you access to that repo.

That said, for learning purposes it probably makes sense to write this in JS. These scripts might have useful patterns to look into:

https://github.com/Trustroots/trustroots/tree/master/migrations
https://github.com/Trustroots/trustroots/tree/master/scripts/db-maintenance
https://github.com/Trustroots/trustroots/tree/master/scripts/influxdb

[yargs](https://github.com/yargs/yargs) package is already available in `devDependencies` and would probably come handy.

Related: https://github.com/Trustroots/trustroots/issues/414

**Comment by simison** [comment]
@mrkvon did you have any useful code for populating the messages DB?

**Comment by mrkvon** [comment]
[tr-influx-fake-messages](/mrkvon/tr-influx-fake-messages) is a very naive script for populating the database with messages which i've used for testing message statistics. It doesn't create `Threads` and it drops the database at the beginning.
I believe it is not very useful for the general case unless it is edited substantially. Have a look if you wish. :)

**Comment by simison** [comment]
https://github.com/meanjs/mean/pull/1808

**Comment by Jagjeet** [comment]
I was looking at this as part of Hacktoberfest. Are there any updated thoughts on how to do this? I noted the original request is almost two years old so just figured I would check in.

**Comment by simison** [comment]
With https://github.com/Trustroots/trustroots/pull/711 and https://github.com/Trustroots/trustroots/pull/740 merged (kudos @Jagjeet :tada:), I think this is at pretty good state for now. That is; we can _actually_ generate some useful mock data for relevant parts of the app.
