### ISSUE TITLE
Push historical time to reply message to stathat

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#471]
@mrkvon Thanks for getting the stathat stuff running. It's awesome to have metrics there, super easy to jump in and create dashboards, etc.

One question. How much time / effort would you estimate is involved in pushing historical data? Is this something that's already implemented and we just need to run it on the production servers? Or is it a new migration we'd need to write and run?

Right now we only have a couple of weeks of data on stathat, and it'd be absolutely fantastic if we could see data going back to the launch of Trustroots. Obviously it might not be practical, hence why I'm asking for your thoughts on the work involved as a first step.

**Comment by mrkvon** [comment]
We already have some scripts for historical data in `./scripts/influxdb/`. They may be rewritten for the general stats api with not much effort. Stathat has methods to push timestamped data and Stats api supports them when timestamp is provided.

Note for implementing: Careful about duplicate data. Influxdb doesn't save identical data twice. Influxdb might. The pushing to history must be limited in time.

**Comment by simison** [comment]
I think we're fine atm
