### ISSUE TITLE
How do we best measure member engagement?

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#472]
We currently have great visibility into our membership numbers. How do we get similarly simple visibility into member engagement? What are the best metrics to measure that?

Some ideas we have right now:
* Measure time from first message to first reply
  - This tells us on average, if first replies are getting faster or slower over time
* How many messages get a reply within 30m, 4h, 24h, 7d
* Percentage of first messages which get a reply

What other ideas are there? How else could we measure this? What would be the best metric?

**Comment by mrkvon** [comment]
I remember a discussion with @guaka on topic of focusing on quality, not quantity. I believe it was related to http://www.timewellspent.io/. I still miss some of the resources though.

**Comment by mrkvon** [comment]
Related discussion #416

**Comment by chmac** [comment]
I'm leaning towards the idea that the key metric might me percentage of messages which receive a reply within 24 hours. There's really a lot of useful thought on #416.

**Comment by chmac** [comment]
How about measuring just the percentage of votes thumbs up vs thumbs down when people answer the question "Was this message in the spirit of Trustroots"?

**Comment by chmac** [comment]
I've run some numbers. Here's the percentage of new messages (first message between any two users) that got a reply in 1hr, 4hrs, 24hrs, and 1 week respectively (plus the total number of such messages).

![buckets from messages](https://cloud.githubusercontent.com/assets/690997/24084065/73f2c38e-0ce3-11e7-87bc-a7a0274adb5f.png)

It looks like the number of new connections between users and the reply ratios are pretty flat over time.

I'd guess the key metric here is that we have a similar number of messages between users despite having significantly more members. We've probably doubled the total number of members in the last 12 months or so, but we have the same level of interaction on the site. From a quick look at Google Analytics it looks like we also have a similar number of sessions over time.

<img width="761" alt="google analytics sessions all time" src="https://cloud.githubusercontent.com/assets/690997/24084083/e21d994c-0ce3-11e7-953f-6dcb956c4013.png">

Maybe we should keep an eye on these numbers but measure engagement as the percentage of users who have sent or received a message in a given month.

**Comment by kalpaitch** [comment]
Are we talking about engagement with the Trustroots service or engagement with users. Because if the former then there are many ways other than sending messages that users can engage??

**Comment by simison** [comment]
@kalpaitch anything that we can actually measure. :-)

**Comment by kalpaitch** [comment]
Sure, cos in that case:
- when they last accessed the service
- how regularly they access the service (by a factor of time)
- how often they perform a new search (by a factor of time)
- how many people they've invited to the service (by a factor of time)

And what's really nice if you can then generate one compound  measurement of all of the above based on given biases. Even better if you can do this at a level that allows this information to be used in listing and profile pages so you can return the most 'engaged' users first or display how active/engaged any given user is.

**Comment by simison** [comment]
(ping @chmac)

>when they last accessed the service

This could be interesting one to implement soon (#160), just to get better insight.

**Comment by kalpaitch** [comment]
In a strange sort of way how regularly they access the service is a more relevant stat given that last access doesn't necessarily indicate they're particularly 'engaged', they might even have accidentally logged in.
