### ISSUE TITLE
Is historical data in MessageStats accurate?

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#476]
I was doing some data munging this weekend. I was looking into what percentage of first messages between 2 users get a reply in 1 hour, 4 hours, 24 hours, and 1 week. At first I used the `MessageStat`s collection. Here's the graph.

![first message reply time buckets](https://cloud.githubusercontent.com/assets/690997/24084146/14a7109a-0ce5-11e7-9002-41525eee34f1.png)

I thought that the total number of `MessageStat` entries (the brown line) didn't look right. I dumped all the data from `messages` and then calculated the time between every first message and the first reply. Here's the graph this produced.

![buckets from messages](https://cloud.githubusercontent.com/assets/690997/24084160/56145876-0ce5-11e7-9432-a3addf3c82d0.png)

Here's a snippet of the code I used to create this in case I have some flaw in my logic. Explanation below.

```javascript

// Parse out the date
const d = new Date(_.get(doc, 'created.$date'))

// Parse out the sender and recipient
const sender = _.get(doc, 'userFrom.$oid')
const recipient = _.get(doc, 'userTo.$oid')

// Has the recipient already sent a message to the sender?
// We check if there's already a timestamp saved at FROM_IDTO_ID
var stat = _.get(messageStats, recipient + sender, false)
if (stat) {
  // Yes, this is a reply
  // Do we already have a repliedAt time?
  if (!_.get(stat, 'repliedAt', false)) {
    // No, we don't, so set it now
    _.set(stat, 'repliedAt', d)
  }
// This is not a reply, is this the first message from sender to recipient?
} else if (!_.get(messageStats, sender + recipient, false)) {
  // Yes, this is the first message from sender to recipient
  _.set(messageStats, sender + recipient, {createdAt: d})
}
```

The code above is run once for every message object. They're in a slightly weird format because they're parsed out of a JSON document that `mongoexport` produced.

I'm building `messageStats` which is an object. When user ID `abc123` sends a message to user ID `def456` I create a record like `abc123def456: { createdAt: Date() }`. Then if `def456` replies I add a `replied at: Date()` to that object. One huge assumption I make is that the messages as dumped from mongo are in date order. That may not be true. I'll try to check that now.

@mrkvon @simison As I read the graphs above, and if my code is correct, it looks like the `messagestat` collection in mongo doesn't line up with the `message` data. I don't know enough to know if this is true or not, but that was my thought when I saw the data. What do you think?

**Comment by chmac** [comment]
Quick test of the `messages` output shows they are in date order. I believe the assumption was correct.

**Comment by simison** [comment]
Yo! Finally back to VLN.

I had a look at why Grafana had stopped working. A couple of restarts and an upgrade later it seems to be running again. There was a big version upgrade in between, might've broken something.

Here's more fish:

http://grafana.trustroots.org/dashboard/db/kpi
http://grafana.trustroots.org/dashboard/db/messages
http://grafana.trustroots.org/dashboard/db/messages-detailed

**Comment by mrkvon** [comment]
From graphs it seems we haven't filled the historical MessageStat data. I'll look into the code. Quite likely we counted the historical stats differently and used MessageStat collection for current use only.

**Comment by simison** [comment]
@mrkvon @chmac See #457 — should I close that one too?

**Comment by mrkvon** [comment]
To be precise, MessageStat is used to cache reply statistics displayed in user profile. It's not intended to be historically accurate.
