### ISSUE TITLE
Set up Agenda/Stathat alerts

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#480]
Grafana now [has alerts](http://docs.grafana.org/alerting/rules/) and Stathat [supports them](https://www.stathat.com/manual/alerts), too. Our data is available at both services currently.

Which one we should use for alerting and what we should get alerted about?

- [ ] High signups 
- [ ] High signup errors
- [ ] High login fails
- [ ] High Sparkpost events
- [ ] Low Sparkpost events
- [ ] —?

Notify via:
- [ ] SMS
- [ ] Email
- [x] Slack

Related to _Catch email glitches_ #428

**Comment by chmac** [comment]
Simplest option possible. I'd guess that's stathat's automatic anomaly detection. Hopefully it's enough to catch anything that goes significantly out of whack. Alerts via slack would be fine, suggest we create a distinct channel for that so we can get notifications. That'll also filter through to email eventually.

**Comment by simison** [comment]
Simple :thumbsup: 

Suppose that automatic anomaly detection requires some help, tho:

![image](https://cloud.githubusercontent.com/assets/87168/24210200/055df182-0f31-11e7-986a-c6c8214a8cbd.png)

It might be challenging with our low event levels.

**Comment by chmac** [comment]
Yeah, maybe stathat's anomaly detection doesn't work when we're only intermittently pushing events every n minutes.

Bottom line, I'd kill this for now. If the site goes down, or fails in some way, we'll hear about it in a day or two, and that's fine for now. When we have 10x or 100x the daily users, then it'll be more important, and then this stuff will also be easier as we'll have more events. :-)

**Comment by simison** [comment]
>If the site goes down, or fails in some way, we'll hear about it in a day or two, and that's fine for now. 

Thats the thing — in the past when emails started failing, we didn't notice it.

So perhaps one alert for low Sparkpost events would be good? Regarding signups and that sorta stuff, you're right.

**Comment by chmac** [comment]
How long did it take before we noticed?

**Comment by simison** [comment]
> How long did it take before we noticed?

Something over a week.

**Comment by chmac** [comment]
I guess for now that's fine. We saw reply rates dropping, I think as we get better visibility into our 2 key metrics, reply rate in 24h and total member numbers, we'll be able to spot issues like this as the reply rate drops.

**Comment by simison** [comment]
:thumbsup: fair enough. I take it you'll be following reply rate closely this year. ;-)
