### ISSUE TITLE
Profile in map sidebar invisible on small desktop screens

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#481]
This happens since introducing the _filter by tribes_ feature on map (which is btw really cool).

When clicking a place/person in the map, the profile/accommodation detail appears below the filter menu. On my small screen (1024*600) that's completely out of view. (Only a change in scrollbar length shows that something has happened).

I'm already used to that, but for the first time users, that can be confusing. I suggest to scroll that view to the beginning of the detail automatically whenever a user is clicked. Or perhaps a different tab. Or something completely different (ignoring this included). :)

**Comment by simison** [comment]
👍  totally, I've had this in my head for a while already.

**Comment by simison** [comment]
This is now tabbed:

![image](https://user-images.githubusercontent.com/87168/29796635-ebfe1364-8c5a-11e7-9b65-f3419770c7d2.png)
