### ISSUE TITLE
Location search with local + English names

### ISSUE THREAD

**Issue by mschwarzer** [Trustroots/trustroots#484]
When searching for a location, the city name is displayed only in the local language / name. This can be confusing if the local name is in a different alphabet, e.g. search query for "Tokyo" and the suggested location is in Kanji:

![trustroots](https://cloud.githubusercontent.com/assets/7977470/24338463/95f27cc4-12e0-11e7-8167-063c790eebbd.png)

I would suggest to display both the local and the English name of a location. If you can point to the code that is responsible for this, I may create a pull request for this feature by myself.

**Comment by mschwarzer** [comment]
As far as I understood, a localized index is required to retrieve place names in different languages ( `carmen:text_{language code}` via https://github.com/mapbox/carmen ). Is this correct? Or what parameter needs to be set in the API query? I'm not familiar with the MapBox API.

**Comment by simison** [comment]
Just tested, you're right. Just adding `&language=en` [to the call](https://github.com/Trustroots/trustroots/blob/fc519c5e74e822dc9949eb9be23a4cd57dfe07ef/modules/core/client/services/location.client.service.js#L132-L134) works.

@mschwarzer wanna get the honour of adding it there? :-)

I'd also switch from dynamic `//` protocol to `https://`.

**Comment by mschwarzer** [comment]
Thanks. I'll have try next week ;-)
