### ISSUE TITLE
Research onesignal.com privacy implications

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#485]
Would be great to get a clear, concise summary of:

* What data onesignal.com collect
  - How much personally identifiable information is necessary to give them as part of using the service for example.
* What they do with that data
  - Are they permitted to sell personally identifiable information?
* Do they have any statements about EU privacy laws? Often EU companies are restricted from using US services like this, but maybe they have some kind of statement covering their position, etc.

**Comment by mrkvon** [comment]
WIP

https://onesignal.com/privacy_policy

**Comment by simison** [comment]
Looks like https://www.pushwoosh.com is an identical big service, with smart/safe terms and free for our scale.

https://www.pushwoosh.com/privacy-policy/
https://www.pushwoosh.com/terms-of-use/

**Comment by simison** [comment]
@mrkvon suppose we can go ahead with Pushwoosh.com instead and forget about Onesignal. Closing this.

Thanks a bunch for research. :thumbsup:

**Comment by nicksellen** [comment]
Pushwoosh does not support **Remote API** [1] in the free tier [2]. 

[1] http://docs.pushwoosh.com/docs/createmessage
[2] https://www.pushwoosh.com/pricing/

**Comment by simison** [comment]
Oh, that’s unfortunate. I didn’t imagine there would be any other way than via API.

**Comment by chmac** [comment]
I'd be very happy to see what @mrkvon makes of onesignal.com. It seems to be an option that would scale with us, and so I think it makes sense to wait for a more detailed review of their offer from a privacy perspective.

**Comment by simison** [comment]
@chmac, @mrkvon wrote above:
>I advise not to use this service.

**Comment by chmac** [comment]
Aha, I see, the original comment was updated so it didn't arrive by email. Got it.

**Comment by simison** [comment]
@chmac I looked at Boxcar.io last night — I like how their API/documentation is more simple than Onesignal's. It's just 7e/mo (or free up to 100 devices) so not breaking the bank.
