### ISSUE TITLE
Precomposed template contact info/location message to share with guests

### ISSUE THREAD

**Issue by daiyi** [Trustroots/trustroots#490]
Idea! a private "welcome to my house" section, maybe just a plaintext textfield, that users can use to compose a message with their contact info, address, house rules, etc. Once they decide to host someone, they can use a "send welcome message" button within message threads to give guests their information.

And maybe a similar "traveler contact info" section, a similar plaintext field where travelers can compose a message with their contact info to share back to hosts.

--

Background information: 

I notice a pattern when I'm communicating on hospitality sites: after a host decides to welcome a traveler into their home, they share some contact information, generally along the lines of:

- synchronous contact info (whatsapp, messenger, sms)
- address (plaintext, or google maps link)
- additional instructions ("go through the side gate", "I get off work at 6pm, so please arrive after that")
- maybe public transit info
- other house stuff, like wifi passwords, please take anything you'd like from the fridge, take off shoes before entry, book exchange shelf in the livingroom, no meat zone, etc

I end up re-assembling a message like this from scratch each time, or copy-pasting from a past message. Some of the hosts I've had have something clever ready, such as a "welcome guide" page on their personal website, so they only need to send a link that has all the information. My idea here is to improve ease of communication by simplifying the action of rewriting (with the possibility of leaving important stuff out), copy/pasting this message each time, or creating a separate external webpage (I like doing that, but not everyone does :P )

Just some ideas! I'm kind of excited about this so I may give it a shot after I'm back from the mountains/highlands in May (: what do yall think?

**Comment by kalpaitch** [comment]
I really like this idea. I wanted to get this implemented on WarmShowers. It's also a good way to encourage a 'formal' hosting acceptance flow which is easier to track and get accurate usage statistics on.

**Comment by daiyi** [comment]
I hadn't even though about the usage stats aspect, but it is true! yes yes

An upgrade after text field would be to have a little placard or something, but I kind of like the idea of starting out with just the textarea so people can use it however they like.

**Comment by vssdeo** [comment]
This feature is needed as its a very common use case, If I remember correctly it was there in CS also & while replying back I could just insert directions / details etc, then there is this concept of template, to help adding the same text like journey specific details that you re-write every time ( I do for each country with approx overview of route ).
