### ISSUE TITLE
copy & paste in text area of send messages removes formatting especially newlines

### ISSUE THREAD

**Issue by vssdeo** [Trustroots/trustroots#496]
Sending messages on trustroots I am copying and pasting the travel template of my plans, and it loses it formatting especially the newlines.

Reproduce.

1. Copy a block of text with formatting or just with new lines
2. Go to messages & paste while sending a message
3. As soon as you paste all formatting gone

**Comment by simison** [comment]
Probably good idea to try copy+pasting from browser, MS word, Google docs etc other weird sources and see if it ends up breaking anything.

**Comment by vssdeo** [comment]
New lines and basic formatting is kept rest is removed. Keeping structure and links good rest removed.

![screen shot 2017-05-03 at 11 07 59 pm](https://cloud.githubusercontent.com/assets/19357612/25673624/ac947f58-3055-11e7-821b-6b24d278eb83.png)
![screen shot 2017-05-03 at 11 08 12 pm](https://cloud.githubusercontent.com/assets/19357612/25673622/ac8d0782-3055-11e7-8307-7a38783be99e.png)
