### ISSUE TITLE
Welcome / onboarding emails

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#501]
A series of emails when a user signs up.

## First

First email as soon as the user has confirmed their email address.

```
Hi [NAME]!

This is Natalia from the Trustroots Foundation. Trustroots is an open, transparent, fun, and international sharing community. We believe in a world where people can trust each other.

We are excited to have you here because that means one of our existing members trusted you to join in. You too can help trust grow by inviting your friends to our community.

Please take a few minutes to fill out your profile. This is the foundation of your experience in Trustroots.

Happy trails!

Natalia
```

## Second

We send this email 24 hours after the user signed up. Would be awesome if we can highlight the invite code and link, make the text big, so they stand out and are super obvious in the forwarded email.

```
Hey [NAME], forward this email to invite friends to join Trustroots, the international sharing community.

Invite code: [CODE]

This code is valid for 24 hours. To get a new code, [blablabla](https://www.trustroots.org/invite)

Signup: www.trustroots.org
```

## Third

Work in progress...

**Comment by simison** [comment]
>Please take a few minutes to fill out your profile. This is the foundation of your experience in Trustroots.

Let's elaborate this a bit more and stress more that it's important? _helps you to find hosts and find good guests_ etc

**Comment by simison** [comment]
Third level of engagement e.g.:
- volunteer
- donate
- spread in your networks
- give us feedback

**Comment by simison** [comment]
And let's send the second one to everyone in the network?

**Comment by chmac** [comment]
@simison Totally up for the emails being improved. Suggest we kick them live as they are so as not to lose any time and create a second issue to improve the text.

Agree that reaching out to everyone in the network makes sense. Was thinking to add a special code that's valid for 7 days or something for that email, but maybe that's also an unnecessary delay!

**Comment by chmac** [comment]
Ideally I'd like to link to a blog post that explains what a good profile looks like. Or a helpdesk article or something. But we don't really have anything right now. Anyone want to write some tips on what makes a good profile?
