### ISSUE TITLE
Increase invite code acceptance window

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#502]
* Use the server time
* Push the acceptance out to 5 days

**Comment by chmac** [comment]
you can use this: `appSettings.time` e.g. here: https://github.com/Trustroots/trustroots/blob/bd2d4adfc04f3d958510e10d39a639cd36b1a314/modules/users/client/controllers/invite.client.controller.js#L20

**Comment by simison** [comment]
(attempts to fix timezone bugs in invite-code system we just couldn't replicate yet)

**Comment by chmac** [comment]
Using `appSettings.time` won't work. It's a string, and it's static. It's the time that the app was loaded from the server, not the current time. So if you leave the app open for many days, it'll always be many days old.
