### ISSUE TITLE
Better onboarding email copy

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#505]
See #501 for the first version.

> Please take a few minutes to fill out your profile. This is the foundation of your experience in Trustroots.

Let's elaborate this a bit more and stress more that it's important? helps you to find hosts and find good guests etc

Third email / third level of engagement e.g.:

volunteer
donate
spread trustroots in your networks
join tribes
give us feedback

**Comment by simison** [comment]
Third email looks like this:

- [plain text version](https://github.com/Trustroots/trustroots/blob/master/modules/core/server/views/email-templates-text/welcome-sequence-third.server.view.html)
- [html version](https://github.com/Trustroots/trustroots/blob/master/modules/core/server/views/email-templates/welcome-sequence-third.server.view.html)
