### ISSUE TITLE
project split

### ISSUE THREAD

**Issue by vencax** [Trustroots/trustroots#515]
It is IMHO better to keep frontend and backend separated as a standalone projects. 
It allows split the people who manage both projects (naturally = frontend people and backend people), independently test the parts, split responsibilities, to have all the stuff like pull reqs, issues, code more clear, readable and tidy.
The deployment staff like codeship scripts and similar can co to separate repository as well :)
What do you think?

**Comment by simison** [comment]
Hey! Thanks for writing us.

Yep, this is how it would structured if we would start building TR today. :-)

However, we're in a middle of trying to grow this thing bigger and engage users better, so jumping into a huge restructuring of everything isn't really possible.

Good food for thought and definitely something to look into when Angular1 frontend starts feeling waaay too outdated.
