### ISSUE TITLE
Another project split

### ISSUE THREAD

**Issue by vencax** [Trustroots/trustroots#517]
To be complete: I would suggest another project split (the first here https://github.com/Trustroots/trustroots/issues/515). Frontend logic can use MobX as state management. It allows to write complete application without viewing logic. And of course well test it.
The other part (viewing part) can be then written in react (or vue.js) or most importantly in ReactNative as a mobile app. This viewing parts does not need to cope with app logic at all. They just care how to view  the app state.

**Comment by simison** [comment]
I wrote a reply to this in another issue already; https://github.com/Trustroots/trustroots/issues/515#issuecomment-303826936
