### ISSUE TITLE
Add the maitre snippet to invite page

### ISSUE THREAD

**Issue by chmac** [Trustroots/trustroots#519]
Here's our snippet, apparently we drop it in where we want the waiting list form to appear.

```
<script type="text/javascript">
        window.Maitre = { uuid: "MF930c37aeb3" };
</script>
<script data-maitre src='https://maitreapp.co/widget.js' async></script>
```

**Comment by simison** [comment]
![image](https://cloud.githubusercontent.com/assets/87168/26760778/f4842ff6-4929-11e7-8d29-94bdc7e5d83e.png)

@chmac can you modify that "Invite 5 friends to join Trustroots" header to be removed? It's coming from the widget.

Can you also share Maitre credentials with me at laspass

**Comment by simison** [comment]
@chmac can you modify "reply-to" domain? Anything else than @trustroots.org might seem suspicious for people.

![image](https://cloud.githubusercontent.com/assets/87168/26760945/a08516c8-492d-11e7-9015-1453abda9e9e.png)

**Comment by chmac** [comment]
@simison I don't think we can change the from address, but I'll have a look. I also think it'd be good to remove the 5 number from the app so we can change that on the fly without having to redeploy.

**Comment by simison** [comment]
Deployed to prod :tada:

https://www.trustroots.org/signup

**Comment by simison** [comment]
@chmac we could show different text above the widget when we notice they're at the page trough invitation. WDYT?

**Comment by chmac** [comment]
@simison Not a bad idea, but a minor optimisation to take care of whenever we've got nothing better to do I'd guess (which is another way of saying never! :-D ).
