### ISSUE TITLE
Last seen stats

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#529]
This could just be something super simple that calculates average "last seen" data and pushes it to stats in [daily stats job](https://github.com/Trustroots/trustroots/blob/master/modules/statistics/server/jobs/daily-statistics.server.job.js).

Logic itself can be here: https://github.com/Trustroots/trustroots/blob/master/modules/statistics/server/controllers/statistics.server.controller.js

https://momentjs.com/ might be useful here.

_How many users logged last day, week, month, year, ... never),_ (_other ideas?_)

**Comment by trmendes** [comment]
There is a problem with the 'users logged last day' which is:

 let's imagine that a 100 users logged into TR yesterday. So those 100 users will have seen = today - 1
 let's now say that half of the same users who logged into TR yesterday logged into TR today too. 
 Now we will have a statistic saying that we had 50 users logged users yesterday and 50 today which is wrong. 

 Shall we keep the yesterday statistic? Any better idea of how to sum how many users logged a day before today?

**Comment by simison** [comment]
Follow-ups to https://github.com/Trustroots/trustroots/issues/755
