### ISSUE TITLE
Admin Panel and Dashboard

### ISSUE THREAD

**Issue by coooolers** [Trustroots/trustroots#533]
Features like Users List, Number of Properties in a particular area, Search, Sort, Filter, etc. for example filter Active Users

Analyatics: IP Addresses, Ban IP Address etcetra...

**Comment by simison** [comment]
Hey! Thanks for asking(?) We don't have currently and we're not planning currently neither.

Analytics we have rolling with external app, it doesn't make sense to implement inside TR app.
