### ISSUE TITLE
Improve mobile experience for setting a location for hosting

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#547]
It's a bit of a drag on small screens, especially keyboard open when tapping "search".

**Comment by daiyi** [comment]
The map selection is not working on mobile for me ): (even when I tell my browser to show desktop version)

The map remains blank, and when I put my cursor in the search box the keyboard bumps up the map overlay over the search box.

![screenshot_20170818-100057](https://user-images.githubusercontent.com/1589186/29450352-aa4e06ea-83fe-11e7-9bb9-b0a0c2e126cc.png)

![screenshot_20170818-100114](https://user-images.githubusercontent.com/1589186/29450345-a49294be-83fe-11e7-92e8-c8354cedf286.png)

**Comment by simison** [comment]
Thanks, yeah I totally need to work on it more (#547)

Blank map issue I've attempted to fix already twice and it's hard to replicate. Does changing phone's orientation to horizontal fix the map?

**Comment by simison** [comment]
A bit better now:
![image](https://user-images.githubusercontent.com/87168/29490403-309e1f24-8543-11e7-9643-ec66dc13cdb2.png)

![image](https://user-images.githubusercontent.com/87168/29490404-3c91a7ce-8543-11e7-8a39-40adb5042eff.png)

But still needs improving, I'll keep this open as a reminder.

**Comment by simison** [comment]
I could probably hide the main navigation while adding/modifying host/meet offer...
