### ISSUE TITLE
Cannot update profile name

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#551]
Got a few reports about people not being able to update their name at the profile.

Need to investigate a bit more.

**Comment by chreekat** [comment]
My new, modified name shows up in the textboxes on profile/edit, but doesn't show up elsewhere.

**Comment by simison** [comment]
Oh right, so it seems like `firstName`and `lastName` are stored but `displayName` isn't.

https://github.com/Trustroots/trustroots/blob/master/modules/users/server/models/user.server.model.js#L102-L117

**Comment by simison** [comment]
Generating `displayName` just got dropped out when moving validators to Schema level from the controller earlier, and this one didn't have tests.

Mongoose [virtuals](http://mongoosejs.com/docs/guide.html#virtuals) would be better way handling these but meh.

**Comment by simison** [comment]
Seems like this is still an issue at least for those who got affected by the bug earlier:

> I tried updating my name again and it still doesn't work (appears as the changed name in the Basics section of the Edit Profile page but remains as the old name on the My Profile page and in the right-hand dropdown on the menu/navigation bar.

> I have just tried to update my profile again but nothing has changed, the system saves the changed name but doesn't diplay it as such - it keeps displaying the old name. So, at least for my case, the bug doesn't seem to be fixed.

**Comment by guaka** [comment]
Has this been resolved in the meanwhile?
