### ISSUE TITLE
Send notification to nearby people when someone adds meet offer on map

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#557]
This should obviously be as simple as possible, but there are quite a lot of open questions:

- Whom to send? People living there, people offering hosting, people with other meet offers? (_Maybe everyone at first and improve it then_).

- Should it be sent to everyone, even when it's a busy place? If I place meet offer in Berlin, should all several hundred people get a notification? Should we limit it to only people on same tribes or other factors?

- Should email be opt-in or op-out? _Preferably opt-out._

**Comment by jhabdas** [comment]
BLE and rotate offer?

**Comment by simison** [comment]
"BLE"?

I'll also need to keep this as simple as possible so ideal solutions aren't
always possible if they are technically complex.

Mikael

**Comment by jhabdas** [comment]
Sorry. BLE is Bluetooth low energy. Thought is to have physical devices use it to surface offers to nearby individuals and rotate through them with time-sensitivity. Figured it might work well in the crowded place scenario and help move more communication towards push as opposed to emails which could get buried.

**Comment by Regenwasser** [comment]
If Trustroot is active and many use that feature this will be complicated. Meets would have to be bundled in daily or weekly "newsletters". But currently it would be nice to notify the tribes.

I tested meet 2 or 3 times without any luck in Berlin. Can we track how many people view a meet offer or get a message, because they posted a meet offer to see some sort of success rate?

**Comment by noahsmindfuck** [comment]
I would go for a yes/no switch in the profile that says "Do you want to meet people in your area?" and if it is switched to "yes" they receive notifications, none for "no". It should be mandatory to fill this with either yes or no when you create a profile, default set to "yes".
