### ISSUE TITLE
Login tab sequence

### ISSUE THREAD

**Issue by beatnickgr** [Trustroots/trustroots#560]
The ones who just use a keyboard to login, are used to type username tab password tab enter.
But on TR the 3rd tab will hit the "forgot password" instead.

Please change the tab sequence to username, password, login, forgot password.

HTML form code: https://github.com/Trustroots/trustroots/blob/master/modules/users/client/views/authentication/signin.client.view.html

Just needs adding tabindex to username input (`tabindex="1"`), password input (2), and login button (3).

**Comment by yohgenius** [comment]
hello, i'm interested to do this issue... may i take it?

**Comment by simison** [comment]
@yohgenius absolutely! Would be great to have a PR from you.

Feel free to look for other issues with tabbing (accessibility in general) as well!

**Comment by simison** [comment]
@yohgenius lemme know if you need help setting up the dev environment and if you email me (mikael@ihminen.org), I can add you to our developer chat.

**Comment by yohgenius** [comment]
Okay, thanks for the acceptance.. 
I will fork the project first and will come again to ask if there is any problem... :)

**Comment by benJervis** [comment]
Hi @simison,

If this issue has gone stale, am I able to submit a PR for it? 

I have one ready to go, and it'd be great to get another Hacktoberfest item in.

**Comment by simison** [comment]
@benJervis sure! Just PR if you have it ready as it seems like it's already 9 days since @yohgenius was last time active on this.

**Comment by yohgenius** [comment]
yeah, sorry i still haven't finished this issue because some installation problems..
feel free to take it and i will take another issue after i got my laptop ready...

**Comment by simison** [comment]
@yohgenius no worries! Feel free to have a look at other issues labelled [Hacktoberfest](https://github.com/Trustroots/trustroots/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest) or [easy](https://github.com/Trustroots/trustroots/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy) as well!

**Comment by yohgenius** [comment]
thanks @simison, i don't know what's wrong with my laptop.
everytime i try to install new dependency like laravel or mongoDB in this case, it always give me some errors and sometimes i have problems looking for the solution.

**Comment by simison** [comment]
@benJervis @beatnickgr this went to production today. Thanks again! :tada:

**Comment by simison** [comment]
@yohgenius, @benJervis here's another very quick and easy one if you're interested to add one more PR to your #hacktoberfest: https://github.com/Trustroots/trustroots/issues/565 ;-)
