### ISSUE TITLE
Problem with hosting location picker and Firefox 55

### ISSUE THREAD

**Issue by abustany** [Trustroots/trustroots#561]
The location picker (used for setting the hosting location) does not seem to work with the current deployed version (463605b) and Firefox 55 / Linux x86_64. Chrome 61 seems to work fine. The attached screenshot shows the issue (tiles don't load/display as they should).

![trustroots_location_picker](https://user-images.githubusercontent.com/2526296/31166898-9d6963cc-a8f0-11e7-9c07-dfc88a938455.png)

**Comment by simison** [comment]
Thanks for the heads up! I'll have a look.

**Comment by simison** [comment]
@abustany this should now work on production. Thanks again!

**Comment by abustany** [comment]
Yep, I can confirm that the issue is fixed, thanks :)
