### ISSUE TITLE
Add ability to archive message threads

### ISSUE THREAD

**Issue by jangorecki** [Trustroots/trustroots#567]
Just a simple flag so we can filter out our past messages that were left without reply.

**Comment by simison** [comment]
@jancborchardt wanna elaborate the need a bit more? I'm not sure if I follow.

Now you can see if you've replied a message from that little arrow icon:

![image](https://user-images.githubusercontent.com/87168/31731073-92dff702-b43c-11e7-968a-bacb0f82b84f.png)

**Comment by jancborchardt** [comment]
(@simison I guess you meant @jangorecki, but hi anyway ;)

**Comment by simison** [comment]
Hah, funny tab completion incident. :-) Sorry for the spamping!

**Comment by jangorecki** [comment]
@simison separate tab for message that you are not interested to browse through anymore. Same as on CS.

**Comment by jangorecki** [comment]
Yes

**Comment by jangorecki** [comment]
I cannot removed the new label unfortunatelly

**Comment by TMC89** [comment]
+ the ability to remove unwanted/old messages (suggestion through support)
