### ISSUE TITLE
Cannot open message thread from "unknown" member

### ISSUE THREAD

**Issue by abustany** [Trustroots/trustroots#574]
Hi,

In my inbox I have a thread with a member that probably deleted its profile (name says "Unknown member"). When I try to open the thread (to mark the unread messages as read), I get a Javascript exception, and the UI goes back to the inbox.

My profile is https://www.trustroots.org/profile/adrien/overview

**Comment by simison** [comment]
Thanks, you're right. We still have those messages (only user profile gets deleted) so it would make sense to show them.

**Comment by trmendes** [comment]
duplicate #596
