### ISSUE TITLE
Surfing report, October 23 2017

### ISSUE THREAD

**Issue by chreekat** [Trustroots/trustroots#578]
After doing some real surfing, I collected some thoughts on the experience.

As a surfer,
1. I want a list view of hosts visible on the map, so that I can quickly review and compare – #721 
2. I would like to know which hosts I've already viewed, so that I can be efficient in my search

Other issues/feedback:
1. Definitely need to filter out those with 0% responses
2. On page loads, I often see lots of flashes of empty default data
3. Clicking on a user activates both 'Overview' and 'About'. Both highlight in nav, and it takes two clicks to get back to the map – #746 
4. 'Send a message' is hard to find on the user page
5. Clicking around a profile necessitates lots of 'Back' clicks to get to the map (related to 3)

**Comment by simison** [comment]
I looove love love this kind of reports. Thank you @chreekat !

**Comment by guaka** [comment]
Shall we turn some of this into more actionable issues? (or link to existing ones)
