### ISSUE TITLE
Not receiving email confirmation 

### ISSUE THREAD

**Issue by matt-and-cici** [Trustroots/trustroots#579]
Hello, we have received an invitaion from our friend that is part of the trustroots community. We got the code and everything worked. We did our profile amd the only thing missing is receiving an email from Trustroots to complete our registration before we are able to look for hosts. We have tried with various emails and we have tried contacting trustroots support team through their website, email, facebook and now this blog. If anyone can help us, that would be amazing. Thank you in advance, Matt and Cici

**Comment by simison** [comment]
Emails are rolling again.

Sorry for the trouble folks and thanks for the patience! We've had server issues and I've been on the road for the past weeks. All good now 👌 and looking into what to improve for this not happen again. I'm adding one more person who can help when server goes south if others are on the road.

**Comment by matt-and-cici** [comment]
Hello,
The issue is not resolved.
We received a bunch of confirmation emails, but all of them were expired, so now we cannot still activate the account. We sent a new email from our profile to confirm one again, and it is not working once again.
We still cannot activate the account.

Thank you for any help.
Matthew

Sent from my iPhone

On Mar 10, 2018, at 12:24 PM, Mikael Korpela <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #579<https://github.com/Trustroots/trustroots/issues/579>.
