### ISSUE TITLE
Not receiving e-mail after clicking "Forgot password"

### ISSUE THREAD

**Issue by CRCulver** [Trustroots/trustroots#581]
In spite of #577 and #579 having been closed as fixed, I am still not receiving any e-mail after clicking the “Forgot [password]” link on the login screen. My mail server logs show that TR is not even connecting to try to deliver the e-mail.

**Comment by chreekat** [comment]
@simison let me know if I can help out with sysadmin tasks. I'd be happy to be a backup

**Comment by trmendes** [comment]
@CRCulver Hi! Do you still have any problems with it?

**Comment by simison** [comment]
After some fixes in spring, haven't heard about this issue anymore. 👍
