### ISSUE TITLE
Heroku install

### ISSUE THREAD

**Issue by bothman** [Trustroots/trustroots#583]
Hi,
Is there any special settings that we need to do to run the app in Heroku ?

I have pushed the code and I got "Application error"

**Comment by simison** [comment]
Hi @bothman !

> Is there any special settings that we need to do to run the app in Heroku ?

I'm not really familiar with Heroku but you might want to have a look at Meanjs Heroku deployment: https://github.com/meanjs/mean#deploying-meanjs-to-heroku

Trustroots code also relies on saving profile images to disk, which wouldn't work with Heroku.

What are you planning on doing with the code? :-)
