### ISSUE TITLE
Replying "no" to push notification question does not persist between browser resets

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots#585]
Either my "No, Thanks" is stored in my cookie which is deleted with closing the browser or it is not stored at all. It is annoying. Please make it stop.

**Comment by simison** [comment]
Yep, these get currently stored in the browser's local storage (something like a cookie).

**Comment by noahsmindfuck** [comment]
It pops up in every tab (using Firefox), even without closing the browser.

**Comment by trmendes** [comment]
@noahsmindfuck Do you have any addon that cleans your browser state everytime you do something? I'm asking you 'cause I use firefox and firefox only asks me once and it happens only when I clean my firefox using an addon I have or whenever I close and open the browser. I believe this is a browser configuration issue and not a Trustroots system bug.

Do you still facing this issue?

**Comment by noahsmindfuck** [comment]
@trmendes I use "NoMiner" and "AdBlock Plus" as addons. I do not have my history cleared automatically and I am not in private mode.
Still, replying "No, thanks!" makes any new tab show the question again. I don't know so much about browsers, I mangled with my user agent config a little to give out wrong information about my device and OS but that's it.
I do delete cookies every time I close my browser though. But I do not close my browser between opening the tabs so that shouldn't interfere.

Any other info I can provide?

**Comment by trmendes** [comment]
@noahsmindfuck 
Check this link:
https://support.mozilla.org/en-US/kb/push-notifications-firefox#w_how-do-i-stop-firefox-asking-me-to-allow-notifications

**Comment by noahsmindfuck** [comment]
That did it! Removing trustroots.org from the websites that have permission to send messages made them go a way. What magic! ;)

**Comment by noahsmindfuck** [comment]
Ups, that was accidential

**Comment by noahsmindfuck** [comment]
Sorry for the chaos. Same thing is happening again, no matter what setting I use for notification permission.

**Comment by trmendes** [comment]
Have you tried it using chrome or even another computer?

**Comment by noahsmindfuck** [comment]
I did try to use private mode and - voila - the in private mode I am not asked when I open Trustroots and neither when I open links in Trustroots in new tabs.
So the question remains. 

Why am I asked this question all the time when I use Firefox to
- log in to Trustroots
- open anything in Trustroots in a new tab
- but not if I use private mode
- and why was that solved for a short time after I removed the permissions for Trustroots and came back whithout any action of mine?

I do not see how using another computer or another browser will help in this case.

As I wrote earlier I am clearing cookies and site data every time I close(!) Firefox. 
I tested the following: 
Keeping my instance of Trustroots open and opening it again in a new window instead of a new tab but still, even though the login is preserved, so it is stored somewhere, the notification setting is not preserved, not stored.

Maybe this is a pure browser configuration issue, maybe it is both. It would be great to understand where Trustroots stores the notification setting to understand the issue better.

**Comment by noahsmindfuck** [comment]
Also, the reason why I think this is a Trustroots issue and not a browser issue: The notification is from Trustroots, not from the browser!
![2018-08-03-080948_1920x1080_scrot](https://user-images.githubusercontent.com/24893086/43627022-ceee5efa-96f4-11e8-946c-b8abb81b0b7d.png)

**Comment by guaka** [comment]
(May be related to Trustroots/trustroots-expo-mobile#12)

**Comment by topalavlad** [comment]
After reading a bit, `session` storage [gets cleared](https://www.w3schools.com/html/html5_webstorage.asp) when a tab is closed so that was not a correct solution. I moved the `tr.push.asked` key to a different `namespace` that doesn't get cleared on log out.

**Comment by petr-hajek** [comment]
From my testing on Linux Mint:
Displayed when log-out / log-in in the same browser
on FF 63.0.3 (non private), Chromium 70.0.3538.110 (both normal & private).
Only working OK for FF in private mode.
Does not matter what is the answer.

**Comment by simison** [comment]
>Only working OK

Can you describe how does it behave specifically?

See https://github.com/Trustroots/trustroots/pull/816#issuecomment-440793026 for more context.

**Comment by petr-hajek** [comment]
> > Only working OK
> 
> Can you describe how does it behave specifically? Just to make sure we don't have different expectations. :-)
> 
> See [#816 (comment)](https://github.com/Trustroots/trustroots/pull/816#issuecomment-440793026) for more context.

It means it does not display the notification in FF private mode.
I expect that I do not get this pop up every time I log into TR with the same browser.

**Comment by simison** [comment]
>     

It means it does not display the notification in FF private mode.https://github.com/Trustroots/trustroots/blob/f0fcf8c7cb3e114339585644aaf0c7dc384da2ee/modules/core/client/services/push.client.service.js#L72-L80
