### ISSUE TITLE
Inapproriate email domain suggestion in the registration page

### ISSUE THREAD

**Issue by eyalroz** [Trustroots/trustroots#587]
I've just gotten an invite from someone, and am registering myself on the network. As I enter my email, eyalroz@technion.ac.il , I get the suggestion "did you mean eyalroz@technion.co.il ?" I can say "Nope", but again - inappropriate suggestion. Related to my other issue (#586).

**Comment by simison** [comment]
Since this is a bug in an external system and it's already been a while, I'm going to close.
