### ISSUE TITLE
FAQ thingies

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#594]
- [x] "How can can I contact you?" => remove one can
- [x] https://talk.hitchwiki.org/ is down
- [ ] Add section: How can I help? With at least link to https://github.com/Trustroots/trustroots/wiki/Volunteering  -  https://github.com/Trustroots/community/issues/10

**Comment by simison** [comment]
FAQ sections are here: https://github.com/Trustroots/trustroots/tree/master/modules/pages/client/views

**Comment by trmendes** [comment]
Shall I use any other address to replace "https://talk.hitchwiki.org" or should I remove all the links and keep the text only?

**Comment by simison** [comment]
@trmendes looks like @guaka already removed that link from the FAQ in https://github.com/Trustroots/trustroots/commit/23e8e7b6550b07193b6530249a30e87f651136d7#diff-8e2b45ba5a0a0a0882c6e637c2695303

**Comment by trmendes** [comment]
I see! Pefect \o/

There is a "How can can" on faq-general though.

https://github.com/Trustroots/trustroots/blob/3b9a37b4afe14f52f05be092e737b20ea7457900/modules/pages/client/views/faq-general.client.view.html#L104

Can I remove that one?

What about the Add section: How can I help?

Though about copy the text from the beginning of the volunteer document

Trustroots is a community of travellers for sharing, hosting and getting people together. If you want to help grow this network you can <ADD A LINK HERE>find some things to do here</ADD A LINK HERE>.

Is that ok?

**Comment by guaka** [comment]
@trmendes 
- yeah fix the other "can can"
- that's a good line for "how can I help", best link it to this: https://github.com/Trustroots/trustroots/wiki/Volunteering is probably the best place to link to
