### ISSUE TITLE
mongo 3.6 doesn't work

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#597]
workaround:
- install mongo 3.4, how?

what's the problem?

**Comment by trmendes** [comment]
I believe the problem with 3.6 is related to this issue #580

I'm running TR using mongodb 3.6.5 and the problem I get is the same related at this issue. Some queries are missing a cursor.

There is a pull request to upgrade mongoose but I'm not sure how this could help fixing this issue with mongodb 3.6 

PR: https://github.com/Trustroots/trustroots/pull/539

**Comment by guaka** [comment]
Ah ok, so mongo 3.6.5 still mostly works for you?

**Comment by trmendes** [comment]
Like I said before. I'm a beginner at JavaScript, Mongo and this all web developing thing!! I can't say it is working but I can login, logout, send messages, read messages, change my profile info. What I know I can't do is: I can't use the search page and the map does not show anything. All I get there is an error saying we are missing a cursor :( like the one in #580

**Comment by simison** [comment]
I'll close this one and let's keep notes at https://github.com/Trustroots/trustroots/issues/580

**Comment by simison** [comment]
>install mongo 3.4, how?

https://docs.mongodb.com/v3.4/installation/
