### ISSUE TITLE
problem with (no) username

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#599]
on mobile:

"There is a problem with my username. I can not add one but the app tells me I need one to complete my profile."

<img width="676" alt="image" src="https://user-images.githubusercontent.com/54728/40988092-e7b2b664-68f2-11e8-96b7-ec6739fc8f52.png">

more info at https://trustroots.zendesk.com/inbox/conversations/2206 (for those with access)

**Comment by trmendes** [comment]
related #595

**Comment by simison** [comment]
Username ended to `.` — I updated it directly in DB.
