### ISSUE TITLE
markdown (or links) in user profiles?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#60]
- [ ] Yup, I agree about turning URLs into links.
- [x] Now you can highlight text and use basic WYSWYG.
- [ ] Markdown goes into "would be nice" but not urgent at all
- [ ] easily link to `@simison` usernames  #120 

https://www.trustroots.org/#!/profile/guaka

![screen shot 2014-12-07 at 16 27 13](https://cloud.githubusercontent.com/assets/54728/5331488/f32c14e4-7e2d-11e4-8653-54ec2fc79013.png)

**Comment by chreekat** [comment]
fwiw I find the wysiwyg buggy. After highlighting some text and making it a quote, the font size jumped from 14px to 18px. That's raised-eyebrow number one. Then, the font size occasionally stays at 18px when I press &lt;return> and leave the quoted region.

![wysiwyg](https://cloud.githubusercontent.com/assets/538538/5836946/cb5bc514-a172-11e4-8a93-dfd2bc1145a1.gif)
