### ISSUE TITLE
Show more info of contacts: location and contact status

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#612]
It would be very useful - and quite simple to add - to see the place and country where contacts of someone are located.

E.g. now I'm looking for people in Vienna, and I know my friend has lived there, so she must have friends in Vienna, but now I have to open 22 profiles to see whom of her contacts are in Vienna.

https://www.trustroots.org/profile/*/contacts

<img width="874" alt="image" src="https://user-images.githubusercontent.com/54728/42418631-ca61043c-82a4-11e8-863c-26f4bb1a6991.png">

While at it it would be a simple thing to also add whether a person is already a contact.
(This is useful to know if you should still add someone you know. Now I'm not sure whether I added a person and I have to open their profile to check)

**Comment by trmendes** [comment]
Just a side note: We know TR have some problems running MongoDB > 3.4 but since I'm not sure if we do know which features are affected by it: The contact list feature isn't working with MongoDb 3.6

**Comment by simison** [comment]
>The contact list feature isn't working with MongoDb 3.6

Thanks, added a list to the issue about this: https://github.com/Trustroots/trustroots/issues/580

**Comment by trmendes** [comment]
Wondering if I could try this one. It seems like a nice one to learn a bit more about the frontend

**Comment by simison** [comment]
Contextually related to "Show my friends on the map" #396  and "make from/living locations into geo info" #395

**Comment by guaka** [comment]
Got this working, needs 1px right padding though, not sure how/where to best add that

<img width="402" alt="image" src="https://user-images.githubusercontent.com/54728/46863011-8c1b4580-ce16-11e8-8848-5bf71c42477c.png">

I think it's better to not use the `<small>` tag, and use divs with a `small` CSS class instead.
