### ISSUE TITLE
Contact list could mention users location

### ISSUE THREAD

**Issue by jangorecki** [Trustroots/trustroots#613]
On the page where you can list your contacts
https://www.trustroots.org/profile/username/contacts
it would be nice to have location (city, country) included under usernames, so you can easily see where your contacts are currently located.

**Comment by Tartesos** [comment]
Second that.

**Comment by simison** [comment]
Related to "Show my friends on map" #396  and "make from/living locations into geo info" #395

**Comment by simison** [comment]
Actually closing up this one as a duplicate of https://github.com/Trustroots/trustroots/issues/612
