### ISSUE TITLE
Username change history

### ISSUE THREAD

**Issue by trmendes** [Trustroots/trustroots#617]
It would be nice if we could have a history of all the changes the user did to the username.

Right now we are working in the feature where the user will be able to change her/his username.

The idea behind this issue is to save each of this change to the user document and then allow us to prevent new users or even the same user to re-use the login they or someone had before.

This issue is a comple of #595

**Comment by mrkvon** [comment]
So far we have discussed the following approaches to design the username history:

1. Keep the data in the array `usernameHistory` in User model
2. Have dummy users for every historical username - with a field `redirectUsername` containing the current username
3. Have separate models for past and present usernames (@trmendes)
 > What about having a new collection where every new document will be a map of the User.id with its last username and whenever a new user is being created we check both Collections. The one that contains the username that are being used by the users and those which were valid someday. I though about this approach because we could use this same collection to keep a history of ID/USERNAME of users who deleted their accounts.

Note to self: Points 2. and 3. seem to suggest model inheritance, perhaps possible with [discriminators](http://mongoosejs.com/docs/discriminators.html) (???)
