### ISSUE TITLE
Scroll problems on messages view

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#63]
Doesn't appear always, but at random pattern.

Touch pad scrolling works just fine.

(Firefox)

**Comment by jancborchardt** [comment]
Doesn’t work for me even with a touchpad. In both Firefox and Chrome.

**Comment by simison** [comment]
#172

**Comment by jancborchardt** [comment]
In #172 there doesn’t even seem to be a scrollbar. A scrollbar is shown for me and I can use it with the mouse, just not with the touchpad.

**Comment by simison** [comment]
I just head about the same issue on Windows Phone.

**Comment by yogiben** [comment]
Doesn't work for me on Chrome, Mac.

Also, scrollbar showing when there is nothing to scroll (short content).

**Comment by chmac** [comment]
I also can't scroll with the trackpad on a single message view. I'm able to scroll by clicking the scrollbar (when it appears). I see something related to scrolling in the `<div id="..." class="message ng-scope ng-isolate-scope ng-animate" ...` tag, maybe it's there?

**Comment by chmac** [comment]
I am able to scroll up and down using the arrow keys.

**Comment by guaka** [comment]
Same here, I hadn't even tried arrow keys, but they work fine.

**Comment by simison** [comment]
Note to self, test:
http://iscrolljs.com/#scrollbars
http://dimsemenov.com/plugins/royal-slider/documentation/

iScroll I've used before and I like it a lot.

**Comment by rettfoss** [comment]
Doesn't work on Chrome, a bit irritating

**Comment by simison** [comment]
Fix going to production tonight.
