### ISSUE TITLE
Facebook links from profiles don't work

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#637]
From my own profile: https://www.facebook.com/app_scoped_user_id/10152809941777209

Sorry, this content isn't available right now
The link you followed may have expired, or the page may only be visible to an audience you're not in.
Go back to the previous page · Go to News Feed · Visit our Help Center

<img width="707" alt="image" src="https://user-images.githubusercontent.com/54728/44473706-348c0500-a631-11e8-8ddf-b07977b69141.png">

**Comment by simison** [comment]
Yeah, should skim FB API changes to see what has changed. Similar: https://github.com/Trustroots/trustroots/issues/611

**Comment by guaka** [comment]
Do we have the FB uid?
In that case linking to `https://facebook.com/profile.php?id=<UID>` is probably a simple solution.

**Comment by guaka** [comment]
I guess we don't have the FB uid. But this looks good: https://stackoverflow.com/questions/23805866/get-facebook-user-id-from-app-scoped-user-id

**Comment by simison** [comment]
We have app-scoped UIDs and their API doesn't allow exposing the actual user IDs. Looks like we need to do some changes at FB admin panel to gain access to `user_link` permissions again.

**Comment by simison** [comment]
We heard back from Facebook. This might require some small changes to our site — until those are done, FB links are going to be broken but the connection button should remain working.

I might hide links from profiles but for now I'll keep it there in case we get this solved soonish.
