### ISSUE TITLE
Is MEAN still active?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#638]
I looked around a bit, and MEAN.io looks like an inactive project these days. Is my assessment correct?

If not, what does this mean for Trustroots development?
Also, how come it's not active anymore?

If it is, where is the activity taking place?

**Comment by simison** [comment]
Short answer: _nope_.

Note that http://meanjs.org/ (inactive now) and http://mean.io/ are two separate projects. The former was a fork of mean.io in 2014: http://blog.meanjs.org/post/76726660228/forking-out-of-an-open-source-conflict

Trustroots was built on meanjs.org version.

[Riess.js](https://github.com/lirantal/Riess.js) was an attempt to move it forward but it seems to have stalled, too.

Anyway, they’re written in Angular v1 which is old and outdated and there wasn’t clear update path to v2 and onwards (think Drupal style major breaking updates), so we got stuck.

We’ll eventually need to look into replacing Trustroots frontend bit-by-bit with something else, e.g.  React. It'll be a good change to decouple backend and frontend codebases a bit further, too.

I’d say regarding TR's framework, a lower hanging fruit would be to turn at least backend code from ES5 to ES6, I wrote a bit about it in chat, copypasting some bits:

>I’ve been playing with codemodding in another project and it was fun, I’m planning to do the same at least for the backend codebase using 5to6-codemods: https://github.com/5to6/5to6-codemod

>here’s a nice list of further reading and list of examples:  https://github.com/sejoker/awesome-jscodeshift

>In theory porting the backend is pretty straightforward;  needs separate eslint rules for client/server folders, `eslint --fix`, some codemodding and manual sorting out.
>

**Comment by guaka** [comment]
I'm still curious, what does it mean that meanjs.org is not active anymore? I.e. in terms of upgrades of stuff, and documentation, should we just forget it's "MEAN"?

**Comment by simison** [comment]
>I'm still curious, what does it mean that meanjs.org is not active anymore? I.e. in terms of upgrades of stuff, and documentation, 

We're on our own now. :-) Docs and stuff are still out there so it doesn't hurt to mention the fact, but going forward there aren't any "free" framework level updates trickling down for us.

>should we just forget it's "MEAN"?

Basically yes.
