### ISSUE TITLE
Search: add "last online" filter

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#639]
We need a search filter to easily filter out people who haven't logged in recently.

**Comment by simison** [comment]
This comes up pretty frequently in feedback.

It _might_ punish folks living outside cities (they get fewer messages → no reason to log in that often) but people searching for members from the countryside might be smart about this and tune their search filters.

That said, if people are doing this _anyway_  manually by ignoring people who didn't log in for a while, it needs to be a filter.

It can be above languages:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/87168/44569339-b2abf100-a782-11e8-9b66-a4b5873956ec.png">

For reference, this is how it looks like at CS:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/87168/44569474-2817c180-a783-11e8-9ea3-cdc190f31442.png">

I think we might do with just _"Don't show people seen long ago"_ toggle and start with 6 months. TR has too few members for a very fine-tuned search. We can adapt this as the number of people on the map increases. Let's leave it off for starters.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/87168/44569539-6ca35d00-a783-11e8-889d-99a36850fb7f.png">

We should also automatically filter out users who didn't log in within two years; that can be a separate PR before the toggle.

API code lives [in offers module](https://github.com/Trustroots/trustroots/blob/39bd908f9d1cf720829bc463f14a3a1634bc7adc/modules/offers/server/controllers/offers.server.controller.js#L367-L370) (+ [tests](https://github.com/Trustroots/trustroots/blob/39bd908f9d1cf720829bc463f14a3a1634bc7adc/modules/offers/tests/server/offer.server.routes.tests.js)).

Client side code lives in search module:
- [search-sidebar-filters.client.view.html](https://github.com/Trustroots/trustroots/blob/39bd908f9d1cf720829bc463f14a3a1634bc7adc/modules/search/client/views/search-sidebar-filters.client.view.html)
- [filters.client.service.js](https://github.com/Trustroots/trustroots/blob/39bd908f9d1cf720829bc463f14a3a1634bc7adc/modules/search/client/services/filters.client.service.js)
- [search.client.controller.js](https://github.com/Trustroots/trustroots/blob/master/modules/search/client/controllers/search.client.controller.js)

@guaka wanna implement the API side?  :-)

**Comment by simison** [comment]
_"Don't show people seen long ago"_ is a bit rubbish label, ideas for a better copy?

**Comment by guaka** [comment]
"Online in the past 6 months"?

Could become a slider in the future, with several options, e.g.
- past day
- past week
- past month
- past 6 months
- past 2 years

**Comment by guaka** [comment]
"Online in the past 6 months"?

**Comment by simison** [comment]
That works, thank you!

>Could become a slider in the future, with several options, e.g.

Yeah — the flexibility can be built in the API already (i.e. it can just take strings as values "6 months" "1 day" etc) and _not_ have API side default.

In the client, we'd expose only two values:
- _on: 6 months_
- _off: 24 months_
