### ISSUE TITLE
Write descriptions for tribes

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#644]
[Tribes](https://www.trustroots.org/tribes) can have descriptions, e.g. [Foodsharing](https://www.trustroots.org/tribes/foodsharing):

<img width="508" alt="image" src="https://user-images.githubusercontent.com/87168/44568609-39130380-a780-11e8-9767-dcbe2ff3be41.png">

Several other tribes could do with short descriptions, too.

Feel free to write them in comments below and I'll put them in the database.

**Comment by guaka** [comment]
https://docs.google.com/spreadsheets/d/17CmX8aPS-LkqhDEO8Q_i4I_pe656_r7nDcwlwiSxvek/edit?ouid=105108367254312434377&usp=sheets_home&ths=true

**Comment by guaka** [comment]
We did this :)
