### ISSUE TITLE
Fix docker setup

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#662]
[Docker](https://www.docker.com/) has come a looong way since we set up it initially and it's pretty decent way to develop these days.

Our current Docker-compose based setup is broken (https://github.com/Trustroots/trustroots/issues/618#issuecomment-413538027, https://github.com/Trustroots/trustroots/issues/646#issuecomment-415713689) and should be fixed.

**Comment by MasonM** [comment]
FYI, I entered 3 PRs that fixed all the issues I ran into while setting this up:
https://github.com/Trustroots/trustroots/pull/751
https://github.com/Trustroots/trustroots/pull/752
https://github.com/Trustroots/trustroots/pull/750
