### ISSUE TITLE
Add the missing 80% of users to the map / search results

### ISSUE THREAD

**Issue by Regenwasser** [Trustroots/trustroots#667]
### Current situation:

**80% of users** _(currently 25,092 people - namely everyone who isn't hosting)_ **are not shown on the map**. Nobody can write them and therefore they are effectively removed from the community.

### Expectations:

Everyone is shown on the map, so they can be contacted. If a user travels somewhere or signs up they want to see a lot of search results that they can interact with and meet, even if they stay in a tent or a hotel. Not everyone is looking for a host.

________________

There's of course a bunch of other issues related to this, mainly:

- Make from/living location fields store actual geo info #395 [High Priority]
 
Also a good idea to include an eMail to all or the affected users here to announce the changes are done as @simison already suggested.

**Comment by hitchhooker** [comment]
ive also been hoping for feature to show location even while on the road, would be cool to be also invited to stay sometimes instead of requesting based on my location.

**Comment by Regenwasser** [comment]
> I've also been hoping for feature to show location even while on the road, would be cool to be also invited to stay sometimes instead of requesting based on my location.

Have you seen the [meet feature](https://www.trustroots.org/offer/meet) yet? You can use it to manually place blue markers in all the locations that you visit. 

It's not the automatic or easy solution that you hope for yet, but the idea has been around since the beginning of Trustroots and even Hitchwiki (as Mikael mentions in #358).
