### ISSUE TITLE
Make all location fields autocomplete addresses / places 

### ISSUE THREAD

**Issue by Regenwasser** [Trustroots/trustroots#668]
Referencing #547 and #76 -

We know from user feedback, selecting your location can be very difficult and painful, especially on mobile devices or in the case that you want to select a certain spot. 

###  Current Experience:

A user can only select and search for a country or city and not the street or point of interest. 

Users that want to select their home or a meeting location need to search for the city and then use the map to find an address. This is takes long on mobile devices and for people that are not great with maps or that don't know the city well it's very difficult.

In the profile the lack of autocomplete also leads to more people not entering a full address.

### Expectation:

When I organise a meetup I might want to search for things like "Mauerpark, Berlin" and the map should directly zoom into the location. Saving users a lot of time by not having to manually find the place. 

In "Profile: _Where do you live_" we need it for a useful location and the hosting location to show where you're hosting (as long as hosting location still is a separate thing).

### Locations that this issue is about: 

- Hosting location: https://www.trustroots.org/offer/host 
- Meeting location: https://www.trustroots.org/offer/meet/add
- Profile: _Where do you live_: https://www.trustroots.org/profile/edit/locations

Edit: Implement something like this: https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by topalavlad** [comment]
I'd like to give this feature a try this week. I found this [leaflet plugin](https://esri.github.io/esri-leaflet/examples/search-map-service.html) that seems good ([60KB minified](https://bundlephobia.com/result?p=esri-leaflet@2.2.3)). 

It doesn't have street numbers compared to Google Places API, but it doesn't need an account, API key but finds streets even in my small home town and seems free regardless of the number of searches.

Any opinions on this?

**Comment by Regenwasser** [comment]
The demo that you linked to makes it seem like it does support house numbers in the major cities that I've tested (Germany, France, Spain)? What it doesn't seem to do is points of interest, like for example parks.

It's also doesn't recognize things if you don't enter them the way it expects you to. e.g a London address (where they don't have house numbers): "Hamilton House, London E3 4NL, UK" doesn't find a location.

But I guess that's due to limited info of OSM. Algolia has the same problem - https://community.algolia.com/places/ (again limited free usage - but also very good UX wise).

You'd want someone else for dev feedback, but otherwise it looks like this would be a huge improvement regardless (that we urgently need to tackle other issues). Thank you.

**Comment by simison** [comment]
@topalavlad this one needs to be expanded to support addresses and other info:

https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/modules/core/client/services/location.client.service.js#L114-L188

API Docs: https://www.mapbox.com/api-documentation/#geocoding

**Comment by simison** [comment]
See also `tr-location` directive and check where it's used: https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/modules/core/client/directives/tr-location.client.directive.js

**Comment by topalavlad** [comment]
Easiest fix seems to be removing `'&types=' + (types || 'country,region,place,locality,neighborhood')` from the query which makes it return POIs, streets and other objectives also. The only other change is using one point to move the map instead of 2 point bounds.
I did this and it works better than with the restricted types but there still are streets and objectives that are not found.

Does any one want to give it a try - [search playground](https://www.mapbox.com/search-playground/) and see if we're good with the result?

**Comment by simison** [comment]
Types is needed for `from` and `living` inputs, as those shouldn't contain addresses but cities or countries.
