### ISSUE TITLE
Show "no profile found" for missing & deleted profiles

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#669]
https://www.trustroots.org/profile/abcdefdoesnotexist
<img width="740" alt="image" src="https://user-images.githubusercontent.com/54728/44954004-314c1100-ae9c-11e8-99a4-e78cccce6f83.png">

it would be nice to have some more verbosity when a profile is not found

**Comment by Regenwasser** [comment]
There's a [404 page](https://www.trustroots.org/not-found ) that you get forwarded to in other cases.

![image](https://user-images.githubusercontent.com/1645834/44954584-60668080-aea4-11e8-993f-e6a6d8f78f28.png)

We can just use one in both cases, but it would be good to keep the navigation header in place (the current 404 doesn't have it).

**Comment by simison** [comment]
Seems like a regression, since "no profile found" has been there before:

https://github.com/Trustroots/trustroots/blob/c820c66fe921c9470f4ec71393b5a96b162d8fa2/modules/users/client/views/profile/profile-view.client.view.html#L80-L88

**Comment by guaka** [comment]
Looks like `profile-view.client.view.html` isn't even loaded on profile 404s.
When setting `ng-if="true"` I see the alert on existing profiles, but not on /profile/doesntexist

Note I do get these warnings for non-existing profiles, and not for proper profiles:
```warn: CSP violation report #ljeanw report={"csp-report":{"blocked-uri":"","document-uri":"http://localhost:3000/profile/doesntexist","line-number":1,"original-policy":"default-src http://localhost:3000; script-src 'unsafe-inline' 'unsafe-eval' http://localhost:3000 http://*.facebook.com http://*.facebook.net http://*.fbcdn.net http://*.twitter.com http://*.google-analytics.com http://*.gstatic.com http://*.addthis.com http://*.addthisedge.com http://maitreapp.co http://ajax.googleapis.com 'nonce-da780012-9d5e-4539-9c7e-f924be676d85' ws://localhost:35729 http://localhost:35729; font-src http://localhost:3000 data:; style-src http://localhost:3000 'unsafe-inline'; img-src http://localhost:3000 http://*.tiles.mapbox.com http://api.mapbox.com http://*.tile.openstreetmap.org http://*.vis.earthdata.nasa.gov http://*.facebook.com http://*.fbcdn.net http://*.fbsbx.com http://*.twitter.com http://*.google-analytics.com http://*.gstatic.com http://*.googleusercontent.com http://*.g.doubleclick.net http://gravatar.com http://i0.wp.com http://i1.wp.com http://i2.wp.com http://ucarecdn.com data:; connect-src http://localhost:3000 http://maitreapp.co http://api.mapbox.com http://fcm.googleapis.com ws://localhost:35729 http://localhost:35729; object-src http://localhost:3000; media-src http://localhost:3000; form-action http://localhost:3000 http://trustroots.us9.list-manage.com; frame-ancestors 'none'; child-src http://localhost:3000 http://*.twitter.com http://*.facebook.com http://*.addthis.com http://*.addthisedge.com; base-uri http://localhost:3000; report-uri http://localhost:3000/api/report-csp-violation","referrer":"","script-sample":"// Promises \nvar _eid_promises = {}; \n//...","source-file":"http://localhost:3000/profile/doesntexist","violated-directive":"script-src"}}```

**Comment by simison** [comment]
@guaka that's probably unrelated and sounds like one of your browser extensions is attempting to insert some JS onto the page.

**Comment by guaka** [comment]
I removed "good first issue" and "easy", because it's not :)

**Comment by simison** [comment]
Fixed in https://github.com/Trustroots/trustroots/pull/720

Now it looks like this:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/87168/47269900-a5399a00-d56c-11e8-98f2-b746e9f09bca.png">
