### ISSUE TITLE
admin tool: user masquerading

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#670]
**Is your feature request related to a problem? Please describe.**
Sometimes people complain they didn't get replies, I'd like a simple admin tool that can give me insights in what's happening. I.e. see the messages this person has sent to which specific profiles.

This also requires an "admin" flag. (This could be done through a (mostly) hidden tribe.)

Couchsurfing had masquerading functionality (that also allowed seeing messages). This could be a good way to handle these things generically.
Of course it's good if all these actions are logged somewhere.

Another issue is that people sometimes encounter very specific bugs, e.g.

> I cannot change my hosting status, nor my location. When I attempt it (my profile -> start hosting travelers or changing status), I get taken back to the login page, and asked for username and password. The same happens from my Android phone, chrome or firefox browser on PC.
> I guess the problem could come from the fact that my current city is set to '?' (since I was homeless, traveling for 3 years). However, if I try to change my location, I also get taken back to the login page. How can this be solved? Could you try changing my location to XXXXXX, to see if that solves the problem?

In such cases it would be very useful to log in as them, check what's up and possibly even fix it right away.

**Describe the solution you'd like**

Allow site administrators (or anyone with enough permissions) to switch users and surf the site as that user (no password required). That person can switch back to their own user account at any time.

Ideally all masquerading actions are logged in the database.

**Describe alternatives you've considered**
TINA.

**Additional context**

See e.g. https://www.drupal.org/project/masquerade

Add links to discussion on Slack (or Discourse).

**Comment by guaka** [comment]
Related to this, it would be good to build a tool that (automatically) analyses what type of messages get replies (and from which sort of members). 
E.g. question to ask: is maybe vs yes relevant for reply rate?

**Comment by chreekat** [comment]
This sounds the job for a log analyzer, would you agree? I haven't spent
much time with them, but I've had the likes of Kibana recommended to me,
and something called "the ELK stack".

**Comment by guaka** [comment]
A log analyzer can't do this job. @chreekat I updated the issue description to make myself clearer.
