### ISSUE TITLE
Ask for password on 'delete user profile' request

### ISSUE THREAD

**Issue by trmendes** [Trustroots/trustroots#674]
Trustroots should ask the user the password whenever the button "delete my profile" is pressed.  This will help to prevent  the case (or make it harder to delete) where the user left the computer unlocked and logged in into the email and trustroots account.

Right now, the way TR deal with that request is: TR sends an e-mail with a link to confirm the user request and only after the user follow that link the profile will be deleted.

**Comment by simison** [comment]
Thanks for this!

If they have access to their email, they also have access to the password in a form of a password reset email, no?

Do other profile removals in other sites ask for the password?

**Comment by trmendes** [comment]
Yes! They will have and that is why I wrote (or make it harder to delete). If they have access to email and trustroots and they need a password to delete they will have to first logout trustroots to then ask for a new password. After that, set a new password, login and then try to delete tha profile again. Way harder, right? (but doable)

I normally delete accounts on sites I don't use anymore and most of them are asking for a password to delete the account.
