### ISSUE TITLE
iOS safari: most of "back to map" button is hidden

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#675]
when viewing profiles on mobile safari (iOS) most of the "back to map" button is hidden

(also in expo.io on iOS)

![file](https://user-images.githubusercontent.com/54728/45017374-c2032800-b027-11e8-973b-d1c6349e4858.jpg)

**Comment by simison** [comment]
The same with desktop safari:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/87168/45017624-bd8f3d00-b030-11e8-99de-6124f95a0e18.png">

**Comment by guaka** [comment]
should look like this (from desktop firefox)

<img width="332" alt="image" src="https://user-images.githubusercontent.com/54728/45017650-64bba680-b028-11e8-84ba-dbab783124f1.png">

**Comment by guaka** [comment]
problem is here: https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/modules/search/client/less/sidebar.less#L185

**Comment by guaka** [comment]
`position: absolute;` is already better but I don't think it's intended like this:

![image](https://user-images.githubusercontent.com/54728/45028210-7448e880-b044-11e8-9b45-64a46543ce86.png)

**Comment by guaka** [comment]
could it help to upgrade bootstrap?

**Comment by simison** [comment]
I don't think it's related to Bootstrap — it's some simple CSS quirk and prolly quick to fix — I'll look into it tonight. :thumbsup:
