### ISSUE TITLE
internet gone when sending a message: message should be retained

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#683]
reproduce:
- go to https://www.trustroots.org/messages/guaka
- write a nice message
- internet disappears
- message is gone

ideally:
- message stays visible until it actually arrived at server
- message is kept in local

**Comment by simison** [comment]
:thumbsup: Message is already kept in sessionstorage during writing so just needs some logic adjustments for when to clear it out.

**Comment by guaka** [comment]
Ah, right... I had opened the thread in another tab, then the message was gone.
Now I refreshed the original thread and the message came back.

Yeah, I'd prefer to see the message twice than seeing it not at all. When on slow connections I often saw the message disappear and only show up a minute later (not nice).

**Comment by abustany** [comment]
argh this just hit me too (error while sending because some stupid captive portal logged me out)... Had I known the message was in session storage, I'd have retrieved it before messing up with the text field again (and erasing the old message this way :'( )
