### ISSUE TITLE
Showing users more info when they are about to ask for a place to stay

### ISSUE THREAD

**Issue by trmendes** [Trustroots/trustroots#685]
I know it might sound a bit complicated but having a look at CS I see that are people who use their profile page to send messages to those who might want to ask for a place to stay.

Some people would write down things like "I can't host couples" or "I can't host boys". Some people write down long messages about what they expect from their guest. Some of them even made me feel like they are tired of dealing with some culture differences and some would even write on caps things like "please, be sure you read my profile before send me a message".

The thing is: If the person don't read the profile that person will never reach any part of the text that says: "please read it before send me a message".

CS has a page where you can write down some rules you have when hosting people but I'm not sure if they do anything with that info.

It would be nice if TR could have this kind of 'hosting "rules"' profile too where people could write down what are they expecting from their guests.

Having that profile TR could show it to any user that is thinking about send that person a message. Like "Before you ask for a place, this host wants you to read and agree on this"...

This could be an optional feature for those who wants to host people.

This is just an idea and I want to hear from you what do you think about it. If it is a good idea or not...and if it is how can we make it better...:)

**Comment by chreekat** [comment]
This makes me think of "pull request templates"!
