### ISSUE TITLE
Profile avatar

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#7]
- [x] Show Gravatar
- [x] Show Facebook profile pic
- [x] Upload your own
- [x] Choose which one to show (default to Gravatar)

**Comment by simison** [comment]
At master branch there's now uploading avatar -feature. Grande merci schön for @Remigr! Please, some testing for this would be awesome! (@guaka)

You'll need to migrate your DB, install some new dependencies etc. You can just run `sh ./scripts/update.sh`.

For me `migrate` command didn't work (on OSX) right away. I had to have that package globally installed: `npm install -g migrate`. Then run `migrate` again. Read more from [troubleshooting](https://github.com/Trustroots/trustroots/wiki/Troubleshooting#my-database-is-not-up-to-date-with-model) ("my database is not up to date...")

**Comment by roberts-gh** [comment]
![dog_smile](https://cloud.githubusercontent.com/assets/290852/5688693/6f5af594-9828-11e4-90a0-fb556deaff7e.jpg)

**Comment by guaka** [comment]
testing this on dev.trustroots.org, here's what happens:
* I get an image not found (without any image)
* I go to https://dev.trustroots.org/#!/profile/guakatest/edit
* upload .jpg
* new image not showing up
* refresh gives error: 
```
 Error: Error setting TTL index on collection : sessions
    at /srv/trustroots/node_modules/connect-mongo/lib/connect-mongo.js:169:23
    at /srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1459:28
    at /srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1605:30
    at /srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:169:22
    at Cursor.nextObject (/srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:744:16)
    at Cursor.toArray (/srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:168:10)
    at fallbackListIndexes (/srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1604:65)
    at /srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1615:20
    at /srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1153:22
    at /srv/trustroots/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
```
* now image still is set on Gravatar (which doesn't exist for the email address I use here)

**Comment by simison** [comment]
Aha, yea so it does crash at some point. Might be any of these or something else:

- Perhaps dev DB isn't migrated for the feature yet.
- Folder lacking write access
- Folder doesn't exist
- Some NPM package not functioning

(TTL error is due mongo not being up while the Node app is already running, I need to copy a fix for that from mean.js master but it's unrelated.)

Sorry I haven't got time to check this in detail & push to production, but soon soon. :-)
