### ISSUE TITLE
Username reminder

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#70]
"I forgot my username" -page.

- Type in email
- It sends your username to your email
- Can be copied largely from "forgot my password" controllers/views

**Comment by guaka** [comment]
Isn't it simpler to allow password retrieval (and login) through email and also send them their username? That would cover the case where someone forgot their username.

**Comment by simison** [comment]
:+1: #50

**Comment by roberts-gh** [comment]
(+1 to login with email address, not username)
