### ISSUE TITLE
down for maintenance when opening a couple of tabs

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#701]
I often get "Unfortunately Trustroots is down for a bit of maintenance right now." when opening a bunch of tabs. This shouldn't happen.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/54728/46865169-cd165880-ce1c-11e8-93f1-e028fb338957.png">

**Comment by thefifthisa** [comment]
Hey @guaka, I'd like to look into this! Do you mind giving more context on when the issue occurs? I can't seem to reproduce it.

**Comment by guaka** [comment]
here's how I can reproduce it:
- go to the contacts of a profile with a lot of contacts, e.g.
https://www.trustroots.org/profile/mikael/contacts
- open 7 of those contacts

**Comment by mrkvon** [comment]
API returns status `503`. Sounds like hitting a rate limit (too many requests in too little time).

This is a response body
```html
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by simison** [comment]
Yap, you're hitting rate limits configured in Nginx.

I've just adjusted them a bit so this should happen less likely now.

Let me know if you hit these issues again!
