### ISSUE TITLE
Get location from device for setting location

### ISSUE THREAD

**Issue by Akronix** [Trustroots/trustroots#703]
When the user wants to set the location for hosting/meeting/living/being from locations there should be the feature to get the device location and populate that field.

**Comment by Regenwasser** [comment]
Thanks for opening this issue. Yes, a locate me / use my location button to get the address or just a icon would already be very helpful here.  

Maybe whoever can tackle this can also expand the autocomplete for addresses and search terms (#668) at the same time.

_____
If anyone needs help in the design message me on Slack (@rooting) or add the "[Needs] Design" label, so someone will suggest something.

**Comment by Regenwasser** [comment]
This and #668 are solving the feedback of #76. (Now closed).

**Comment by rumwerfer** [comment]
Closing in favor of #126. Please reopen if I misunderstood and it's not the same issue.
