### ISSUE TITLE
open locations with other apps

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#704]
When I'm using TR on my phone I'd like to open locations with mapping applications.

See https://en.wikipedia.org/wiki/Geo_URI_scheme

**Comment by guaka** [comment]
geo:37.786971,-122.399677 doesn't work with Chrome and Firefox on my macbook. On Safari on iPhone it takes me to the "Go Map!!" app without letting me choose. So Geo URIs are probably not a good way to do this.

**Comment by guaka** [comment]
At least the hosting location.
But the hosting location is a bit randomized, so it's actually a bit
trickier than just turning that location into a link.

**Comment by simison** [comment]
Looks like there's "uncertainty" support for this schema:

> The geo URI also allows for an optional "uncertainty" value, separated by a semicolon, representing the uncertainty of the location in meters, and is described using the "u" URI parameter.[1] A geo URI with an uncertainty parameter looks as follows:
>
>    `geo:37.786971,-122.399677;u=35`

In our case this would be 200 meters: https://github.com/Trustroots/trustroots/blob/5e15aa47987fd335fba4fb98aaf5503cec3e73b9/modules/offers/server/models/offer.server.model.js#L32-L37

**Comment by simison** [comment]
This could be an extra button next to "bigger map" button in profiles:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/87168/46907210-cddfe500-cf17-11e8-8ac9-70a7056f9b97.png">

Label could be e.g. _"Open in device"_ or something non technical that indicates that device's default app will open the location (and we don't know if it's computer or mobile, remember).

**Comment by guaka** [comment]
@topalavlad let's see, once we manage to get an iOS app it's not that strange to differentiate geo links based on OS https://github.com/Trustroots/trustroots-expo-mobile/issues/10

**Comment by simison** [comment]
On the web app (this repo) we should abide by standards ([`geo:`](https://en.wikipedia.org/wiki/Geo_URI_scheme)) and let OS or applications decide how to handle it.

Inside the ReactNative wrapper, we can indeed change things around depending on the platform.

**Comment by simison** [comment]
`ng-href` should do the trick :thumbsup: 

Do you think you could concentrate directly in the template?
```
ng-href="geo:{{ trOfferHost.offer.location[0] }},{{ trOfferHost.offer.location[1] }};u=200"
```

https://docs.angularjs.org/api/ng/directive/ngHref

**Comment by simison** [comment]
Let's hide this on big screens for now, good idea. :thumbsup:

**Comment by topalavlad** [comment]
I deleted my comment to rewrite it but you were quicker.

> `ng-href` should do the trick 👍 https://docs.angularjs.org/api/ng/directive/ngHref
I did use `ng-href` initially but it kept adding `href` starting with `unsafe`. Finally figured out I had to whitelist Geo URIs: `$compileProvider.aHrefSanitizationWhitelist(/^geo:.*/);`

For hiding on big screens, do you guys already have a way of telling it's a mobile browser? (I only found the native app one).
If not, what do you guys think about using leaflet's way:
`var mobile = typeof orientation !== 'undefined' || userAgentContains('mobile');`?

**Comment by simison** [comment]
I like the leaflet way 👍  Good finding!
