### ISSUE TITLE
Reply via e-mail

### ISSUE THREAD

**Issue by doktorhorst** [Trustroots/trustroots#715]
It would be very convenient if you could reply to a TR message by replying to the notification e-mail.

Warmshowers does this and it's great. I guess this is a lot of work though, but maybe for some time in the future.

**Comment by simison** [comment]
Yep, this one is definetely "would be nice" but it's not trivial and thus it's hard to justfity time spent on it vs other enchantments.

I'll keep the previous issue (https://github.com/Trustroots/trustroots/issues/163) about this open and close this one as a dublicate. 

Thanks for the feedback!

**Comment by doktorhorst** [comment]
Oh, somehow I couldn't find the previous issue. It's definitely not as important as other stuff
