### ISSUE TITLE
Message of "Unknown member" can neither be read nor deleted

### ISSUE THREAD

**Issue by Anth0rx** [Trustroots/trustroots#726]
I have a message of an "Unknown member" (probably a deleted account?). Unfortunately this message can neither be read nor deleted and as such always appears as unread.

Related to #596

**Comment by guaka** [comment]
We have this pull request to fix that: #633 
Wanna test/comment?

**Comment by simison** [comment]
Thanks, I'll close this one so that we can track this at #596 since essentially same fix will solve both problems.
