### ISSUE TITLE
Show user's tribes on its own tab at the profile

### ISSUE THREAD

**Issue by petr-hajek** [Trustroots/trustroots#728]
URL `/profile/username/tribes` does not display any data.

This needs to be implemented in order to have a page to display all tribes of an user in case we want to limit number of tribes displayed in the basic profile view: #404 

Tribes link should be displayed in the navigation panel next to Contacts (in case the user is member of any tribe)

**Comment by simison** [comment]
Here's illustration where the tab should be:

![image](https://user-images.githubusercontent.com/87168/47254067-20178d80-d465-11e8-9c42-ff43987ac25d.png)

**Comment by simison** [comment]
Yeah, that already happens on 320px wide screens (e.g. iPhone 5S) even without extra tab. :-/

https://github.com/Trustroots/trustroots/issues/741

**Comment by Regenwasser** [comment]
> Or to leave tribes in the Info tab, just collapse it?

Yes, I'd really like that solution a lot more. I don't really see a strong justification for adding an extra tab and making the navigation more complicated for it that has little info in it (and is partly a duplicate of the overview).

Also, with how many people that other site would actually show extra info? What's the percentage of over 5 or over 10 tribes?  

Regardless, we could also solve this problem by just differently showing it in the profile, so it doesn't take up as much space.

**Comment by petr-hajek** [comment]
Fair enough, I agree. I originally created because /profile/username/tribes was mentioned in #404 butwe can just change AC for that one.

**Comment by simison** [comment]
This might become more relevant once there are more tribes. At that point, it's less of a _"short list of my interests"_ and more like something that users can discover through other profiles.

**Comment by simison** [comment]
There might some leftover code in user-profile controllers/views/styles that should be cleaned out. This tab was originally planned when we launched tribes a while back.
