### ISSUE TITLE
sticky footer over the top of some links

### ISSUE THREAD

**Issue by rdoc101** [Trustroots/trustroots#73]
Quite often on pages the footer is covering very important links and you can not click on them. 
To reproduce easily just go on https://www.trustroots.org/#!/ ie signup page, and set screen resolution to 320 * 480 (i found this by being on my useless mobile, but then came across the same problem on different pages on my normal laptop screen.). Here the sticky footer covers too many links. I'd just not have it being sticky....

**Comment by simison** [comment]
Needs testing:
- [ ] login
- [ ] password reset
- [ ] welcome page after signup
- [ ] signup
- [ ] confirm changed email
- [ ] confirm friend connection
- [ ] front page
