### ISSUE TITLE
Collapse the Tribes section in search

### ISSUE THREAD

**Issue by petr-hajek** [Trustroots/trustroots#730]
As the number of Tribes is growing and new filters are added, it'd be useful to be able to collapse the whole section in the Search>Filter by clicking on the Tribes header. Especially when using TR on a device with smaller screen.

**Comment by danidanitr** [comment]
We came up with this:

**1/ My tribes**
- No search form = So people only select the tribes they really feel part of and then filter only with these
if we were to add a search form here, then we lose the idea of people only selecting the tribes they really want to. So no search form here.
![tribes_1](https://user-images.githubusercontent.com/43136016/47291933-cbf7df00-d605-11e8-83e0-5b6c3c43bf0c.jpg)

**2/ All tribes**
- It is going to be listed from most popular to less popular (we thought this doesn't even have to be mentioned, any listing in others websites shows relevant items first.
- Search form = Here yes. If there are 100 then searching the one you want will be easier
![tribes_1_1](https://user-images.githubusercontent.com/43136016/47291935-cd290c00-d605-11e8-9079-34cf1c8ca6d8.jpg)

_If in the future there are many many many tribes then we can add alphabetical filter, popular filter and others. For now like this works._

Clear tribes = does the same job, bringing filter to zero.
