### ISSUE TITLE
Semicolon rule is not enforced in eslint

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#731]
Currently, no eslint rule for semicolons is enforced.

Could be fixed with a rule `semi: [2, 'always']` in `.eslintrc.js`.

The rule `always` seems to have existed in the past. Currently it yields less than 10 errors in master.

[related eslint docs](https://eslint.org/docs/rules/semi)

**Comment by krisgardiner** [comment]
Would love to tackle this :) #732

**Comment by mrkvon** [comment]
Fixed via #737
