### ISSUE TITLE
Notification dialogue displayed with each login

### ISSUE THREAD

**Issue by petr-hajek** [Trustroots/trustroots#745]
When I log in, notification dialogue is displayed. No matter what I select, it shows up during the next log in.
![image](https://user-images.githubusercontent.com/38785076/47258981-87ecc900-d4a3-11e8-824b-384a32b0b346.png)

**Comment by guaka** [comment]
May be related to https://github.com/Trustroots/trustroots-expo-mobile/issues/12

**Comment by simison** [comment]
Thanks for the report! It's been a bit hard to replicate this at my end.

@petr-hajek could you write down:
- browser + version
- if you have any privacy extensions that might change how cookies and local storage behave
- If you've changed browsers cookie/session/local storage settings from defaults

**Comment by simison** [comment]
Dublicate of: https://github.com/Trustroots/trustroots/issues/585
