### ISSUE TITLE
Update Agenda, background job worker from v1 to v2

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#754]
[Agenda](https://github.com/agenda/agenda) v2 was a complete rewrite to support promises instead of callbacks.

Agenda is run in the background worker to process jobs. Main app and the worker run separately in parallel with `npm start`.

v2 changelog: https://github.com/agenda/agenda/blob/master/History.md#200--2018-07-19

Rewrite needed mainly at:
- Worker entry script: https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/config/lib/worker.js
- At bunch of `modules/*/server/jobs/*.server.job.js` -files

I'm not sure if we should wait for ES5 → ES6 migration before updating Agenda, because we could jump directly using `async/await` -format (that we don't support at the moment).

**Comment by mrkvon** [comment]
Do we already have an issue about the migration ES5 -> ES6+? It's been coming up on different occasions.

It will need a change in linter and some period in which it will be ok to write the code in ES 2017.

The `./eslintrc` may [need `{ "parserOptions": { "ecmaVersion": 8 } }`](https://eslint.org/docs/user-guide/configuring#specifying-parser-options) for support of `async/await` syntax. I don't know how this will affect Angularjs code. By this action we'll also drop support for older versions of nodejs. I.e. [prior to 9.11.2](https://node.green/#ES2017). If we target ES2018, (`"ecmaVersion": 9`), we'll need [nodejs v10.3.0+](https://node.green/#ES2018)

**Comment by simison** [comment]
@mrkvon opened one here to keep track of ES6 migration: https://github.com/Trustroots/trustroots/issues/804
