### ISSUE TITLE
Add more data to daily snapshot statistics

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#755]
Add daily snapshot statistics for:

- Percentage of members [by gender](https://github.com/Trustroots/trustroots/blob/ecf0049f25fdb43aef82c480df204800f2c0639b/modules/users/server/models/user.server.model.js#L144-L148)
    - This is useful to follow if we have "gender gap" and if it's changing over time.
    - If we can recognise that there is a gender gap; we can follow if we're fixing it.
- Thread references. Folks can give "no" or "yes" reply to message threads:
    <img src="https://user-images.githubusercontent.com/87168/47271111-d8385980-d57d-11e8-9903-b1247f6b21a0.png" width="200"> 
   We're interested in following a percentage of negative replies from a number of message threads. Could be useful to group this by "total", "month" and "week" (i.e. limit to only references given in the past N days) to see if there are spikes since total % tends to stay pretty stable.  [See Mongoose schema](https://github.com/Trustroots/trustroots/blob/ecf0049f25fdb43aef82c480df204800f2c0639b/modules/references-thread/server/models/reference-thread.server.model.js)
- Number and % of people who joined a circle, or different number of circles ([example data snapshot](https://ideas.trustroots.org/2020/06/20/new-tribes/#comment-132))

---

#### Technical guide

In [`modules/statistics/server/controllers/statistics.server.controller.js`](https://github.com/Trustroots/trustroots/blob/ecf0049f25fdb43aef82c480df204800f2c0639b/modules/statistics/server/controllers/statistics.server.controller.js) we have methods for each stat.

In [`modules/statistics/server/jobs/daily-statistics.server.job.js`](https://github.com/Trustroots/trustroots/blob/ecf0049f25fdb43aef82c480df204800f2c0639b/modules/statistics/server/jobs/daily-statistics.server.job.js) we run a daily job to store these to Influx DB.

Stats are stored in [InfluxDB](https://portal.influxdata.com/downloads) so you'll likely need to set up and [configure](https://github.com/Trustroots/trustroots/blob/ecf0049f25fdb43aef82c480df204800f2c0639b/config/env/local.sample.js#L28-L41) one at your dev machine. We'll be pulling these stats out to Grafana (https://grafana.trustroots.org/).

One PR doesn't need to add everything; it's easier to review if one PR adds one new stat.

**Comment by simison** [comment]
@guaka:

>Thread references. Folks can give "no" or "yes" reply to message threads:
>We're interested in following percentage of negative replies compared to number of message threads

Anything else would useful to know about this? Group them by user ID somehow?


Some useful snapshot statistics about `seen`, `updated`, `created` vs time right now? Any ideas? Would be nice to have something that's not always just trending upwards because number of members is _always_ going to trend.

https://github.com/Trustroots/trustroots/blob/a6f5ae3864125a134f60c06f69003e8f501b0c91/modules/users/server/models/user.server.model.js#L225-L235

Anything else we want to snapshot-measure?

**Comment by simison** [comment]
There's a good start for last-seen stats at https://github.com/Trustroots/trustroots/pull/616 by @trmendes

**Comment by guaka** [comment]
can we do some of these:
- number of pages visited per person?
- time spent on the website?
- when we launch references it'll be great to have stats about this: #718 


---------------

Ideally our future awesome metrics will be somehow related to:
- positive real life experience (time or number of) vs time spent on the website/app
- positive real experience time vs negative real life experiences

So we should know whether an experience is positive or negative after someone enter data #718.

(These metrics are in sharp contrast to FAANG that are optimizing to keep people on their website/app. https://humanetech.com/)

**Comment by guaka** [comment]
Another metric I thought that will be important: the percentage of members in the hitchhiking tribe.
If we want to be a social network for not just hitchhikers this number should go down to <10% at some point.

**Comment by simison** [comment]
> the percentage of members in the hitchhiking tribe.
> If we want to be a social network for not just hitchhikers this number should go down to <10% at some point.
> 


Very cool idea!

**Comment by guaka** [comment]
Another one: I'd like to see how much specific tribes are growing, especially https://www.trustroots.org/tribes/families
