### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#757]
See https://github.com/Trustroots/trustroots/community

@simison does it make sense to add a `PULL_REQUEST_TEMPLATE.md`?

**Comment by simison** [comment]
Example: https://github.com/Automattic/wp-calypso/blob/c7a9a576b270594d2fc417121f729026aece7a5d/.github/PULL_REQUEST_TEMPLATE.md

**Comment by sionelt** [comment]
I'll take this easy one :)
