### ISSUE TITLE
Expose email hash from API only for Gravatar users

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#764]
Expose email hash from API only for Gravatar users.

**Comment by simison** [comment]
See `avatarSource` and `emailHash` from https://github.com/Trustroots/trustroots/blob/1840ab1480c67104f804f952fdeeb37af06f07c3/modules/users/server/models/user.server.model.js

`emailHash` should be exposed from API only when `avatarSource=gravatar`
