### ISSUE TITLE
allow HTML in tribe descriptions

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#768]
(even better: markdown :)

see e.g. https://www.trustroots.org/tribes/hitchhikers - it'd be good to have a link to Hitchwiki

**Comment by topalavlad** [comment]
It's only admins that modify the tribe descriptions, right?
I would go with markdown. Do you guys already have a good library in mind? There aren't many options for versions before angular 2.

1. [ng-showdown](https://github.com/showdownjs/ng-showdown) - based on [showdownjs](https://github.com/showdownjs/showdown) which seems still actively maintained
2. [ng-marked](https://github.com/Hypercubed/angular-marked) - based on [markedjs](https://github.com/markedjs/marked) which is supposed to be faster
3. [ngx-markdown](https://github.com/jfcere/ngx-markdown) - seems like the most up to date and well maintained but I doubt it's compatible with `Angular 1.5.11`. Couldn't find compatibility list, but it's most likely 2+

Opinions?

**Comment by simison** [comment]
Let's not add Markdown for this; it'll add a huge bunch of `kb`s of JS to bundle for very little gain.

Updating descriptions to support HTML in https://github.com/Trustroots/trustroots/pull/777

**Comment by guaka** [comment]
Would it be possible to handle the markdown server side? And thus not
increase the bundle?
