### ISSUE TITLE
tribes/*: overlapping text with big fonts

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#769]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/54728/47508552-9c024300-d874-11e8-9ba9-de3ea1bec25f.png">

https://www.trustroots.org/tribes/hikers

**Comment by kndarp** [comment]
Hi!
I'd like to contribute to this issue.

**Comment by humphriescarly** [comment]
Hi @kndarp,
I am really sorry - this is my first pull request and I didn't realize I needed to comment on the issue. Just refreshed and saw I'd stepped on your toes.

@guaka - please review and hopefully this does the trick. 

Thanks,
Carly

**Comment by simison** [comment]
@humphriescarly no worries at all! Typically issues are mentioned in PRs so that others can see when there are open ones in the fly. #770 was missing that mention so you could've not known about it.

Congrats for your first PR!!! I'm stoked you decided to do it for Trustroots!
