### ISSUE TITLE
Notify admins when a profile gets 3+ "not in the spirit" downvotes for threads

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#781]
**Is your feature request related to a problem? Please describe.**

We want to ensure that most exchanges of messages stay in the spirit of trustroots.

**Describe the solution you'd like**

When a user profile gets their 3rd downvote a message should be sent to admins (see also #767).

Note that so far only 10 profiles have received 3 or more downvotes.

**Additional context**

see also #780 

ping @Akronix @simison 

https://trustroots.slack.com/archives/C37BHPV6G/p1540716661002600

**Comment by simison** [comment]
Related https://github.com/Trustroots/trustroots/issues/755
