### ISSUE TITLE
Update deprecated Mongoose methods

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#782]
We've upgraded Mongoose to v5 in PR https://github.com/Trustroots/trustroots/pull/659, which deprecated a whole bunch of methods:

See [migration guide](https://github.com/Automattic/mongoose/blob/578a16d4516e666cbb0a3435a127b8396bd9f95c/migrating_to_5.md)

These all should be upgraded.

A good way to see _some_ of these throw warnings is to run test-suite (`npm run server:test`).

These updates don't need to be done in one big swoop — indeed it's easier to review+merge if they're done in smaller sections (e.g. module by module).

**Comment by himanshumehta1114** [comment]
Fixed deprecated warnings. PR made : #785
