### ISSUE TITLE
Set birthdate back to unknown

### ISSUE THREAD

**Issue by doktorhorst** [Trustroots/trustroots#792]
I like the fact that you don't have to enter your birthdate when registering. However, (after trying to reproduce misbehavior from a support message,) I can't set my birthdate back to an unknown date.

Steps to reproduce:
1. Go to https://www.trustroots.org/profile/edit
2. Set a birthdate (if you haven't already) and save
3. Select [Month] [Day] [Year] as birthdate and save

Expected behavior:
Set birthdate (and thus age in the profile) back to *nothing*

Actual behavior:
Switches back to the birthdate from step 2.

Firefox 62, Ubuntu

**Comment by simison** [comment]
Good catch. :thumbsup:

Visually it could be just extra "x" next to date inputs:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/87168/47775905-b49dad80-dcf9-11e8-961d-07f6d530903f.png">

**Comment by topalavlad** [comment]
`undefined` values are filtered and not sent to the server so the birthDate is not overwritten if the selected value is not valid. The easy fix is to set it to null whenever the user selects an invalid date: `ngModel.$setViewValue(null);`

I'll do that but I would also like to add the clear button which seems more user friendly. However, any way I tried to add the button there doesn't get `ng-click` triggered which is very weird. I even copied a whole button tag from other pages and set the action to `ng-click="alert('aaaaa')"` but it never gets triggered. I tried different `type`, different tags.

Did anyone else see this behavior before?

**Comment by simison** [comment]
Okay to do the API part in separate PR first, if there are blockers in adding the UI button.

**Comment by topalavlad** [comment]
> Prolly better not spend too much time on this one. :-)
But curiosity is killing me :(. I'll leave the button be for now.

Changing other fields doesn't change the birthdate, but changing any of the day/month/year will update it to `null` if the value is invalid, compared to the previous behavior where nothing was sent to the backend.
