### ISSUE TITLE
email confirmation for profile deletion

### ISSUE THREAD

**Issue by doktorhorst** [Trustroots/trustroots#798]
A member accidentally deleted their profile.
To avoid this, we could add an one more step for profile deletion:
an email sent out with a link, that must be clicked before the profile is deleted.

**Comment by simison** [comment]
We indeed already send an email.

Curious to why the user thinks they removed it accidentally? It's quite a few steps to take to really remove it.

Steps visually:

<img width="429" alt="screen shot 2018-11-01 at 20 02 07" src="https://user-images.githubusercontent.com/87168/47870088-54019400-de11-11e8-8a0e-d742f9515bd7.png">

<img width="558" alt="screen shot 2018-11-01 at 20 01 55" src="https://user-images.githubusercontent.com/87168/47870091-56fc8480-de11-11e8-9f34-b55f589b5eef.png">

<img width="630" alt="image" src="https://user-images.githubusercontent.com/87168/47870169-90cd8b00-de11-11e8-989d-cdbc1eb21a01.png">

<img width="530" alt="image" src="https://user-images.githubusercontent.com/87168/47870188-9925c600-de11-11e8-97fb-2909f46b562c.png">

**Comment by doktorhorst** [comment]
Oh, reading the support message it seemed as it was only a one-step-thing. Nevermind.
The person wrote something like "I did not want to delete it, I only wanted to confirm it".
I don't think there is a need to further improve this process.

**Comment by doktorhorst** [comment]
PS: This had definitely to do with English not being the (ex-)member's mother tongue. (one reason more to add translations ;) )
