### ISSUE TITLE
link to apk.trustroots.org

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots#799]
Right now, if you want to use the android app without google, you find the link to apk.trustroots.org only hidden in a FAQ entry.
I think it would be cool to include a link on the landing page, maybe not as obvious as the "store links":
![grafik](https://user-images.githubusercontent.com/31466125/47867773-cdde5100-de02-11e8-810e-bfb008a38a3b.png)

**Comment by simison** [comment]
"Other ways to download the app" link would be easier to understand and it can open a modal where we link to a bunch of things, including Fdroid repo instructions.

Visually it could look like in your mockup.

**Comment by simison** [comment]
@rumwerfer I think you might have the technical know-how now yourself too. Just saying' ;-)
