### ISSUE TITLE
Hosting Message actions buttons need some padding

### ISSUE THREAD

**Issue by trmendes** [Trustroots/trustroots#801]
The 3 buttons related to the actions towards a host request need some bottom margin to look better.

![2018-11-02-170322_sway](https://user-images.githubusercontent.com/16507629/47929718-32181800-deca-11e8-9d8d-fff5b32d45d4.png)

**Comment by gizemkeser** [comment]
Hi @simison, I would like to work on this issue

**Comment by gizemkeser** [comment]
I can not reproduce this problem.
It seems ok when I checked. Please see screenshot.
<img width="417" alt="screen shot 2018-11-08 at 22 09 52" src="https://user-images.githubusercontent.com/44727928/48221738-e838a180-e3a3-11e8-8010-2557b41fe3c4.png">

**Comment by simison** [comment]
Hmm @trmendes which browser was this on?

**Comment by trmendes** [comment]
Hi @simison. Firefox. To simulate it you will have to change the size of your firefox window. At some sizes it happens and at others it does not happens.

**Comment by gizemkeser** [comment]
Hi @trmendes I tested by changing the size of window but could not reproduce on Firefox either. 

![screenshot from 2018-11-16 23-40-46](https://user-images.githubusercontent.com/44727928/48646488-0e8cbb80-e9fa-11e8-82b7-8e3c94eda881.png)
