### ISSUE TITLE
ES6 migration

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#804]
For better developer experience, we should upgrade the codebase to ES6.

Some notes:

- [x] Update `eslint` config to support ES6 env (done): 
   - [x] we might need to run two separate configs for different sections of the application for a short while. That's far from ideal so we should keep boundaries of ES5/6 as clear as possible (e.g. clientside/serverside).
   - [x] For easier management of different eslint configs, move eslint out from Gulp: https://github.com/Trustroots/trustroots/pull/990
- [x] Add Babel to Webpack build to transpile code back to ES5 for client-side files. (done)
   - Our Angular1 eslint rules might need attention at this point
- [ ] Do swipes of basic ES5-to-ES6 updates either with codemods (https://github.com/5to6/5to6-codemod) and/or with `eslint --fix`.
   - Smaller the PRs the easier it's to review/test/merge.
   - Good boundaries for each PR might be app modules as well as clientside/serverside. Serverside changes should probably go in first because that will work out of the box while clientside will need transpiling.
- [ ] Add Prettier for automated code formatting to keep ES5 and ES6 codebases more aligned and just generally for developer happiness (issue #858, PR #932)

**Comment by simison** [comment]
FYI @nicksellen who might have experience from this and @mrkvon who I know is super excited about this as well. :-)

**Comment by nicksellen** [comment]
I think this can be closed, now https://github.com/Trustroots/trustroots/pull/1126 is merged :rocket: 

(the open prettier topic has it's own issue)
