### ISSUE TITLE
Replace the custom request validation with a validation library/middleware

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#807]
We need to validate user data in requests effectively.

Code like https://github.com/Trustroots/trustroots/pull/723/files#diff-06592c03aca32c259b68a91d2caef34dR17 is reinventing the wheel. Such a refactor will be useful elsewhere, too. (where?)

I'm a fan of json-schema, but others will do, too.

**Comment by nicksellen** [comment]
Could consider integrating https://v4.loopback.io/ and implementing new API endpoints using that. It's still got express underneath it all, so _maybe_ it possible to just slot into existing site with some wrangling. It uses json-schema and [ajv](https://www.npmjs.com/package/ajv) internally.
