### ISSUE TITLE
Question mark as a living location crashes the app

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#814]
Setting "living location" (via https://www.trustroots.org/profile/edit/locations) to contain `?` will cause redirects to login page each time user attempts to edit it again.

This is because the input attempts to load suggestions from Mapbox with URL like:
```
https://api.mapbox.com/geocoding/v5/mapbox.places/?.json?access_...
```

That `/?.json` bit will cause Mapbox API to return 401 unauthenticated and our app thinks _our_ API returned unauthenticated, assuming the user is no more logged in and throws them to the login page.

There are a few fixes around this, any of them will fix this issue but all of them should be made:

- [ ] We shouldn't be querying Mapbox by just rendering those inputs on screen. We should call them only when input actually has changed.
- [ ] We shouldn't query Mapbox with `?` in the value (good to check what happens with `&`, too). - 
- [ ] We shouldn't be querying Mapbox with one character long values at all
- [ ] _Unauthenticated_ interceptor should care only about URLs pointing to our domain, not elsewhere:
    https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/modules/users/client/config/users.client.config.js#L13-L23

**Comment by mrkvon** [comment]
`encodeURIComponent` might be useful somewhere in the process

**Comment by mrtmrtmlck** [comment]
I would like to work on this issue 😊

**Comment by simison** [comment]
@mrtmrtmlck Sure! Each task listed here could be their own PR for easier review and merging.

**Comment by mrtmrtmlck** [comment]
@simison locationService.suggestions doesn't work in my local since Mapbox environment variables are empty. Could you please help me ?

**Comment by simison** [comment]
Good question! In the file `config/env/local.js` you should have Mapbox section that you can uncomment and get Mapbox rocking. 👍  If you don't have it there, you should find it from `config/env/local.sample.js` at least.

**Comment by mrtmrtmlck** [comment]
@simison One more question 😊 What is the exact difference between 1. and 2. solutions ? Could you please explain the first solution a bit more ("We shouldn't be querying Mapbox by just rendering those inputs on screen...") ?

**Comment by mrtmrtmlck** [comment]
@simison Related to my above question, I noticed that when refreshing the page it sends a request mapbox api. You mean it should only send request when input changes. 

Related to "We shouldn't be querying Mapbox with one character long values at all", I noticed that location input directive has typeahead-min-length = 3 by default. So, it doesn't query mapbox api less than 3 characters. Should I still validate input length in LocationService in case of it is called by somewhere else ?

**Comment by simison** [comment]
>Could you please explain the first solution a bit more ("We shouldn't be querying Mapbox by just rendering those inputs on screen...") ?

Yeah, exactly like you wrote:

>I noticed that when refreshing the page it sends a request mapbox api. You mean it should only send request when input changes.

When I open https://www.trustroots.org/profile/edit/locations , I can see two queries done Mapbox API:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/87168/48159452-e6a4a600-e2dd-11e8-8754-cc4bfbb7a5f6.png">

Since we're just showing those values in their inputs, there should not be a need to do these queries:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/87168/48159568-3aaf8a80-e2de-11e8-9cde-90bc1ec3409a.png">

We should fix that at any case, regardless of this `?` bug.

We should also fix this:

>We shouldn't query Mapbox with `?` in the value

So when I type to any search input (either at profile editing or at [map search](https://www.trustroots.org/search), adding a question mark breaks the query. Try typing `london?`. We should either use `encodeURIComponent` or remove `?` completely from search query before we send it to Mapbox.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/87168/48159661-85c99d80-e2de-11e8-9e04-c02ff8df068b.png">

This can be done here for `val`: 
https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/modules/core/client/services/location.client.service.js#L119-L132

**Comment by simison** [comment]
Those location fields are using this directive: https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/modules/core/client/directives/tr-location.client.directive.js

**Comment by mrtmrtmlck** [comment]
Thank you very much for your reply! I am working on it 😊

**Comment by simison** [comment]
All these fixes are now in production 👍 

@guaka you can let the user with `?` in their location know.

**Comment by guaka** [comment]
I informed them it's fixed now.
