### ISSUE TITLE
problems around usernames with dots and other charactors

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#815]
**Describe the bug**

I'm starting to see a pattern with some of the weirder issues that I'm seeing in the support queue. It seems people are (or have been) able to create usernames with dots, but that this later on can cause issues with other parts such as logging in and resetting passwords.

I think it would be good to run all user related test cases with usernames that contain a dot.

**To Reproduce**
...

**Expected behavior**
...

** Fixes **

- [x] disallow usernames ending in dots
- [x] we could contact these 14 users and remove the trailing dot?

**Comment by simison** [comment]
Would be great to get as many repeatable example cases as possible.

**Comment by guaka** [comment]
> I am trying to fill my profile, but a message appear all the time about my username.
> Please explane my what is happening. Cause this message doesnt let me to save anything I change
> 
> -- 
> Username: zz. 
> 

(I changed the username here. It's two letters and a dot.)

https://trustroots.zendesk.com/inbox/conversations/1472

**Comment by guaka** [comment]
There are 14 users with a username ending in a dot. `db.getCollection('users').find({ username: { $regex: /\.$/ }})`

It's a good idea to not allow usernames ending in dots from now on.

**Comment by guaka** [comment]
Contacted the two users with that contacted us.
I will wait for their reply and then contact the other 12 after the username change PR #606 goes live.

**Comment by guaka** [comment]
I've contacted everyone (still 13) that still has a trailing dot.
