### ISSUE TITLE
Files in testutils folder are not linted

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#818]
**Describe the bug**
When running `npm run lint`, the files in `./testutils/` don't get linted.

**To Reproduce**
On `master` open `./testutils/server.testutil.js` and remove a semicolon or make another linting error.
Run `npm run lint`.
No error reported.

If you run `npx eslint ./testutils/`, you should see the error reported as expected.

**Expected behavior**
Files in `./testutils/` get linted with `npm run lint` and other scripts which include `gulp eslint` task.

**Comment by simison** [comment]
Good catch!

My editor's eslint does lint those files too so at least they're not ignored; they're juts not part of the gulp task doing the linting.

Adding the folder here should help:

https://github.com/Trustroots/trustroots/blob/c462a447b8766949d104d8a54230036d99b82d5f/gulpfile.js#L263-L277

**Comment by simison** [comment]
They're linted now 👍
