### ISSUE TITLE
add link to profile in automated emails

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#833]
"You are receiving this email because you have an active account on Trustroots."

"an active account" should link to the user account

**Comment by geniusit** [comment]
Hello,
I have still never contributed to any opensource projects. I would like to fix this issue. Is it possible?
Thank you

**Comment by simison** [comment]
Sure! 

Here's the template:
https://github.com/Trustroots/trustroots/blob/018cd6996f9bfe4ce390b2cce2562196edab3e59/modules/core/server/views/email-templates/email.server.view.html#L288

Here's the controller:
https://github.com/Trustroots/trustroots/blob/master/modules/core/server/services/email.server.service.js#L438-L479

- URLs to profiles are `https://www.trustroots.org/profile/USERNAME`
- Usernames you can grab from `user.username`
- `https://www.trustroots.org` part is available in that file as `url` variable
