### ISSUE TITLE
FAQ: How to write a good hosting request

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#835]
improve https://www.trustroots.org/guide

moved from github wiki:

### Short version
* Make sure your own profile is complete. You're much more likely to get a positive response if you have written a bit about yourself. Absolute bare minimum: links to profiles elsewhere.
* Write a little bit about yourself in the message. No essay though.
* Read their profiles. If someone is vegan you don't want to tell them how you want to try Currywurst (unless it's vegan Currywurst of course). You also want to look for things in common, e.g. you both hitchhiked through Syria (and survived).
* Trustroots is very much about spontaneous travel. Don't write to people 2 months ahead.

### Long version
_(Not necessary)_

## More information
(target=_blank)
* http://couchwiki.org/en/How_to_write_a_couch_request
* https://www.bewelcome.org/wiki/Writing_your_host

**Comment by simison** [comment]
Nice!

These messages also show up when starting a new message thread:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/87168/48508834-46f49400-e858-11e8-9111-26798ccb65c9.png">

The pre-filled text in the message field is also very much related to "good hosting requests". Should it have some other content? Should we completely remove it?

Let's also make sure this page is linked form welcome email sequence.

**Comment by guaka** [comment]
I'm totally for removing the "I'm travelling to __" thing :)

**Comment by simison** [comment]
>I'm totally for removing the "I'm travelling to __" thing :)

Heck yea me too — could you open an issue or PR?

**Comment by guaka** [comment]
Doing some of this as part of #864

**Comment by guaka** [comment]
I think with the [edit button] in place we can close this issue, if someone deems it important to improve the page they will do it :)
