### ISSUE TITLE
when writing to member: remove filled in template

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#837]
This should disappear:

"I’m traveling to ______ because

I chose to write to you because"

<img width="901" alt="image" src="https://user-images.githubusercontent.com/54728/48509754-3e00c400-e852-11e8-93cc-9dac71283e9d.png">

see also https://github.com/Trustroots/trustroots/issues/835#issuecomment-438799819

**Comment by guaka** [comment]
@laazee told me she was also interested in doing this one, but I guess it's such a small one that we can say "first come first serve"... :)

So, OK, go ahead!

**Comment by RGHuynh** [comment]
Ok, cool thanks.

**Comment by simison** [comment]
>Isn't Hacktoberfest only happening in October?

Yep! It seems like folks still discover this repository via the label. 🤷‍♂️
