### ISSUE TITLE
Facebook friends on map

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#84]
FB doesn't offer direct API for this anymore, but we could read friend's latest posts and sniff the location from there.

Also "Show my friends on map": #396

**Comment by guaka** [comment]
closing this, will open geolocation issues soon :)

**Comment by simison** [comment]
@guaka skim through these first: https://github.com/Trustroots/trustroots/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+location ;-)
