### ISSUE TITLE
Trustroots volunteer tribe

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#855]
It would be very useful to have a Trustroots volunteer tribe: this makes it much more likely that volunteers will meet, hang out, host, and talk and do Trustroots stuff.

Probably good to start this as our first invite-only tribe

**Comment by simison** [comment]
I think we can launch it right away :thumbsup:

**Comment by guaka** [comment]
Awesome!

For this to be properly useful it would help to be able to see people who are not hosting.
