### ISSUE TITLE
changing username doesn't work for a profile, but it works after loading and saving the data from the profile

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#860]
**Describe the bug**

User can't change their username. Has never changed their username.

**To Reproduce**

1. Create profile with profile creation date 2016-12-22.
2. Try to change username.
3. Can't change username. 

After changing date (locally, in database) to 2017-12-22 it is possible to change username.

**Additional context**
https://trustroots.zendesk.com/inbox/conversations/2268 (only accessible for those with access)

**Comment by guaka** [comment]
Weird: if I change the profile creation date with just one second it also becomes possible to change the username.

**Comment by simison** [comment]
> if I change the profile creation date with just one second it also becomes possible to change the username.

And if you change it back to original 2016 it's not?

**Comment by guaka** [comment]
The only thing I did: use Robo 3T to edit the document, and save it,
without any changes. After that it was possible the change the
username. Before that it wasn't.

**Comment by guaka** [comment]
Another user with this problem, https://trustroots.zendesk.com/inbox/conversations/1026

**Comment by guaka** [comment]
It makes no sense to me from a data perspective, but if we load and save all users it's probably going to be solved.

**Comment by noahsmindfuck** [comment]
maybe this is relateid:
https://trustrosssssots.zendesk.com/inbox/conversations/2701

**Comment by tg-x** [comment]
Just tried this: on the generated page `user.usernameUpdateAllowed` was set to true,
however the username change field was still disabled,
After removing the `disabled` attribute manually in the browser and clicking the change button, the change was successful although no message was displayed.
The login username and profile URL were updated, however the profile page still displays the old @username next to the name

**Comment by tg-x** [comment]
the reason for the latter is that there's a separate `displayUsername` profile attribute that is not updated

**Comment by simison** [comment]
That didplayusername mechanism could be removed, as it isn't so useful at the end.
