### ISSUE TITLE
more public stats 

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#865]
**Is your feature request related to a problem? Please describe.**
Some questions I seem to hear a lot:
- How many members are there in [country]?
- How many people are signing up? (e.g. per week)
- How many people are logging in? (e.g. per week)

**Describe the solution you'd like**
Add some more data to https://www.trustroots.org/statistics that can answer these questions.

E.g. 
- graph with number of signups by week
- graph with number of logins by week
- list of countries by number of members (I'm also thinking about SEO here, it's good if we have more content and keywords on the site:)

Is it possible to get this from our grafana?

**Comment by simison** [comment]
I just made https://grafana.trustroots.org/ publicly so that we can link there from `/statistics`

**Comment by guaka** [comment]
mostly good now, let's also add some of this:
- [ ] KPI
- [ ] message stats
- [ ] retention data
