### ISSUE TITLE
currently deployed code, where is it (not) showing and add date?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#876]
- "Currently deployed code", on which pages?
- let's add the date of that code, to show how dynamic this project is ;)

**Comment by guaka** [comment]
Ah now I see it's actually a hover!

**Comment by simison** [comment]
> let's add the date of that code, to show how dynamic this project is

Just link to GitHub? ;-)

**Comment by rumwerfer** [comment]
I just stumbled over this one while labeling unlabeled issues, and don't quite understand it. Is there still something to be done or can this be closed?
