### ISSUE TITLE
Receiving template emails after changing email address on existing account

### ISSUE THREAD

**Issue by platschi** [Trustroots/trustroots#880]
**Describe the bug**
I am a TR user since 2014, but recently changed the email address in my Trustroots profile. Now, suddenly I received "Welcome to Trustroots", "Meet new people" and "How is it going" emails from you, which I don't really want / need as I am not a new member, but only simply changed my email address. This is confusing.

**To Reproduce**
1. Change email address on an existing profile

**Expected behavior**
Confirmation of Email Change (**Received**!), nothing else

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
- 2018-11-25 discussion on slack https://trustroots.slack.com/archives/C08SENA9Z/p1543128901153400

**Comment by simison** [comment]
Thanks, I haven't been able to replicate this but based on other reports we've gotten this might indeed be the cause.

Do you remember if you changed anything else from your profile?

**Comment by guaka** [comment]
#841 may help with this, these emails are popping up a lot when running locally with copy of prod db.

**Comment by platschi** [comment]
> Do you remember if you changed anything else from your profile?

Nope, just email address.

**Comment by guaka** [comment]
Here's another one https://trustroots.zendesk.com/inbox/conversations/2268?q=welcome

**Comment by Breizhelle** [comment]
Happened to me recently as well.
I just changed my email address and received the welcome email a week ago.
So it's not an isolated bug.

**Comment by guaka** [comment]
Happening to me now :)

**Comment by rumwerfer** [comment]
+1 from support
