### ISSUE TITLE
on /signin: "Become a member" needs to be way bigger and more visible on

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#889]
on /signin: "Become a member" needs to be way bigger and more visible on

https://www.trustroots.org/signin?continue=true

![image](https://user-images.githubusercontent.com/54728/49048010-97191200-f1d9-11e8-96fb-a90600ec09ad.png)

**Comment by RGHuynh** [comment]
Can I work on this issue?

**Comment by simison** [comment]
Thanks for the offer @RGHuynh ! This is already taken care in https://github.com/Trustroots/trustroots/pull/891

Maybe there's something else on the list you'd like to tackle? https://github.com/Trustroots/trustroots/labels/good%20first%20issue
