### ISSUE TITLE
why does "reply rate / replies within" show for some profiles and not for others

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#893]
**Describe the bug**
- https://www.trustroots.org/profile/guaka shows "reply rate" and "replies within"
- https://www.trustroots.org/profile/mikael doesn't show either
**Expected behavior**
I'd expect these to show up on all profiles.

If there's no sensible number, e.g. because no messages have been received, that is useful information in itself.

**Comment by simison** [comment]
Yep, indeed no messages within a specific time window (I think it's 3 months currently). That's very similar to how it works e.g. at Warmshowers.

**Comment by guaka** [comment]
I sent you a message on TR in the past 3 months and it's not showing on your profile.

It would be cool to put something like "they didn't receive a message in the past 3 months, send them a message now!"

**Comment by simison** [comment]
>I sent you a message on TR in the past 3 months and it's not showing on your profile.

it's very much possible there's also a bug :thumbsup:

**Comment by mrkvon** [comment]
We care only about the first messages and first replies to them, between each pair of people.
If you had had a conversation before and then you had a conversation in past 3 months, it doesn't count.

How would it count, if we wanted to include it?

**Comment by noahsmindfuck** [comment]
At Warmshowers it's like this:
> Message responsiveness: 100%
> (4 responses to 4 messages since 2018-11-18)
I would really like to make sense of the reply rate in a users profile, esp. with a key in time. 
E.G: my reply rate is somewhere at 86%. Even I myself can not make any sense on why that is the case and would like to know more about it :)

**Comment by noahsmindfuck** [comment]
At Warmshowers it's like this:
> Message responsiveness: 100%
> (4 responses to 4 messages since 2018-11-18)
I would really like to make sense of trhe reply rate in a users profile, esp. with a key in time. 
E.G: my reply rate is somewhere at 86%. Even I myself can not make any sense on why that is the case and would like to know more about it :)

**Comment by mrkvon** [comment]
I also feel the warmshowers way helps me understand what's going on. We could take an inspiration. Possibly the space for the longer message can be a design issue for us.

Implementing this would be a question of serving and presenting the already existing data in a new way. Is doable.
If somebody is interested in moving this forward, you can ask me to explain things. (`git blame` will reveal that the code was my responsibility :) )

@noahsmindfuck It's likely that in the last 3 months 7 people opened a conversation with you and you replied to 6 of them. If that's not correct, we might have a bug.
(alternatively 14/12 conversations opened by others/answered by you in the last month)

**Comment by andreas-anhaeuser** [comment]
I have a feature request which is somehow related to this. Not sure whether this is the right place to post it, though. (if not, maybe somebody knows a better place?)

I find the current "Reply rate" metric a bit misleading. People often respond to host requests (usually, that's what the initial contact is about) at a time when the request is not relevant anymore: "Sorry, I missed your message, hope you found somewhere else to stay. Best wishes, XY". Before contacting someone it would be interesting to know whether they reply **in time**, not whether they reply at all (potentially way too late).
Implementation suggestion: Provide a button similar to the "This persons messages are polite and respectful" button, saying "This person replied to my request in time" [yes / no / doesn't apply].
