### ISSUE TITLE
Improve /signup

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#898]
https://www.trustroots.org/signup doesn't inspire trust (I think). If someone would send me a page like this without me knowing any context I'd run away.

- [ ] add Trustroots logo
- [ ] more branding, e.g. color
- [ ] add footer with some more information
- [ ] change URL for other steps, i.e. `signup/2` and `signup/3`
- [x] optional field "how did you hear about trustroots" #879
- [ ] remove "First name" and "Last name" fields
- [ ] ...more ideas? 

relates to #892 

Ideally we'd be closely monitoring drop-off, for that I'd need matomo (see #828)

**Comment by guaka** [comment]
Oh actually it's right there :)

**Comment by simison** [comment]
Could be added to here, tho: https://www.trustroots.org/sitemap.xml

**Comment by guaka** [comment]
I was looking at [my own SEO tool](https://apprankshaper.com/), where I didn't notice it:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/54728/49288430-fbb9c280-f4a0-11e8-92e8-9e3625333faa.png">

Strange that these still have the escaped_fragment stuff:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/54728/49288492-2c99f780-f4a1-11e8-8ff8-abe79861c977.png">

This is also interesting, clicks/impressions and rankings from the past 90 days for the keyword "trustroots"
<img width="769" alt="image" src="https://user-images.githubusercontent.com/54728/49288542-56531e80-f4a1-11e8-9001-1940b3005485.png">

**Comment by guaka** [comment]
chatting with @laazee, who suggested to remove First and Last name fields. Makes total sense!

**Comment by guaka** [comment]
More @laazee:

It's also scary that there's 3 steps
It's like, oh god how long is this gonna take
"Done" shouldn't be a step
Neither should tribes

The first page should be "EMAIL" only
after you get their email, on the second page you ask for everything else

**Comment by simison** [comment]
>chatting with @laazee, who suggested to remove First and Last name fields. Makes total sense!

Noting that these are required fields currently and I'd like to keep it as; `username` is a terribly technical thing and doesn't really convey trust like the name does.

Granted folks can write what ever to the name (or upload as their picture) but they still most of the time fill their actual name and pictures; thus increasing the perceived trust.

Basically the whole app expects those fields to be filled so it would be a lot of rewriting to make name+lastname optional.

**Comment by simison** [comment]
Agree completely with the sentiment to make the signup as easy and quick as possible. :-)

So we have two goals during the new user flow:
- get folks to signup
- get folks to fill up their profiles (description, picture, tribes.. that sorta things)

Any kind of welcome flow where users are guided to fill their profiles will lead to more filled profiles, so I guess it's just a question how we guide folks through it; during the mandatory signup steps right after they've done the signup?

Technically tribes and signup parts of the flow are already separate; the profile is created right after the step 1.

We could have the "done" step appear right after signing up and show the tribes and possible other profile filling nudges right after it. What do you think?

**Comment by simison** [comment]
Further brainstorming on other quick wins. We could remove 3 steps and just have flow like this:

## Signup
<img width="546" alt="image" src="https://user-images.githubusercontent.com/87168/49295430-6b8a7600-f4be-11e8-9086-e9cfe04010c2.png">

## Done!

<img width="932" alt="image" src="https://user-images.githubusercontent.com/87168/49295754-2ca8f000-f4bf-11e8-8e22-dd6734bc2b93.png">

**Comment by guaka** [comment]
Very nice!

Looking more into data I'm finding 70% drop-off for people who don't land on `/signup`
<img width="308" alt="image" src="https://user-images.githubusercontent.com/54728/49296056-8a393e80-f4b7-11e8-9adc-26574d2e34bc.png">

**Comment by simison** [comment]
Nice, do those numbers look right when cross-checked with Grafana? (folks who finish the flow vs actual signup numbers during the same time)

The funnel was set up quite a while back and there might have been some changes at the site meanwhile.

If it does work, we have an excellent gauge to follow while doing changes to see if we're actually moving the needle or just moving bits around.

**Comment by guaka** [comment]
The GA funnel seems to be set up correctly.

I created a segment "visited signup", which works well at the behavior flow thingy
https://analytics.google.com/analytics/web/#/report/content-engagement-flow/a56947356w90521310p94140732/_u.date00=20180101&_u.date01=20181129&_.useg=userpaMqrqWzQY2UDqaRI1P0ww

This is since 2018-01-01:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/54728/49300995-e013e380-f4c3-11e8-81b6-583d0e1bd955.png">

But this is since 2018-09-30:
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/54728/49301405-ce7f0b80-f4c4-11e8-99ff-5fced22d7dbc.png">


So actually, our drop off is really not so bad since we stopped invite-only. Still room for improvement though.
