### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#9]
- [x] **Google Analytics**

* `+` widely known
* `-` controlled by Google

- [x] **Piwik**

* `+-` controlled by ourselves
* `+-` _seems_ better for privacy
* `-` more hassle and (much) more likely to break

**Comment by pierreozoux** [comment]
Ok, I'm ready to start piwik for you :)

Do you want it behind your domain name, or I can setup a shared instance if needed?
What is the amount of traffic you get?

I have to warn you, it's still beta! I think the best it to keep both during this phase. Please let me know :)
We could start with ideas.trustroots.org also?

**Comment by simison** [comment]
Wohoo, this is great news. :-)

Currently ~77K pageviews/month and ~5000 visitors/month, but I expect this to go even x5 in half a year or so. We've had 3 peaks lasting a few days but they were only x3-4 from usual traffic. We're [still small](https://www.trustroots.org/#!/statistics). ;-)

We'll need it behind https so getting a cert for a separate subdomain doesn't make so much sense (suppose you're running it behind https anyway?), or do you think there would be some good sides on having it at piwik.trustroots.org? You would probably set up something like piwik.indiehosters.net?

Yes I agree it's good to have both for testing phase.

PS I'm spreading Indie Hosters stickers in bay area! :-)

**Comment by pierreozoux** [comment]
Yes, I don't host anyting without https, it is easier :)

It has to be a subdomain of yours or mine. It could be stats.trustroots.org or stats.tokoloho.co (I use the last for some collocations apps).
It could also be a proper domain name like sttts.org (stats trust roots). or tr-cdn.org \o/

If it is a subdomain of yours:
 + less likely to be blocked by noscript (sub-domain)
 - you have to handle your cert (I'll give you a CSR)
 - you'll have to delegate the dns of this sub-domain

I think that this is actually the best option, but I let you decide.

PS: great :) Actually, we forgot to put the website... (If you can write it on the back, would be great :) )

**Comment by guaka** [comment]
great! piwik.trustroots.org makes most sense I think. stats.trustroots
would be my second choice.

sent from my mobile phone

**Comment by simison** [comment]
Okidoki! I'll set sub domain today or on Monday.

**Comment by pierreozoux** [comment]
Ok, so:

you have to add ns entries for piwik.trustroots.org
freedns1.registrar-servers.com
freedns2.registrar-servers.com
freedns3.registrar-servers.com
freedns4.registrar-servers.com
freedns5.registrar-servers.com
(I still use another dns server (namecheap), but it will be fixes in mid-term).

I just sent you the CSR by mail.

**Comment by simison** [comment]
So this is now set up, but not in production yet.

We’ll run Google Analytics and Piwik in parallel for a while to test this out

piwik.trustroots.org SSL cert is at our Namecheap (2$ discount one) and Pierre is taking care of name servers.

I'll send @Trustroots/board logins today.

**Comment by simison** [comment]
Yo, I just enabled Piwik at trustroots.org

@pierreozoux

**Comment by simison** [comment]
This could improve things http://luisfarzati.github.io/angulartics/

**Comment by pierreozoux** [comment]
@simison: I didn't have time yet to look on the city database, but besides that, is it working as expected?

**Comment by simison** [comment]
Seems so! Take your time, we're running GA in parallel for now.

**Comment by chmac** [comment]
I think we should keep GA indefinitely. I understand the data is **much** better than piwik. Particularly if we use demographic tracking. It's also potentially better from a privacy perspective in terms of how much data *we* have. Google get all of it, but that's easily blocked via Ghostery / etc.

**Comment by guaka** [comment]
I think keeping GA is a good idea.
Meanwhile we can encourage people to install privacy tools that increase
their privacy overall.

**Comment by Remigr** [comment]
What is the point of using Piwik if you want to keep Google Analytic? 
I think Trustroots should have a clear opinion about privacy. 
Telling people to use privacy tools is just not enough, who is it going to affect but the people who already use privacy tools.
What real benefit the use of Google Analytic brings ? Or is it just a little bit easier to use than Piwik?

**Comment by chmac** [comment]
Agreed, I'm not sure why we installed piwik, doesn't make sense to have both. I'd suggest we remove piwik and keep GA. It provides **much** better data as I understand it. But I'll defer to @guaka's superior knowledge here. If it makes sense to have both for some reason, also happy with that.

**Comment by simison** [comment]
Yo, I thought I went it trough already with @guaka months ago.

Actually, most of the important analytics I'm planning to do with Statsd in the future (#204). GA is like a toy when it comes to actually understanding your data.

Some pointers; 
- There isn't really big difference in data/quality regarding how we actually use these tools (page flow, traffic sources, browser% and other very basic stuff). GA is great for other types of sites and projects (when concentrating on SEO for instance) — in our case it doesn't really bring that much extra value.
- We'll do profiling-analytics in other ways anyway, doesn't make sense to rely on GA for that stuff. We have that data in our DB.
- For piwik we can have a super simple "don't track me" button, which gives a way nicer message out compared to Ghostery/whatnot complicated instructions.

And most and foremost; it's good publicity, gives a nice signal out with very small effort while it doesn't really make any technical difference.

We'll need this for other wiki-sites to replace Kasper's hosted Piwik, makes sense to test now with TR which is much smaller in traffic compared to HW. We're basically slowly moving other projects under the same foundation (moved domains already).

**Comment by guaka** [comment]
@simison I wasn't hosting Piwik for a long time because the instances I was running were killing MySQL with data overkill. Only set one Piwik up again recently (and only for 3 [business](https://sourenfurniture.com/) websites), and I might simply ditch old data there at some point.

GA isn't really useful for SEO anymore (since Google doesn't pass search queries). It's good for tracking conversions, in TR context: we can see where we get (most) signups from. We can't easily add that functionality to our own code base.

It'd be a nice signal to ditch GA but it's worse to then later turn it back on.

So overall: GA isn't great but I strongly urge to keep GA running until we have a proper alternative (showing traffic sources for conversions) that we can rely on, which has been up and running _at least_ 6 months (including HW data).

**Comment by simison** [comment]
> So overall: GA isn't great but I strongly urge to keep GA running until we have a proper alternative (showing traffic sources for conversions) that we can rely on, which has been up and running at least 6 months (including HW data).

:+1: 

Feel free to also brainstorm possible metrics for Statsd (#204).

**Comment by pierreozoux** [comment]
Just to know how is it going? Do you still use https://piwik.trustroots.org/ ?

I'm cleaning my servers :)

**Comment by guaka** [comment]
I'm not sure if it's used.

**Comment by pierreozoux** [comment]
In this case, I'll just shut it down.
I recommend closing the issue as well to keep things clean :)


On 29-01-2016 10:27, Kasper Souren wrote:
> I'm not sure if it's used.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Trustroots/trustroots/issues/9#issuecomment-176683445
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by pierreozoux** [comment]
Actually it is still on:
https://www.trustroots.org/

Let me know when I can remove it (to avoid errors in people's browser)

**Comment by simison** [comment]
@pierreozoux Sorry delay, been very busy here. :-)

I just removed the script from the site, all clear now.

Yeah so it turns out Piwik isn't quite in bar with other tools...

**Comment by guaka** [comment]
Piwik is great for a lot of things though!

**Comment by simison** [comment]
Aye! :+1:

**Comment by platschi** [comment]
Imho, bad decision. What stuff you need to track with GA that Piwik cannot?

**Comment by simison** [comment]
@platschi yeaah it's not great situation but oh well. It's a bit like Photoshop and Gimp. The experience is very different although you can edit a photo with both. We also have pretty extensive knowledge already from GA due other work we do. We'll try not to spend time on tinkering with tools but bring our core mission forward instead. Piwik is great for some other projects instead, as Kasper says! At least we considered. ;-)

**Comment by guaka** [comment]
I'll definitely set up Piwik again for TR in the future if I can spend 10+
hours on this project :)

**Comment by pierreozoux** [comment]
I can still host if you need :)

On 24-02-2016 22:00, Kasper Souren wrote:
> I'll definitely set up Piwik again for TR in the future if I can spend 10+
> hours on this project :)
> 
> 
> 
> On Wed, Feb 24, 2016 at 10:57 PM, Mikael Korpela <notifications@github.com>
> wrote:
> 
>> @platschi <https://github.com/platschi> yeaah it's not great situation
>> but oh well. It's a bit like Photoshop and Gimp. The experience is very
>> different although you can edit a photo with both. We also have pretty
>> extensive knowledge already from GA due other work we do. We'll try not to
>> spend time on tinkering with tools but bring our core mission forward
>> instead. Piwik is great for some other projects instead, as Kasper says! At
>> least we considered. ;-)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Trustroots/trustroots/issues/9#issuecomment-188470112>
>> .
>>
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Trustroots/trustroots/issues/9#issuecomment-188471449
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux
