### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#903]
- [x] add standard footer to /statistics
- [ ] add footer to any other page?
- [ ] make it look good
- [x] add standard footer to /messages -- already there
- [x] add standard footer to /meet? (that, or remove existing footer) -- already there
- [x] postponed till [consensus](https://meta.trustroots.org/t/show-last-date-the-code-was-changed/87): something like GitHub deploy date, date of most recent commit is good enough?
- [x] link to version on github, 
- [x] social media icons
- [x] at least links to: /contact, /faq, /foundation, /volunteering, /rules, /donate, /privacy
- [x] language selector, for now just a [link to meta](https://meta.trustroots.org/t/lets-translate-trustroots/59/3)
- [ ] _anything else?_

Here's some good stuff:
https://www.orbitmedia.com/blog/website-footer-design-best-practices/

**Comment by simison** [comment]
This will be excluded also on message pages and host/meetup editing, as well on all page on mobile (so 50-60% of users). So not really a whole lot places left for footer.

It might be better use of time to think how to make those things visible in some other ways?

**Comment by simison** [comment]
Oh ye I don't wanna dismiss good thinking and totally in for quick wins. 💪

What I meant to say that getting footer work on most of our pages is very
hard and making it consistent across all views kinda impossible.

Let's add those links you suggested to the footer that already exists.

Another easy enough improvement is to take the footer from the front page
and show it on pages that are under "pages" module (but not on profile
pages and such since it's a bit much for those).
Existing minifooter layout is under core module currently.

**Comment by guaka** [comment]
Trying to get the datetime from [git-rev](https://www.npmjs.com/package/git-rev)'s `.log`, which gives me:

```
SyntaxError: Unexpected token A in JSON at position 295
    at JSON.parse (<anonymous>)
    at /Users/guaka/trustroots/node_modules/git-rev/index.js:25:17
    at /Users/guaka/trustroots/node_modules/git-rev/index.js:5:5
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

**Comment by guaka** [comment]
`git-rev` is broken and [unmaintained](https://github.com/tblobaum/git-rev/pulls).

Locally I fixed it by adding `-n1` to the above `_command`.

https://github.com/tblobaum/git-rev/pull/22 could be fix, would it make sense to get @maxingchi version of `git-rev`?

Or is it OK to just do this inside our own code base?

**Comment by simison** [comment]
Yeah, the module is so tiny that just copying methods directly from it is perfectly fine:

https://github.com/tblobaum/git-rev/blob/0f4266a8c892c71d3a82b10724a33a6bd6adbd25/index.js#L1-L38

**Comment by guaka** [comment]
OK!

This is what it looks like now:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/54728/49528532-63fb1080-f8b4-11e8-82ee-bb5c591a723b.png">

So I'll also use the date instead of "time ago", which probably won't work well for us with the current setup.

Where should I put this code though?  It's used inside `lib/express.js` now (and also somewhere in the statistics module! I'll refactor that as well as part of this PR).

**Comment by simison** [comment]
I think as a user (even as a geeky one) I would be thinking _"what changed??"_ when seeing that.

**Comment by simison** [comment]
> Where should I put this code though? It's used inside lib/express.js now (and also somewhere in the statistics module! I'll refactor that as well as part of this PR).

[Core controller](https://github.com/Trustroots/trustroots/blob/9234c8e55d6b58894428c77891176430c36da664/modules/core/server/controllers/core.server.controller.js) might make sense the most unless directly at `express.js` but it's already quite piled up with random stuff.

**Comment by guaka** [comment]
Ok, asked for some more feedback here https://meta.trustroots.org/t/show-last-date-the-code-was-changed/87 before plunging in :)

**Comment by guaka** [comment]
weird stuff when I set `footerHidden` to `false` for /statistics
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/54728/49583059-46cb4e00-f957-11e8-8657-1fcf6fbaa5d7.png">
