### ISSUE TITLE
feature: "Log me out of other devices"

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#906]
https://trustroots.zendesk.com/inbox/conversations/2528
"Somebody got an access to my account on his device and decided to cause some chaos and trouble for everyone around.
I kindly request that you make sure I get logged out of every possible device. I have already changed my password, so the problem won't reappear."

## Related
https://stackoverflow.com/questions/51319396/using-node-js-and-passport-js-how-can-i-logout-and-delete-all-cookie-sessions

**Comment by mrkvon** [comment]
So we could actually have a button for this somewhere. (i.e. in `account` or the main menu), right?

**Comment by simison** [comment]
Totally. Account page sounds like a good place :thumbsup:

**Comment by guaka** [comment]
Ha yeah, I saw that piece of code, one thought that came up was to suspend this user and then unsuspend them :)

Meanwhile we did find (and delete) the specific sessions of this user like this: `db.getCollection('sessions').find({ session: { $regex: /USERID/ } })`.
