### ISSUE TITLE
database schema?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#907]
If we don't have this already, it would be nice to have a database schema somewhere, or some docs going into this direction. If we do have this, where is it?

relates to #906 - as it's not so clear how `sessions` relate to `users`.

cc @mrkvon @simison

**Comment by simison** [comment]
We do have; each module has its schema file, e.g. here's one for contacts:

https://github.com/Trustroots/trustroots/blob/master/modules/contacts/server/models/contacts.server.model.js

**Comment by simison** [comment]
Though sessions and background job tables don't have, since those are handled by Express-sessions and Agenda modules.

**Comment by guaka** [comment]
OK!

This will do for now:
```
$ find .|grep model\.js                                                                        
./offers/server/models/offer.server.model.js
./messages/server/models/message.server.model.js
./messages/server/models/message-stat.server.model.js
./messages/server/models/thread.server.model.js
./tribes/server/models/tribe.server.model.js
./references/server/models/reference.server.model.js
./contacts/server/models/contacts.server.model.js
./support/server/models/support.server.model.js
./users/server/models/user.server.model.js
./references-thread/server/models/reference-thread.server.model.js
```
