### ISSUE TITLE
Why is Travis testing both node v10 and v11?

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#914]
Why is Travis testing both node v10 and v11?
<img width="947" alt="image" src="https://user-images.githubusercontent.com/54728/49471450-38711b00-f80d-11e8-84fa-bc22f6507e9b.png">

**Comment by simison** [comment]
Prod server runs on v10 LTS but I want to make sure we don't break the next version either.

**Comment by guaka** [comment]
OK
