### ISSUE TITLE
Set up logging for client side JavaScript errors

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#922]
https://sentry.io/

> Open-source error tracking that helps developers monitor and fix crashes in real time. Iterate continuously. Boost efficiency. Improve user experience.

**Comment by guaka** [comment]
great for moving to React #912

**Comment by simison** [comment]
YESSSSS 🙌

**Comment by nicksellen** [comment]
https://github.com/Trustroots/trustroots/issues/1197 is a duplicate, but more recent/specific, so I close this one.
