### ISSUE TITLE
Implicit meet offer does not display through date

### ISSUE THREAD

**Issue by petr-hajek** [Trustroots/trustroots#923]
**Describe the bug**
When you open new meet request it shows the Visible through field without the date. Only if you change the length to something else and back to month it works.

**To Reproduce**
1. Click on Meet button
2. Scroll to How long should this be visible?
3. No date is displayed (also if you click "A month")

**Expected behavior**
The date is displayed automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/38785076/49655580-44dabb00-fa3b-11e8-9cbd-ad8b9c5a9616.png)

**Desktop (please complete the following information):**
FF 63.0.3 (Linux Mint)

**Comment by topalavlad** [comment]
Took a quick look at this and because the default is 30 days, when "A month" is selected initially, `oldValue` and `newValue` are already equal so `setValidUntilDays()` won't be called:

```
$scope.$watch('trOfferValidUntil.offerValidityInDays', function (newValue, oldValue) {
    if (newValue !== oldValue) {
        setValidUntilDays(newValue);
    }
});
```

I'll try to do a PR where `setValidUntilDays` is called if date was not pre-populated.
