### ISSUE TITLE
Remove save&exit button and add cancel in Meet (desktop)

### ISSUE THREAD

**Issue by petr-hajek** [Trustroots/trustroots#924]
**Is your feature request related to a problem? Please describe.**
In the desktop view of Meet there is Save & exit button which can be pressed before the user finished the flow. At the same time it is missing a cancel button

**Describe the solution you'd like**
Replace the Save & Exit with Cancel button (so it will be same like in the mobile view).

**Comment by simison** [comment]
>Replace the Save & Exit with Next/Finish button. Or drop it totally like it is in the mobile version.

It'll just need to take into account that folks might want a way to exit the flow without saving.

**Comment by simison** [comment]
@petr-hajek Would you mind splitting this to two separate issues (one for empty description and one for buttons-flow) so it's easier to keep track of these? :-) Thanks!

**Comment by petr-hajek** [comment]
OK compulsory description is here: https://github.com/Trustroots/trustroots/issues/941
