### ISSUE TITLE
dev needs to send emails

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#933]
https://dev.trustroots.org needs to send real emails
Otherwise it's hard for people to really test, e.g. signup won't work, no reference emails, etc.

cc @simison @zrthstr

**Comment by simison** [comment]
You'll need to generate new API keys and add dev as a sending domain to https://www.sparkpost.com/

I'd just be extra careful not to:
- Get any dev -server mails triggering webhooks in trustroots.org
- Have separate sending domains (perhaps even separate from `*.trustroots.org`) to not interrupt the reputation of `trustroots.org` domain in terms of spam filters at Google and elsewhere.

**Comment by guaka** [comment]
@simison 
- What do you mean with "Get any dev -server mails triggering webhooks in trustroots.org"?
- I can send from dev.tr.bfr.ee

**Comment by guaka** [comment]
Added settings to `mailer` in config/env/local.js on the dev server, with this I managed to get an email from dev but it's with `localhost:3000` as the base URL.
