### ISSUE TITLE
Improve Search User API

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#944]
Follow up of #531.

Improve /api/users?search=string

- [x] pagination
- [ ] expand the user profile fields returned, or allow user to specify which fields to return
- [x] ~~improve search via usernames; figure out how dots, dashes etc. are treated by text index~~
_it is working fine for periods, hyphen and underscores. If you put period or hyphen into the search it works the same like a space_

**Comment by mrkvon** [comment]
ping @Akronix 

Feel free to update the issue with further requirements.

**Comment by Akronix** [comment]
How about fuzzy search?
Searching for "Abe" should return all instances of Abel, one of them myself: Abel Por Qué No.
And better, searching for "Avel" (similar names) should find "Abel" as well...

**Comment by simison** [comment]
>Searching for "Abe" should return all instances of Abel

So this was possible with MongoDB regexp queries but the issue was that they weren't relying on indices and thus very slow — is that correct @mrkvon ?

I wonder if we could do 2nd expensive query with regexp if first one doesn't yeld results?

>And better, searching for "Avel" (similar names) should find "Abel" as well...

I agree that's how it should work ideally. Great if it's easy and performant enough with MongoDB Indices but I suspect it won't be either. :-( Investing time and maintenance energy in something like ElasticSearch at this point probably isn't worth the effort on the other hand?

**Comment by guaka** [comment]
Sounds like premature scaling.
How slow is a regexp search really?
How many searches do we expect on a daily basis?

**Comment by simison** [comment]
Yep, that's a valid point. If someone whips up a PR I'm happy to help to measure with production data (~34K users).

**Comment by guaka** [comment]
The admin search I've been working on works pretty well with 34k users -
it's quite crude but does the job well.
https://github.com/Trustroots/trustroots/pull/960

**Comment by mrkvon** [comment]
> potentially very slow

I believe the main issue is being a potential vector of DoS attack. Not the slowness on its own.
So, can we limit amount of requests per second for a specific url + method?

Also, unlike a search using indices, this will get worse as the amount of members grows.

**Comment by simison** [comment]
>I believe the main issue is being a potential vector of DoS attack. Not the slowness on its own.
So, can we limit amount of requests from one user per second for a specific API endpoint?

Yes, we already do that for the whole `/api` but adding a separate more strict "bucket" for specific API endpoints is very straightforward.

It's configured in Nginx.

**Comment by mrkvon** [comment]
Then go on with the regex. Just make a restrictive rate limit and be aware that it's a temporary solution which is not scalable as the amount of members grows.

https://docs.mongodb.com/manual/reference/operator/query/regex/#index-use

Some case-sensitive search (i.e. `?search=abel` doesn't find `Abel`) can use indices.
Eventually, we could create lowercase versions of searched fields to have (pseudo)case-insensitive search with index.

Or we can migrate to a database which supports more option. :sweat_smile: :-1:

**Comment by Akronix** [comment]
Good discussion.

I'd go ahead with regexp.
Then, when scaling become an actual issue, we can consider to move to elasticsearch.
