### ISSUE TITLE
A way to collapse the search-map-sidebar 

### ISSUE THREAD

**Issue by rdoc101** [Trustroots/trustroots#95]
On the map view.
Once the search-map-sidebar comes up it isn't possible to collapse it, and so lose a third of the maps viewable area until refreshing the page.

**Comment by simison** [comment]
Took a while but this handy little handlebar is now online. :-)

![image](https://cloud.githubusercontent.com/assets/87168/13511614/8cd9190a-e19e-11e5-861c-0439bdfe5a0d.png)
