### ISSUE TITLE
Change React file naming convention from CamelCase to kebap-case

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#950]
As suggested in #935 [here](https://github.com/Trustroots/trustroots/pull/935#commitcomment-31614683)

### Why?
- current file naming convention of Trustroots is kebap-case
- some operating systems are case insensitive

### Why not?
- React documentation is mostly following CamelCase names for React component files
  - note that [React documentation doesn't encourage any particular file naming convention](https://stackoverflow.com/questions/43973199/file-naming-conventions-in-reactjs)

### What needs to be done?
- Update [importing React components to Angular](https://github.com/Trustroots/trustroots/blob/master/config/webpack/entries/main.js).
- Rename all files in `/modules/**/client/components/*.js`
- Rename module imports
- Reflect the change in React documentation (`/docs/React.md`)

**Comment by mrkvon** [comment]
ping @simison @Akronix

**Comment by Akronix** [comment]
Maybe React doesn't encourage any file convention, but I haven't seen any code in react that is not CamelCase.
I don't know if this corresponds, but although Java allows you to use any name convention, everybody uses CamelCase.
But well, If people find better to keep the former naming convention and thus use kebab-case for react, it's OK. But for any project written in React, I would never consider kebab-case.

By the way, what is the problem with this exactly:
* some operating systems are case insensitive
Does it mean that for some operating systems (which?) case in-sensitiveness is an issue for CamelCase? what do they do with Java source files?

**Comment by guaka** [comment]
I think CamelCase files would actually be good to know what's already converted to React.
Since we want to do the transition in a relatively short time it won't be a mix for long.

I think the changing caps aren't a problem because `-` and `.` would disappear. So the filename would also change if lower/uppercase is insignificant (like on Macs, somehow).
