### ISSUE TITLE
Mobile app doesn't get notifications for new contact requests

### ISSUE THREAD

**Issue by Akronix** [Trustroots/trustroots#963]
**Is your feature request related to a problem? Please describe.**
I've received a new contact request (mail notified) but the mobile app didn't notify. I opened the app and I couldn't see any highlight or indicator regarding the request. In order to accept the connection, I had to do something definitely non-straightforward:
Go to my profile -> go to contacts -> find one contact with pending contact request -> accept it.

I know other people with no computer no accepting my contact requests and I think this is because of this.

**Describe the solution you'd like**
Be notified by the app and have an indicator for contact requests inside the app.

**Comment by guaka** [comment]
This is not just for the app, it's also a problem for someone using only the website.

Simple solution: we create and use a "Root of Trust" system profile to send these notifications? I think it's good enough and it avoids a lot of thinking, designing and coding. Can also be used for the references and other automated emails. The profile's email address can be support@trustroots.org.

**Comment by simison** [comment]
@guaka what do you refer to by saying "sending notifications"?

**Comment by guaka** [comment]
notifications include:
- contact request
- new reference from someone

there may be more now, otherwise there will be more for sure

**Comment by simison** [comment]
I meant what is "notification" — an email, push notification?

**Comment by guaka** [comment]
So these events will become trustroots messages sent by user "root of trust", and thus it will be emails and/or push notifications, depending on the receiving user's settings, just like messages from other users.

**Comment by simison** [comment]
It honestly sounds like it'll be much much easier to just inject the actual push notification and email if those are now missing for some events rather than try to inject messages to user's inbox. :-) The framework is already there, just add new push notifications here:

https://github.com/Trustroots/trustroots/blob/d287e782f7337442ff898ae8d95af0aea75c7312/modules/core/server/services/push.server.service.js

**Comment by guaka** [comment]
Emails and push notifications doesn't show anything to someone who is using only web without notifications and who doesn't read emails (or misses an email, this has happened to me, I only noticed some contact requests months later). So it requires _something_.
