### ISSUE TITLE
DRY up email templates

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#966]
DRY up email templates

follow up from #928
- [ ] add some more tests for emails
- [ ] put most of the the table stuff in one place

<img width="759" alt="image" src="https://user-images.githubusercontent.com/54728/49943164-79d98880-fee7-11e8-909b-4e9a6b81afd5.png">

**Comment by guaka** [comment]
_@simison added this_
--------------------------
Yep, that's a refactor long due.

Basically, those tables would need to be moved to a layout and reused each time with {% extends './layout.server.view.html' %}

You're right in that email HTML is gnarly. 😁 Can't be really helped.
@simison
simison a minute ago Member

Templates are Nunjucks templates: https://mozilla.github.io/nunjucks/

**Comment by simison** [comment]
Done in https://github.com/Trustroots/trustroots/pull/987
