### ISSUE TITLE
Email buttons: only text is clickable

### ISSUE THREAD

**Issue by mrkvon** [Trustroots/trustroots#989]
**Describe the bug**
I expect the whole button to be clickable. Now it's just the text that has the link.

**To Reproduce**
- Receive an email with an action button.
- Hover over the button.
- Observe that the text has the link, but the button doesn't.

**Comment by quite** [comment]
Hm, the `a` inside the `td` has `display:block;`. Shouldn't that do it? https://github.com/Trustroots/trustroots/blob/a4b55578d9a5f2377cbb6b0de33133fd969c9104/modules/core/server/views/email-templates/email.server.view.html#L67

**Comment by rafalwawrzyk** [comment]
Hi guys, do you working on this issue? :smiley:

**Comment by simison** [comment]
@rafalwawrzyk I don't think anyone is working on it — feel free to tackle it!

**Comment by rafalwawrzyk** [comment]
Ok @simison  , i check this
